if(${MCU_NAME} MATCHES "(^ATMEGA103$)")
    set(SYSTEM_LIB_SOURCE "system/src/__Lib_System.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/LTE64K/__Lib_Math_NoMOVW.c")
    set(MATH_DOUBLE_SOURCE "math_double/LTE64K/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/lte64k/__lib_delays.c")
elseif(${MCU_NAME} MATCHES "(^ATTINY1634$|^ATTINY167$|^ATTINY87$)")
    set(SYSTEM_LIB_SOURCE "system/src/__Lib_System.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/LTE64K/__Lib_Math_NoHwMul.c")
    set(MATH_DOUBLE_SOURCE "math_double/LTE64K/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/lte64k/__lib_delays.c")
elseif(${MCU_NAME} MATCHES "(^AT90USB162$|^AT90USB82$|^ATMEGA16U2$|^ATMEGA32U2$|^ATMEGA8U2$)")
    set(SYSTEM_LIB_SOURCE "system/src/__Lib_System.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/LTE64K/__Lib_Math.c")
    set(MATH_DOUBLE_SOURCE "math_double/LTE64K/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/lte64k/__lib_delays.c")
elseif(${MCU_NAME} MATCHES "(^ATMEGA328PB$|^AT90PWM1$|^AT90PWM161$|^AT90PWM81$|^ATMEGA168A$|^ATMEGA168P$|^ATMEGA168PA$|^ATMEGA168PB$|^ATMEGA16HVA$|^ATMEGA16M1$|^ATMEGA328$|^ATMEGA328P$|^ATMEGA32C1$|^ATMEGA32M1$|^ATMEGA48$|^ATMEGA48A$|^ATMEGA48P$|^ATMEGA48PA$|^ATMEGA64C1$|^ATMEGA64M1$|^ATMEGA8$|^ATMEGA8515$|^ATMEGA8535$|^ATMEGA88$|^ATMEGA88A$|^ATMEGA88P$|^ATMEGA88PA$|^ATMEGA8A$|^ATMEGA8HVA$)")
    set(SYSTEM_LIB_SOURCE "system/src/__Lib_System_nocall.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/LTE64K/__Lib_Math.c")
    set(MATH_DOUBLE_SOURCE "math_double/LTE64K/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/lte64k/__lib_delays.c")
elseif(${MCU_NAME} MATCHES "(^ATTINY13$|^ATTINY13A$|^ATTINY2313$|^ATTINY2313A$|^ATTINY24$|^ATTINY24A$|^ATTINY25$|^ATTINY261$|^ATTINY261A$|^ATTINY4313$|^ATTINY43U$|^ATTINY44$|^ATTINY441$|^ATTINY44A$|^ATTINY45$|^ATTINY461$|^ATTINY461A$|^ATTINY48$|^ATTINY828$|^ATTINY84$|^ATTINY841$|^ATTINY84A$|^ATTINY85$|^ATTINY861$|^ATTINY861A$|^ATTINY88$)")
    set(SYSTEM_LIB_SOURCE "system/src/__Lib_System_nocall.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/LTE64K/__Lib_Math_NoHwMul.c")
    set(MATH_DOUBLE_SOURCE "math_double/LTE64K/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/lte64k/__lib_delays.c")
elseif(${MCU_NAME} MATCHES "(^AT90S2313$|^AT90S2323$|^AT90S2343$|^AT90S4414$|^AT90S4433$|^AT90S4434$|^AT90S8515$|^AT90S8535$|^ATTINY102$|^ATTINY104$|^ATTINY22$|^ATTINY26$)")
    set(SYSTEM_LIB_SOURCE "system/src/__Lib_System_nocall.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/LTE64K/__Lib_Math_NoMOVW.c")
    set(MATH_DOUBLE_SOURCE "math_double/LTE64K/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/lte64k/__lib_delays.c")
endif()
