if(${MCU_NAME} MATCHES "(^AT90USB162$|^AT90USB82$|^ATMEGA16U2$|^ATMEGA32U2$|^ATMEGA8U2$)")
    set(SYSTEM_LIB_SOURCE "system/src/__Lib_System.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/LTE64K/__Lib_Math.c")
    set(MATH_DOUBLE_SOURCE "math_double/LTE64K/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/lte64k/__lib_delays.c")
endif()