if(${MCU_NAME} MATCHES "(^MKV5[68]F(.+)$)")
    set(SYSTEM_LIB_SOURCE "system/NXP/M7/src/__Lib_System.c")
    set(SYSTEM_LIB_INCLUDE_DIR "system/NXP/M7/include/")
    set(MATH_LIB_SOURCE "math/M7/__Lib_Math.c")
    set(MATH_DOUBLE_SOURCE "math_double/M7/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/m7/__lib_delays.c")
endif()
