if(${MCU_NAME} MATCHES "(^MK6[56]F[NX](.+)$)")
    set(SYSTEM_LIB_SOURCE "system/NXP/M4/src/__Lib_System_K66.c")
    set(SYSTEM_LIB_INCLUDE_DIR "system/NXP/M4/include/")
    set(MATH_LIB_SOURCE "math/M4EF/__Lib_Math.c")
    set(MATH_DOUBLE_SOURCE "math_double/M4EF/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/m4ef/__lib_delays.c")
endif()