// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00004000;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;


// Interrupt Vector Table Constants
const unsigned short IVT_ADDR_PSC2_CAPT = 0x0002;
const unsigned short IVT_ADDR_PSC2_EC = 0x0004;
const unsigned short IVT_ADDR_PSC2_EEC = 0x0006;
const unsigned short IVT_ADDR_PSC0_CAPT = 0x0008;
const unsigned short IVT_ADDR_PSC0_EC = 0x000A;
const unsigned short IVT_ADDR_PSC0_EEC = 0x000C;
const unsigned short IVT_ADDR_ANALOG_COMP_1 = 0x000E;
const unsigned short IVT_ADDR_ANALOG_COMP_2 = 0x0010;
const unsigned short IVT_ADDR_ANALOG_COMP_3 = 0x0012;
const unsigned short IVT_ADDR_INT0 = 0x0014;
const unsigned short IVT_ADDR_TIMER1_CAPT = 0x0016;
const unsigned short IVT_ADDR_TIMER1_OVF = 0x0018;
const unsigned short IVT_ADDR_ADC = 0x001A;
const unsigned short IVT_ADDR_INT1 = 0x001C;
const unsigned short IVT_ADDR_SPI_STC = 0x001E;
const unsigned short IVT_ADDR_INT2 = 0x0020;
const unsigned short IVT_ADDR_WDT = 0x0022;
const unsigned short IVT_ADDR_EE_READY = 0x0024;
const unsigned short IVT_ADDR_SPM_READY = 0x0026;

sfr io   unsigned char PORTB                     absolute 0x0025;
sfr io   unsigned char DDRB                      absolute 0x0024;
sfr io   unsigned char volatile PINB                      absolute 0x0023;
sfr io   unsigned char PORTD                     absolute 0x002B;
sfr io   unsigned char DDRD                      absolute 0x002A;
sfr io   unsigned char volatile PIND                      absolute 0x0029;
sfr io   unsigned char PORTE                     absolute 0x002E;
sfr io   unsigned char DDRE                      absolute 0x002D;
sfr io   unsigned char volatile PINE                      absolute 0x002C;
sfr io   unsigned char volatile DACH                      absolute 0x0059;
    const register unsigned short int DACH0 = 0;
    sbit  DACH0_bit at DACH.B0;
    const register unsigned short int DACH1 = 1;
    sbit  DACH1_bit at DACH.B1;
    const register unsigned short int DACH2 = 2;
    sbit  DACH2_bit at DACH.B2;
    const register unsigned short int DACH3 = 3;
    sbit  DACH3_bit at DACH.B3;
    const register unsigned short int DACH4 = 4;
    sbit  DACH4_bit at DACH.B4;
    const register unsigned short int DACH5 = 5;
    sbit  DACH5_bit at DACH.B5;
    const register unsigned short int DACH6 = 6;
    sbit  DACH6_bit at DACH.B6;
    const register unsigned short int DACH7 = 7;
    sbit  DACH7_bit at DACH.B7;

sfr io   unsigned char volatile DACL                      absolute 0x0058;
    const register unsigned short int DACL0 = 0;
    sbit  DACL0_bit at DACL.B0;
    const register unsigned short int DACL1 = 1;
    sbit  DACL1_bit at DACL.B1;
    const register unsigned short int DACL2 = 2;
    sbit  DACL2_bit at DACL.B2;
    const register unsigned short int DACL3 = 3;
    sbit  DACL3_bit at DACL.B3;
    const register unsigned short int DACL4 = 4;
    sbit  DACL4_bit at DACL.B4;
    const register unsigned short int DACL5 = 5;
    sbit  DACL5_bit at DACL.B5;
    const register unsigned short int DACL6 = 6;
    sbit  DACL6_bit at DACL.B6;
    const register unsigned short int DACL7 = 7;
    sbit  DACL7_bit at DACL.B7;

sfr data unsigned char volatile DACON                     absolute 0x0076;
    const register unsigned short int DAATE = 7;
    sbit  DAATE_bit at DACON.B7;
    const register unsigned short int DATS0 = 4;
    sbit  DATS0_bit at DACON.B4;
    const register unsigned short int DATS1 = 5;
    sbit  DATS1_bit at DACON.B5;
    const register unsigned short int DATS2 = 6;
    sbit  DATS2_bit at DACON.B6;
    const register unsigned short int DALA = 2;
    sbit  DALA_bit at DACON.B2;
    const register unsigned short int DAEN = 0;
    sbit  DAEN_bit at DACON.B0;

sfr io   unsigned char SPCR                      absolute 0x0037;
    const register unsigned short int SPIE = 7;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPE = 6;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int DORD = 5;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int MSTR = 4;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int CPOL = 3;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPHA = 2;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int SPR0 = 0;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR1 = 1;
    sbit  SPR1_bit at SPCR.B1;

sfr io   unsigned char volatile SPSR                      absolute 0x0038;
    const register unsigned short int SPIF = 7;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int WCOL = 6;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int SPI2X = 0;
    sbit  SPI2X_bit at SPSR.B0;

sfr io   unsigned char volatile SPDR                      absolute 0x0056;
sfr data unsigned char volatile WDTCSR                    absolute 0x0082;
    const register unsigned short int WDIF = 7;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIE = 6;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDP0 = 0;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP1 = 1;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP2 = 2;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP3 = 5;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDCE = 4;
    sbit  WDCE_bit at WDTCSR.B4;
    const register unsigned short int WDE = 3;
    sbit  WDE_bit at WDTCSR.B3;

sfr data unsigned char volatile EICRA                     absolute 0x0089;
    const register unsigned short int ISC20 = 4;
    sbit  ISC20_bit at EICRA.B4;
    const register unsigned short int ISC21 = 5;
    sbit  ISC21_bit at EICRA.B5;
    const register unsigned short int ISC10 = 2;
    sbit  ISC10_bit at EICRA.B2;
    const register unsigned short int ISC11 = 3;
    sbit  ISC11_bit at EICRA.B3;
    const register unsigned short int ISC00 = 0;
    sbit  ISC00_bit at EICRA.B0;
    const register unsigned short int ISC01 = 1;
    sbit  ISC01_bit at EICRA.B1;

sfr io   unsigned char EIMSK                     absolute 0x0041;
    const register unsigned short int INT0 = 0;
    sbit  INT0_bit at EIMSK.B0;
    const register unsigned short int INT1 = 1;
    sbit  INT1_bit at EIMSK.B1;
    const register unsigned short int INT2 = 2;
    sbit  INT2_bit at EIMSK.B2;

sfr io   unsigned char volatile EIFR                      absolute 0x0040;
    const register unsigned short int INTF0 = 0;
    sbit  INTF0_bit at EIFR.B0;
    const register unsigned short int INTF1 = 1;
    sbit  INTF1_bit at EIFR.B1;
    const register unsigned short int INTF2 = 2;
    sbit  INTF2_bit at EIFR.B2;

sfr io   unsigned char ADMUX                     absolute 0x0028;
    const register unsigned short int REFS0 = 6;
    sbit  REFS0_bit at ADMUX.B6;
    const register unsigned short int REFS1 = 7;
    sbit  REFS1_bit at ADMUX.B7;
    const register unsigned short int ADLAR = 5;
    sbit  ADLAR_bit at ADMUX.B5;
    const register unsigned short int MUX0 = 0;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX1 = 1;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX2 = 2;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX3 = 3;
    sbit  MUX3_bit at ADMUX.B3;

sfr io   unsigned char volatile ADCSRA                    absolute 0x0026;
    const register unsigned short int ADEN = 7;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADSC = 6;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADATE = 5;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADIF = 4;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIE = 3;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS2 = 2;
    sbit  ADPS2_bit at ADCSRA.B2;

sfr io   unsigned int  volatile ADC                       absolute 0x004C;
sfr io   unsigned char volatile ADCL                      absolute 0x004C;
sfr io   unsigned char volatile ADCH                      absolute 0x004D;
sfr io   unsigned char ADCSRB                    absolute 0x0027;
    const register unsigned short int ADHSM = 7;
    sbit  ADHSM_bit at ADCSRB.B7;
    const register unsigned short int ADNCDIS = 6;
    sbit  ADNCDIS_bit at ADCSRB.B6;
    const register unsigned short int ADSSEN = 4;
    sbit  ADSSEN_bit at ADCSRB.B4;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS2_bit at ADCSRB.B2;
    const register unsigned short int ADTS3 = 3;
    sbit  ADTS3_bit at ADCSRB.B3;

sfr data unsigned char DIDR0                     absolute 0x0077;
    const register unsigned short int ADC7D = 7;
    sbit  ADC7D_bit at DIDR0.B7;
    const register unsigned short int ADC6D = 6;
    sbit  ADC6D_bit at DIDR0.B6;
    const register unsigned short int ADC5D = 5;
    sbit  ADC5D_bit at DIDR0.B5;
    const register unsigned short int ADC4D = 4;
    sbit  ADC4D_bit at DIDR0.B4;
    const register unsigned short int ADC3D = 3;
    sbit  ADC3D_bit at DIDR0.B3;
    const register unsigned short int ADC2D = 2;
    sbit  ADC2D_bit at DIDR0.B2;
    const register unsigned short int ADC1D = 1;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC0D = 0;
    sbit  ADC0D_bit at DIDR0.B0;

sfr data unsigned char DIDR1                     absolute 0x0078;
    const register unsigned short int ACMP1MD = 3;
    sbit  ACMP1MD_bit at DIDR1.B3;
    const register unsigned short int AMP0POSD = 2;
    sbit  AMP0POSD_bit at DIDR1.B2;
    const register unsigned short int ADC10D = 1;
    sbit  ADC10D_bit at DIDR1.B1;
    const register unsigned short int ADC9D = 0;
    sbit  ADC9D_bit at DIDR1.B0;

sfr data unsigned char volatile AMP0CSR                   absolute 0x0079;
    const register unsigned short int AMP0EN = 7;
    sbit  AMP0EN_bit at AMP0CSR.B7;
    const register unsigned short int AMP0IS = 6;
    sbit  AMP0IS_bit at AMP0CSR.B6;
    const register unsigned short int AMP0G0 = 4;
    sbit  AMP0G0_bit at AMP0CSR.B4;
    const register unsigned short int AMP0G1 = 5;
    sbit  AMP0G1_bit at AMP0CSR.B5;
    const register unsigned short int AMP0GS = 3;
    sbit  AMP0GS_bit at AMP0CSR.B3;
    const register unsigned short int AMP0TS0 = 0;
    sbit  AMP0TS0_bit at AMP0CSR.B0;
    const register unsigned short int AMP0TS1 = 1;
    sbit  AMP0TS1_bit at AMP0CSR.B1;

sfr data unsigned char volatile AC3CON                    absolute 0x007F;
    const register unsigned short int AC3EN = 7;
    sbit  AC3EN_bit at AC3CON.B7;
    const register unsigned short int AC3IE = 6;
    sbit  AC3IE_bit at AC3CON.B6;
    const register unsigned short int AC3IS0 = 4;
    sbit  AC3IS0_bit at AC3CON.B4;
    const register unsigned short int AC3IS1 = 5;
    sbit  AC3IS1_bit at AC3CON.B5;
    const register unsigned short int AC3OEA = 3;
    sbit  AC3OEA_bit at AC3CON.B3;
    const register unsigned short int AC3M0 = 0;
    sbit  AC3M0_bit at AC3CON.B0;
    const register unsigned short int AC3M1 = 1;
    sbit  AC3M1_bit at AC3CON.B1;
    const register unsigned short int AC3M2 = 2;
    sbit  AC3M2_bit at AC3CON.B2;

sfr data unsigned char volatile AC1CON                    absolute 0x007D;
    const register unsigned short int AC1EN = 7;
    sbit  AC1EN_bit at AC1CON.B7;
    const register unsigned short int AC1IE = 6;
    sbit  AC1IE_bit at AC1CON.B6;
    const register unsigned short int AC1IS0 = 4;
    sbit  AC1IS0_bit at AC1CON.B4;
    const register unsigned short int AC1IS1 = 5;
    sbit  AC1IS1_bit at AC1CON.B5;
    const register unsigned short int AC1M0 = 0;
    sbit  AC1M0_bit at AC1CON.B0;
    const register unsigned short int AC1M1 = 1;
    sbit  AC1M1_bit at AC1CON.B1;
    const register unsigned short int AC1M2 = 2;
    sbit  AC1M2_bit at AC1CON.B2;

sfr data unsigned char volatile AC2CON                    absolute 0x007E;
    const register unsigned short int AC2EN = 7;
    sbit  AC2EN_bit at AC2CON.B7;
    const register unsigned short int AC2IE = 6;
    sbit  AC2IE_bit at AC2CON.B6;
    const register unsigned short int AC2IS0 = 4;
    sbit  AC2IS0_bit at AC2CON.B4;
    const register unsigned short int AC2IS1 = 5;
    sbit  AC2IS1_bit at AC2CON.B5;
    const register unsigned short int AC2M0 = 0;
    sbit  AC2M0_bit at AC2CON.B0;
    const register unsigned short int AC2M1 = 1;
    sbit  AC2M1_bit at AC2CON.B1;
    const register unsigned short int AC2M2 = 2;
    sbit  AC2M2_bit at AC2CON.B2;

sfr io   unsigned char volatile ACSR                      absolute 0x0020;
    const register unsigned short int AC3IF = 7;
    sbit  AC3IF_bit at ACSR.B7;
    const register unsigned short int AC2IF = 6;
    sbit  AC2IF_bit at ACSR.B6;
    const register unsigned short int AC1IF = 5;
    sbit  AC1IF_bit at ACSR.B5;
    const register unsigned short int AC3O = 3;
    sbit  AC3O_bit at ACSR.B3;
    const register unsigned short int AC2O = 2;
    sbit  AC2O_bit at ACSR.B2;
    const register unsigned short int AC1O = 1;
    sbit  AC1O_bit at ACSR.B1;

sfr data unsigned char volatile AC3ECON                   absolute 0x007C;
    const register unsigned short int AC3OI = 5;
    sbit  AC3OI_bit at AC3ECON.B5;
    const register unsigned short int AC3OE = 4;
    sbit  AC3OE_bit at AC3ECON.B4;
    const register unsigned short int AC3H0 = 0;
    sbit  AC3H0_bit at AC3ECON.B0;
    const register unsigned short int AC3H1 = 1;
    sbit  AC3H1_bit at AC3ECON.B1;
    const register unsigned short int AC3H2 = 2;
    sbit  AC3H2_bit at AC3ECON.B2;

sfr data unsigned char volatile AC2ECON                   absolute 0x007B;
    const register unsigned short int AC2OI = 5;
    sbit  AC2OI_bit at AC2ECON.B5;
    const register unsigned short int AC2OE = 4;
    sbit  AC2OE_bit at AC2ECON.B4;
    const register unsigned short int AC2H0 = 0;
    sbit  AC2H0_bit at AC2ECON.B0;
    const register unsigned short int AC2H1 = 1;
    sbit  AC2H1_bit at AC2ECON.B1;
    const register unsigned short int AC2H2 = 2;
    sbit  AC2H2_bit at AC2ECON.B2;

sfr data unsigned char volatile AC1ECON                   absolute 0x007A;
    const register unsigned short int AC1OI = 5;
    sbit  AC1OI_bit at AC1ECON.B5;
    const register unsigned short int AC1OE = 4;
    sbit  AC1OE_bit at AC1ECON.B4;
    const register unsigned short int AC1ICE = 3;
    sbit  AC1ICE_bit at AC1ECON.B3;
    const register unsigned short int AC1H0 = 0;
    sbit  AC1H0_bit at AC1ECON.B0;
    const register unsigned short int AC1H1 = 1;
    sbit  AC1H1_bit at AC1ECON.B1;
    const register unsigned short int AC1H2 = 2;
    sbit  AC1H2_bit at AC1ECON.B2;

sfr io   unsigned char volatile SREG                      absolute 0x005F;
    const register unsigned short int SREG_I = 7;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_C_bit at SREG.B0;

sfr io   unsigned int  volatile SP                        absolute 0x005D;
sfr io   unsigned char volatile SPL                       absolute 0x005D;
sfr io   unsigned char volatile MCUCR                     absolute 0x0055;
    const register unsigned short int PUD = 4;
    sbit  PUD_bit at MCUCR.B4;
    const register unsigned short int RSTDIS = 3;
    sbit  RSTDIS_bit at MCUCR.B3;
    const register unsigned short int CKRC81 = 2;
    sbit  CKRC81_bit at MCUCR.B2;
    const register unsigned short int IVSEL = 1;
    sbit  IVSEL_bit at MCUCR.B1;
    const register unsigned short int IVCE = 0;
    sbit  IVCE_bit at MCUCR.B0;

sfr io   unsigned char volatile MCUSR                     absolute 0x0054;
    const register unsigned short int WDRF = 3;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int BORF = 2;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int EXTRF = 1;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int PORF = 0;
    sbit  PORF_bit at MCUSR.B0;

sfr data unsigned char OSCCAL                    absolute 0x0088;
    const register unsigned short int OSCCAL0 = 0;
    sbit  OSCCAL0_bit at OSCCAL.B0;
    const register unsigned short int OSCCAL1 = 1;
    sbit  OSCCAL1_bit at OSCCAL.B1;
    const register unsigned short int OSCCAL2 = 2;
    sbit  OSCCAL2_bit at OSCCAL.B2;
    const register unsigned short int OSCCAL3 = 3;
    sbit  OSCCAL3_bit at OSCCAL.B3;
    const register unsigned short int OSCCAL4 = 4;
    sbit  OSCCAL4_bit at OSCCAL.B4;
    const register unsigned short int OSCCAL5 = 5;
    sbit  OSCCAL5_bit at OSCCAL.B5;
    const register unsigned short int OSCCAL6 = 6;
    sbit  OSCCAL6_bit at OSCCAL.B6;
    const register unsigned short int OSCCAL7 = 7;
    sbit  OSCCAL7_bit at OSCCAL.B7;

sfr data unsigned char volatile CLKPR                     absolute 0x0083;
    const register unsigned short int CLKPCE = 7;
    sbit  CLKPCE_bit at CLKPR.B7;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPS3_bit at CLKPR.B3;

sfr io   unsigned char SMCR                      absolute 0x0053;
    const register unsigned short int SM0 = 1;
    sbit  SM0_bit at SMCR.B1;
    const register unsigned short int SM1 = 2;
    sbit  SM1_bit at SMCR.B2;
    const register unsigned short int SM2 = 3;
    sbit  SM2_bit at SMCR.B3;
    const register unsigned short int SE = 0;
    sbit  SE_bit at SMCR.B0;

sfr io   unsigned char volatile GPIOR2                    absolute 0x003B;
    const register unsigned short int GPIOR27 = 7;
    sbit  GPIOR27_bit at GPIOR2.B7;
    const register unsigned short int GPIOR26 = 6;
    sbit  GPIOR26_bit at GPIOR2.B6;
    const register unsigned short int GPIOR25 = 5;
    sbit  GPIOR25_bit at GPIOR2.B5;
    const register unsigned short int GPIOR24 = 4;
    sbit  GPIOR24_bit at GPIOR2.B4;
    const register unsigned short int GPIOR23 = 3;
    sbit  GPIOR23_bit at GPIOR2.B3;
    const register unsigned short int GPIOR22 = 2;
    sbit  GPIOR22_bit at GPIOR2.B2;
    const register unsigned short int GPIOR21 = 1;
    sbit  GPIOR21_bit at GPIOR2.B1;
    const register unsigned short int GPIOR20 = 0;
    sbit  GPIOR20_bit at GPIOR2.B0;

sfr io   unsigned char volatile GPIOR1                    absolute 0x003A;
    const register unsigned short int GPIOR17 = 7;
    sbit  GPIOR17_bit at GPIOR1.B7;
    const register unsigned short int GPIOR16 = 6;
    sbit  GPIOR16_bit at GPIOR1.B6;
    const register unsigned short int GPIOR15 = 5;
    sbit  GPIOR15_bit at GPIOR1.B5;
    const register unsigned short int GPIOR14 = 4;
    sbit  GPIOR14_bit at GPIOR1.B4;
    const register unsigned short int GPIOR13 = 3;
    sbit  GPIOR13_bit at GPIOR1.B3;
    const register unsigned short int GPIOR12 = 2;
    sbit  GPIOR12_bit at GPIOR1.B2;
    const register unsigned short int GPIOR11 = 1;
    sbit  GPIOR11_bit at GPIOR1.B1;
    const register unsigned short int GPIOR10 = 0;
    sbit  GPIOR10_bit at GPIOR1.B0;

sfr io   unsigned char volatile GPIOR0                    absolute 0x0039;
    const register unsigned short int GPIOR07 = 7;
    sbit  GPIOR07_bit at GPIOR0.B7;
    const register unsigned short int GPIOR06 = 6;
    sbit  GPIOR06_bit at GPIOR0.B6;
    const register unsigned short int GPIOR05 = 5;
    sbit  GPIOR05_bit at GPIOR0.B5;
    const register unsigned short int GPIOR04 = 4;
    sbit  GPIOR04_bit at GPIOR0.B4;
    const register unsigned short int GPIOR03 = 3;
    sbit  GPIOR03_bit at GPIOR0.B3;
    const register unsigned short int GPIOR02 = 2;
    sbit  GPIOR02_bit at GPIOR0.B2;
    const register unsigned short int GPIOR01 = 1;
    sbit  GPIOR01_bit at GPIOR0.B1;
    const register unsigned short int GPIOR00 = 0;
    sbit  GPIOR00_bit at GPIOR0.B0;

sfr data unsigned char volatile PLLCSR                    absolute 0x0087;
    const register unsigned short int PLLF0 = 2;
    sbit  PLLF0_bit at PLLCSR.B2;
    const register unsigned short int PLLF1 = 3;
    sbit  PLLF1_bit at PLLCSR.B3;
    const register unsigned short int PLLF2 = 4;
    sbit  PLLF2_bit at PLLCSR.B4;
    const register unsigned short int PLLF3 = 5;
    sbit  PLLF3_bit at PLLCSR.B5;
    const register unsigned short int PLLE = 1;
    sbit  PLLE_bit at PLLCSR.B1;
    const register unsigned short int PLOCK = 0;
    sbit  PLOCK_bit at PLLCSR.B0;

sfr data unsigned char volatile PRR                       absolute 0x0086;
    const register unsigned short int PRPSC2 = 7;
    sbit  PRPSC2_bit at PRR.B7;
    const register unsigned short int PRPSCR = 5;
    sbit  PRPSCR_bit at PRR.B5;
    const register unsigned short int PRTIM1 = 4;
    sbit  PRTIM1_bit at PRR.B4;
    const register unsigned short int PRSPI = 2;
    sbit  PRSPI_bit at PRR.B2;
    const register unsigned short int PRADC = 0;
    sbit  PRADC_bit at PRR.B0;

sfr data unsigned char volatile CLKCSR                    absolute 0x0084;
    const register unsigned short int CLKCCE = 7;
    sbit  CLKCCE_bit at CLKCSR.B7;
    const register unsigned short int CLKRDY = 4;
    sbit  CLKRDY_bit at CLKCSR.B4;
    const register unsigned short int CLKC0 = 0;
    sbit  CLKC0_bit at CLKCSR.B0;
    const register unsigned short int CLKC1 = 1;
    sbit  CLKC1_bit at CLKCSR.B1;
    const register unsigned short int CLKC2 = 2;
    sbit  CLKC2_bit at CLKCSR.B2;
    const register unsigned short int CLKC3 = 3;
    sbit  CLKC3_bit at CLKCSR.B3;

sfr data unsigned char volatile CLKSELR                   absolute 0x0085;
    const register unsigned short int COUT = 6;
    sbit  COUT_bit at CLKSELR.B6;
    const register unsigned short int CSUT0 = 4;
    sbit  CSUT0_bit at CLKSELR.B4;
    const register unsigned short int CSUT1 = 5;
    sbit  CSUT1_bit at CLKSELR.B5;
    const register unsigned short int CKSEL0 = 0;
    sbit  CKSEL0_bit at CLKSELR.B0;
    const register unsigned short int CKSEL1 = 1;
    sbit  CKSEL1_bit at CLKSELR.B1;
    const register unsigned short int CKSEL2 = 2;
    sbit  CKSEL2_bit at CLKSELR.B2;
    const register unsigned short int CKSEL3 = 3;
    sbit  CKSEL3_bit at CLKSELR.B3;

sfr data unsigned char volatile BGCCR                     absolute 0x0081;
    const register unsigned short int BGCC0 = 0;
    sbit  BGCC0_bit at BGCCR.B0;
    const register unsigned short int BGCC1 = 1;
    sbit  BGCC1_bit at BGCCR.B1;
    const register unsigned short int BGCC2 = 2;
    sbit  BGCC2_bit at BGCCR.B2;
    const register unsigned short int BGCC3 = 3;
    sbit  BGCC3_bit at BGCCR.B3;

sfr data unsigned char volatile BGCRR                     absolute 0x0080;
    const register unsigned short int BGCR0 = 0;
    sbit  BGCR0_bit at BGCRR.B0;
    const register unsigned short int BGCR1 = 1;
    sbit  BGCR1_bit at BGCRR.B1;
    const register unsigned short int BGCR2 = 2;
    sbit  BGCR2_bit at BGCRR.B2;
    const register unsigned short int BGCR3 = 3;
    sbit  BGCR3_bit at BGCRR.B3;

sfr io   unsigned int  volatile EEAR                      absolute 0x003E;
sfr io   unsigned char volatile EEARL                     absolute 0x003E;
sfr io   unsigned char volatile EEARH                     absolute 0x003F;
sfr io   unsigned char volatile EEDR                      absolute 0x003D;
sfr io   unsigned char volatile EECR                      absolute 0x003C;
    const register unsigned short int NVMBSY = 7;
    sbit  NVMBSY_bit at EECR.B7;
    const register unsigned short int EEPAGE = 6;
    sbit  EEPAGE_bit at EECR.B6;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM1 = 5;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EERIE = 3;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EEMWE = 2;
    sbit  EEMWE_bit at EECR.B2;
    const register unsigned short int EEWE = 1;
    sbit  EEWE_bit at EECR.B1;
    const register unsigned short int EERE = 0;
    sbit  EERE_bit at EECR.B0;

sfr data unsigned int  volatile PICR0                     absolute 0x0068;
sfr data unsigned char volatile PFRC0B                    absolute 0x0063;
    const register unsigned short int PCAE0B = 7;
    sbit  PCAE0B_bit at PFRC0B.B7;
    const register unsigned short int PISEL0B = 6;
    sbit  PISEL0B_bit at PFRC0B.B6;
    const register unsigned short int PELEV0B = 5;
    sbit  PELEV0B_bit at PFRC0B.B5;
    const register unsigned short int PFLTE0B = 4;
    sbit  PFLTE0B_bit at PFRC0B.B4;
    const register unsigned short int PRFM0B0 = 0;
    sbit  PRFM0B0_bit at PFRC0B.B0;
    const register unsigned short int PRFM0B1 = 1;
    sbit  PRFM0B1_bit at PFRC0B.B1;
    const register unsigned short int PRFM0B2 = 2;
    sbit  PRFM0B2_bit at PFRC0B.B2;
    const register unsigned short int PRFM0B3 = 3;
    sbit  PRFM0B3_bit at PFRC0B.B3;

sfr data unsigned char volatile PFRC0A                    absolute 0x0062;
    const register unsigned short int PCAE0A = 7;
    sbit  PCAE0A_bit at PFRC0A.B7;
    const register unsigned short int PISEL0A = 6;
    sbit  PISEL0A_bit at PFRC0A.B6;
    const register unsigned short int PELEV0A = 5;
    sbit  PELEV0A_bit at PFRC0A.B5;
    const register unsigned short int PFLTE0A = 4;
    sbit  PFLTE0A_bit at PFRC0A.B4;
    const register unsigned short int PRFM0A0 = 0;
    sbit  PRFM0A0_bit at PFRC0A.B0;
    const register unsigned short int PRFM0A1 = 1;
    sbit  PRFM0A1_bit at PFRC0A.B1;
    const register unsigned short int PRFM0A2 = 2;
    sbit  PRFM0A2_bit at PFRC0A.B2;
    const register unsigned short int PRFM0A3 = 3;
    sbit  PRFM0A3_bit at PFRC0A.B3;

sfr io   unsigned char volatile PCTL0                     absolute 0x0032;
    const register unsigned short int PPRE00 = 6;
    sbit  PPRE00_bit at PCTL0.B6;
    const register unsigned short int PPRE01 = 7;
    sbit  PPRE01_bit at PCTL0.B7;
    const register unsigned short int PBFM00 = 2;
    sbit  PBFM00_bit at PCTL0.B2;
    const register unsigned short int PBFM01 = 5;
    sbit  PBFM01_bit at PCTL0.B5;
    const register unsigned short int PAOC0B = 4;
    sbit  PAOC0B_bit at PCTL0.B4;
    const register unsigned short int PAOC0A = 3;
    sbit  PAOC0A_bit at PCTL0.B3;
    const register unsigned short int PCCYC0 = 1;
    sbit  PCCYC0_bit at PCTL0.B1;
    const register unsigned short int PRUN0 = 0;
    sbit  PRUN0_bit at PCTL0.B0;

sfr io   unsigned char volatile PCNF0                     absolute 0x0031;
    const register unsigned short int PFIFTY0 = 7;
    sbit  PFIFTY0_bit at PCNF0.B7;
    const register unsigned short int PALOCK0 = 6;
    sbit  PALOCK0_bit at PCNF0.B6;
    const register unsigned short int PLOCK0 = 5;
    sbit  PLOCK0_bit at PCNF0.B5;
    const register unsigned short int PMODE00 = 3;
    sbit  PMODE00_bit at PCNF0.B3;
    const register unsigned short int PMODE01 = 4;
    sbit  PMODE01_bit at PCNF0.B4;
    const register unsigned short int POP0 = 2;
    sbit  POP0_bit at PCNF0.B2;
    const register unsigned short int PCLKSEL0 = 1;
    sbit  PCLKSEL0_bit at PCNF0.B1;

sfr io   unsigned int  volatile OCR0RB                    absolute 0x0044;
sfr io   unsigned int  volatile OCR0SB                    absolute 0x0042;
sfr io   unsigned int  volatile OCR0RA                    absolute 0x004A;
sfr data unsigned int  volatile OCR0SA                    absolute 0x0060;
sfr data unsigned char volatile PSOC0                     absolute 0x006A;
    const register unsigned short int PISEL0A1 = 7;
    sbit  PISEL0A1_bit at PSOC0.B7;
    const register unsigned short int PISEL0B1 = 6;
    sbit  PISEL0B1_bit at PSOC0.B6;
    const register unsigned short int PSYNC00 = 4;
    sbit  PSYNC00_bit at PSOC0.B4;
    const register unsigned short int PSYNC01 = 5;
    sbit  PSYNC01_bit at PSOC0.B5;
    const register unsigned short int POEN0B = 2;
    sbit  POEN0B_bit at PSOC0.B2;
    const register unsigned short int POEN0A = 0;
    sbit  POEN0A_bit at PSOC0.B0;

sfr io   unsigned char volatile PIM0                      absolute 0x002F;
    const register unsigned short int PEVE0B = 4;
    sbit  PEVE0B_bit at PIM0.B4;
    const register unsigned short int PEVE0A = 3;
    sbit  PEVE0A_bit at PIM0.B3;
    const register unsigned short int PEOEPE0 = 1;
    sbit  PEOEPE0_bit at PIM0.B1;
    const register unsigned short int PEOPE0 = 0;
    sbit  PEOPE0_bit at PIM0.B0;

sfr io   unsigned char volatile PIFR0                     absolute 0x0030;
    const register unsigned short int POAC0B = 7;
    sbit  POAC0B_bit at PIFR0.B7;
    const register unsigned short int POAC0A = 6;
    sbit  POAC0A_bit at PIFR0.B6;
    const register unsigned short int PEV0B = 4;
    sbit  PEV0B_bit at PIFR0.B4;
    const register unsigned short int PEV0A = 3;
    sbit  PEV0A_bit at PIFR0.B3;
    const register unsigned short int PRN00 = 1;
    sbit  PRN00_bit at PIFR0.B1;
    const register unsigned short int PRN01 = 2;
    sbit  PRN01_bit at PIFR0.B2;
    const register unsigned short int PEOP0 = 0;
    sbit  PEOP0_bit at PIFR0.B0;

sfr data unsigned char volatile PICR2H                    absolute 0x006D;
    const register unsigned short int PCST2 = 7;
    sbit  PCST2_bit at PICR2H.B7;
    const register unsigned short int PICR210 = 2;
    sbit  PICR210_bit at PICR2H.B2;
    const register unsigned short int PICR211 = 3;
    sbit  PICR211_bit at PICR2H.B3;
    const register unsigned short int PICR20 = 0;
    sbit  PICR20_bit at PICR2H.B0;
    const register unsigned short int PICR21 = 1;
    sbit  PICR21_bit at PICR2H.B1;

sfr data unsigned char volatile PICR2L                    absolute 0x006C;
sfr data unsigned char volatile PFRC2B                    absolute 0x0067;
    const register unsigned short int PCAE2B = 7;
    sbit  PCAE2B_bit at PFRC2B.B7;
    const register unsigned short int PISEL2B = 6;
    sbit  PISEL2B_bit at PFRC2B.B6;
    const register unsigned short int PELEV2B = 5;
    sbit  PELEV2B_bit at PFRC2B.B5;
    const register unsigned short int PFLTE2B = 4;
    sbit  PFLTE2B_bit at PFRC2B.B4;
    const register unsigned short int PRFM2B0 = 0;
    sbit  PRFM2B0_bit at PFRC2B.B0;
    const register unsigned short int PRFM2B1 = 1;
    sbit  PRFM2B1_bit at PFRC2B.B1;
    const register unsigned short int PRFM2B2 = 2;
    sbit  PRFM2B2_bit at PFRC2B.B2;
    const register unsigned short int PRFM2B3 = 3;
    sbit  PRFM2B3_bit at PFRC2B.B3;

sfr data unsigned char volatile PFRC2A                    absolute 0x0066;
    const register unsigned short int PCAE2A = 7;
    sbit  PCAE2A_bit at PFRC2A.B7;
    const register unsigned short int PISEL2A = 6;
    sbit  PISEL2A_bit at PFRC2A.B6;
    const register unsigned short int PELEV2A = 5;
    sbit  PELEV2A_bit at PFRC2A.B5;
    const register unsigned short int PFLTE2A = 4;
    sbit  PFLTE2A_bit at PFRC2A.B4;
    const register unsigned short int PRFM2A0 = 0;
    sbit  PRFM2A0_bit at PFRC2A.B0;
    const register unsigned short int PRFM2A1 = 1;
    sbit  PRFM2A1_bit at PFRC2A.B1;
    const register unsigned short int PRFM2A2 = 2;
    sbit  PRFM2A2_bit at PFRC2A.B2;
    const register unsigned short int PRFM2A3 = 3;
    sbit  PRFM2A3_bit at PFRC2A.B3;

sfr io   unsigned char volatile PCTL2                     absolute 0x0036;
    const register unsigned short int PPRE20 = 6;
    sbit  PPRE20_bit at PCTL2.B6;
    const register unsigned short int PPRE21 = 7;
    sbit  PPRE21_bit at PCTL2.B7;
    const register unsigned short int PBFM2 = 5;
    sbit  PBFM2_bit at PCTL2.B5;
    const register unsigned short int PAOC2B = 4;
    sbit  PAOC2B_bit at PCTL2.B4;
    const register unsigned short int PAOC2A = 3;
    sbit  PAOC2A_bit at PCTL2.B3;
    const register unsigned short int PARUN2 = 2;
    sbit  PARUN2_bit at PCTL2.B2;
    const register unsigned short int PCCYC2 = 1;
    sbit  PCCYC2_bit at PCTL2.B1;
    const register unsigned short int PRUN2 = 0;
    sbit  PRUN2_bit at PCTL2.B0;

sfr io   unsigned char volatile PCNF2                     absolute 0x0035;
    const register unsigned short int PFIFTY2 = 7;
    sbit  PFIFTY2_bit at PCNF2.B7;
    const register unsigned short int PALOCK2 = 6;
    sbit  PALOCK2_bit at PCNF2.B6;
    const register unsigned short int PLOCK2 = 5;
    sbit  PLOCK2_bit at PCNF2.B5;
    const register unsigned short int PMODE20 = 3;
    sbit  PMODE20_bit at PCNF2.B3;
    const register unsigned short int PMODE21 = 4;
    sbit  PMODE21_bit at PCNF2.B4;
    const register unsigned short int POP2 = 2;
    sbit  POP2_bit at PCNF2.B2;
    const register unsigned short int PCLKSEL2 = 1;
    sbit  PCLKSEL2_bit at PCNF2.B1;
    const register unsigned short int POME2 = 0;
    sbit  POME2_bit at PCNF2.B0;

sfr data unsigned char volatile PCNFE2                    absolute 0x0070;
    const register unsigned short int PASDLK20 = 5;
    sbit  PASDLK20_bit at PCNFE2.B5;
    const register unsigned short int PASDLK21 = 6;
    sbit  PASDLK21_bit at PCNFE2.B6;
    const register unsigned short int PASDLK22 = 7;
    sbit  PASDLK22_bit at PCNFE2.B7;
    const register unsigned short int PBFM21 = 4;
    sbit  PBFM21_bit at PCNFE2.B4;
    const register unsigned short int PELEV2A1 = 3;
    sbit  PELEV2A1_bit at PCNFE2.B3;
    const register unsigned short int PELEV2B1 = 2;
    sbit  PELEV2B1_bit at PCNFE2.B2;
    const register unsigned short int PISEL2A1 = 1;
    sbit  PISEL2A1_bit at PCNFE2.B1;
    const register unsigned short int PISEL2B1 = 0;
    sbit  PISEL2B1_bit at PCNFE2.B0;

sfr io   unsigned int  volatile OCR2RB                    absolute 0x0048;
sfr io   unsigned int  volatile OCR2SB                    absolute 0x0046;
sfr io   unsigned int  volatile OCR2RA                    absolute 0x004E;
sfr data unsigned int  volatile OCR2SA                    absolute 0x0064;
sfr data unsigned char volatile POM2                      absolute 0x006F;
    const register unsigned short int POMV2B0 = 4;
    sbit  POMV2B0_bit at POM2.B4;
    const register unsigned short int POMV2B1 = 5;
    sbit  POMV2B1_bit at POM2.B5;
    const register unsigned short int POMV2B2 = 6;
    sbit  POMV2B2_bit at POM2.B6;
    const register unsigned short int POMV2B3 = 7;
    sbit  POMV2B3_bit at POM2.B7;
    const register unsigned short int POMV2A0 = 0;
    sbit  POMV2A0_bit at POM2.B0;
    const register unsigned short int POMV2A1 = 1;
    sbit  POMV2A1_bit at POM2.B1;
    const register unsigned short int POMV2A2 = 2;
    sbit  POMV2A2_bit at POM2.B2;
    const register unsigned short int POMV2A3 = 3;
    sbit  POMV2A3_bit at POM2.B3;

sfr data unsigned char volatile PSOC2                     absolute 0x006E;
    const register unsigned short int POS20 = 6;
    sbit  POS20_bit at PSOC2.B6;
    const register unsigned short int POS21 = 7;
    sbit  POS21_bit at PSOC2.B7;
    const register unsigned short int PSYNC20 = 4;
    sbit  PSYNC20_bit at PSOC2.B4;
    const register unsigned short int PSYNC21 = 5;
    sbit  PSYNC21_bit at PSOC2.B5;
    const register unsigned short int POEN2D = 3;
    sbit  POEN2D_bit at PSOC2.B3;
    const register unsigned short int POEN2B = 2;
    sbit  POEN2B_bit at PSOC2.B2;
    const register unsigned short int POEN2C = 1;
    sbit  POEN2C_bit at PSOC2.B1;
    const register unsigned short int POEN2A = 0;
    sbit  POEN2A_bit at PSOC2.B0;

sfr io   unsigned char volatile PIM2                      absolute 0x0033;
    const register unsigned short int PSEIE2 = 5;
    sbit  PSEIE2_bit at PIM2.B5;
    const register unsigned short int PEVE2B = 4;
    sbit  PEVE2B_bit at PIM2.B4;
    const register unsigned short int PEVE2A = 3;
    sbit  PEVE2A_bit at PIM2.B3;
    const register unsigned short int PEOEPE2 = 1;
    sbit  PEOEPE2_bit at PIM2.B1;
    const register unsigned short int PEOPE2 = 0;
    sbit  PEOPE2_bit at PIM2.B0;

sfr io   unsigned char volatile PIFR2                     absolute 0x0034;
    const register unsigned short int POAC2B = 7;
    sbit  POAC2B_bit at PIFR2.B7;
    const register unsigned short int POAC2A = 6;
    sbit  POAC2A_bit at PIFR2.B6;
    const register unsigned short int PSEI2 = 5;
    sbit  PSEI2_bit at PIFR2.B5;
    const register unsigned short int PEV2B = 4;
    sbit  PEV2B_bit at PIFR2.B4;
    const register unsigned short int PEV2A = 3;
    sbit  PEV2A_bit at PIFR2.B3;
    const register unsigned short int PRN20 = 1;
    sbit  PRN20_bit at PIFR2.B1;
    const register unsigned short int PRN21 = 2;
    sbit  PRN21_bit at PIFR2.B2;
    const register unsigned short int PEOP2 = 0;
    sbit  PEOP2_bit at PIFR2.B0;

sfr data unsigned char volatile PASDLY2                   absolute 0x0071;
sfr io   unsigned char TIMSK1                    absolute 0x0021;
    const register unsigned short int ICIE1 = 5;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int TOIE1 = 0;
    sbit  TOIE1_bit at TIMSK1.B0;

sfr io   unsigned char volatile TIFR1                     absolute 0x0022;
    const register unsigned short int ICF1 = 5;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int TOV1 = 0;
    sbit  TOV1_bit at TIFR1.B0;

sfr data unsigned char TCCR1B                    absolute 0x008A;
    const register unsigned short int ICNC1 = 7;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICES1 = 6;
    sbit  ICES1_bit at TCCR1B.B6;
    const register unsigned short int WGM13 = 4;
    sbit  WGM13_bit at TCCR1B.B4;
    const register unsigned short int CS10 = 0;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS11 = 1;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS12 = 2;
    sbit  CS12_bit at TCCR1B.B2;

sfr io   unsigned int  volatile TCNT1                     absolute 0x005A;
sfr io   unsigned char volatile TCNT1L                    absolute 0x005A;
sfr io   unsigned char volatile TCNT1H                    absolute 0x005B;
sfr data unsigned int  volatile ICR1                      absolute 0x008C;
sfr io   unsigned char volatile SPMCSR                    absolute 0x0057;
    const register unsigned short int SPMIE = 7;
    sbit  SPMIE_bit at SPMCSR.B7;
    const register unsigned short int RWWSB = 6;
    sbit  RWWSB_bit at SPMCSR.B6;
    const register unsigned short int SIGRD = 5;
    sbit  SIGRD_bit at SPMCSR.B5;
    const register unsigned short int RWWSRE = 4;
    sbit  RWWSRE_bit at SPMCSR.B4;
    const register unsigned short int BLBSET = 3;
    sbit  BLBSET_bit at SPMCSR.B3;
    const register unsigned short int PGWRT = 2;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGERS = 1;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int SPMEN = 0;
    sbit  SPMEN_bit at SPMCSR.B0;

sfr io   unsigned char volatile EXTENDED_                 absolute 0x0002;
    const register unsigned short int PSC2RB = 7;
    sbit  PSC2RB_bit at EXTENDED_.B7;
    const register unsigned short int PSC2RBA = 6;
    sbit  PSC2RBA_bit at EXTENDED_.B6;
    const register unsigned short int PSC0RB = 5;
    sbit  PSC0RB_bit at EXTENDED_.B5;
    const register unsigned short int PSCRV = 4;
    sbit  PSCRV_bit at EXTENDED_.B4;
    const register unsigned short int PSCINRB = 3;
    sbit  PSCINRB_bit at EXTENDED_.B3;
    const register unsigned short int BODLEVEL0 = 0;
    sbit  BODLEVEL0_bit at EXTENDED_.B0;
    const register unsigned short int BODLEVEL1 = 1;
    sbit  BODLEVEL1_bit at EXTENDED_.B1;
    const register unsigned short int BODLEVEL2 = 2;
    sbit  BODLEVEL2_bit at EXTENDED_.B2;

sfr io   unsigned char volatile HIGH                      absolute 0x0001;
    const register unsigned short int RSTDISBL = 7;
    sbit  RSTDISBL_bit at HIGH.B7;
    const register unsigned short int DWEN = 6;
    sbit  DWEN_bit at HIGH.B6;
    const register unsigned short int SPIEN = 5;
    sbit  SPIEN_bit at HIGH.B5;
    const register unsigned short int WDTON = 4;
    sbit  WDTON_bit at HIGH.B4;
    const register unsigned short int EESAVE = 3;
    sbit  EESAVE_bit at HIGH.B3;
    const register unsigned short int BOOTSZ0 = 1;
    sbit  BOOTSZ0_bit at HIGH.B1;
    const register unsigned short int BOOTSZ1 = 2;
    sbit  BOOTSZ1_bit at HIGH.B2;
    const register unsigned short int BOOTRST = 0;
    sbit  BOOTRST_bit at HIGH.B0;

sfr io   unsigned char volatile LOW                       absolute 0x0000;
    const register unsigned short int CKDIV8 = 7;
    sbit  CKDIV8_bit at LOW.B7;
    const register unsigned short int CKOUT = 6;
    sbit  CKOUT_bit at LOW.B6;
    const register unsigned short int SUT_CKSEL0 = 0;
    sbit  SUT_CKSEL0_bit at LOW.B0;
    const register unsigned short int SUT_CKSEL1 = 1;
    sbit  SUT_CKSEL1_bit at LOW.B1;
    const register unsigned short int SUT_CKSEL2 = 2;
    sbit  SUT_CKSEL2_bit at LOW.B2;
    const register unsigned short int SUT_CKSEL3 = 3;
    sbit  SUT_CKSEL3_bit at LOW.B3;
    const register unsigned short int SUT_CKSEL4 = 4;
    sbit  SUT_CKSEL4_bit at LOW.B4;
    const register unsigned short int SUT_CKSEL5 = 5;
    sbit  SUT_CKSEL5_bit at LOW.B5;

sfr io   unsigned char volatile LOCKBIT                   absolute 0x0000;
    const register unsigned short int LB0 = 0;
    sbit  LB0_bit at LOCKBIT.B0;
    const register unsigned short int LB1 = 1;
    sbit  LB1_bit at LOCKBIT.B1;
    const register unsigned short int BLB00 = 2;
    sbit  BLB00_bit at LOCKBIT.B2;
    const register unsigned short int BLB01 = 3;
    sbit  BLB01_bit at LOCKBIT.B3;
    const register unsigned short int BLB10 = 4;
    sbit  BLB10_bit at LOCKBIT.B4;
    const register unsigned short int BLB11 = 5;
    sbit  BLB11_bit at LOCKBIT.B5;

