// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00004000;

// Flash page size in program words
const int __FLASH_PAGE_SIZE = 64;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;

const unsigned int IVT_ADDR_RESET            = 0x0000;
const unsigned int IVT_ADDR_PSC2_CAPT        = 0x0002;
const unsigned int IVT_ADDR_PSC2_EC          = 0x0004;
const unsigned int IVT_ADDR_PSC1_CAPT        = 0x0006;
const unsigned int IVT_ADDR_PSC1_EC          = 0x0008;
const unsigned int IVT_ADDR_PSC0_CAPT        = 0x000A;
const unsigned int IVT_ADDR_PSC0_EC          = 0x000C;
const unsigned int IVT_ADDR_ANALOG_COMP_0    = 0x000E;
const unsigned int IVT_ADDR_ANALOG_COMP_1    = 0x0010;
const unsigned int IVT_ADDR_ANALOG_COMP_2    = 0x0012;
const unsigned int IVT_ADDR_INT0             = 0x0014;
const unsigned int IVT_ADDR_TIMER1_CAPT      = 0x0016;
const unsigned int IVT_ADDR_TIMER1_COMPA     = 0x0018;
const unsigned int IVT_ADDR_TIMER1_COMPB     = 0x001A;
const unsigned int IVT_ADDR_RESERVED15       = 0x001C;
const unsigned int IVT_ADDR_TIMER1_OVF       = 0x001E;
const unsigned int IVT_ADDR_TIMER0_COMP_A    = 0x0020;
const unsigned int IVT_ADDR_TIMER0_OVF       = 0x0022;
const unsigned int IVT_ADDR_ADC              = 0x0024;
const unsigned int IVT_ADDR_INT1             = 0x0026;
const unsigned int IVT_ADDR_SPI__STC         = 0x0028;
const unsigned int IVT_ADDR_USART__RX        = 0x002A;
const unsigned int IVT_ADDR_USART__UDRE      = 0x002C;
const unsigned int IVT_ADDR_USART__TX        = 0x002E;
const unsigned int IVT_ADDR_INT2             = 0x0030;
const unsigned int IVT_ADDR_WDT              = 0x0032;
const unsigned int IVT_ADDR_EE_READY         = 0x0034;
const unsigned int IVT_ADDR_TIMER0_COMPB     = 0x0036;
const unsigned int IVT_ADDR_INT3             = 0x0038;
const unsigned int IVT_ADDR_RESERVED30       = 0x003A;
const unsigned int IVT_ADDR_RESERVED31       = 0x003C;
const unsigned int IVT_ADDR_SPM_READY        = 0x003E;


sfr data unsigned short volatile PICR2H absolute 0xFF;
    sbit  PICR2_8_bit at PICR2H.B0;
    const register unsigned short int PICR2_8 = 0;
    sbit  PICR2_9_bit at PICR2H.B1;
    const register unsigned short int PICR2_9 = 1;
    sbit  PICR2_10_bit at PICR2H.B2;
    const register unsigned short int PICR2_10 = 2;
    sbit  PICR2_11_bit at PICR2H.B3;
    const register unsigned short int PICR2_11 = 3;
    sbit  PCST2_bit at PICR2H.B7;
    const register unsigned short int PCST2 = 7;

sfr data unsigned short volatile PICR2L absolute 0xFE;
    sbit  PICR2_0_bit at PICR2L.B0;
    const register unsigned short int PICR2_0 = 0;
    sbit  PICR2_1_bit at PICR2L.B1;
    const register unsigned short int PICR2_1 = 1;
    sbit  PICR2_2_bit at PICR2L.B2;
    const register unsigned short int PICR2_2 = 2;
    sbit  PICR2_3_bit at PICR2L.B3;
    const register unsigned short int PICR2_3 = 3;
    sbit  PICR2_4_bit at PICR2L.B4;
    const register unsigned short int PICR2_4 = 4;
    sbit  PICR2_5_bit at PICR2L.B5;
    const register unsigned short int PICR2_5 = 5;
    sbit  PICR2_6_bit at PICR2L.B6;
    const register unsigned short int PICR2_6 = 6;
    sbit  PICR2_7_bit at PICR2L.B7;
    const register unsigned short int PICR2_7 = 7;

sfr data unsigned short volatile PFRC2B absolute 0xFD;
    sbit  PRFM2B0_bit at PFRC2B.B0;
    const register unsigned short int PRFM2B0 = 0;
    sbit  PRFM2B1_bit at PFRC2B.B1;
    const register unsigned short int PRFM2B1 = 1;
    sbit  PRFM2B2_bit at PFRC2B.B2;
    const register unsigned short int PRFM2B2 = 2;
    sbit  PRFM2B3_bit at PFRC2B.B3;
    const register unsigned short int PRFM2B3 = 3;
    sbit  PFLTE2B_bit at PFRC2B.B4;
    const register unsigned short int PFLTE2B = 4;
    sbit  PELEV2B_bit at PFRC2B.B5;
    const register unsigned short int PELEV2B = 5;
    sbit  PISEL2B_bit at PFRC2B.B6;
    const register unsigned short int PISEL2B = 6;
    sbit  PCAE2B_bit at PFRC2B.B7;
    const register unsigned short int PCAE2B = 7;

sfr data unsigned short volatile PFRC2A absolute 0xFC;
    sbit  PRFM2A0_bit at PFRC2A.B0;
    const register unsigned short int PRFM2A0 = 0;
    sbit  PRFM2A1_bit at PFRC2A.B1;
    const register unsigned short int PRFM2A1 = 1;
    sbit  PRFM2A2_bit at PFRC2A.B2;
    const register unsigned short int PRFM2A2 = 2;
    sbit  PRFM2A3_bit at PFRC2A.B3;
    const register unsigned short int PRFM2A3 = 3;
    sbit  PFLTE2A_bit at PFRC2A.B4;
    const register unsigned short int PFLTE2A = 4;
    sbit  PELEV2A_bit at PFRC2A.B5;
    const register unsigned short int PELEV2A = 5;
    sbit  PISEL2A_bit at PFRC2A.B6;
    const register unsigned short int PISEL2A = 6;
    sbit  PCAE2A_bit at PFRC2A.B7;
    const register unsigned short int PCAE2A = 7;

sfr data unsigned short volatile PCTL2 absolute 0xFB;
    sbit  PRUN2_bit at PCTL2.B0;
    const register unsigned short int PRUN2 = 0;
    sbit  PCCYC2_bit at PCTL2.B1;
    const register unsigned short int PCCYC2 = 1;
    sbit  PARUN2_bit at PCTL2.B2;
    const register unsigned short int PARUN2 = 2;
    sbit  PAOC2A_bit at PCTL2.B3;
    const register unsigned short int PAOC2A = 3;
    sbit  PAOC2B_bit at PCTL2.B4;
    const register unsigned short int PAOC2B = 4;
    sbit  PBFM2_bit at PCTL2.B5;
    const register unsigned short int PBFM2 = 5;
    sbit  PPRE20_bit at PCTL2.B6;
    const register unsigned short int PPRE20 = 6;
    sbit  PPRE21_bit at PCTL2.B7;
    const register unsigned short int PPRE21 = 7;

sfr data unsigned short volatile PCNF2 absolute 0xFA;
    sbit  POME2_bit at PCNF2.B0;
    const register unsigned short int POME2 = 0;
    sbit  PCLKSEL2_bit at PCNF2.B1;
    const register unsigned short int PCLKSEL2 = 1;
    sbit  POP2_bit at PCNF2.B2;
    const register unsigned short int POP2 = 2;
    sbit  PMODE20_bit at PCNF2.B3;
    const register unsigned short int PMODE20 = 3;
    sbit  PMODE21_bit at PCNF2.B4;
    const register unsigned short int PMODE21 = 4;
    sbit  PLOCK2_bit at PCNF2.B5;
    const register unsigned short int PLOCK2 = 5;
    sbit  PALOCK2_bit at PCNF2.B6;
    const register unsigned short int PALOCK2 = 6;
    sbit  PFIFTY2_bit at PCNF2.B7;
    const register unsigned short int PFIFTY2 = 7;

sfr data unsigned short volatile OCR2RBH absolute 0xF9;
    sbit  OCR2RB_8_bit at OCR2RBH.B0;
    const register unsigned short int OCR2RB_8 = 0;
    sbit  OCR2RB_9_bit at OCR2RBH.B1;
    const register unsigned short int OCR2RB_9 = 1;
    sbit  OCR2RB_10_bit at OCR2RBH.B2;
    const register unsigned short int OCR2RB_10 = 2;
    sbit  OCR2RB_11_bit at OCR2RBH.B3;
    const register unsigned short int OCR2RB_11 = 3;
    sbit  OCR2RB_12_bit at OCR2RBH.B4;
    const register unsigned short int OCR2RB_12 = 4;
    sbit  OCR2RB_13_bit at OCR2RBH.B5;
    const register unsigned short int OCR2RB_13 = 5;
    sbit  OCR2RB_14_bit at OCR2RBH.B6;
    const register unsigned short int OCR2RB_14 = 6;
    sbit  OCR2RB_15_bit at OCR2RBH.B7;
    const register unsigned short int OCR2RB_15 = 7;

sfr data unsigned short volatile OCR2RBL absolute 0xF8;
    sbit  OCR2RB_0_bit at OCR2RBL.B0;
    const register unsigned short int OCR2RB_0 = 0;
    sbit  OCR2RB_1_bit at OCR2RBL.B1;
    const register unsigned short int OCR2RB_1 = 1;
    sbit  OCR2RB_2_bit at OCR2RBL.B2;
    const register unsigned short int OCR2RB_2 = 2;
    sbit  OCR2RB_3_bit at OCR2RBL.B3;
    const register unsigned short int OCR2RB_3 = 3;
    sbit  OCR2RB_4_bit at OCR2RBL.B4;
    const register unsigned short int OCR2RB_4 = 4;
    sbit  OCR2RB_5_bit at OCR2RBL.B5;
    const register unsigned short int OCR2RB_5 = 5;
    sbit  OCR2RB_6_bit at OCR2RBL.B6;
    const register unsigned short int OCR2RB_6 = 6;
    sbit  OCR2RB_7_bit at OCR2RBL.B7;
    const register unsigned short int OCR2RB_7 = 7;

sfr data unsigned short volatile OCR2SBH absolute 0xF7;
    sbit  OCR2SB_8_bit at OCR2SBH.B0;
    const register unsigned short int OCR2SB_8 = 0;
    sbit  OCR2SB_9_bit at OCR2SBH.B1;
    const register unsigned short int OCR2SB_9 = 1;
    sbit  OCR2SB_10_bit at OCR2SBH.B2;
    const register unsigned short int OCR2SB_10 = 2;
    sbit  OCR2SB_11_bit at OCR2SBH.B3;
    const register unsigned short int OCR2SB_11 = 3;

sfr data unsigned short volatile OCR2SBL absolute 0xF6;
    sbit  OCR2SB_0_bit at OCR2SBL.B0;
    const register unsigned short int OCR2SB_0 = 0;
    sbit  OCR2SB_1_bit at OCR2SBL.B1;
    const register unsigned short int OCR2SB_1 = 1;
    sbit  OCR2SB_2_bit at OCR2SBL.B2;
    const register unsigned short int OCR2SB_2 = 2;
    sbit  OCR2SB_3_bit at OCR2SBL.B3;
    const register unsigned short int OCR2SB_3 = 3;
    sbit  OCR2SB_4_bit at OCR2SBL.B4;
    const register unsigned short int OCR2SB_4 = 4;
    sbit  OCR2SB_5_bit at OCR2SBL.B5;
    const register unsigned short int OCR2SB_5 = 5;
    sbit  OCR2SB_6_bit at OCR2SBL.B6;
    const register unsigned short int OCR2SB_6 = 6;
    sbit  OCR2SB_7_bit at OCR2SBL.B7;
    const register unsigned short int OCR2SB_7 = 7;

sfr data unsigned short volatile OCR2RAH absolute 0xF5;
    sbit  OCR2RA_8_bit at OCR2RAH.B0;
    const register unsigned short int OCR2RA_8 = 0;
    sbit  OCR2RA_9_bit at OCR2RAH.B1;
    const register unsigned short int OCR2RA_9 = 1;
    sbit  OCR2RA_10_bit at OCR2RAH.B2;
    const register unsigned short int OCR2RA_10 = 2;
    sbit  OCR2RA_11_bit at OCR2RAH.B3;
    const register unsigned short int OCR2RA_11 = 3;

sfr data unsigned short volatile OCR2RAL absolute 0xF4;
    sbit  OCR2RA_0_bit at OCR2RAL.B0;
    const register unsigned short int OCR2RA_0 = 0;
    sbit  OCR2RA_1_bit at OCR2RAL.B1;
    const register unsigned short int OCR2RA_1 = 1;
    sbit  OCR2RA_2_bit at OCR2RAL.B2;
    const register unsigned short int OCR2RA_2 = 2;
    sbit  OCR2RA_3_bit at OCR2RAL.B3;
    const register unsigned short int OCR2RA_3 = 3;
    sbit  OCR2RA_4_bit at OCR2RAL.B4;
    const register unsigned short int OCR2RA_4 = 4;
    sbit  OCR2RA_5_bit at OCR2RAL.B5;
    const register unsigned short int OCR2RA_5 = 5;
    sbit  OCR2RA_6_bit at OCR2RAL.B6;
    const register unsigned short int OCR2RA_6 = 6;
    sbit  OCR2RA_7_bit at OCR2RAL.B7;
    const register unsigned short int OCR2RA_7 = 7;

sfr data unsigned short volatile OCR2SAH absolute 0xF3;
    sbit  OCR2SA_8_bit at OCR2SAH.B0;
    const register unsigned short int OCR2SA_8 = 0;
    sbit  OCR2SA_9_bit at OCR2SAH.B1;
    const register unsigned short int OCR2SA_9 = 1;
    sbit  OCR2SA_10_bit at OCR2SAH.B2;
    const register unsigned short int OCR2SA_10 = 2;
    sbit  OCR2SA_11_bit at OCR2SAH.B3;
    const register unsigned short int OCR2SA_11 = 3;

sfr data unsigned short volatile OCR2SAL absolute 0xF2;
    sbit  OCR2SA_0_bit at OCR2SAL.B0;
    const register unsigned short int OCR2SA_0 = 0;
    sbit  OCR2SA_1_bit at OCR2SAL.B1;
    const register unsigned short int OCR2SA_1 = 1;
    sbit  OCR2SA_2_bit at OCR2SAL.B2;
    const register unsigned short int OCR2SA_2 = 2;
    sbit  OCR2SA_3_bit at OCR2SAL.B3;
    const register unsigned short int OCR2SA_3 = 3;
    sbit  OCR2SA_4_bit at OCR2SAL.B4;
    const register unsigned short int OCR2SA_4 = 4;
    sbit  OCR2SA_5_bit at OCR2SAL.B5;
    const register unsigned short int OCR2SA_5 = 5;
    sbit  OCR2SA_6_bit at OCR2SAL.B6;
    const register unsigned short int OCR2SA_6 = 6;
    sbit  OCR2SA_7_bit at OCR2SAL.B7;
    const register unsigned short int OCR2SA_7 = 7;

sfr data unsigned short volatile POM2 absolute 0xF1;
    sbit  POMV2A0_bit at POM2.B0;
    const register unsigned short int POMV2A0 = 0;
    sbit  POMV2A1_bit at POM2.B1;
    const register unsigned short int POMV2A1 = 1;
    sbit  POMV2A2_bit at POM2.B2;
    const register unsigned short int POMV2A2 = 2;
    sbit  POMV2A3_bit at POM2.B3;
    const register unsigned short int POMV2A3 = 3;
    sbit  POMV2B0_bit at POM2.B4;
    const register unsigned short int POMV2B0 = 4;
    sbit  POMV2B1_bit at POM2.B5;
    const register unsigned short int POMV2B1 = 5;
    sbit  POMV2B2_bit at POM2.B6;
    const register unsigned short int POMV2B2 = 6;
    sbit  POMV2B3_bit at POM2.B7;
    const register unsigned short int POMV2B3 = 7;

sfr data unsigned short volatile PSOC2 absolute 0xF0;
    sbit  POEN2A_bit at PSOC2.B0;
    const register unsigned short int POEN2A = 0;
    sbit  POEN2C_bit at PSOC2.B1;
    const register unsigned short int POEN2C = 1;
    sbit  POEN2B_bit at PSOC2.B2;
    const register unsigned short int POEN2B = 2;
    sbit  POEN2D_bit at PSOC2.B3;
    const register unsigned short int POEN2D = 3;
    sbit  PSYNC2_0_bit at PSOC2.B4;
    const register unsigned short int PSYNC2_0 = 4;
    sbit  PSYNC2_1_bit at PSOC2.B5;
    const register unsigned short int PSYNC2_1 = 5;
    sbit  POS22_bit at PSOC2.B6;
    const register unsigned short int POS22 = 6;
    sbit  POS23_bit at PSOC2.B7;
    const register unsigned short int POS23 = 7;

sfr data unsigned short volatile PICR0H absolute 0xDF;
    sbit  PICR0_8_bit at PICR0H.B0;
    const register unsigned short int PICR0_8 = 0;
    sbit  PICR0_9_bit at PICR0H.B1;
    const register unsigned short int PICR0_9 = 1;
    sbit  PICR0_10_bit at PICR0H.B2;
    const register unsigned short int PICR0_10 = 2;
    sbit  PICR0_11_bit at PICR0H.B3;
    const register unsigned short int PICR0_11 = 3;
    sbit  PCST0_bit at PICR0H.B7;
    const register unsigned short int PCST0 = 7;

sfr data unsigned short volatile PICR0L absolute 0xDE;
    sbit  PICR0_0_bit at PICR0L.B0;
    const register unsigned short int PICR0_0 = 0;
    sbit  PICR0_1_bit at PICR0L.B1;
    const register unsigned short int PICR0_1 = 1;
    sbit  PICR0_2_bit at PICR0L.B2;
    const register unsigned short int PICR0_2 = 2;
    sbit  PICR0_3_bit at PICR0L.B3;
    const register unsigned short int PICR0_3 = 3;
    sbit  PICR0_4_bit at PICR0L.B4;
    const register unsigned short int PICR0_4 = 4;
    sbit  PICR0_5_bit at PICR0L.B5;
    const register unsigned short int PICR0_5 = 5;
    sbit  PICR0_6_bit at PICR0L.B6;
    const register unsigned short int PICR0_6 = 6;
    sbit  PICR0_7_bit at PICR0L.B7;
    const register unsigned short int PICR0_7 = 7;

sfr data unsigned short volatile PFRC0B absolute 0xDD;
    sbit  PRFM0B0_bit at PFRC0B.B0;
    const register unsigned short int PRFM0B0 = 0;
    sbit  PRFM0B1_bit at PFRC0B.B1;
    const register unsigned short int PRFM0B1 = 1;
    sbit  PRFM0B2_bit at PFRC0B.B2;
    const register unsigned short int PRFM0B2 = 2;
    sbit  PRFM0B3_bit at PFRC0B.B3;
    const register unsigned short int PRFM0B3 = 3;
    sbit  PFLTE0B_bit at PFRC0B.B4;
    const register unsigned short int PFLTE0B = 4;
    sbit  PELEV0B_bit at PFRC0B.B5;
    const register unsigned short int PELEV0B = 5;
    sbit  PISEL0B_bit at PFRC0B.B6;
    const register unsigned short int PISEL0B = 6;
    sbit  PCAE0B_bit at PFRC0B.B7;
    const register unsigned short int PCAE0B = 7;

sfr data unsigned short volatile PFRC0A absolute 0xDC;
    sbit  PRFM0A0_bit at PFRC0A.B0;
    const register unsigned short int PRFM0A0 = 0;
    sbit  PRFM0A1_bit at PFRC0A.B1;
    const register unsigned short int PRFM0A1 = 1;
    sbit  PRFM0A2_bit at PFRC0A.B2;
    const register unsigned short int PRFM0A2 = 2;
    sbit  PRFM0A3_bit at PFRC0A.B3;
    const register unsigned short int PRFM0A3 = 3;
    sbit  PFLTE0A_bit at PFRC0A.B4;
    const register unsigned short int PFLTE0A = 4;
    sbit  PELEV0A_bit at PFRC0A.B5;
    const register unsigned short int PELEV0A = 5;
    sbit  PISEL0A_bit at PFRC0A.B6;
    const register unsigned short int PISEL0A = 6;
    sbit  PCAE0A_bit at PFRC0A.B7;
    const register unsigned short int PCAE0A = 7;

sfr data unsigned short volatile PCTL0 absolute 0xDB;
    sbit  PRUN0_bit at PCTL0.B0;
    const register unsigned short int PRUN0 = 0;
    sbit  PCCYC0_bit at PCTL0.B1;
    const register unsigned short int PCCYC0 = 1;
    sbit  PARUN0_bit at PCTL0.B2;
    const register unsigned short int PARUN0 = 2;
    sbit  PAOC0A_bit at PCTL0.B3;
    const register unsigned short int PAOC0A = 3;
    sbit  PAOC0B_bit at PCTL0.B4;
    const register unsigned short int PAOC0B = 4;
    sbit  PBFM0_bit at PCTL0.B5;
    const register unsigned short int PBFM0 = 5;
    sbit  PPRE00_bit at PCTL0.B6;
    const register unsigned short int PPRE00 = 6;
    sbit  PPRE01_bit at PCTL0.B7;
    const register unsigned short int PPRE01 = 7;

sfr data unsigned short volatile PCNF0 absolute 0xDA;
    sbit  PCLKSEL0_bit at PCNF0.B1;
    const register unsigned short int PCLKSEL0 = 1;
    sbit  POP0_bit at PCNF0.B2;
    const register unsigned short int POP0 = 2;
    sbit  PMODE00_bit at PCNF0.B3;
    const register unsigned short int PMODE00 = 3;
    sbit  PMODE01_bit at PCNF0.B4;
    const register unsigned short int PMODE01 = 4;
    sbit  PLOCK0_bit at PCNF0.B5;
    const register unsigned short int PLOCK0 = 5;
    sbit  PALOCK0_bit at PCNF0.B6;
    const register unsigned short int PALOCK0 = 6;
    sbit  PFIFTY0_bit at PCNF0.B7;
    const register unsigned short int PFIFTY0 = 7;

sfr data unsigned short volatile OCR0RBH absolute 0xD9;
    sbit  OCR0RB_8_bit at OCR0RBH.B0;
    const register unsigned short int OCR0RB_8 = 0;
    sbit  OCR0RB_9_bit at OCR0RBH.B1;
    const register unsigned short int OCR0RB_9 = 1;
    sbit  OCR0RB_00_bit at OCR0RBH.B2;
    const register unsigned short int OCR0RB_00 = 2;
    sbit  OCR0RB_01_bit at OCR0RBH.B3;
    const register unsigned short int OCR0RB_01 = 3;
    sbit  OCR0RB_02_bit at OCR0RBH.B4;
    const register unsigned short int OCR0RB_02 = 4;
    sbit  OCR0RB_03_bit at OCR0RBH.B5;
    const register unsigned short int OCR0RB_03 = 5;
    sbit  OCR0RB_04_bit at OCR0RBH.B6;
    const register unsigned short int OCR0RB_04 = 6;
    sbit  OCR0RB_05_bit at OCR0RBH.B7;
    const register unsigned short int OCR0RB_05 = 7;

sfr data unsigned short volatile OCR0RBL absolute 0xD8;
    sbit  OCR0RB_0_bit at OCR0RBL.B0;
    const register unsigned short int OCR0RB_0 = 0;
    sbit  OCR0RB_1_bit at OCR0RBL.B1;
    const register unsigned short int OCR0RB_1 = 1;
    sbit  OCR0RB_2_bit at OCR0RBL.B2;
    const register unsigned short int OCR0RB_2 = 2;
    sbit  OCR0RB_3_bit at OCR0RBL.B3;
    const register unsigned short int OCR0RB_3 = 3;
    sbit  OCR0RB_4_bit at OCR0RBL.B4;
    const register unsigned short int OCR0RB_4 = 4;
    sbit  OCR0RB_5_bit at OCR0RBL.B5;
    const register unsigned short int OCR0RB_5 = 5;
    sbit  OCR0RB_6_bit at OCR0RBL.B6;
    const register unsigned short int OCR0RB_6 = 6;
    sbit  OCR0RB_7_bit at OCR0RBL.B7;
    const register unsigned short int OCR0RB_7 = 7;

sfr data unsigned short volatile OCR0SBH absolute 0xD7;
    sbit  OCR0SB_8_bit at OCR0SBH.B0;
    const register unsigned short int OCR0SB_8 = 0;
    sbit  OCR0SB_9_bit at OCR0SBH.B1;
    const register unsigned short int OCR0SB_9 = 1;
    sbit  OCR0SB_00_bit at OCR0SBH.B2;
    const register unsigned short int OCR0SB_00 = 2;
    sbit  OCR0SB_01_bit at OCR0SBH.B3;
    const register unsigned short int OCR0SB_01 = 3;

sfr data unsigned short volatile OCR0SBL absolute 0xD6;
    sbit  OCR0SB_0_bit at OCR0SBL.B0;
    const register unsigned short int OCR0SB_0 = 0;
    sbit  OCR0SB_1_bit at OCR0SBL.B1;
    const register unsigned short int OCR0SB_1 = 1;
    sbit  OCR0SB_2_bit at OCR0SBL.B2;
    const register unsigned short int OCR0SB_2 = 2;
    sbit  OCR0SB_3_bit at OCR0SBL.B3;
    const register unsigned short int OCR0SB_3 = 3;
    sbit  OCR0SB_4_bit at OCR0SBL.B4;
    const register unsigned short int OCR0SB_4 = 4;
    sbit  OCR0SB_5_bit at OCR0SBL.B5;
    const register unsigned short int OCR0SB_5 = 5;
    sbit  OCR0SB_6_bit at OCR0SBL.B6;
    const register unsigned short int OCR0SB_6 = 6;
    sbit  OCR0SB_7_bit at OCR0SBL.B7;
    const register unsigned short int OCR0SB_7 = 7;

sfr data unsigned short volatile OCR0RAH absolute 0xD5;
    sbit  OCR0RA_8_bit at OCR0RAH.B0;
    const register unsigned short int OCR0RA_8 = 0;
    sbit  OCR0RA_9_bit at OCR0RAH.B1;
    const register unsigned short int OCR0RA_9 = 1;
    sbit  OCR0RA_00_bit at OCR0RAH.B2;
    const register unsigned short int OCR0RA_00 = 2;
    sbit  OCR0RA_01_bit at OCR0RAH.B3;
    const register unsigned short int OCR0RA_01 = 3;

sfr data unsigned short volatile OCR0RAL absolute 0xD4;
    sbit  OCR0RA_0_bit at OCR0RAL.B0;
    const register unsigned short int OCR0RA_0 = 0;
    sbit  OCR0RA_1_bit at OCR0RAL.B1;
    const register unsigned short int OCR0RA_1 = 1;
    sbit  OCR0RA_2_bit at OCR0RAL.B2;
    const register unsigned short int OCR0RA_2 = 2;
    sbit  OCR0RA_3_bit at OCR0RAL.B3;
    const register unsigned short int OCR0RA_3 = 3;
    sbit  OCR0RA_4_bit at OCR0RAL.B4;
    const register unsigned short int OCR0RA_4 = 4;
    sbit  OCR0RA_5_bit at OCR0RAL.B5;
    const register unsigned short int OCR0RA_5 = 5;
    sbit  OCR0RA_6_bit at OCR0RAL.B6;
    const register unsigned short int OCR0RA_6 = 6;
    sbit  OCR0RA_7_bit at OCR0RAL.B7;
    const register unsigned short int OCR0RA_7 = 7;

sfr data unsigned short volatile OCR0SAH absolute 0xD3;
    sbit  OCR0SA_8_bit at OCR0SAH.B0;
    const register unsigned short int OCR0SA_8 = 0;
    sbit  OCR0SA_9_bit at OCR0SAH.B1;
    const register unsigned short int OCR0SA_9 = 1;
    sbit  OCR0SA_00_bit at OCR0SAH.B2;
    const register unsigned short int OCR0SA_00 = 2;
    sbit  OCR0SA_01_bit at OCR0SAH.B3;
    const register unsigned short int OCR0SA_01 = 3;

sfr data unsigned short volatile OCR0SAL absolute 0xD2;
    sbit  OCR0SA_0_bit at OCR0SAL.B0;
    const register unsigned short int OCR0SA_0 = 0;
    sbit  OCR0SA_1_bit at OCR0SAL.B1;
    const register unsigned short int OCR0SA_1 = 1;
    sbit  OCR0SA_2_bit at OCR0SAL.B2;
    const register unsigned short int OCR0SA_2 = 2;
    sbit  OCR0SA_3_bit at OCR0SAL.B3;
    const register unsigned short int OCR0SA_3 = 3;
    sbit  OCR0SA_4_bit at OCR0SAL.B4;
    const register unsigned short int OCR0SA_4 = 4;
    sbit  OCR0SA_5_bit at OCR0SAL.B5;
    const register unsigned short int OCR0SA_5 = 5;
    sbit  OCR0SA_6_bit at OCR0SAL.B6;
    const register unsigned short int OCR0SA_6 = 6;
    sbit  OCR0SA_7_bit at OCR0SAL.B7;
    const register unsigned short int OCR0SA_7 = 7;

sfr data unsigned short volatile PSOC0 absolute 0xD0;
    sbit  POEN0A_bit at PSOC0.B0;
    const register unsigned short int POEN0A = 0;
    sbit  POEN0B_bit at PSOC0.B2;
    const register unsigned short int POEN0B = 2;
    sbit  PSYNC00_bit at PSOC0.B4;
    const register unsigned short int PSYNC00 = 4;
    sbit  PSYNC01_bit at PSOC0.B5;
    const register unsigned short int PSYNC01 = 5;

sfr data unsigned short volatile EUDR absolute 0xCE;
    sbit  EUDR0_bit at EUDR.B0;
    const register unsigned short int EUDR0 = 0;
    sbit  EUDR1_bit at EUDR.B1;
    const register unsigned short int EUDR1 = 1;
    sbit  EUDR2_bit at EUDR.B2;
    const register unsigned short int EUDR2 = 2;
    sbit  EUDR3_bit at EUDR.B3;
    const register unsigned short int EUDR3 = 3;
    sbit  EUDR4_bit at EUDR.B4;
    const register unsigned short int EUDR4 = 4;
    sbit  EUDR5_bit at EUDR.B5;
    const register unsigned short int EUDR5 = 5;
    sbit  EUDR6_bit at EUDR.B6;
    const register unsigned short int EUDR6 = 6;
    sbit  EUDR7_bit at EUDR.B7;
    const register unsigned short int EUDR7 = 7;

sfr data unsigned short volatile MUBRRH absolute 0xCD;
    sbit  MUBRR8_bit at MUBRRH.B0;
    const register unsigned short int MUBRR8 = 0;
    sbit  MUBRR9_bit at MUBRRH.B1;
    const register unsigned short int MUBRR9 = 1;
    sbit  MUBRR10_bit at MUBRRH.B2;
    const register unsigned short int MUBRR10 = 2;
    sbit  MUBRR11_bit at MUBRRH.B3;
    const register unsigned short int MUBRR11 = 3;
    sbit  MUBRR12_bit at MUBRRH.B4;
    const register unsigned short int MUBRR12 = 4;
    sbit  MUBRR13_bit at MUBRRH.B5;
    const register unsigned short int MUBRR13 = 5;
    sbit  MUBRR14_bit at MUBRRH.B6;
    const register unsigned short int MUBRR14 = 6;
    sbit  MUBRR15_bit at MUBRRH.B7;
    const register unsigned short int MUBRR15 = 7;

sfr data unsigned short volatile MUBRRL absolute 0xCC;
    sbit  MUBRR0_bit at MUBRRL.B0;
    const register unsigned short int MUBRR0 = 0;
    sbit  MUBRR1_bit at MUBRRL.B1;
    const register unsigned short int MUBRR1 = 1;
    sbit  MUBRR2_bit at MUBRRL.B2;
    const register unsigned short int MUBRR2 = 2;
    sbit  MUBRR3_bit at MUBRRL.B3;
    const register unsigned short int MUBRR3 = 3;
    sbit  MUBRR4_bit at MUBRRL.B4;
    const register unsigned short int MUBRR4 = 4;
    sbit  MUBRR5_bit at MUBRRL.B5;
    const register unsigned short int MUBRR5 = 5;
    sbit  MUBRR6_bit at MUBRRL.B6;
    const register unsigned short int MUBRR6 = 6;
    sbit  MUBRR7_bit at MUBRRL.B7;
    const register unsigned short int MUBRR7 = 7;

sfr data unsigned short volatile EUCSRC absolute 0xCA;
    sbit  STP0_bit at EUCSRC.B0;
    const register unsigned short int STP0 = 0;
    sbit  STP1_bit at EUCSRC.B1;
    const register unsigned short int STP1 = 1;
    sbit  F1617_bit at EUCSRC.B2;
    const register unsigned short int F1617 = 2;
    sbit  FEM_bit at EUCSRC.B3;
    const register unsigned short int FEM = 3;

sfr data unsigned short volatile EUCSRB absolute 0xC9;
    sbit  BODR_bit at EUCSRB.B0;
    const register unsigned short int BODR = 0;
    sbit  EMCH_bit at EUCSRB.B1;
    const register unsigned short int EMCH = 1;
    sbit  EUSBS_bit at EUCSRB.B3;
    const register unsigned short int EUSBS = 3;
    sbit  EUSART_bit at EUCSRB.B4;
    const register unsigned short int EUSART = 4;

sfr data unsigned short volatile EUCSRA absolute 0xC8;
    sbit  URxS0_bit at EUCSRA.B0;
    const register unsigned short int URxS0 = 0;
    sbit  URxS1_bit at EUCSRA.B1;
    const register unsigned short int URxS1 = 1;
    sbit  URxS2_bit at EUCSRA.B2;
    const register unsigned short int URxS2 = 2;
    sbit  URxS3_bit at EUCSRA.B3;
    const register unsigned short int URxS3 = 3;
    sbit  UTxS0_bit at EUCSRA.B4;
    const register unsigned short int UTxS0 = 4;
    sbit  UTxS1_bit at EUCSRA.B5;
    const register unsigned short int UTxS1 = 5;
    sbit  UTxS2_bit at EUCSRA.B6;
    const register unsigned short int UTxS2 = 6;
    sbit  UTxS3_bit at EUCSRA.B7;
    const register unsigned short int UTxS3 = 7;

sfr data unsigned short volatile UDR0 absolute 0xC6;
sfr data unsigned short volatile UDR absolute 0xC6;
    sbit  UDR0__bit at UDR.B0;
    const register unsigned short int UDR0_ = 0;
    sbit  UDR1_bit at UDR.B1;
    const register unsigned short int UDR1 = 1;
    sbit  UDR2_bit at UDR.B2;
    const register unsigned short int UDR2 = 2;
    sbit  UDR3_bit at UDR.B3;
    const register unsigned short int UDR3 = 3;
    sbit  UDR4_bit at UDR.B4;
    const register unsigned short int UDR4 = 4;
    sbit  UDR5_bit at UDR.B5;
    const register unsigned short int UDR5 = 5;
    sbit  UDR6_bit at UDR.B6;
    const register unsigned short int UDR6 = 6;
    sbit  UDR7_bit at UDR.B7;
    const register unsigned short int UDR7 = 7;

sfr data unsigned short UBRRH absolute 0xC5;
    sbit  UBRR8_bit at UBRRH.B0;
    const register unsigned short int UBRR8 = 0;
    sbit  UBRR9_bit at UBRRH.B1;
    const register unsigned short int UBRR9 = 1;
    sbit  UBRR10_bit at UBRRH.B2;
    const register unsigned short int UBRR10 = 2;
    sbit  UBRR11_bit at UBRRH.B3;
    const register unsigned short int UBRR11 = 3;

sfr data unsigned short UBRRL absolute 0xC4;
    sbit  UBRR0_bit at UBRRL.B0;
    const register unsigned short int UBRR0 = 0;
    sbit  UBRR1_bit at UBRRL.B1;
    const register unsigned short int UBRR1 = 1;
    sbit  UBRR2_bit at UBRRL.B2;
    const register unsigned short int UBRR2 = 2;
    sbit  UBRR3_bit at UBRRL.B3;
    const register unsigned short int UBRR3 = 3;
    sbit  UBRR4_bit at UBRRL.B4;
    const register unsigned short int UBRR4 = 4;
    sbit  UBRR5_bit at UBRRL.B5;
    const register unsigned short int UBRR5 = 5;
    sbit  UBRR6_bit at UBRRL.B6;
    const register unsigned short int UBRR6 = 6;
    sbit  UBRR7_bit at UBRRL.B7;
    const register unsigned short int UBRR7 = 7;

sfr data unsigned short volatile UCSR0C absolute 0xC2;
sfr data unsigned short volatile UCSRC absolute 0xC2;
    sbit  UCPOL_bit at UCSRC.B0;
    const register unsigned short int UCPOL = 0;
    sbit  UCSZ0_bit at UCSRC.B1;
    const register unsigned short int UCSZ0 = 1;
    sbit  UCSZ1_bit at UCSRC.B2;
    const register unsigned short int UCSZ1 = 2;
    sbit  USBS_bit at UCSRC.B3;
    const register unsigned short int USBS = 3;
    sbit  UPM0_bit at UCSRC.B4;
    const register unsigned short int UPM0 = 4;
    sbit  UPM1_bit at UCSRC.B5;
    const register unsigned short int UPM1 = 5;
    sbit  UMSEL0_bit at UCSRC.B6;
    const register unsigned short int UMSEL0 = 6;

sfr data unsigned short volatile UCSR0B absolute 0xC1;
sfr data unsigned short volatile UCSRB absolute 0xC1;
    sbit  TXB8_bit at UCSRB.B0;
    const register unsigned short int TXB8 = 0;
    sbit  RXB8_bit at UCSRB.B1;
    const register unsigned short int RXB8 = 1;
    sbit  UCSZ2_bit at UCSRB.B2;
    const register unsigned short int UCSZ2 = 2;
    sbit  TXEN_bit at UCSRB.B3;
    const register unsigned short int TXEN = 3;
    sbit  RXEN_bit at UCSRB.B4;
    const register unsigned short int RXEN = 4;
    sbit  UDRIE_bit at UCSRB.B5;
    const register unsigned short int UDRIE = 5;
    sbit  TXCIE_bit at UCSRB.B6;
    const register unsigned short int TXCIE = 6;
    sbit  RXCIE_bit at UCSRB.B7;
    const register unsigned short int RXCIE = 7;

sfr data unsigned short volatile UCSRA absolute 0xC0;
    sbit  MPCM_bit at UCSRA.B0;
    const register unsigned short int MPCM = 0;
    sbit  U2X_bit at UCSRA.B1;
    const register unsigned short int U2X = 1;
    sbit  UPE_bit at UCSRA.B2;
    const register unsigned short int UPE = 2;
    sbit  DOR_bit at UCSRA.B3;
    const register unsigned short int DOR = 3;
    sbit  FE_bit at UCSRA.B4;
    const register unsigned short int FE = 4;
    sbit  UDRE0_bit at UCSRA.B5;
    const register unsigned short int UDRE0 = 5;
    sbit  UDRE_bit at UCSRA.B5;
    const register unsigned short int UDRE = 5;
    sbit  TXC0_bit at UCSRA.B6;
    const register unsigned short int TXC0 = 6;
    sbit  TXC_bit at UCSRA.B6;
    const register unsigned short int TXC = 6;
    sbit  RXC0_bit at UCSRA.B7;
    const register unsigned short int RXC0 = 7;
    sbit  RXC_bit at UCSRA.B7;
    const register unsigned short int RXC = 7;

sfr data unsigned short volatile AC2CON absolute 0xAF;
    sbit  AC2M0_bit at AC2CON.B0;
    const register unsigned short int AC2M0 = 0;
    sbit  AC2M1_bit at AC2CON.B1;
    const register unsigned short int AC2M1 = 1;
    sbit  AC2M2_bit at AC2CON.B2;
    const register unsigned short int AC2M2 = 2;
    sbit  AC2IS0_bit at AC2CON.B4;
    const register unsigned short int AC2IS0 = 4;
    sbit  AC2IS1_bit at AC2CON.B5;
    const register unsigned short int AC2IS1 = 5;
    sbit  AC2IE_bit at AC2CON.B6;
    const register unsigned short int AC2IE = 6;
    sbit  AC2EN_bit at AC2CON.B7;
    const register unsigned short int AC2EN = 7;

sfr data unsigned short volatile AC1CON absolute 0xAE;
    sbit  AC1M0_bit at AC1CON.B0;
    const register unsigned short int AC1M0 = 0;
    sbit  AC1M1_bit at AC1CON.B1;
    const register unsigned short int AC1M1 = 1;
    sbit  AC1M2_bit at AC1CON.B2;
    const register unsigned short int AC1M2 = 2;
    sbit  AC1ICE_bit at AC1CON.B3;
    const register unsigned short int AC1ICE = 3;
    sbit  AC1IS0_bit at AC1CON.B4;
    const register unsigned short int AC1IS0 = 4;
    sbit  AC1IS1_bit at AC1CON.B5;
    const register unsigned short int AC1IS1 = 5;
    sbit  AC1IE_bit at AC1CON.B6;
    const register unsigned short int AC1IE = 6;
    sbit  AC1EN_bit at AC1CON.B7;
    const register unsigned short int AC1EN = 7;

sfr data unsigned short volatile AC0CON absolute 0xAD;
    sbit  AC0M0_bit at AC0CON.B0;
    const register unsigned short int AC0M0 = 0;
    sbit  AC0M1_bit at AC0CON.B1;
    const register unsigned short int AC0M1 = 1;
    sbit  AC0M2_bit at AC0CON.B2;
    const register unsigned short int AC0M2 = 2;
    sbit  AC0IS0_bit at AC0CON.B4;
    const register unsigned short int AC0IS0 = 4;
    sbit  AC0IS1_bit at AC0CON.B5;
    const register unsigned short int AC0IS1 = 5;
    sbit  AC0IE_bit at AC0CON.B6;
    const register unsigned short int AC0IE = 6;
    sbit  AC0EN_bit at AC0CON.B7;
    const register unsigned short int AC0EN = 7;

sfr data unsigned short volatile DACH absolute 0xAC;
    sbit  DACH0_bit at DACH.B0;
    const register unsigned short int DACH0 = 0;
    sbit  DACH1_bit at DACH.B1;
    const register unsigned short int DACH1 = 1;
    sbit  DACH2_bit at DACH.B2;
    const register unsigned short int DACH2 = 2;
    sbit  DACH3_bit at DACH.B3;
    const register unsigned short int DACH3 = 3;
    sbit  DACH4_bit at DACH.B4;
    const register unsigned short int DACH4 = 4;
    sbit  DACH5_bit at DACH.B5;
    const register unsigned short int DACH5 = 5;
    sbit  DACH6_bit at DACH.B6;
    const register unsigned short int DACH6 = 6;
    sbit  DACH7_bit at DACH.B7;
    const register unsigned short int DACH7 = 7;

sfr data unsigned short volatile DACL absolute 0xAB;
    sbit  DACL0_bit at DACL.B0;
    const register unsigned short int DACL0 = 0;
    sbit  DACL1_bit at DACL.B1;
    const register unsigned short int DACL1 = 1;
    sbit  DACL2_bit at DACL.B2;
    const register unsigned short int DACL2 = 2;
    sbit  DACL3_bit at DACL.B3;
    const register unsigned short int DACL3 = 3;
    sbit  DACL4_bit at DACL.B4;
    const register unsigned short int DACL4 = 4;
    sbit  DACL5_bit at DACL.B5;
    const register unsigned short int DACL5 = 5;
    sbit  DACL6_bit at DACL.B6;
    const register unsigned short int DACL6 = 6;
    sbit  DACL7_bit at DACL.B7;
    const register unsigned short int DACL7 = 7;

sfr data unsigned short volatile DACON absolute 0xAA;
    sbit  DAEN_bit at DACON.B0;
    const register unsigned short int DAEN = 0;
    sbit  DALA_bit at DACON.B2;
    const register unsigned short int DALA = 2;
    sbit  DATS0_bit at DACON.B4;
    const register unsigned short int DATS0 = 4;
    sbit  DATS1_bit at DACON.B5;
    const register unsigned short int DATS1 = 5;
    sbit  DATS2_bit at DACON.B6;
    const register unsigned short int DATS2 = 6;
    sbit  DAATE_bit at DACON.B7;
    const register unsigned short int DAATE = 7;

sfr data unsigned short volatile PIM2 absolute 0xA5;
    sbit  PEOPE2_bit at PIM2.B0;
    const register unsigned short int PEOPE2 = 0;
    sbit  PEVE2A_bit at PIM2.B3;
    const register unsigned short int PEVE2A = 3;
    sbit  PEVE2B_bit at PIM2.B4;
    const register unsigned short int PEVE2B = 4;
    sbit  PSEIE2_bit at PIM2.B5;
    const register unsigned short int PSEIE2 = 5;

sfr data unsigned short volatile PIFR2 absolute 0xA4;
    sbit  PEOP2_bit at PIFR2.B0;
    const register unsigned short int PEOP2 = 0;
    sbit  PRN20_bit at PIFR2.B1;
    const register unsigned short int PRN20 = 1;
    sbit  PRN21_bit at PIFR2.B2;
    const register unsigned short int PRN21 = 2;
    sbit  PEV2A_bit at PIFR2.B3;
    const register unsigned short int PEV2A = 3;
    sbit  PEV2B_bit at PIFR2.B4;
    const register unsigned short int PEV2B = 4;
    sbit  PSEI2_bit at PIFR2.B5;
    const register unsigned short int PSEI2 = 5;
    sbit  POAC2A_bit at PIFR2.B6;
    const register unsigned short int POAC2A = 6;
    sbit  POAC2B_bit at PIFR2.B7;
    const register unsigned short int POAC2B = 7;

sfr data unsigned short volatile PIM1 absolute 0xA3;

sfr data unsigned short volatile PIFR1 absolute 0xA2;

sfr data unsigned short volatile PIM0 absolute 0xA1;
    sbit  PEOPE0_bit at PIM0.B0;
    const register unsigned short int PEOPE0 = 0;
    sbit  PEVE0A_bit at PIM0.B3;
    const register unsigned short int PEVE0A = 3;
    sbit  PEVE0B_bit at PIM0.B4;
    const register unsigned short int PEVE0B = 4;
    sbit  PSEIE0_bit at PIM0.B5;
    const register unsigned short int PSEIE0 = 5;

sfr data unsigned short volatile PIFR0 absolute 0xA0;
    sbit  PEOP0_bit at PIFR0.B0;
    const register unsigned short int PEOP0 = 0;
    sbit  PRN00_bit at PIFR0.B1;
    const register unsigned short int PRN00 = 1;
    sbit  PRN01_bit at PIFR0.B2;
    const register unsigned short int PRN01 = 2;
    sbit  PEV0A_bit at PIFR0.B3;
    const register unsigned short int PEV0A = 3;
    sbit  PEV0B_bit at PIFR0.B4;
    const register unsigned short int PEV0B = 4;
    sbit  PSEI0_bit at PIFR0.B5;
    const register unsigned short int PSEI0 = 5;
    sbit  POAC0A_bit at PIFR0.B6;
    const register unsigned short int POAC0A = 6;
    sbit  POAC0B_bit at PIFR0.B7;
    const register unsigned short int POAC0B = 7;

sfr data unsigned short OCR1BH absolute 0x8B;
    sbit  OCR1BH0_bit at OCR1BH.B0;
    const register unsigned short int OCR1BH0 = 0;
    sbit  OCR1BH1_bit at OCR1BH.B1;
    const register unsigned short int OCR1BH1 = 1;
    sbit  OCR1BH2_bit at OCR1BH.B2;
    const register unsigned short int OCR1BH2 = 2;
    sbit  OCR1BH3_bit at OCR1BH.B3;
    const register unsigned short int OCR1BH3 = 3;
    sbit  OCR1BH4_bit at OCR1BH.B4;
    const register unsigned short int OCR1BH4 = 4;
    sbit  OCR1BH5_bit at OCR1BH.B5;
    const register unsigned short int OCR1BH5 = 5;
    sbit  OCR1BH6_bit at OCR1BH.B6;
    const register unsigned short int OCR1BH6 = 6;
    sbit  OCR1BH7_bit at OCR1BH.B7;
    const register unsigned short int OCR1BH7 = 7;

sfr data unsigned short OCR1BL absolute 0x8A;
    sbit  OCR1BL0_bit at OCR1BL.B0;
    const register unsigned short int OCR1BL0 = 0;
    sbit  OCR1BL1_bit at OCR1BL.B1;
    const register unsigned short int OCR1BL1 = 1;
    sbit  OCR1BL2_bit at OCR1BL.B2;
    const register unsigned short int OCR1BL2 = 2;
    sbit  OCR1BL3_bit at OCR1BL.B3;
    const register unsigned short int OCR1BL3 = 3;
    sbit  OCR1BL4_bit at OCR1BL.B4;
    const register unsigned short int OCR1BL4 = 4;
    sbit  OCR1BL5_bit at OCR1BL.B5;
    const register unsigned short int OCR1BL5 = 5;
    sbit  OCR1BL6_bit at OCR1BL.B6;
    const register unsigned short int OCR1BL6 = 6;
    sbit  OCR1BL7_bit at OCR1BL.B7;
    const register unsigned short int OCR1BL7 = 7;

sfr data unsigned short OCR1AH absolute 0x89;
    sbit  OCR1AH0_bit at OCR1AH.B0;
    const register unsigned short int OCR1AH0 = 0;
    sbit  OCR1AH1_bit at OCR1AH.B1;
    const register unsigned short int OCR1AH1 = 1;
    sbit  OCR1AH2_bit at OCR1AH.B2;
    const register unsigned short int OCR1AH2 = 2;
    sbit  OCR1AH3_bit at OCR1AH.B3;
    const register unsigned short int OCR1AH3 = 3;
    sbit  OCR1AH4_bit at OCR1AH.B4;
    const register unsigned short int OCR1AH4 = 4;
    sbit  OCR1AH5_bit at OCR1AH.B5;
    const register unsigned short int OCR1AH5 = 5;
    sbit  OCR1AH6_bit at OCR1AH.B6;
    const register unsigned short int OCR1AH6 = 6;
    sbit  OCR1AH7_bit at OCR1AH.B7;
    const register unsigned short int OCR1AH7 = 7;

sfr data unsigned short OCR1AL absolute 0x88;
    sbit  OCR1AL0_bit at OCR1AL.B0;
    const register unsigned short int OCR1AL0 = 0;
    sbit  OCR1AL1_bit at OCR1AL.B1;
    const register unsigned short int OCR1AL1 = 1;
    sbit  OCR1AL2_bit at OCR1AL.B2;
    const register unsigned short int OCR1AL2 = 2;
    sbit  OCR1AL3_bit at OCR1AL.B3;
    const register unsigned short int OCR1AL3 = 3;
    sbit  OCR1AL4_bit at OCR1AL.B4;
    const register unsigned short int OCR1AL4 = 4;
    sbit  OCR1AL5_bit at OCR1AL.B5;
    const register unsigned short int OCR1AL5 = 5;
    sbit  OCR1AL6_bit at OCR1AL.B6;
    const register unsigned short int OCR1AL6 = 6;
    sbit  OCR1AL7_bit at OCR1AL.B7;
    const register unsigned short int OCR1AL7 = 7;

sfr data unsigned short volatile ICR1H absolute 0x87;
    sbit  ICR1H0_bit at ICR1H.B0;
    const register unsigned short int ICR1H0 = 0;
    sbit  ICR1H1_bit at ICR1H.B1;
    const register unsigned short int ICR1H1 = 1;
    sbit  ICR1H2_bit at ICR1H.B2;
    const register unsigned short int ICR1H2 = 2;
    sbit  ICR1H3_bit at ICR1H.B3;
    const register unsigned short int ICR1H3 = 3;
    sbit  ICR1H4_bit at ICR1H.B4;
    const register unsigned short int ICR1H4 = 4;
    sbit  ICR1H5_bit at ICR1H.B5;
    const register unsigned short int ICR1H5 = 5;
    sbit  ICR1H6_bit at ICR1H.B6;
    const register unsigned short int ICR1H6 = 6;
    sbit  ICR1H7_bit at ICR1H.B7;
    const register unsigned short int ICR1H7 = 7;

sfr data unsigned short volatile ICR1L absolute 0x86;
    sbit  ICR1L0_bit at ICR1L.B0;
    const register unsigned short int ICR1L0 = 0;
    sbit  ICR1L1_bit at ICR1L.B1;
    const register unsigned short int ICR1L1 = 1;
    sbit  ICR1L2_bit at ICR1L.B2;
    const register unsigned short int ICR1L2 = 2;
    sbit  ICR1L3_bit at ICR1L.B3;
    const register unsigned short int ICR1L3 = 3;
    sbit  ICR1L4_bit at ICR1L.B4;
    const register unsigned short int ICR1L4 = 4;
    sbit  ICR1L5_bit at ICR1L.B5;
    const register unsigned short int ICR1L5 = 5;
    sbit  ICR1L6_bit at ICR1L.B6;
    const register unsigned short int ICR1L6 = 6;
    sbit  ICR1L7_bit at ICR1L.B7;
    const register unsigned short int ICR1L7 = 7;

sfr data unsigned short volatile TCNT1H absolute 0x85;
    sbit  TCNT1H0_bit at TCNT1H.B0;
    const register unsigned short int TCNT1H0 = 0;
    sbit  TCNT1H1_bit at TCNT1H.B1;
    const register unsigned short int TCNT1H1 = 1;
    sbit  TCNT1H2_bit at TCNT1H.B2;
    const register unsigned short int TCNT1H2 = 2;
    sbit  TCNT1H3_bit at TCNT1H.B3;
    const register unsigned short int TCNT1H3 = 3;
    sbit  TCNT1H4_bit at TCNT1H.B4;
    const register unsigned short int TCNT1H4 = 4;
    sbit  TCNT1H5_bit at TCNT1H.B5;
    const register unsigned short int TCNT1H5 = 5;
    sbit  TCNT1H6_bit at TCNT1H.B6;
    const register unsigned short int TCNT1H6 = 6;
    sbit  TCNT1H7_bit at TCNT1H.B7;
    const register unsigned short int TCNT1H7 = 7;

sfr data unsigned short volatile TCNT1L absolute 0x84;
    sbit  TCNT1L0_bit at TCNT1L.B0;
    const register unsigned short int TCNT1L0 = 0;
    sbit  TCNT1L1_bit at TCNT1L.B1;
    const register unsigned short int TCNT1L1 = 1;
    sbit  TCNT1L2_bit at TCNT1L.B2;
    const register unsigned short int TCNT1L2 = 2;
    sbit  TCNT1L3_bit at TCNT1L.B3;
    const register unsigned short int TCNT1L3 = 3;
    sbit  TCNT1L4_bit at TCNT1L.B4;
    const register unsigned short int TCNT1L4 = 4;
    sbit  TCNT1L5_bit at TCNT1L.B5;
    const register unsigned short int TCNT1L5 = 5;
    sbit  TCNT1L6_bit at TCNT1L.B6;
    const register unsigned short int TCNT1L6 = 6;
    sbit  TCNT1L7_bit at TCNT1L.B7;
    const register unsigned short int TCNT1L7 = 7;

sfr data unsigned short volatile TCCR1C absolute 0x82;
    sbit  FOC1B_bit at TCCR1C.B6;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1A = 7;

sfr data unsigned short TCCR1B absolute 0x81;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS10 = 0;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS11 = 1;
    sbit  CS12_bit at TCCR1B.B2;
    const register unsigned short int CS12 = 2;
    sbit  WGM12_bit at TCCR1B.B3;
    const register unsigned short int WGM12 = 3;
    sbit  WGM13_bit at TCCR1B.B4;
    const register unsigned short int WGM13 = 4;
    sbit  ICES1_bit at TCCR1B.B6;
    const register unsigned short int ICES1 = 6;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICNC1 = 7;

sfr data unsigned short TCCR1A absolute 0x80;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM10 = 0;
    sbit  WGM11_bit at TCCR1A.B1;
    const register unsigned short int WGM11 = 1;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1A1 = 7;

sfr data unsigned short DIDR1 absolute 0x7F;
    sbit  ADC8D_bit at DIDR1.B0;
    const register unsigned short int ADC8D = 0;
    sbit  ADC9D_bit at DIDR1.B1;
    const register unsigned short int ADC9D = 1;
    sbit  ADC10D_bit at DIDR1.B2;
    const register unsigned short int ADC10D = 2;
    sbit  AMP0ND_bit at DIDR1.B3;
    const register unsigned short int AMP0ND = 3;
    sbit  AMP0PD_bit at DIDR1.B4;
    const register unsigned short int AMP0PD = 4;
    sbit  ACMP0D_bit at DIDR1.B5;
    const register unsigned short int ACMP0D = 5;

sfr data unsigned short DIDR0 absolute 0x7E;
    sbit  ADC0D_bit at DIDR0.B0;
    const register unsigned short int ADC0D = 0;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC1D = 1;
    sbit  ADC2D_bit at DIDR0.B2;
    const register unsigned short int ADC2D = 2;
    sbit  ADC3D_bit at DIDR0.B3;
    const register unsigned short int ADC3D = 3;
    sbit  ADC4D_bit at DIDR0.B4;
    const register unsigned short int ADC4D = 4;
    sbit  ADC5D_bit at DIDR0.B5;
    const register unsigned short int ADC5D = 5;
    sbit  ADC6D_bit at DIDR0.B6;
    const register unsigned short int ADC6D = 6;
    sbit  ADC7D_bit at DIDR0.B7;
    const register unsigned short int ADC7D = 7;

sfr data unsigned short ADMUX absolute 0x7C;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX0 = 0;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX1 = 1;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX2 = 2;
    sbit  MUX3_bit at ADMUX.B3;
    const register unsigned short int MUX3 = 3;
    sbit  ADLAR_bit at ADMUX.B5;
    const register unsigned short int ADLAR = 5;
    sbit  REFS0_bit at ADMUX.B6;
    const register unsigned short int REFS0 = 6;
    sbit  REFS1_bit at ADMUX.B7;
    const register unsigned short int REFS1 = 7;

sfr data unsigned short ADCSRB absolute 0x7B;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS2_bit at ADCSRB.B2;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS3_bit at ADCSRB.B3;
    const register unsigned short int ADTS3 = 3;
    sbit  ADASCR_bit at ADCSRB.B4;
    const register unsigned short int ADASCR = 4;
    sbit  ADHSM_bit at ADCSRB.B7;
    const register unsigned short int ADHSM = 7;

sfr data unsigned short volatile ADCSRA absolute 0x7A;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS2_bit at ADCSRA.B2;
    const register unsigned short int ADPS2 = 2;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADIE = 3;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIF = 4;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADATE = 5;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADSC = 6;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADEN = 7;

sfr data unsigned short volatile ADCH absolute 0x79;
    sbit  ADCH0_bit at ADCH.B0;
    const register unsigned short int ADCH0 = 0;
    sbit  ADCH1_bit at ADCH.B1;
    const register unsigned short int ADCH1 = 1;
    sbit  ADCH2_bit at ADCH.B2;
    const register unsigned short int ADCH2 = 2;
    sbit  ADCH3_bit at ADCH.B3;
    const register unsigned short int ADCH3 = 3;
    sbit  ADCH4_bit at ADCH.B4;
    const register unsigned short int ADCH4 = 4;
    sbit  ADCH5_bit at ADCH.B5;
    const register unsigned short int ADCH5 = 5;
    sbit  ADCH6_bit at ADCH.B6;
    const register unsigned short int ADCH6 = 6;
    sbit  ADCH7_bit at ADCH.B7;
    const register unsigned short int ADCH7 = 7;

sfr data unsigned short volatile ADCL absolute 0x78;
    sbit  ADCL0_bit at ADCL.B0;
    const register unsigned short int ADCL0 = 0;
    sbit  ADCL1_bit at ADCL.B1;
    const register unsigned short int ADCL1 = 1;
    sbit  ADCL2_bit at ADCL.B2;
    const register unsigned short int ADCL2 = 2;
    sbit  ADCL3_bit at ADCL.B3;
    const register unsigned short int ADCL3 = 3;
    sbit  ADCL4_bit at ADCL.B4;
    const register unsigned short int ADCL4 = 4;
    sbit  ADCL5_bit at ADCL.B5;
    const register unsigned short int ADCL5 = 5;
    sbit  ADCL6_bit at ADCL.B6;
    const register unsigned short int ADCL6 = 6;
    sbit  ADCL7_bit at ADCL.B7;
    const register unsigned short int ADCL7 = 7;

sfr data unsigned short volatile AMP1CSR absolute 0x77;
    sbit  AMP1TS0_bit at AMP1CSR.B0;
    const register unsigned short int AMP1TS0 = 0;
    sbit  AMP1TS1_bit at AMP1CSR.B1;
    const register unsigned short int AMP1TS1 = 1;
    sbit  AMP1G0_bit at AMP1CSR.B4;
    const register unsigned short int AMP1G0 = 4;
    sbit  AMP1G1_bit at AMP1CSR.B5;
    const register unsigned short int AMP1G1 = 5;
    sbit  AMP1IS_bit at AMP1CSR.B6;
    const register unsigned short int AMP1IS = 6;
    sbit  AMP1EN_bit at AMP1CSR.B7;
    const register unsigned short int AMP1EN = 7;

sfr data unsigned short volatile AMP0CSR absolute 0x76;
    sbit  AMP0TS0_bit at AMP0CSR.B0;
    const register unsigned short int AMP0TS0 = 0;
    sbit  AMP0TS1_bit at AMP0CSR.B1;
    const register unsigned short int AMP0TS1 = 1;
    sbit  AMP0G0_bit at AMP0CSR.B4;
    const register unsigned short int AMP0G0 = 4;
    sbit  AMP0G1_bit at AMP0CSR.B5;
    const register unsigned short int AMP0G1 = 5;
    sbit  AMP0IS_bit at AMP0CSR.B6;
    const register unsigned short int AMP0IS = 6;
    sbit  AMP0EN_bit at AMP0CSR.B7;
    const register unsigned short int AMP0EN = 7;

sfr data unsigned short TIMSK1 absolute 0x6F;
    sbit  TOIE1_bit at TIMSK1.B0;
    const register unsigned short int TOIE1 = 0;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1B = 2;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int ICIE1 = 5;

sfr data unsigned short TIMSK0 absolute 0x6E;
    sbit  TOIE0_bit at TIMSK0.B0;
    const register unsigned short int TOIE0 = 0;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0B = 2;

sfr data unsigned short volatile EICRA absolute 0x69;
    sbit  ISC00_bit at EICRA.B0;
    const register unsigned short int ISC00 = 0;
    sbit  ISC01_bit at EICRA.B1;
    const register unsigned short int ISC01 = 1;
    sbit  ISC10_bit at EICRA.B2;
    const register unsigned short int ISC10 = 2;
    sbit  ISC11_bit at EICRA.B3;
    const register unsigned short int ISC11 = 3;
    sbit  ISC20_bit at EICRA.B4;
    const register unsigned short int ISC20 = 4;
    sbit  ISC21_bit at EICRA.B5;
    const register unsigned short int ISC21 = 5;

sfr data unsigned short OSCCAL absolute 0x66;
    sbit  CAL0_bit at OSCCAL.B0;
    const register unsigned short int CAL0 = 0;
    sbit  CAL1_bit at OSCCAL.B1;
    const register unsigned short int CAL1 = 1;
    sbit  CAL2_bit at OSCCAL.B2;
    const register unsigned short int CAL2 = 2;
    sbit  CAL3_bit at OSCCAL.B3;
    const register unsigned short int CAL3 = 3;
    sbit  CAL4_bit at OSCCAL.B4;
    const register unsigned short int CAL4 = 4;
    sbit  CAL5_bit at OSCCAL.B5;
    const register unsigned short int CAL5 = 5;
    sbit  CAL6_bit at OSCCAL.B6;
    const register unsigned short int CAL6 = 6;

sfr data unsigned short volatile PRR absolute 0x64;
    sbit  PRADC_bit at PRR.B0;
    const register unsigned short int PRADC = 0;
    sbit  PRUSART0_bit at PRR.B1;
    const register unsigned short int PRUSART0 = 1;
    sbit  PRSPI_bit at PRR.B2;
    const register unsigned short int PRSPI = 2;
    sbit  PRTIM0_bit at PRR.B3;
    const register unsigned short int PRTIM0 = 3;
    sbit  PRTIM1_bit at PRR.B4;
    const register unsigned short int PRTIM1 = 4;
    sbit  PRPSC0_bit at PRR.B5;
    const register unsigned short int PRPSC0 = 5;
    sbit  PRPSC1_bit at PRR.B6;
    const register unsigned short int PRPSC1 = 6;
    sbit  PRPSC2_bit at PRR.B7;
    const register unsigned short int PRPSC2 = 7;

sfr data unsigned short volatile CLKPR absolute 0x61;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS3_bit at CLKPR.B3;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPCE_bit at CLKPR.B7;
    const register unsigned short int CLKPCE = 7;

sfr data unsigned short volatile WDTCSR absolute 0x60;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP0 = 0;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP1 = 1;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP2 = 2;
    sbit  WDE_bit at WDTCSR.B3;
    const register unsigned short int WDE = 3;
    sbit  WDCE_bit at WDTCSR.B4;
    const register unsigned short int WDCE = 4;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDP3 = 5;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDIE = 6;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIF = 7;

sfr io unsigned short volatile SREG absolute 0x5F;
    sbit  SREG_C_bit at SREG.B0;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_I = 7;

sfr io unsigned short volatile SPH absolute 0x5E;
    sbit  SP8_bit at SPH.B0;
    const register unsigned short int SP8 = 0;
    sbit  SP9_bit at SPH.B1;
    const register unsigned short int SP9 = 1;
    sbit  SP10_bit at SPH.B2;
    const register unsigned short int SP10 = 2;
    sbit  SP11_bit at SPH.B3;
    const register unsigned short int SP11 = 3;
    sbit  SP12_bit at SPH.B4;
    const register unsigned short int SP12 = 4;
    sbit  SP13_bit at SPH.B5;
    const register unsigned short int SP13 = 5;
    sbit  SP14_bit at SPH.B6;
    const register unsigned short int SP14 = 6;
    sbit  SP15_bit at SPH.B7;
    const register unsigned short int SP15 = 7;

sfr io unsigned short volatile SPL absolute 0x5D;
    sbit  SP0_bit at SPL.B0;
    const register unsigned short int SP0 = 0;
    sbit  SP1_bit at SPL.B1;
    const register unsigned short int SP1 = 1;
    sbit  SP2_bit at SPL.B2;
    const register unsigned short int SP2 = 2;
    sbit  SP3_bit at SPL.B3;
    const register unsigned short int SP3 = 3;
    sbit  SP4_bit at SPL.B4;
    const register unsigned short int SP4 = 4;
    sbit  SP5_bit at SPL.B5;
    const register unsigned short int SP5 = 5;
    sbit  SP6_bit at SPL.B6;
    const register unsigned short int SP6 = 6;
    sbit  SP7_bit at SPL.B7;
    const register unsigned short int SP7 = 7;

sfr io unsigned short volatile SPMCSR absolute 0x57;
    sbit  SPMEN_bit at SPMCSR.B0;
    const register unsigned short int SPMEN = 0;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int PGERS = 1;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGWRT = 2;
    sbit  BLBSET_bit at SPMCSR.B3;
    const register unsigned short int BLBSET = 3;
    sbit  RWWSRE_bit at SPMCSR.B4;
    const register unsigned short int RWWSRE = 4;
    sbit  RWWSB_bit at SPMCSR.B6;
    const register unsigned short int RWWSB = 6;
    sbit  SPMIE_bit at SPMCSR.B7;
    const register unsigned short int SPMIE = 7;

sfr io unsigned short volatile MCUCR absolute 0x55;
    sbit  IVCE_bit at MCUCR.B0;
    const register unsigned short int IVCE = 0;
    sbit  IVSEL_bit at MCUCR.B1;
    const register unsigned short int IVSEL = 1;
    sbit  PUD_bit at MCUCR.B4;
    const register unsigned short int PUD = 4;
    sbit  SPIPS_bit at MCUCR.B7;
    const register unsigned short int SPIPS = 7;

sfr io unsigned short volatile MCUSR absolute 0x54;
    sbit  PORF_bit at MCUSR.B0;
    const register unsigned short int PORF = 0;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int EXTRF = 1;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int BORF = 2;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int WDRF = 3;

sfr io unsigned short SMCR absolute 0x53;
    sbit  SE_bit at SMCR.B0;
    const register unsigned short int SE = 0;
    sbit  SM0_bit at SMCR.B1;
    const register unsigned short int SM0 = 1;
    sbit  SM1_bit at SMCR.B2;
    const register unsigned short int SM1 = 2;
    sbit  SM2_bit at SMCR.B3;
    const register unsigned short int SM2 = 3;

sfr io unsigned short volatile ACSR absolute 0x50;
    sbit  AC0O_bit at ACSR.B0;
    const register unsigned short int AC0O = 0;
    sbit  AC1O_bit at ACSR.B1;
    const register unsigned short int AC1O = 1;
    sbit  AC2O_bit at ACSR.B2;
    const register unsigned short int AC2O = 2;
    sbit  AC0IF_bit at ACSR.B4;
    const register unsigned short int AC0IF = 4;
    sbit  AC1IF_bit at ACSR.B5;
    const register unsigned short int AC1IF = 5;
    sbit  AC2IF_bit at ACSR.B6;
    const register unsigned short int AC2IF = 6;
    sbit  ACCKDIV_bit at ACSR.B7;
    const register unsigned short int ACCKDIV = 7;

sfr io unsigned short volatile SPDR absolute 0x4E;
    sbit  SPDR0_bit at SPDR.B0;
    const register unsigned short int SPDR0 = 0;
    sbit  SPDR1_bit at SPDR.B1;
    const register unsigned short int SPDR1 = 1;
    sbit  SPDR2_bit at SPDR.B2;
    const register unsigned short int SPDR2 = 2;
    sbit  SPDR3_bit at SPDR.B3;
    const register unsigned short int SPDR3 = 3;
    sbit  SPDR4_bit at SPDR.B4;
    const register unsigned short int SPDR4 = 4;
    sbit  SPDR5_bit at SPDR.B5;
    const register unsigned short int SPDR5 = 5;
    sbit  SPDR6_bit at SPDR.B6;
    const register unsigned short int SPDR6 = 6;
    sbit  SPDR7_bit at SPDR.B7;
    const register unsigned short int SPDR7 = 7;

sfr io unsigned short volatile SPSR absolute 0x4D;
    sbit  SPI2X_bit at SPSR.B0;
    const register unsigned short int SPI2X = 0;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int WCOL = 6;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int SPIF = 7;

sfr io unsigned short SPCR absolute 0x4C;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR0 = 0;
    sbit  SPR1_bit at SPCR.B1;
    const register unsigned short int SPR1 = 1;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int CPHA = 2;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPOL = 3;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int MSTR = 4;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int DORD = 5;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int SPE = 6;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPIE = 7;

sfr io unsigned short volatile PLLCSR absolute 0x49;
    sbit  PLOCK_bit at PLLCSR.B0;
    const register unsigned short int PLOCK = 0;
    sbit  PLLE_bit at PLLCSR.B1;
    const register unsigned short int PLLE = 1;
    sbit  PLLF_bit at PLLCSR.B2;
    const register unsigned short int PLLF = 2;

sfr io unsigned short OCR0B absolute 0x48;
    sbit  OCR0B_0_bit at OCR0B.B0;
    const register unsigned short int OCR0B_0 = 0;
    sbit  OCR0B_1_bit at OCR0B.B1;
    const register unsigned short int OCR0B_1 = 1;
    sbit  OCR0B_2_bit at OCR0B.B2;
    const register unsigned short int OCR0B_2 = 2;
    sbit  OCR0B_3_bit at OCR0B.B3;
    const register unsigned short int OCR0B_3 = 3;
    sbit  OCR0B_4_bit at OCR0B.B4;
    const register unsigned short int OCR0B_4 = 4;
    sbit  OCR0B_5_bit at OCR0B.B5;
    const register unsigned short int OCR0B_5 = 5;
    sbit  OCR0B_6_bit at OCR0B.B6;
    const register unsigned short int OCR0B_6 = 6;
    sbit  OCR0B_7_bit at OCR0B.B7;
    const register unsigned short int OCR0B_7 = 7;

sfr io unsigned short OCR0A absolute 0x47;
    sbit  OCR0A_0_bit at OCR0A.B0;
    const register unsigned short int OCR0A_0 = 0;
    sbit  OCR0A_1_bit at OCR0A.B1;
    const register unsigned short int OCR0A_1 = 1;
    sbit  OCR0A_2_bit at OCR0A.B2;
    const register unsigned short int OCR0A_2 = 2;
    sbit  OCR0A_3_bit at OCR0A.B3;
    const register unsigned short int OCR0A_3 = 3;
    sbit  OCR0A_4_bit at OCR0A.B4;
    const register unsigned short int OCR0A_4 = 4;
    sbit  OCR0A_5_bit at OCR0A.B5;
    const register unsigned short int OCR0A_5 = 5;
    sbit  OCR0A_6_bit at OCR0A.B6;
    const register unsigned short int OCR0A_6 = 6;
    sbit  OCR0A_7_bit at OCR0A.B7;
    const register unsigned short int OCR0A_7 = 7;

sfr io unsigned short volatile TCNT0 absolute 0x46;
    sbit  TCNT0_0_bit at TCNT0.B0;
    const register unsigned short int TCNT0_0 = 0;
    sbit  TCNT0_1_bit at TCNT0.B1;
    const register unsigned short int TCNT0_1 = 1;
    sbit  TCNT0_2_bit at TCNT0.B2;
    const register unsigned short int TCNT0_2 = 2;
    sbit  TCNT0_3_bit at TCNT0.B3;
    const register unsigned short int TCNT0_3 = 3;
    sbit  TCNT0_4_bit at TCNT0.B4;
    const register unsigned short int TCNT0_4 = 4;
    sbit  TCNT0_5_bit at TCNT0.B5;
    const register unsigned short int TCNT0_5 = 5;
    sbit  TCNT0_6_bit at TCNT0.B6;
    const register unsigned short int TCNT0_6 = 6;
    sbit  TCNT0_7_bit at TCNT0.B7;
    const register unsigned short int TCNT0_7 = 7;

sfr io unsigned short TCCR0B absolute 0x45;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS00 = 0;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS01 = 1;
    sbit  CS02_bit at TCCR0B.B2;
    const register unsigned short int CS02 = 2;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int WGM02 = 3;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0A = 7;

sfr io unsigned short TCCR0A absolute 0x44;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM00 = 0;
    sbit  WGM01_bit at TCCR0A.B1;
    const register unsigned short int WGM01 = 1;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0A1 = 7;

sfr io unsigned short volatile GTCCR absolute 0x43;
    sbit  PSR10_bit at GTCCR.B0;
    const register unsigned short int PSR10 = 0;
    sbit  ICPSEL1_bit at GTCCR.B6;
    const register unsigned short int ICPSEL1 = 6;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int TSM = 7;
    sbit  PSRSYNC_bit at GTCCR.B0;
    const register unsigned short int PSRSYNC = 0;

sfr io unsigned short EEARH absolute 0x42;
    sbit  EEAR8_bit at EEARH.B0;
    const register unsigned short int EEAR8 = 0;
    sbit  EEAR9_bit at EEARH.B1;
    const register unsigned short int EEAR9 = 1;
    sbit  EEAR10_bit at EEARH.B2;
    const register unsigned short int EEAR10 = 2;
    sbit  EEAR11_bit at EEARH.B3;
    const register unsigned short int EEAR11 = 3;

sfr io unsigned short EEARL absolute 0x41;
    sbit  EEARL0_bit at EEARL.B0;
    const register unsigned short int EEARL0 = 0;
    sbit  EEARL1_bit at EEARL.B1;
    const register unsigned short int EEARL1 = 1;
    sbit  EEARL2_bit at EEARL.B2;
    const register unsigned short int EEARL2 = 2;
    sbit  EEARL3_bit at EEARL.B3;
    const register unsigned short int EEARL3 = 3;
    sbit  EEARL4_bit at EEARL.B4;
    const register unsigned short int EEARL4 = 4;
    sbit  EEARL5_bit at EEARL.B5;
    const register unsigned short int EEARL5 = 5;
    sbit  EEARL6_bit at EEARL.B6;
    const register unsigned short int EEARL6 = 6;
    sbit  EEARL7_bit at EEARL.B7;
    const register unsigned short int EEARL7 = 7;

sfr io unsigned short volatile EEDR absolute 0x40;
    sbit  EEDR0_bit at EEDR.B0;
    const register unsigned short int EEDR0 = 0;
    sbit  EEDR1_bit at EEDR.B1;
    const register unsigned short int EEDR1 = 1;
    sbit  EEDR2_bit at EEDR.B2;
    const register unsigned short int EEDR2 = 2;
    sbit  EEDR3_bit at EEDR.B3;
    const register unsigned short int EEDR3 = 3;
    sbit  EEDR4_bit at EEDR.B4;
    const register unsigned short int EEDR4 = 4;
    sbit  EEDR5_bit at EEDR.B5;
    const register unsigned short int EEDR5 = 5;
    sbit  EEDR6_bit at EEDR.B6;
    const register unsigned short int EEDR6 = 6;
    sbit  EEDR7_bit at EEDR.B7;
    const register unsigned short int EEDR7 = 7;

sfr io unsigned short volatile EECR absolute 0x3F;
    sbit  EERE_bit at EECR.B0;
    const register unsigned short int EERE = 0;
    sbit  EEWE_bit at EECR.B1;
    const register unsigned short int EEWE = 1;
    sbit  EEMWE_bit at EECR.B2;
    const register unsigned short int EEMWE = 2;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EERIE = 3;

sfr io unsigned short volatile GPIOR0 absolute 0x3E;
    sbit  GPIOR00_bit at GPIOR0.B0;
    const register unsigned short int GPIOR00 = 0;
    sbit  GPIOR01_bit at GPIOR0.B1;
    const register unsigned short int GPIOR01 = 1;
    sbit  GPIOR02_bit at GPIOR0.B2;
    const register unsigned short int GPIOR02 = 2;
    sbit  GPIOR03_bit at GPIOR0.B3;
    const register unsigned short int GPIOR03 = 3;
    sbit  GPIOR04_bit at GPIOR0.B4;
    const register unsigned short int GPIOR04 = 4;
    sbit  GPIOR05_bit at GPIOR0.B5;
    const register unsigned short int GPIOR05 = 5;
    sbit  GPIOR06_bit at GPIOR0.B6;
    const register unsigned short int GPIOR06 = 6;
    sbit  GPIOR07_bit at GPIOR0.B7;
    const register unsigned short int GPIOR07 = 7;

sfr io unsigned short EIMSK absolute 0x3D;
    sbit  INT0_bit at EIMSK.B0;
    const register unsigned short int INT0 = 0;
    sbit  INT1_bit at EIMSK.B1;
    const register unsigned short int INT1 = 1;
    sbit  INT2_bit at EIMSK.B2;
    const register unsigned short int INT2 = 2;

sfr io unsigned short volatile EIFR absolute 0x3C;
    sbit  INTF0_bit at EIFR.B0;
    const register unsigned short int INTF0 = 0;
    sbit  INTF1_bit at EIFR.B1;
    const register unsigned short int INTF1 = 1;
    sbit  INTF2_bit at EIFR.B2;
    const register unsigned short int INTF2 = 2;

sfr io unsigned short volatile GPIOR3 absolute 0x3B;
    sbit  GPIOR30_bit at GPIOR3.B0;
    const register unsigned short int GPIOR30 = 0;
    sbit  GPIOR31_bit at GPIOR3.B1;
    const register unsigned short int GPIOR31 = 1;
    sbit  GPIOR32_bit at GPIOR3.B2;
    const register unsigned short int GPIOR32 = 2;
    sbit  GPIOR33_bit at GPIOR3.B3;
    const register unsigned short int GPIOR33 = 3;
    sbit  GPIOR34_bit at GPIOR3.B4;
    const register unsigned short int GPIOR34 = 4;
    sbit  GPIOR35_bit at GPIOR3.B5;
    const register unsigned short int GPIOR35 = 5;
    sbit  GPIOR36_bit at GPIOR3.B6;
    const register unsigned short int GPIOR36 = 6;
    sbit  GPIOR37_bit at GPIOR3.B7;
    const register unsigned short int GPIOR37 = 7;

sfr io unsigned short volatile GPIOR2 absolute 0x3A;
    sbit  GPIOR20_bit at GPIOR2.B0;
    const register unsigned short int GPIOR20 = 0;
    sbit  GPIOR21_bit at GPIOR2.B1;
    const register unsigned short int GPIOR21 = 1;
    sbit  GPIOR22_bit at GPIOR2.B2;
    const register unsigned short int GPIOR22 = 2;
    sbit  GPIOR23_bit at GPIOR2.B3;
    const register unsigned short int GPIOR23 = 3;
    sbit  GPIOR24_bit at GPIOR2.B4;
    const register unsigned short int GPIOR24 = 4;
    sbit  GPIOR25_bit at GPIOR2.B5;
    const register unsigned short int GPIOR25 = 5;
    sbit  GPIOR26_bit at GPIOR2.B6;
    const register unsigned short int GPIOR26 = 6;
    sbit  GPIOR27_bit at GPIOR2.B7;
    const register unsigned short int GPIOR27 = 7;

sfr io unsigned short volatile GPIOR1 absolute 0x39;
    sbit  GPIOR10_bit at GPIOR1.B0;
    const register unsigned short int GPIOR10 = 0;
    sbit  GPIOR11_bit at GPIOR1.B1;
    const register unsigned short int GPIOR11 = 1;
    sbit  GPIOR12_bit at GPIOR1.B2;
    const register unsigned short int GPIOR12 = 2;
    sbit  GPIOR13_bit at GPIOR1.B3;
    const register unsigned short int GPIOR13 = 3;
    sbit  GPIOR14_bit at GPIOR1.B4;
    const register unsigned short int GPIOR14 = 4;
    sbit  GPIOR15_bit at GPIOR1.B5;
    const register unsigned short int GPIOR15 = 5;
    sbit  GPIOR16_bit at GPIOR1.B6;
    const register unsigned short int GPIOR16 = 6;
    sbit  GPIOR17_bit at GPIOR1.B7;
    const register unsigned short int GPIOR17 = 7;

sfr io unsigned short volatile TIFR1 absolute 0x36;
    sbit  TOV1_bit at TIFR1.B0;
    const register unsigned short int TOV1 = 0;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1B = 2;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int ICF1 = 5;

sfr io unsigned short volatile TIFR0 absolute 0x35;
    sbit  TOV0_bit at TIFR0.B0;
    const register unsigned short int TOV0 = 0;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0B = 2;

sfr io unsigned short PORTE absolute 0x2E;
    sbit  PORTE0_bit at PORTE.B0;
    const register unsigned short int PORTE0 = 0;
    sbit  PORTE1_bit at PORTE.B1;
    const register unsigned short int PORTE1 = 1;
    sbit  PORTE2_bit at PORTE.B2;
    const register unsigned short int PORTE2 = 2;

sfr io unsigned short DDRE absolute 0x2D;
    sbit  DDE0_bit at DDRE.B0;
    const register unsigned short int DDE0 = 0;
    sbit  DDE1_bit at DDRE.B1;
    const register unsigned short int DDE1 = 1;
    sbit  DDE2_bit at DDRE.B2;
    const register unsigned short int DDE2 = 2;

sfr io unsigned short volatile PINE absolute 0x2C;
    sbit  PINE0_bit at PINE.B0;
    const register unsigned short int PINE0 = 0;
    sbit  PINE1_bit at PINE.B1;
    const register unsigned short int PINE1 = 1;
    sbit  PINE2_bit at PINE.B2;
    const register unsigned short int PINE2 = 2;

sfr io unsigned short PORTD absolute 0x2B;
    sbit  PORTD0_bit at PORTD.B0;
    const register unsigned short int PORTD0 = 0;
    sbit  PORTD1_bit at PORTD.B1;
    const register unsigned short int PORTD1 = 1;
    sbit  PORTD2_bit at PORTD.B2;
    const register unsigned short int PORTD2 = 2;
    sbit  PORTD3_bit at PORTD.B3;
    const register unsigned short int PORTD3 = 3;
    sbit  PORTD4_bit at PORTD.B4;
    const register unsigned short int PORTD4 = 4;
    sbit  PORTD5_bit at PORTD.B5;
    const register unsigned short int PORTD5 = 5;
    sbit  PORTD6_bit at PORTD.B6;
    const register unsigned short int PORTD6 = 6;
    sbit  PORTD7_bit at PORTD.B7;
    const register unsigned short int PORTD7 = 7;

sfr io unsigned short DDRD absolute 0x2A;
    sbit  DDD0_bit at DDRD.B0;
    const register unsigned short int DDD0 = 0;
    sbit  DDD1_bit at DDRD.B1;
    const register unsigned short int DDD1 = 1;
    sbit  DDD2_bit at DDRD.B2;
    const register unsigned short int DDD2 = 2;
    sbit  DDD3_bit at DDRD.B3;
    const register unsigned short int DDD3 = 3;
    sbit  DDD4_bit at DDRD.B4;
    const register unsigned short int DDD4 = 4;
    sbit  DDD5_bit at DDRD.B5;
    const register unsigned short int DDD5 = 5;
    sbit  DDD6_bit at DDRD.B6;
    const register unsigned short int DDD6 = 6;
    sbit  DDD7_bit at DDRD.B7;
    const register unsigned short int DDD7 = 7;

sfr io unsigned short volatile PIND absolute 0x29;
    sbit  PIND0_bit at PIND.B0;
    const register unsigned short int PIND0 = 0;
    sbit  PIND1_bit at PIND.B1;
    const register unsigned short int PIND1 = 1;
    sbit  PIND2_bit at PIND.B2;
    const register unsigned short int PIND2 = 2;
    sbit  PIND3_bit at PIND.B3;
    const register unsigned short int PIND3 = 3;
    sbit  PIND4_bit at PIND.B4;
    const register unsigned short int PIND4 = 4;
    sbit  PIND5_bit at PIND.B5;
    const register unsigned short int PIND5 = 5;
    sbit  PIND6_bit at PIND.B6;
    const register unsigned short int PIND6 = 6;
    sbit  PIND7_bit at PIND.B7;
    const register unsigned short int PIND7 = 7;

sfr io unsigned short PORTB absolute 0x25;
    sbit  PORTB0_bit at PORTB.B0;
    const register unsigned short int PORTB0 = 0;
    sbit  PORTB1_bit at PORTB.B1;
    const register unsigned short int PORTB1 = 1;
    sbit  PORTB2_bit at PORTB.B2;
    const register unsigned short int PORTB2 = 2;
    sbit  PORTB3_bit at PORTB.B3;
    const register unsigned short int PORTB3 = 3;
    sbit  PORTB4_bit at PORTB.B4;
    const register unsigned short int PORTB4 = 4;
    sbit  PORTB5_bit at PORTB.B5;
    const register unsigned short int PORTB5 = 5;
    sbit  PORTB6_bit at PORTB.B6;
    const register unsigned short int PORTB6 = 6;
    sbit  PORTB7_bit at PORTB.B7;
    const register unsigned short int PORTB7 = 7;

sfr io unsigned short DDRB absolute 0x24;
    sbit  DDB0_bit at DDRB.B0;
    const register unsigned short int DDB0 = 0;
    sbit  DDB1_bit at DDRB.B1;
    const register unsigned short int DDB1 = 1;
    sbit  DDB2_bit at DDRB.B2;
    const register unsigned short int DDB2 = 2;
    sbit  DDB3_bit at DDRB.B3;
    const register unsigned short int DDB3 = 3;
    sbit  DDB4_bit at DDRB.B4;
    const register unsigned short int DDB4 = 4;
    sbit  DDB5_bit at DDRB.B5;
    const register unsigned short int DDB5 = 5;
    sbit  DDB6_bit at DDRB.B6;
    const register unsigned short int DDB6 = 6;
    sbit  DDB7_bit at DDRB.B7;
    const register unsigned short int DDB7 = 7;

sfr io unsigned short volatile PINB absolute 0x23;
    sbit  PINB0_bit at PINB.B0;
    const register unsigned short int PINB0 = 0;
    sbit  PINB1_bit at PINB.B1;
    const register unsigned short int PINB1 = 1;
    sbit  PINB2_bit at PINB.B2;
    const register unsigned short int PINB2 = 2;
    sbit  PINB3_bit at PINB.B3;
    const register unsigned short int PINB3 = 3;
    sbit  PINB4_bit at PINB.B4;
    const register unsigned short int PINB4 = 4;
    sbit  PINB5_bit at PINB.B5;
    const register unsigned short int PINB5 = 5;
    sbit  PINB6_bit at PINB.B6;
    const register unsigned short int PINB6 = 6;
    sbit  PINB7_bit at PINB.B7;
    const register unsigned short int PINB7 = 7;
