// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00020000;

// Flash page size in program words
const int __FLASH_PAGE_SIZE = 128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;

const unsigned int IVT_ADDR_RESET            = 0x0000;
const unsigned int IVT_ADDR_INT0             = 0x0002;
const unsigned int IVT_ADDR_INT1             = 0x0004;
const unsigned int IVT_ADDR_INT2             = 0x0006;
const unsigned int IVT_ADDR_INT3             = 0x0008;
const unsigned int IVT_ADDR_INT4             = 0x000A;
const unsigned int IVT_ADDR_INT5             = 0x000C;
const unsigned int IVT_ADDR_INT6             = 0x000E;
const unsigned int IVT_ADDR_INT7             = 0x0010;
const unsigned int IVT_ADDR_TIMER2_COMP      = 0x0012;
const unsigned int IVT_ADDR_TIMER2_OVF       = 0x0014;
const unsigned int IVT_ADDR_TIMER1_CAPT      = 0x0016;
const unsigned int IVT_ADDR_TIMER1_COMPA     = 0x0018;
const unsigned int IVT_ADDR_TIMER1_COMPB     = 0x001A;
const unsigned int IVT_ADDR_TIMER1_OVF       = 0x001C;
const unsigned int IVT_ADDR_TIMER0_COMP      = 0x001E;
const unsigned int IVT_ADDR_TIMER0_OVF       = 0x0020;
const unsigned int IVT_ADDR_SPI_STC          = 0x0022;
const unsigned int IVT_ADDR_UART_RX          = 0x0024;
const unsigned int IVT_ADDR_UART_UDRE        = 0x0026;
const unsigned int IVT_ADDR_UART_TX          = 0x0028;
const unsigned int IVT_ADDR_ADC              = 0x002A;
const unsigned int IVT_ADDR_EE_READY         = 0x002C;
const unsigned int IVT_ADDR_ANALOG_COMP      = 0x002E;


sfr io unsigned short volatile SREG absolute 0x5F;
    sbit  SREG_C_bit at SREG.B0;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_I = 7;

sfr io unsigned short volatile SPH absolute 0x5E;
    sbit  SP8_bit at SPH.B0;
    const register unsigned short int SP8 = 0;
    sbit  SP9_bit at SPH.B1;
    const register unsigned short int SP9 = 1;
    sbit  SP10_bit at SPH.B2;
    const register unsigned short int SP10 = 2;
    sbit  SP11_bit at SPH.B3;
    const register unsigned short int SP11 = 3;
    sbit  SP12_bit at SPH.B4;
    const register unsigned short int SP12 = 4;
    sbit  SP13_bit at SPH.B5;
    const register unsigned short int SP13 = 5;
    sbit  SP14_bit at SPH.B6;
    const register unsigned short int SP14 = 6;
    sbit  SP15_bit at SPH.B7;
    const register unsigned short int SP15 = 7;

sfr io unsigned short volatile SPL absolute 0x5D;
    sbit  SP0_bit at SPL.B0;
    const register unsigned short int SP0 = 0;
    sbit  SP1_bit at SPL.B1;
    const register unsigned short int SP1 = 1;
    sbit  SP2_bit at SPL.B2;
    const register unsigned short int SP2 = 2;
    sbit  SP3_bit at SPL.B3;
    const register unsigned short int SP3 = 3;
    sbit  SP4_bit at SPL.B4;
    const register unsigned short int SP4 = 4;
    sbit  SP5_bit at SPL.B5;
    const register unsigned short int SP5 = 5;
    sbit  SP6_bit at SPL.B6;
    const register unsigned short int SP6 = 6;
    sbit  SP7_bit at SPL.B7;
    const register unsigned short int SP7 = 7;

sfr io unsigned short volatile XDIV absolute 0x5C;
    sbit  XDIV0_bit at XDIV.B0;
    const register unsigned short int XDIV0 = 0;
    sbit  XDIV1_bit at XDIV.B1;
    const register unsigned short int XDIV1 = 1;
    sbit  XDIV2_bit at XDIV.B2;
    const register unsigned short int XDIV2 = 2;
    sbit  XDIV3_bit at XDIV.B3;
    const register unsigned short int XDIV3 = 3;
    sbit  XDIV4_bit at XDIV.B4;
    const register unsigned short int XDIV4 = 4;
    sbit  XDIV5_bit at XDIV.B5;
    const register unsigned short int XDIV5 = 5;
    sbit  XDIV6_bit at XDIV.B6;
    const register unsigned short int XDIV6 = 6;
    sbit  XDIVEN_bit at XDIV.B7;
    const register unsigned short int XDIVEN = 7;

sfr io unsigned short volatile RAMPZ absolute 0x5B;
    sbit  RAMPZ0_bit at RAMPZ.B0;
    const register unsigned short int RAMPZ0 = 0;

sfr io unsigned short volatile EICR absolute 0x5A;
    sbit  ISC40_bit at EICR.B0;
    const register unsigned short int ISC40 = 0;
    sbit  ISC41_bit at EICR.B1;
    const register unsigned short int ISC41 = 1;
    sbit  ISC50_bit at EICR.B2;
    const register unsigned short int ISC50 = 2;
    sbit  ISC51_bit at EICR.B3;
    const register unsigned short int ISC51 = 3;
    sbit  ISC60_bit at EICR.B4;
    const register unsigned short int ISC60 = 4;
    sbit  ISC61_bit at EICR.B5;
    const register unsigned short int ISC61 = 5;
    sbit  ISC70_bit at EICR.B6;
    const register unsigned short int ISC70 = 6;
    sbit  ISC71_bit at EICR.B7;
    const register unsigned short int ISC71 = 7;

sfr io unsigned short EIMSK absolute 0x59;
    sbit  INT0_bit at EIMSK.B0;
    const register unsigned short int INT0 = 0;
    sbit  INT1_bit at EIMSK.B1;
    const register unsigned short int INT1 = 1;
    sbit  INT2_bit at EIMSK.B2;
    const register unsigned short int INT2 = 2;
    sbit  INT3_bit at EIMSK.B3;
    const register unsigned short int INT3 = 3;
    sbit  INT4_bit at EIMSK.B4;
    const register unsigned short int INT4 = 4;
    sbit  INT5_bit at EIMSK.B5;
    const register unsigned short int INT5 = 5;
    sbit  INT6_bit at EIMSK.B6;
    const register unsigned short int INT6 = 6;
    sbit  INT7_bit at EIMSK.B7;
    const register unsigned short int INT7 = 7;

sfr io unsigned short volatile EIFR absolute 0x58;
    sbit  INTF4_bit at EIFR.B4;
    const register unsigned short int INTF4 = 4;
    sbit  INTF5_bit at EIFR.B5;
    const register unsigned short int INTF5 = 5;
    sbit  INTF6_bit at EIFR.B6;
    const register unsigned short int INTF6 = 6;
    sbit  INTF7_bit at EIFR.B7;
    const register unsigned short int INTF7 = 7;

sfr io unsigned short TIMSK absolute 0x57;
    sbit  TOIE2_bit at TIMSK.B6;
    const register unsigned short int TOIE2 = 6;
    sbit  OCIE2_bit at TIMSK.B7;
    const register unsigned short int OCIE2 = 7;
    sbit  TOIE0_bit at TIMSK.B0;
    const register unsigned short int TOIE0 = 0;
    sbit  OCIE0_bit at TIMSK.B1;
    const register unsigned short int OCIE0 = 1;
    sbit  TOIE1_bit at TIMSK.B2;
    const register unsigned short int TOIE1 = 2;
    sbit  OCIE1B_bit at TIMSK.B3;
    const register unsigned short int OCIE1B = 3;
    sbit  OCIE1A_bit at TIMSK.B4;
    const register unsigned short int OCIE1A = 4;
    sbit  TICIE1_bit at TIMSK.B5;
    const register unsigned short int TICIE1 = 5;

sfr io unsigned short volatile TIFR absolute 0x56;
    sbit  TOV2_bit at TIFR.B6;
    const register unsigned short int TOV2 = 6;
    sbit  OCF2_bit at TIFR.B7;
    const register unsigned short int OCF2 = 7;
    sbit  TOV0_bit at TIFR.B0;
    const register unsigned short int TOV0 = 0;
    sbit  OCF0_bit at TIFR.B1;
    const register unsigned short int OCF0 = 1;
    sbit  TOV1_bit at TIFR.B2;
    const register unsigned short int TOV1 = 2;
    sbit  OCF1B_bit at TIFR.B3;
    const register unsigned short int OCF1B = 3;
    sbit  OCF1A_bit at TIFR.B4;
    const register unsigned short int OCF1A = 4;
    sbit  ICF1_bit at TIFR.B5;
    const register unsigned short int ICF1 = 5;

sfr io unsigned short volatile MCUCR absolute 0x55;
    sbit  SM0_bit at MCUCR.B3;
    const register unsigned short int SM0 = 3;
    sbit  SM1_bit at MCUCR.B4;
    const register unsigned short int SM1 = 4;
    sbit  SE_bit at MCUCR.B5;
    const register unsigned short int SE = 5;
    sbit  SRW_bit at MCUCR.B6;
    const register unsigned short int SRW = 6;
    sbit  SRE_bit at MCUCR.B7;
    const register unsigned short int SRE = 7;

sfr io unsigned short volatile MCUSR absolute 0x54;
    sbit  PORF_bit at MCUSR.B0;
    const register unsigned short int PORF = 0;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int EXTRF = 1;

sfr io unsigned short TCCR0 absolute 0x53;
    sbit  CS00_bit at TCCR0.B0;
    const register unsigned short int CS00 = 0;
    sbit  CS01_bit at TCCR0.B1;
    const register unsigned short int CS01 = 1;
    sbit  CS02_bit at TCCR0.B2;
    const register unsigned short int CS02 = 2;
    sbit  CTC0_bit at TCCR0.B3;
    const register unsigned short int CTC0 = 3;
    sbit  COM00_bit at TCCR0.B4;
    const register unsigned short int COM00 = 4;
    sbit  COM01_bit at TCCR0.B5;
    const register unsigned short int COM01 = 5;
    sbit  PWM0_bit at TCCR0.B6;
    const register unsigned short int PWM0 = 6;

sfr io unsigned short volatile TCNT0 absolute 0x52;
    sbit  TCNT0_0_bit at TCNT0.B0;
    const register unsigned short int TCNT0_0 = 0;
    sbit  TCNT0_1_bit at TCNT0.B1;
    const register unsigned short int TCNT0_1 = 1;
    sbit  TCNT0_2_bit at TCNT0.B2;
    const register unsigned short int TCNT0_2 = 2;
    sbit  TCNT0_3_bit at TCNT0.B3;
    const register unsigned short int TCNT0_3 = 3;
    sbit  TCNT0_4_bit at TCNT0.B4;
    const register unsigned short int TCNT0_4 = 4;
    sbit  TCNT0_5_bit at TCNT0.B5;
    const register unsigned short int TCNT0_5 = 5;
    sbit  TCNT0_6_bit at TCNT0.B6;
    const register unsigned short int TCNT0_6 = 6;
    sbit  TCNT0_7_bit at TCNT0.B7;
    const register unsigned short int TCNT0_7 = 7;

sfr io unsigned short volatile OCR0 absolute 0x51;
    sbit  OCR0_0_bit at OCR0.B0;
    const register unsigned short int OCR0_0 = 0;
    sbit  OCR0_1_bit at OCR0.B1;
    const register unsigned short int OCR0_1 = 1;
    sbit  OCR0_2_bit at OCR0.B2;
    const register unsigned short int OCR0_2 = 2;
    sbit  OCR0_3_bit at OCR0.B3;
    const register unsigned short int OCR0_3 = 3;
    sbit  OCR0_4_bit at OCR0.B4;
    const register unsigned short int OCR0_4 = 4;
    sbit  OCR0_5_bit at OCR0.B5;
    const register unsigned short int OCR0_5 = 5;
    sbit  OCR0_6_bit at OCR0.B6;
    const register unsigned short int OCR0_6 = 6;
    sbit  OCR0_7_bit at OCR0.B7;
    const register unsigned short int OCR0_7 = 7;

sfr io unsigned short volatile ASSR absolute 0x50;
    sbit  TCR0UB_bit at ASSR.B0;
    const register unsigned short int TCR0UB = 0;
    sbit  OCR0UB_bit at ASSR.B1;
    const register unsigned short int OCR0UB = 1;
    sbit  TCN0UB_bit at ASSR.B2;
    const register unsigned short int TCN0UB = 2;
    sbit  AS0_bit at ASSR.B3;
    const register unsigned short int AS0 = 3;

sfr io unsigned short TCCR1A absolute 0x4F;
    sbit  PWM10_bit at TCCR1A.B0;
    const register unsigned short int PWM10 = 0;
    sbit  PWM11_bit at TCCR1A.B1;
    const register unsigned short int PWM11 = 1;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1A1 = 7;

sfr io unsigned short TCCR1B absolute 0x4E;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS10 = 0;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS11 = 1;
    sbit  CS12_bit at TCCR1B.B2;
    const register unsigned short int CS12 = 2;
    sbit  CTC1_bit at TCCR1B.B3;
    const register unsigned short int CTC1 = 3;
    sbit  ICES1_bit at TCCR1B.B6;
    const register unsigned short int ICES1 = 6;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICNC1 = 7;

sfr io unsigned short volatile TCNT1H absolute 0x4D;
    sbit  TCNT1H0_bit at TCNT1H.B0;
    const register unsigned short int TCNT1H0 = 0;
    sbit  TCNT1H1_bit at TCNT1H.B1;
    const register unsigned short int TCNT1H1 = 1;
    sbit  TCNT1H2_bit at TCNT1H.B2;
    const register unsigned short int TCNT1H2 = 2;
    sbit  TCNT1H3_bit at TCNT1H.B3;
    const register unsigned short int TCNT1H3 = 3;
    sbit  TCNT1H4_bit at TCNT1H.B4;
    const register unsigned short int TCNT1H4 = 4;
    sbit  TCNT1H5_bit at TCNT1H.B5;
    const register unsigned short int TCNT1H5 = 5;
    sbit  TCNT1H6_bit at TCNT1H.B6;
    const register unsigned short int TCNT1H6 = 6;
    sbit  TCNT1H7_bit at TCNT1H.B7;
    const register unsigned short int TCNT1H7 = 7;

sfr io unsigned short volatile TCNT1L absolute 0x4C;
    sbit  TCNT1L0_bit at TCNT1L.B0;
    const register unsigned short int TCNT1L0 = 0;
    sbit  TCNT1L1_bit at TCNT1L.B1;
    const register unsigned short int TCNT1L1 = 1;
    sbit  TCNT1L2_bit at TCNT1L.B2;
    const register unsigned short int TCNT1L2 = 2;
    sbit  TCNT1L3_bit at TCNT1L.B3;
    const register unsigned short int TCNT1L3 = 3;
    sbit  TCNT1L4_bit at TCNT1L.B4;
    const register unsigned short int TCNT1L4 = 4;
    sbit  TCNT1L5_bit at TCNT1L.B5;
    const register unsigned short int TCNT1L5 = 5;
    sbit  TCNT1L6_bit at TCNT1L.B6;
    const register unsigned short int TCNT1L6 = 6;
    sbit  TCNT1L7_bit at TCNT1L.B7;
    const register unsigned short int TCNT1L7 = 7;

sfr io unsigned short OCR1AH absolute 0x4B;
    sbit  OCR1AH0_bit at OCR1AH.B0;
    const register unsigned short int OCR1AH0 = 0;
    sbit  OCR1AH1_bit at OCR1AH.B1;
    const register unsigned short int OCR1AH1 = 1;
    sbit  OCR1AH2_bit at OCR1AH.B2;
    const register unsigned short int OCR1AH2 = 2;
    sbit  OCR1AH3_bit at OCR1AH.B3;
    const register unsigned short int OCR1AH3 = 3;
    sbit  OCR1AH4_bit at OCR1AH.B4;
    const register unsigned short int OCR1AH4 = 4;
    sbit  OCR1AH5_bit at OCR1AH.B5;
    const register unsigned short int OCR1AH5 = 5;
    sbit  OCR1AH6_bit at OCR1AH.B6;
    const register unsigned short int OCR1AH6 = 6;
    sbit  OCR1AH7_bit at OCR1AH.B7;
    const register unsigned short int OCR1AH7 = 7;

sfr io unsigned short OCR1AL absolute 0x4A;
    sbit  OCR1AL0_bit at OCR1AL.B0;
    const register unsigned short int OCR1AL0 = 0;
    sbit  OCR1AL1_bit at OCR1AL.B1;
    const register unsigned short int OCR1AL1 = 1;
    sbit  OCR1AL2_bit at OCR1AL.B2;
    const register unsigned short int OCR1AL2 = 2;
    sbit  OCR1AL3_bit at OCR1AL.B3;
    const register unsigned short int OCR1AL3 = 3;
    sbit  OCR1AL4_bit at OCR1AL.B4;
    const register unsigned short int OCR1AL4 = 4;
    sbit  OCR1AL5_bit at OCR1AL.B5;
    const register unsigned short int OCR1AL5 = 5;
    sbit  OCR1AL6_bit at OCR1AL.B6;
    const register unsigned short int OCR1AL6 = 6;
    sbit  OCR1AL7_bit at OCR1AL.B7;
    const register unsigned short int OCR1AL7 = 7;

sfr io unsigned short OCR1BH absolute 0x49;
    sbit  OCR1BH0_bit at OCR1BH.B0;
    const register unsigned short int OCR1BH0 = 0;
    sbit  OCR1BH1_bit at OCR1BH.B1;
    const register unsigned short int OCR1BH1 = 1;
    sbit  OCR1BH2_bit at OCR1BH.B2;
    const register unsigned short int OCR1BH2 = 2;
    sbit  OCR1BH3_bit at OCR1BH.B3;
    const register unsigned short int OCR1BH3 = 3;
    sbit  OCR1BH4_bit at OCR1BH.B4;
    const register unsigned short int OCR1BH4 = 4;
    sbit  OCR1BH5_bit at OCR1BH.B5;
    const register unsigned short int OCR1BH5 = 5;
    sbit  OCR1BH6_bit at OCR1BH.B6;
    const register unsigned short int OCR1BH6 = 6;
    sbit  OCR1BH7_bit at OCR1BH.B7;
    const register unsigned short int OCR1BH7 = 7;

sfr io unsigned short OCR1BL absolute 0x48;
    sbit  OCR1BL0_bit at OCR1BL.B0;
    const register unsigned short int OCR1BL0 = 0;
    sbit  OCR1BL1_bit at OCR1BL.B1;
    const register unsigned short int OCR1BL1 = 1;
    sbit  OCR1BL2_bit at OCR1BL.B2;
    const register unsigned short int OCR1BL2 = 2;
    sbit  OCR1BL3_bit at OCR1BL.B3;
    const register unsigned short int OCR1BL3 = 3;
    sbit  OCR1BL4_bit at OCR1BL.B4;
    const register unsigned short int OCR1BL4 = 4;
    sbit  OCR1BL5_bit at OCR1BL.B5;
    const register unsigned short int OCR1BL5 = 5;
    sbit  OCR1BL6_bit at OCR1BL.B6;
    const register unsigned short int OCR1BL6 = 6;
    sbit  OCR1BL7_bit at OCR1BL.B7;
    const register unsigned short int OCR1BL7 = 7;

sfr io unsigned short volatile ICR1H absolute 0x47;
    sbit  ICR1H0_bit at ICR1H.B0;
    const register unsigned short int ICR1H0 = 0;
    sbit  ICR1H1_bit at ICR1H.B1;
    const register unsigned short int ICR1H1 = 1;
    sbit  ICR1H2_bit at ICR1H.B2;
    const register unsigned short int ICR1H2 = 2;
    sbit  ICR1H3_bit at ICR1H.B3;
    const register unsigned short int ICR1H3 = 3;
    sbit  ICR1H4_bit at ICR1H.B4;
    const register unsigned short int ICR1H4 = 4;
    sbit  ICR1H5_bit at ICR1H.B5;
    const register unsigned short int ICR1H5 = 5;
    sbit  ICR1H6_bit at ICR1H.B6;
    const register unsigned short int ICR1H6 = 6;
    sbit  ICR1H7_bit at ICR1H.B7;
    const register unsigned short int ICR1H7 = 7;

sfr io unsigned short volatile ICR1L absolute 0x46;
    sbit  ICR1L0_bit at ICR1L.B0;
    const register unsigned short int ICR1L0 = 0;
    sbit  ICR1L1_bit at ICR1L.B1;
    const register unsigned short int ICR1L1 = 1;
    sbit  ICR1L2_bit at ICR1L.B2;
    const register unsigned short int ICR1L2 = 2;
    sbit  ICR1L3_bit at ICR1L.B3;
    const register unsigned short int ICR1L3 = 3;
    sbit  ICR1L4_bit at ICR1L.B4;
    const register unsigned short int ICR1L4 = 4;
    sbit  ICR1L5_bit at ICR1L.B5;
    const register unsigned short int ICR1L5 = 5;
    sbit  ICR1L6_bit at ICR1L.B6;
    const register unsigned short int ICR1L6 = 6;
    sbit  ICR1L7_bit at ICR1L.B7;
    const register unsigned short int ICR1L7 = 7;

sfr io unsigned short volatile TCCR2 absolute 0x45;
    sbit  CS20_bit at TCCR2.B0;
    const register unsigned short int CS20 = 0;
    sbit  CS21_bit at TCCR2.B1;
    const register unsigned short int CS21 = 1;
    sbit  CS22_bit at TCCR2.B2;
    const register unsigned short int CS22 = 2;
    sbit  CTC2_bit at TCCR2.B3;
    const register unsigned short int CTC2 = 3;
    sbit  COM20_bit at TCCR2.B4;
    const register unsigned short int COM20 = 4;
    sbit  COM21_bit at TCCR2.B5;
    const register unsigned short int COM21 = 5;
    sbit  PWM2_bit at TCCR2.B6;
    const register unsigned short int PWM2 = 6;

sfr io unsigned short volatile TCNT2 absolute 0x44;
    sbit  TCNT2_0_bit at TCNT2.B0;
    const register unsigned short int TCNT2_0 = 0;
    sbit  TCNT2_1_bit at TCNT2.B1;
    const register unsigned short int TCNT2_1 = 1;
    sbit  TCNT2_2_bit at TCNT2.B2;
    const register unsigned short int TCNT2_2 = 2;
    sbit  TCNT2_3_bit at TCNT2.B3;
    const register unsigned short int TCNT2_3 = 3;
    sbit  TCNT2_4_bit at TCNT2.B4;
    const register unsigned short int TCNT2_4 = 4;
    sbit  TCNT2_5_bit at TCNT2.B5;
    const register unsigned short int TCNT2_5 = 5;
    sbit  TCNT2_6_bit at TCNT2.B6;
    const register unsigned short int TCNT2_6 = 6;
    sbit  TCNT2_7_bit at TCNT2.B7;
    const register unsigned short int TCNT2_7 = 7;

sfr io unsigned short OCR2 absolute 0x43;
    sbit  OCR2_0_bit at OCR2.B0;
    const register unsigned short int OCR2_0 = 0;
    sbit  OCR2_1_bit at OCR2.B1;
    const register unsigned short int OCR2_1 = 1;
    sbit  OCR2_2_bit at OCR2.B2;
    const register unsigned short int OCR2_2 = 2;
    sbit  OCR2_3_bit at OCR2.B3;
    const register unsigned short int OCR2_3 = 3;
    sbit  OCR2_4_bit at OCR2.B4;
    const register unsigned short int OCR2_4 = 4;
    sbit  OCR2_5_bit at OCR2.B5;
    const register unsigned short int OCR2_5 = 5;
    sbit  OCR2_6_bit at OCR2.B6;
    const register unsigned short int OCR2_6 = 6;
    sbit  OCR2_7_bit at OCR2.B7;
    const register unsigned short int OCR2_7 = 7;

sfr io unsigned short volatile WDTCR absolute 0x41;
    sbit  WDP0_bit at WDTCR.B0;
    const register unsigned short int WDP0 = 0;
    sbit  WDP1_bit at WDTCR.B1;
    const register unsigned short int WDP1 = 1;
    sbit  WDP2_bit at WDTCR.B2;
    const register unsigned short int WDP2 = 2;
    sbit  WDE_bit at WDTCR.B3;
    const register unsigned short int WDE = 3;
    sbit  WDTOE_bit at WDTCR.B4;
    const register unsigned short int WDTOE = 4;

sfr io unsigned short EEARH absolute 0x3F;
    sbit  EEAR8_bit at EEARH.B0;
    const register unsigned short int EEAR8 = 0;
    sbit  EEAR9_bit at EEARH.B1;
    const register unsigned short int EEAR9 = 1;
    sbit  EEAR10_bit at EEARH.B2;
    const register unsigned short int EEAR10 = 2;
    sbit  EEAR11_bit at EEARH.B3;
    const register unsigned short int EEAR11 = 3;

sfr io unsigned short EEARL absolute 0x3E;
    sbit  EEARL0_bit at EEARL.B0;
    const register unsigned short int EEARL0 = 0;
    sbit  EEARL1_bit at EEARL.B1;
    const register unsigned short int EEARL1 = 1;
    sbit  EEARL2_bit at EEARL.B2;
    const register unsigned short int EEARL2 = 2;
    sbit  EEARL3_bit at EEARL.B3;
    const register unsigned short int EEARL3 = 3;
    sbit  EEARL4_bit at EEARL.B4;
    const register unsigned short int EEARL4 = 4;
    sbit  EEARL5_bit at EEARL.B5;
    const register unsigned short int EEARL5 = 5;
    sbit  EEARL6_bit at EEARL.B6;
    const register unsigned short int EEARL6 = 6;
    sbit  EEARL7_bit at EEARL.B7;
    const register unsigned short int EEARL7 = 7;

sfr io unsigned short volatile EEDR absolute 0x3D;
    sbit  EEDR0_bit at EEDR.B0;
    const register unsigned short int EEDR0 = 0;
    sbit  EEDR1_bit at EEDR.B1;
    const register unsigned short int EEDR1 = 1;
    sbit  EEDR2_bit at EEDR.B2;
    const register unsigned short int EEDR2 = 2;
    sbit  EEDR3_bit at EEDR.B3;
    const register unsigned short int EEDR3 = 3;
    sbit  EEDR4_bit at EEDR.B4;
    const register unsigned short int EEDR4 = 4;
    sbit  EEDR5_bit at EEDR.B5;
    const register unsigned short int EEDR5 = 5;
    sbit  EEDR6_bit at EEDR.B6;
    const register unsigned short int EEDR6 = 6;
    sbit  EEDR7_bit at EEDR.B7;
    const register unsigned short int EEDR7 = 7;

sfr io unsigned short volatile EECR absolute 0x3C;
    sbit  EERE_bit at EECR.B0;
    const register unsigned short int EERE = 0;
    sbit  EEWE_bit at EECR.B1;
    const register unsigned short int EEWE = 1;
    sbit  EEMWE_bit at EECR.B2;
    const register unsigned short int EEMWE = 2;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EERIE = 3;

sfr io unsigned short PORTA absolute 0x3B;
    sbit  PORTA0_bit at PORTA.B0;
    const register unsigned short int PORTA0 = 0;
    sbit  PORTA1_bit at PORTA.B1;
    const register unsigned short int PORTA1 = 1;
    sbit  PORTA2_bit at PORTA.B2;
    const register unsigned short int PORTA2 = 2;
    sbit  PORTA3_bit at PORTA.B3;
    const register unsigned short int PORTA3 = 3;
    sbit  PORTA4_bit at PORTA.B4;
    const register unsigned short int PORTA4 = 4;
    sbit  PORTA5_bit at PORTA.B5;
    const register unsigned short int PORTA5 = 5;
    sbit  PORTA6_bit at PORTA.B6;
    const register unsigned short int PORTA6 = 6;
    sbit  PORTA7_bit at PORTA.B7;
    const register unsigned short int PORTA7 = 7;

sfr io unsigned short DDRA absolute 0x3A;
    sbit  DDA0_bit at DDRA.B0;
    const register unsigned short int DDA0 = 0;
    sbit  DDA1_bit at DDRA.B1;
    const register unsigned short int DDA1 = 1;
    sbit  DDA2_bit at DDRA.B2;
    const register unsigned short int DDA2 = 2;
    sbit  DDA3_bit at DDRA.B3;
    const register unsigned short int DDA3 = 3;
    sbit  DDA4_bit at DDRA.B4;
    const register unsigned short int DDA4 = 4;
    sbit  DDA5_bit at DDRA.B5;
    const register unsigned short int DDA5 = 5;
    sbit  DDA6_bit at DDRA.B6;
    const register unsigned short int DDA6 = 6;
    sbit  DDA7_bit at DDRA.B7;
    const register unsigned short int DDA7 = 7;

sfr io unsigned short volatile PINA absolute 0x39;
    sbit  PINA0_bit at PINA.B0;
    const register unsigned short int PINA0 = 0;
    sbit  PINA1_bit at PINA.B1;
    const register unsigned short int PINA1 = 1;
    sbit  PINA2_bit at PINA.B2;
    const register unsigned short int PINA2 = 2;
    sbit  PINA3_bit at PINA.B3;
    const register unsigned short int PINA3 = 3;
    sbit  PINA4_bit at PINA.B4;
    const register unsigned short int PINA4 = 4;
    sbit  PINA5_bit at PINA.B5;
    const register unsigned short int PINA5 = 5;
    sbit  PINA6_bit at PINA.B6;
    const register unsigned short int PINA6 = 6;
    sbit  PINA7_bit at PINA.B7;
    const register unsigned short int PINA7 = 7;

sfr io unsigned short PORTB absolute 0x38;
    sbit  PORTB0_bit at PORTB.B0;
    const register unsigned short int PORTB0 = 0;
    sbit  PORTB1_bit at PORTB.B1;
    const register unsigned short int PORTB1 = 1;
    sbit  PORTB2_bit at PORTB.B2;
    const register unsigned short int PORTB2 = 2;
    sbit  PORTB3_bit at PORTB.B3;
    const register unsigned short int PORTB3 = 3;
    sbit  PORTB4_bit at PORTB.B4;
    const register unsigned short int PORTB4 = 4;
    sbit  PORTB5_bit at PORTB.B5;
    const register unsigned short int PORTB5 = 5;
    sbit  PORTB6_bit at PORTB.B6;
    const register unsigned short int PORTB6 = 6;
    sbit  PORTB7_bit at PORTB.B7;
    const register unsigned short int PORTB7 = 7;

sfr io unsigned short DDRB absolute 0x37;
    sbit  DDB0_bit at DDRB.B0;
    const register unsigned short int DDB0 = 0;
    sbit  DDB1_bit at DDRB.B1;
    const register unsigned short int DDB1 = 1;
    sbit  DDB2_bit at DDRB.B2;
    const register unsigned short int DDB2 = 2;
    sbit  DDB3_bit at DDRB.B3;
    const register unsigned short int DDB3 = 3;
    sbit  DDB4_bit at DDRB.B4;
    const register unsigned short int DDB4 = 4;
    sbit  DDB5_bit at DDRB.B5;
    const register unsigned short int DDB5 = 5;
    sbit  DDB6_bit at DDRB.B6;
    const register unsigned short int DDB6 = 6;
    sbit  DDB7_bit at DDRB.B7;
    const register unsigned short int DDB7 = 7;

sfr io unsigned short volatile PINB absolute 0x36;
    sbit  PINB0_bit at PINB.B0;
    const register unsigned short int PINB0 = 0;
    sbit  PINB1_bit at PINB.B1;
    const register unsigned short int PINB1 = 1;
    sbit  PINB2_bit at PINB.B2;
    const register unsigned short int PINB2 = 2;
    sbit  PINB3_bit at PINB.B3;
    const register unsigned short int PINB3 = 3;
    sbit  PINB4_bit at PINB.B4;
    const register unsigned short int PINB4 = 4;
    sbit  PINB5_bit at PINB.B5;
    const register unsigned short int PINB5 = 5;
    sbit  PINB6_bit at PINB.B6;
    const register unsigned short int PINB6 = 6;
    sbit  PINB7_bit at PINB.B7;
    const register unsigned short int PINB7 = 7;

sfr io unsigned short PORTC absolute 0x35;
    sbit  PORTC0_bit at PORTC.B0;
    const register unsigned short int PORTC0 = 0;
    sbit  PORTC1_bit at PORTC.B1;
    const register unsigned short int PORTC1 = 1;
    sbit  PORTC2_bit at PORTC.B2;
    const register unsigned short int PORTC2 = 2;
    sbit  PORTC3_bit at PORTC.B3;
    const register unsigned short int PORTC3 = 3;
    sbit  PORTC4_bit at PORTC.B4;
    const register unsigned short int PORTC4 = 4;
    sbit  PORTC5_bit at PORTC.B5;
    const register unsigned short int PORTC5 = 5;
    sbit  PORTC6_bit at PORTC.B6;
    const register unsigned short int PORTC6 = 6;
    sbit  PORTC7_bit at PORTC.B7;
    const register unsigned short int PORTC7 = 7;

sfr io unsigned short PORTD absolute 0x32;
    sbit  PORTD0_bit at PORTD.B0;
    const register unsigned short int PORTD0 = 0;
    sbit  PORTD1_bit at PORTD.B1;
    const register unsigned short int PORTD1 = 1;
    sbit  PORTD2_bit at PORTD.B2;
    const register unsigned short int PORTD2 = 2;
    sbit  PORTD3_bit at PORTD.B3;
    const register unsigned short int PORTD3 = 3;
    sbit  PORTD4_bit at PORTD.B4;
    const register unsigned short int PORTD4 = 4;
    sbit  PORTD5_bit at PORTD.B5;
    const register unsigned short int PORTD5 = 5;
    sbit  PORTD6_bit at PORTD.B6;
    const register unsigned short int PORTD6 = 6;
    sbit  PORTD7_bit at PORTD.B7;
    const register unsigned short int PORTD7 = 7;

sfr io unsigned short DDRD absolute 0x31;
    sbit  DDD0_bit at DDRD.B0;
    const register unsigned short int DDD0 = 0;
    sbit  DDD1_bit at DDRD.B1;
    const register unsigned short int DDD1 = 1;
    sbit  DDD2_bit at DDRD.B2;
    const register unsigned short int DDD2 = 2;
    sbit  DDD3_bit at DDRD.B3;
    const register unsigned short int DDD3 = 3;
    sbit  DDD4_bit at DDRD.B4;
    const register unsigned short int DDD4 = 4;
    sbit  DDD5_bit at DDRD.B5;
    const register unsigned short int DDD5 = 5;
    sbit  DDD6_bit at DDRD.B6;
    const register unsigned short int DDD6 = 6;
    sbit  DDD7_bit at DDRD.B7;
    const register unsigned short int DDD7 = 7;

sfr io unsigned short volatile PIND absolute 0x30;
    sbit  PIND0_bit at PIND.B0;
    const register unsigned short int PIND0 = 0;
    sbit  PIND1_bit at PIND.B1;
    const register unsigned short int PIND1 = 1;
    sbit  PIND2_bit at PIND.B2;
    const register unsigned short int PIND2 = 2;
    sbit  PIND3_bit at PIND.B3;
    const register unsigned short int PIND3 = 3;
    sbit  PIND4_bit at PIND.B4;
    const register unsigned short int PIND4 = 4;
    sbit  PIND5_bit at PIND.B5;
    const register unsigned short int PIND5 = 5;
    sbit  PIND6_bit at PIND.B6;
    const register unsigned short int PIND6 = 6;
    sbit  PIND7_bit at PIND.B7;
    const register unsigned short int PIND7 = 7;

sfr io unsigned short volatile SPDR absolute 0x2F;
    sbit  SPDR0_bit at SPDR.B0;
    const register unsigned short int SPDR0 = 0;
    sbit  SPDR1_bit at SPDR.B1;
    const register unsigned short int SPDR1 = 1;
    sbit  SPDR2_bit at SPDR.B2;
    const register unsigned short int SPDR2 = 2;
    sbit  SPDR3_bit at SPDR.B3;
    const register unsigned short int SPDR3 = 3;
    sbit  SPDR4_bit at SPDR.B4;
    const register unsigned short int SPDR4 = 4;
    sbit  SPDR5_bit at SPDR.B5;
    const register unsigned short int SPDR5 = 5;
    sbit  SPDR6_bit at SPDR.B6;
    const register unsigned short int SPDR6 = 6;
    sbit  SPDR7_bit at SPDR.B7;
    const register unsigned short int SPDR7 = 7;

sfr io unsigned short volatile SPSR absolute 0x2E;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int WCOL = 6;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int SPIF = 7;

sfr io unsigned short SPCR absolute 0x2D;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR0 = 0;
    sbit  SPR1_bit at SPCR.B1;
    const register unsigned short int SPR1 = 1;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int CPHA = 2;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPOL = 3;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int MSTR = 4;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int DORD = 5;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int SPE = 6;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPIE = 7;

sfr io unsigned short volatile UDR0 absolute 0x2C;
sfr io unsigned short volatile UDR absolute 0x2C;
    sbit  UDR0__bit at UDR.B0;
    const register unsigned short int UDR0_ = 0;
    sbit  UDR1_bit at UDR.B1;
    const register unsigned short int UDR1 = 1;
    sbit  UDR2_bit at UDR.B2;
    const register unsigned short int UDR2 = 2;
    sbit  UDR3_bit at UDR.B3;
    const register unsigned short int UDR3 = 3;
    sbit  UDR4_bit at UDR.B4;
    const register unsigned short int UDR4 = 4;
    sbit  UDR5_bit at UDR.B5;
    const register unsigned short int UDR5 = 5;
    sbit  UDR6_bit at UDR.B6;
    const register unsigned short int UDR6 = 6;
    sbit  UDR7_bit at UDR.B7;
    const register unsigned short int UDR7 = 7;

sfr io unsigned short volatile USR absolute 0x2B;
    sbit  OR__bit at USR.B3;
    const register unsigned short int OR_ = 3;
    sbit  FE_bit at USR.B4;
    const register unsigned short int FE = 4;
    sbit  UDRE0_bit at USR.B5;
    const register unsigned short int UDRE0 = 5;
    sbit  UDRE_bit at USR.B5;
    const register unsigned short int UDRE = 5;
    sbit  TXC0_bit at USR.B6;
    const register unsigned short int TXC0 = 6;
    sbit  TXC_bit at USR.B6;
    const register unsigned short int TXC = 6;
    sbit  RXC0_bit at USR.B7;
    const register unsigned short int RXC0 = 7;
    sbit  RXC_bit at USR.B7;
    const register unsigned short int RXC = 7;

sfr io unsigned short volatile UCSRB absolute 0x2A;
sfr io unsigned short volatile UCR absolute 0x2A;
    sbit  TXB8_bit at UCR.B0;
    const register unsigned short int TXB8 = 0;
    sbit  RXB8_bit at UCR.B1;
    const register unsigned short int RXB8 = 1;
    sbit  CHR9_bit at UCR.B2;
    const register unsigned short int CHR9 = 2;
    sbit  TXEN_bit at UCR.B3;
    const register unsigned short int TXEN = 3;
    sbit  RXEN_bit at UCR.B4;
    const register unsigned short int RXEN = 4;
    sbit  UDRIE_bit at UCR.B5;
    const register unsigned short int UDRIE = 5;
    sbit  TXCIE_bit at UCR.B6;
    const register unsigned short int TXCIE = 6;
    sbit  RXCIE_bit at UCR.B7;
    const register unsigned short int RXCIE = 7;

sfr io unsigned short UBRR absolute 0x29;
    sbit  UBRR0_bit at UBRR.B0;
    const register unsigned short int UBRR0 = 0;
    sbit  UBRR1_bit at UBRR.B1;
    const register unsigned short int UBRR1 = 1;
    sbit  UBRR2_bit at UBRR.B2;
    const register unsigned short int UBRR2 = 2;
    sbit  UBRR3_bit at UBRR.B3;
    const register unsigned short int UBRR3 = 3;
    sbit  UBRR4_bit at UBRR.B4;
    const register unsigned short int UBRR4 = 4;
    sbit  UBRR5_bit at UBRR.B5;
    const register unsigned short int UBRR5 = 5;
    sbit  UBRR6_bit at UBRR.B6;
    const register unsigned short int UBRR6 = 6;
    sbit  UBRR7_bit at UBRR.B7;
    const register unsigned short int UBRR7 = 7;

sfr io unsigned short volatile ACSR absolute 0x28;
    sbit  ACIS0_bit at ACSR.B0;
    const register unsigned short int ACIS0 = 0;
    sbit  ACIS1_bit at ACSR.B1;
    const register unsigned short int ACIS1 = 1;
    sbit  ACIC_bit at ACSR.B2;
    const register unsigned short int ACIC = 2;
    sbit  ACIE_bit at ACSR.B3;
    const register unsigned short int ACIE = 3;
    sbit  ACI_bit at ACSR.B4;
    const register unsigned short int ACI = 4;
    sbit  ACO_bit at ACSR.B5;
    const register unsigned short int ACO = 5;
    sbit  ACD_bit at ACSR.B7;
    const register unsigned short int ACD = 7;

sfr io unsigned short ADMUX absolute 0x27;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX0 = 0;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX1 = 1;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX2 = 2;

sfr io unsigned short volatile ADCSRA absolute 0x26;
sfr io unsigned short volatile ADCSR absolute 0x26;
    sbit  ADPS0_bit at ADCSR.B0;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS1_bit at ADCSR.B1;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS2_bit at ADCSR.B2;
    const register unsigned short int ADPS2 = 2;
    sbit  ADIE_bit at ADCSR.B3;
    const register unsigned short int ADIE = 3;
    sbit  ADIF_bit at ADCSR.B4;
    const register unsigned short int ADIF = 4;
    sbit  ADSC_bit at ADCSR.B6;
    const register unsigned short int ADSC = 6;
    sbit  ADEN_bit at ADCSR.B7;
    const register unsigned short int ADEN = 7;

sfr io unsigned short volatile ADCH absolute 0x25;
    sbit  ADC8_bit at ADCH.B0;
    const register unsigned short int ADC8 = 0;
    sbit  ADC9_bit at ADCH.B1;
    const register unsigned short int ADC9 = 1;

sfr io unsigned short volatile ADCL absolute 0x24;
    sbit  ADC0_bit at ADCL.B0;
    const register unsigned short int ADC0 = 0;
    sbit  ADC1_bit at ADCL.B1;
    const register unsigned short int ADC1 = 1;
    sbit  ADC2_bit at ADCL.B2;
    const register unsigned short int ADC2 = 2;
    sbit  ADC3_bit at ADCL.B3;
    const register unsigned short int ADC3 = 3;
    sbit  ADC4_bit at ADCL.B4;
    const register unsigned short int ADC4 = 4;
    sbit  ADC5_bit at ADCL.B5;
    const register unsigned short int ADC5 = 5;
    sbit  ADC6_bit at ADCL.B6;
    const register unsigned short int ADC6 = 6;
    sbit  ADC7_bit at ADCL.B7;
    const register unsigned short int ADC7 = 7;

sfr io unsigned short PORTE absolute 0x23;
    sbit  PORTE0_bit at PORTE.B0;
    const register unsigned short int PORTE0 = 0;
    sbit  PORTE1_bit at PORTE.B1;
    const register unsigned short int PORTE1 = 1;
    sbit  PORTE2_bit at PORTE.B2;
    const register unsigned short int PORTE2 = 2;
    sbit  PORTE3_bit at PORTE.B3;
    const register unsigned short int PORTE3 = 3;
    sbit  PORTE4_bit at PORTE.B4;
    const register unsigned short int PORTE4 = 4;
    sbit  PORTE5_bit at PORTE.B5;
    const register unsigned short int PORTE5 = 5;
    sbit  PORTE6_bit at PORTE.B6;
    const register unsigned short int PORTE6 = 6;
    sbit  PORTE7_bit at PORTE.B7;
    const register unsigned short int PORTE7 = 7;

sfr io unsigned short DDRE absolute 0x22;
    sbit  DDE0_bit at DDRE.B0;
    const register unsigned short int DDE0 = 0;
    sbit  DDE1_bit at DDRE.B1;
    const register unsigned short int DDE1 = 1;
    sbit  DDE2_bit at DDRE.B2;
    const register unsigned short int DDE2 = 2;
    sbit  DDE3_bit at DDRE.B3;
    const register unsigned short int DDE3 = 3;
    sbit  DDE4_bit at DDRE.B4;
    const register unsigned short int DDE4 = 4;
    sbit  DDE5_bit at DDRE.B5;
    const register unsigned short int DDE5 = 5;
    sbit  DDE6_bit at DDRE.B6;
    const register unsigned short int DDE6 = 6;
    sbit  DDE7_bit at DDRE.B7;
    const register unsigned short int DDE7 = 7;

sfr io unsigned short volatile PINE absolute 0x21;
    sbit  PINE0_bit at PINE.B0;
    const register unsigned short int PINE0 = 0;
    sbit  PINE1_bit at PINE.B1;
    const register unsigned short int PINE1 = 1;
    sbit  PINE2_bit at PINE.B2;
    const register unsigned short int PINE2 = 2;
    sbit  PINE3_bit at PINE.B3;
    const register unsigned short int PINE3 = 3;
    sbit  PINE4_bit at PINE.B4;
    const register unsigned short int PINE4 = 4;
    sbit  PINE5_bit at PINE.B5;
    const register unsigned short int PINE5 = 5;
    sbit  PINE6_bit at PINE.B6;
    const register unsigned short int PINE6 = 6;
    sbit  PINE7_bit at PINE.B7;
    const register unsigned short int PINE7 = 7;

sfr io unsigned short volatile PINF absolute 0x20;
    sbit  PINF0_bit at PINF.B0;
    const register unsigned short int PINF0 = 0;
    sbit  PINF1_bit at PINF.B1;
    const register unsigned short int PINF1 = 1;
    sbit  PINF2_bit at PINF.B2;
    const register unsigned short int PINF2 = 2;
    sbit  PINF3_bit at PINF.B3;
    const register unsigned short int PINF3 = 3;
    sbit  PINF4_bit at PINF.B4;
    const register unsigned short int PINF4 = 4;
    sbit  PINF5_bit at PINF.B5;
    const register unsigned short int PINF5 = 5;
    sbit  PINF6_bit at PINF.B6;
    const register unsigned short int PINF6 = 6;
    sbit  PINF7_bit at PINF.B7;
    const register unsigned short int PINF7 = 7;
