// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00004000;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;


// Interrupt Vector Table Constants
const unsigned short IVT_ADDR_INT0 = 0x0002;
const unsigned short IVT_ADDR_INT1 = 0x0004;
const unsigned short IVT_ADDR_PCINT0 = 0x0006;
const unsigned short IVT_ADDR_PCINT1 = 0x0008;
const unsigned short IVT_ADDR_PCINT2 = 0x000A;
const unsigned short IVT_ADDR_WDT = 0x000C;
const unsigned short IVT_ADDR_TIMER2_COMPA = 0x000E;
const unsigned short IVT_ADDR_TIMER2_COMPB = 0x0010;
const unsigned short IVT_ADDR_TIMER2_OVF = 0x0012;
const unsigned short IVT_ADDR_TIMER1_CAPT = 0x0014;
const unsigned short IVT_ADDR_TIMER1_COMPA = 0x0016;
const unsigned short IVT_ADDR_TIMER1_COMPB = 0x0018;
const unsigned short IVT_ADDR_TIMER1_OVF = 0x001A;
const unsigned short IVT_ADDR_TIMER0_COMPA = 0x001C;
const unsigned short IVT_ADDR_TIMER0_COMPB = 0x001E;
const unsigned short IVT_ADDR_TIMER0_OVF = 0x0020;
const unsigned short IVT_ADDR_SPI_STC = 0x0022;
const unsigned short IVT_ADDR_USART_RX = 0x0024;
const unsigned short IVT_ADDR_USART_UDRE = 0x0026;
const unsigned short IVT_ADDR_USART_TX = 0x0028;
const unsigned short IVT_ADDR_ADC = 0x002A;
const unsigned short IVT_ADDR_EE_READY = 0x002C;
const unsigned short IVT_ADDR_ANALOG_COMP = 0x002E;
const unsigned short IVT_ADDR_TWI = 0x0030;
const unsigned short IVT_ADDR_SPM_Ready = 0x0032;
const unsigned short IVT_ADDR_USART_START = 0x0034;

sfr data unsigned char volatile UDR0                      absolute 0x00C6;
sfr data unsigned char volatile UCSR0A                    absolute 0x00C0;
    const register unsigned short int RXC0 = 7;
    sbit  RXC0_bit at UCSR0A.B7;
    const register unsigned short int TXC0 = 6;
    sbit  TXC0_bit at UCSR0A.B6;
    const register unsigned short int UDRE0 = 5;
    sbit  UDRE0_bit at UCSR0A.B5;
    const register unsigned short int FE0 = 4;
    sbit  FE0_bit at UCSR0A.B4;
    const register unsigned short int DOR0 = 3;
    sbit  DOR0_bit at UCSR0A.B3;
    const register unsigned short int UPE0 = 2;
    sbit  UPE0_bit at UCSR0A.B2;
    const register unsigned short int U2X0 = 1;
    sbit  U2X0_bit at UCSR0A.B1;
    const register unsigned short int MPCM0 = 0;
    sbit  MPCM0_bit at UCSR0A.B0;

sfr data unsigned char volatile UCSR0B                    absolute 0x00C1;
    const register unsigned short int RXCIE0 = 7;
    sbit  RXCIE0_bit at UCSR0B.B7;
    const register unsigned short int TXCIE0 = 6;
    sbit  TXCIE0_bit at UCSR0B.B6;
    const register unsigned short int UDRIE0 = 5;
    sbit  UDRIE0_bit at UCSR0B.B5;
    const register unsigned short int RXEN0 = 4;
    sbit  RXEN0_bit at UCSR0B.B4;
    const register unsigned short int TXEN0 = 3;
    sbit  TXEN0_bit at UCSR0B.B3;
    const register unsigned short int UCSZ02 = 2;
    sbit  UCSZ02_bit at UCSR0B.B2;
    const register unsigned short int RXB80 = 1;
    sbit  RXB80_bit at UCSR0B.B1;
    const register unsigned short int TXB80 = 0;
    sbit  TXB80_bit at UCSR0B.B0;

sfr data unsigned char volatile UCSR0C                    absolute 0x00C2;
    const register unsigned short int UMSEL00 = 6;
    sbit  UMSEL00_bit at UCSR0C.B6;
    const register unsigned short int UMSEL01 = 7;
    sbit  UMSEL01_bit at UCSR0C.B7;
    const register unsigned short int UPM00 = 4;
    sbit  UPM00_bit at UCSR0C.B4;
    const register unsigned short int UPM01 = 5;
    sbit  UPM01_bit at UCSR0C.B5;
    const register unsigned short int USBS0 = 3;
    sbit  USBS0_bit at UCSR0C.B3;
    const register unsigned short int UCSZ00 = 1;
    sbit  UCSZ00_bit at UCSR0C.B1;
    const register unsigned short int UCSZ01 = 2;
    sbit  UCSZ01_bit at UCSR0C.B2;
    const register unsigned short int UCPOL0 = 0;
    sbit  UCPOL0_bit at UCSR0C.B0;

sfr data unsigned char volatile UCSR0D                    absolute 0x00C3;
    const register unsigned short int RXSIE = 7;
    sbit  RXSIE_bit at UCSR0D.B7;
    const register unsigned short int RXS = 6;
    sbit  RXS_bit at UCSR0D.B6;
    const register unsigned short int SFDE = 5;
    sbit  SFDE_bit at UCSR0D.B5;

sfr data unsigned int  UBRR0                     absolute 0x00C4;
sfr data unsigned char UBRR0L                    absolute 0x00C4;
sfr data unsigned char UBRR0H                    absolute 0x00C5;
sfr data unsigned char TWAMR                     absolute 0x00BD;
    const register unsigned short int TWAM0 = 1;
    sbit  TWAM0_bit at TWAMR.B1;
    const register unsigned short int TWAM1 = 2;
    sbit  TWAM1_bit at TWAMR.B2;
    const register unsigned short int TWAM2 = 3;
    sbit  TWAM2_bit at TWAMR.B3;
    const register unsigned short int TWAM3 = 4;
    sbit  TWAM3_bit at TWAMR.B4;
    const register unsigned short int TWAM4 = 5;
    sbit  TWAM4_bit at TWAMR.B5;
    const register unsigned short int TWAM5 = 6;
    sbit  TWAM5_bit at TWAMR.B6;
    const register unsigned short int TWAM6 = 7;
    sbit  TWAM6_bit at TWAMR.B7;

sfr data unsigned char TWBR                      absolute 0x00B8;
sfr data unsigned char volatile TWCR                      absolute 0x00BC;
    const register unsigned short int TWINT = 7;
    sbit  TWINT_bit at TWCR.B7;
    const register unsigned short int TWEA = 6;
    sbit  TWEA_bit at TWCR.B6;
    const register unsigned short int TWSTA = 5;
    sbit  TWSTA_bit at TWCR.B5;
    const register unsigned short int TWSTO = 4;
    sbit  TWSTO_bit at TWCR.B4;
    const register unsigned short int TWWC = 3;
    sbit  TWWC_bit at TWCR.B3;
    const register unsigned short int TWEN = 2;
    sbit  TWEN_bit at TWCR.B2;
    const register unsigned short int TWIE = 0;
    sbit  TWIE_bit at TWCR.B0;

sfr data unsigned char volatile TWSR                      absolute 0x00B9;
    const register unsigned short int TWS0 = 3;
    sbit  TWS0_bit at TWSR.B3;
    const register unsigned short int TWS1 = 4;
    sbit  TWS1_bit at TWSR.B4;
    const register unsigned short int TWS2 = 5;
    sbit  TWS2_bit at TWSR.B5;
    const register unsigned short int TWS3 = 6;
    sbit  TWS3_bit at TWSR.B6;
    const register unsigned short int TWS4 = 7;
    sbit  TWS4_bit at TWSR.B7;
    const register unsigned short int TWPS0 = 0;
    sbit  TWPS0_bit at TWSR.B0;
    const register unsigned short int TWPS1 = 1;
    sbit  TWPS1_bit at TWSR.B1;

sfr data unsigned char volatile TWDR                      absolute 0x00BB;
sfr data unsigned char TWAR                      absolute 0x00BA;
    const register unsigned short int TWA0 = 1;
    sbit  TWA0_bit at TWAR.B1;
    const register unsigned short int TWA1 = 2;
    sbit  TWA1_bit at TWAR.B2;
    const register unsigned short int TWA2 = 3;
    sbit  TWA2_bit at TWAR.B3;
    const register unsigned short int TWA3 = 4;
    sbit  TWA3_bit at TWAR.B4;
    const register unsigned short int TWA4 = 5;
    sbit  TWA4_bit at TWAR.B5;
    const register unsigned short int TWA5 = 6;
    sbit  TWA5_bit at TWAR.B6;
    const register unsigned short int TWA6 = 7;
    sbit  TWA6_bit at TWAR.B7;
    const register unsigned short int TWGCE = 0;
    sbit  TWGCE_bit at TWAR.B0;

sfr data unsigned char TIMSK1                    absolute 0x006F;
    const register unsigned short int ICIE1 = 5;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int OCIE1B = 2;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int TOIE1 = 0;
    sbit  TOIE1_bit at TIMSK1.B0;

sfr io   unsigned char volatile TIFR1                     absolute 0x0036;
    const register unsigned short int ICF1 = 5;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int OCF1B = 2;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int TOV1 = 0;
    sbit  TOV1_bit at TIFR1.B0;

sfr data unsigned char TCCR1A                    absolute 0x0080;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A1 = 7;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int WGM10 = 0;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM11 = 1;
    sbit  WGM11_bit at TCCR1A.B1;

sfr data unsigned char TCCR1B                    absolute 0x0081;
    const register unsigned short int ICNC1 = 7;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICES1 = 6;
    sbit  ICES1_bit at TCCR1B.B6;
    sbit  WGM10_TCCR1B_bit at TCCR1B.B3;
    sbit  WGM11_TCCR1B_bit at TCCR1B.B4;
    const register unsigned short int CS10 = 0;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS11 = 1;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS12 = 2;
    sbit  CS12_bit at TCCR1B.B2;

sfr data unsigned char volatile TCCR1C                    absolute 0x0082;
    const register unsigned short int FOC1A = 7;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1B_bit at TCCR1C.B6;

sfr data unsigned int  volatile TCNT1                     absolute 0x0084;
sfr data unsigned char volatile TCNT1L                    absolute 0x0084;
sfr data unsigned char volatile TCNT1H                    absolute 0x0085;
sfr data unsigned int  volatile OCR1A                     absolute 0x0088;
sfr data unsigned char volatile OCR1AL                    absolute 0x0088;
sfr data unsigned char volatile OCR1AH                    absolute 0x0089;
sfr data unsigned int  volatile OCR1B                     absolute 0x008A;
sfr data unsigned char volatile OCR1BL                    absolute 0x008A;
sfr data unsigned char volatile OCR1BH                    absolute 0x008B;
sfr data unsigned int  volatile ICR1                      absolute 0x0086;
sfr io   unsigned char volatile GTCCR                     absolute 0x0043;
    const register unsigned short int TSM = 7;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int PSRSYNC = 0;
    sbit  PSRSYNC_bit at GTCCR.B0;

sfr data unsigned char TIMSK2                    absolute 0x0070;
    const register unsigned short int OCIE2B = 2;
    sbit  OCIE2B_bit at TIMSK2.B2;
    const register unsigned short int OCIE2A = 1;
    sbit  OCIE2A_bit at TIMSK2.B1;
    const register unsigned short int TOIE2 = 0;
    sbit  TOIE2_bit at TIMSK2.B0;

sfr io   unsigned char volatile TIFR2                     absolute 0x0037;
    const register unsigned short int OCF2B = 2;
    sbit  OCF2B_bit at TIFR2.B2;
    const register unsigned short int OCF2A = 1;
    sbit  OCF2A_bit at TIFR2.B1;
    const register unsigned short int TOV2 = 0;
    sbit  TOV2_bit at TIFR2.B0;

sfr data unsigned char TCCR2A                    absolute 0x00B0;
    const register unsigned short int COM2A0 = 6;
    sbit  COM2A0_bit at TCCR2A.B6;
    const register unsigned short int COM2A1 = 7;
    sbit  COM2A1_bit at TCCR2A.B7;
    const register unsigned short int COM2B0 = 4;
    sbit  COM2B0_bit at TCCR2A.B4;
    const register unsigned short int COM2B1 = 5;
    sbit  COM2B1_bit at TCCR2A.B5;
    const register unsigned short int WGM20 = 0;
    sbit  WGM20_bit at TCCR2A.B0;
    const register unsigned short int WGM21 = 1;
    sbit  WGM21_bit at TCCR2A.B1;

sfr data unsigned char TCCR2B                    absolute 0x00B1;
    const register unsigned short int FOC2A = 7;
    sbit  FOC2A_bit at TCCR2B.B7;
    const register unsigned short int FOC2B = 6;
    sbit  FOC2B_bit at TCCR2B.B6;
    const register unsigned short int WGM22 = 3;
    sbit  WGM22_bit at TCCR2B.B3;
    const register unsigned short int CS20 = 0;
    sbit  CS20_bit at TCCR2B.B0;
    const register unsigned short int CS21 = 1;
    sbit  CS21_bit at TCCR2B.B1;
    const register unsigned short int CS22 = 2;
    sbit  CS22_bit at TCCR2B.B2;

sfr data unsigned char volatile TCNT2                     absolute 0x00B2;
sfr data unsigned char volatile TCNT2L                    absolute 0x00B2;
sfr data unsigned char volatile TCNT2H                    absolute 0x00B3;
sfr data unsigned char OCR2B                     absolute 0x00B4;
sfr data unsigned char OCR2BL                    absolute 0x00B4;
sfr data unsigned char OCR2BH                    absolute 0x00B5;
sfr data unsigned char OCR2A                     absolute 0x00B3;
sfr data unsigned char OCR2AL                    absolute 0x00B3;
sfr data unsigned char OCR2AH                    absolute 0x00B4;
sfr data unsigned char volatile ASSR                      absolute 0x00B6;
    const register unsigned short int EXCLK = 6;
    sbit  EXCLK_bit at ASSR.B6;
    const register unsigned short int AS2 = 5;
    sbit  AS2_bit at ASSR.B5;
    const register unsigned short int TCN2UB = 4;
    sbit  TCN2UB_bit at ASSR.B4;
    const register unsigned short int OCR2AUB = 3;
    sbit  OCR2AUB_bit at ASSR.B3;
    const register unsigned short int OCR2BUB = 2;
    sbit  OCR2BUB_bit at ASSR.B2;
    const register unsigned short int TCR2AUB = 1;
    sbit  TCR2AUB_bit at ASSR.B1;
    const register unsigned short int TCR2BUB = 0;
    sbit  TCR2BUB_bit at ASSR.B0;

sfr io   unsigned char volatile GTCCR_TC2                 absolute 0x0043;
    sbit  TSM_GTCCR_TC2_bit at GTCCR_TC2.B7;
    const register unsigned short int PSRASY = 1;
    sbit  PSRASY_bit at GTCCR_TC2.B1;

sfr data unsigned char ADMUX                     absolute 0x007C;
    const register unsigned short int REFS0 = 6;
    sbit  REFS0_bit at ADMUX.B6;
    const register unsigned short int REFS1 = 7;
    sbit  REFS1_bit at ADMUX.B7;
    const register unsigned short int ADLAR = 5;
    sbit  ADLAR_bit at ADMUX.B5;
    const register unsigned short int MUX0 = 0;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX1 = 1;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX2 = 2;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX3 = 3;
    sbit  MUX3_bit at ADMUX.B3;

sfr data unsigned int  volatile ADC                       absolute 0x0078;
sfr data unsigned char volatile ADCL                      absolute 0x0078;
sfr data unsigned char volatile ADCH                      absolute 0x0079;
sfr data unsigned char volatile ADCSRA                    absolute 0x007A;
    const register unsigned short int ADEN = 7;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADSC = 6;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADATE = 5;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADIF = 4;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIE = 3;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS2 = 2;
    sbit  ADPS2_bit at ADCSRA.B2;

sfr data unsigned char ADCSRB                    absolute 0x007B;
    const register unsigned short int ACME = 6;
    sbit  ACME_bit at ADCSRB.B6;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS2_bit at ADCSRB.B2;

sfr data unsigned char DIDR0                     absolute 0x007E;
    const register unsigned short int ADC5D = 5;
    sbit  ADC5D_bit at DIDR0.B5;
    const register unsigned short int ADC4D = 4;
    sbit  ADC4D_bit at DIDR0.B4;
    const register unsigned short int ADC3D = 3;
    sbit  ADC3D_bit at DIDR0.B3;
    const register unsigned short int ADC2D = 2;
    sbit  ADC2D_bit at DIDR0.B2;
    const register unsigned short int ADC1D = 1;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC0D = 0;
    sbit  ADC0D_bit at DIDR0.B0;

sfr io   unsigned char volatile ACSR                      absolute 0x0050;
    const register unsigned short int ACD = 7;
    sbit  ACD_bit at ACSR.B7;
    const register unsigned short int ACBG = 6;
    sbit  ACBG_bit at ACSR.B6;
    const register unsigned short int ACO = 5;
    sbit  ACO_bit at ACSR.B5;
    const register unsigned short int ACI = 4;
    sbit  ACI_bit at ACSR.B4;
    const register unsigned short int ACIE = 3;
    sbit  ACIE_bit at ACSR.B3;
    const register unsigned short int ACIC = 2;
    sbit  ACIC_bit at ACSR.B2;
    const register unsigned short int ACIS0 = 0;
    sbit  ACIS0_bit at ACSR.B0;
    const register unsigned short int ACIS1 = 1;
    sbit  ACIS1_bit at ACSR.B1;

sfr data unsigned char DIDR1                     absolute 0x007F;
    const register unsigned short int AIN1D = 1;
    sbit  AIN1D_bit at DIDR1.B1;
    const register unsigned short int AIN0D = 0;
    sbit  AIN0D_bit at DIDR1.B0;

sfr io   unsigned char volatile ACSRB                     absolute 0x002F;
    const register unsigned short int ACOE = 0;
    sbit  ACOE_bit at ACSRB.B0;

sfr io   unsigned char PORTB                     absolute 0x0025;
sfr io   unsigned char DDRB                      absolute 0x0024;
sfr io   unsigned char volatile PINB                      absolute 0x0023;
sfr io   unsigned char PORTC                     absolute 0x0028;
sfr io   unsigned char DDRC                      absolute 0x0027;
sfr io   unsigned char volatile PINC                      absolute 0x0026;
sfr io   unsigned char PORTD                     absolute 0x002B;
sfr io   unsigned char DDRD                      absolute 0x002A;
sfr io   unsigned char volatile PIND                      absolute 0x0029;
sfr io   unsigned char PORTE                     absolute 0x002E;
sfr io   unsigned char DDRE                      absolute 0x002D;
sfr io   unsigned char volatile PINE                      absolute 0x002C;
sfr io   unsigned char OCR0B                     absolute 0x0048;
sfr io   unsigned char OCR0A                     absolute 0x0047;
sfr io   unsigned char volatile TCNT0                     absolute 0x0046;
sfr io   unsigned char volatile TCNT0L                    absolute 0x0046;
sfr io   unsigned char volatile TCNT0H                    absolute 0x0047;
sfr io   unsigned char TCCR0B                    absolute 0x0045;
    const register unsigned short int FOC0A = 7;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int WGM02 = 3;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int CS00 = 0;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS01 = 1;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS02 = 2;
    sbit  CS02_bit at TCCR0B.B2;

sfr io   unsigned char TCCR0A                    absolute 0x0044;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A1 = 7;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int WGM00 = 0;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM01 = 1;
    sbit  WGM01_bit at TCCR0A.B1;

sfr data unsigned char TIMSK0                    absolute 0x006E;
    const register unsigned short int OCIE0B = 2;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int TOIE0 = 0;
    sbit  TOIE0_bit at TIMSK0.B0;

sfr io   unsigned char volatile TIFR0                     absolute 0x0035;
    const register unsigned short int OCF0B = 2;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int TOV0 = 0;
    sbit  TOV0_bit at TIFR0.B0;

sfr io   unsigned char volatile GTCCR_TC0                 absolute 0x0043;
    sbit  TSM_GTCCR_TC0_bit at GTCCR_TC0.B7;
    sbit  PSRSYNC_GTCCR_TC0_bit at GTCCR_TC0.B0;

sfr data unsigned char volatile EICRA                     absolute 0x0069;
    const register unsigned short int ISC10 = 2;
    sbit  ISC10_bit at EICRA.B2;
    const register unsigned short int ISC11 = 3;
    sbit  ISC11_bit at EICRA.B3;
    const register unsigned short int ISC00 = 0;
    sbit  ISC00_bit at EICRA.B0;
    const register unsigned short int ISC01 = 1;
    sbit  ISC01_bit at EICRA.B1;

sfr io   unsigned char EIMSK                     absolute 0x003D;
    const register unsigned short int INT0 = 0;
    sbit  INT0_bit at EIMSK.B0;
    const register unsigned short int INT1 = 1;
    sbit  INT1_bit at EIMSK.B1;

sfr io   unsigned char volatile EIFR                      absolute 0x003C;
    const register unsigned short int INTF0 = 0;
    sbit  INTF0_bit at EIFR.B0;
    const register unsigned short int INTF1 = 1;
    sbit  INTF1_bit at EIFR.B1;

sfr data unsigned char PCICR                     absolute 0x0068;
    const register unsigned short int PCIE0 = 0;
    sbit  PCIE0_bit at PCICR.B0;
    const register unsigned short int PCIE1 = 1;
    sbit  PCIE1_bit at PCICR.B1;
    const register unsigned short int PCIE2 = 2;
    sbit  PCIE2_bit at PCICR.B2;

sfr data unsigned char PCMSK2                    absolute 0x006D;
    const register unsigned short int PCINT0 = 0;
    sbit  PCINT0_bit at PCMSK2.B0;
    const register unsigned short int PCINT1 = 1;
    sbit  PCINT1_bit at PCMSK2.B1;
    const register unsigned short int PCINT2 = 2;
    sbit  PCINT2_bit at PCMSK2.B2;
    const register unsigned short int PCINT3 = 3;
    sbit  PCINT3_bit at PCMSK2.B3;
    const register unsigned short int PCINT4 = 4;
    sbit  PCINT4_bit at PCMSK2.B4;
    const register unsigned short int PCINT5 = 5;
    sbit  PCINT5_bit at PCMSK2.B5;
    const register unsigned short int PCINT6 = 6;
    sbit  PCINT6_bit at PCMSK2.B6;
    const register unsigned short int PCINT7 = 7;
    sbit  PCINT7_bit at PCMSK2.B7;

sfr data unsigned char PCMSK1                    absolute 0x006C;
    sbit  PCINT0_PCMSK1_bit at PCMSK1.B0;
    sbit  PCINT1_PCMSK1_bit at PCMSK1.B1;
    sbit  PCINT2_PCMSK1_bit at PCMSK1.B2;
    sbit  PCINT3_PCMSK1_bit at PCMSK1.B3;
    sbit  PCINT4_PCMSK1_bit at PCMSK1.B4;
    sbit  PCINT5_PCMSK1_bit at PCMSK1.B5;
    sbit  PCINT6_PCMSK1_bit at PCMSK1.B6;

sfr data unsigned char PCMSK0                    absolute 0x006B;
    sbit  PCINT0_PCMSK0_bit at PCMSK0.B0;
    sbit  PCINT1_PCMSK0_bit at PCMSK0.B1;
    sbit  PCINT2_PCMSK0_bit at PCMSK0.B2;
    sbit  PCINT3_PCMSK0_bit at PCMSK0.B3;
    sbit  PCINT4_PCMSK0_bit at PCMSK0.B4;
    sbit  PCINT5_PCMSK0_bit at PCMSK0.B5;
    sbit  PCINT6_PCMSK0_bit at PCMSK0.B6;
    sbit  PCINT7_PCMSK0_bit at PCMSK0.B7;

sfr io   unsigned char volatile PCIFR                     absolute 0x003B;
    const register unsigned short int PCIF0 = 0;
    sbit  PCIF0_bit at PCIFR.B0;
    const register unsigned short int PCIF1 = 1;
    sbit  PCIF1_bit at PCIFR.B1;
    const register unsigned short int PCIF2 = 2;
    sbit  PCIF2_bit at PCIFR.B2;

sfr io   unsigned char volatile SPDR                      absolute 0x004E;
sfr io   unsigned char volatile SPSR                      absolute 0x004D;
    const register unsigned short int SPIF = 7;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int WCOL = 6;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int SPI2X = 0;
    sbit  SPI2X_bit at SPSR.B0;

sfr io   unsigned char SPCR                      absolute 0x004C;
    const register unsigned short int SPIE = 7;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPE = 6;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int DORD = 5;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int MSTR = 4;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int CPOL = 3;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPHA = 2;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int SPR0 = 0;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR1 = 1;
    sbit  SPR1_bit at SPCR.B1;

sfr data unsigned char volatile WDTCSR                    absolute 0x0060;
    const register unsigned short int WDIF = 7;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIE = 6;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDP0 = 0;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP1 = 1;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP2 = 2;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP3 = 5;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDCE = 4;
    sbit  WDCE_bit at WDTCSR.B4;
    const register unsigned short int WDE = 3;
    sbit  WDE_bit at WDTCSR.B3;

sfr io   unsigned int  volatile EEAR                      absolute 0x0041;
sfr io   unsigned char volatile EEARL                     absolute 0x0041;
sfr io   unsigned char volatile EEARH                     absolute 0x0042;
sfr io   unsigned char volatile EEDR                      absolute 0x0040;
sfr io   unsigned char volatile EECR                      absolute 0x003F;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM1 = 5;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EERIE = 3;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EEMPE = 2;
    sbit  EEMPE_bit at EECR.B2;
    const register unsigned short int EEPE = 1;
    sbit  EEPE_bit at EECR.B1;
    const register unsigned short int EERE = 0;
    sbit  EERE_bit at EECR.B0;

sfr data unsigned char volatile PRR                       absolute 0x0064;
    const register unsigned short int PRTWI = 7;
    sbit  PRTWI_bit at PRR.B7;
    const register unsigned short int PRTIM2 = 6;
    sbit  PRTIM2_bit at PRR.B6;
    const register unsigned short int PRTIM0 = 5;
    sbit  PRTIM0_bit at PRR.B5;
    const register unsigned short int PRTIM1 = 3;
    sbit  PRTIM1_bit at PRR.B3;
    const register unsigned short int PRSPI = 2;
    sbit  PRSPI_bit at PRR.B2;
    const register unsigned short int PRUSART0 = 1;
    sbit  PRUSART0_bit at PRR.B1;
    const register unsigned short int PRADC = 0;
    sbit  PRADC_bit at PRR.B0;

sfr data unsigned char OSCCAL                    absolute 0x0066;
    const register unsigned short int OSCCAL0 = 0;
    sbit  OSCCAL0_bit at OSCCAL.B0;
    const register unsigned short int OSCCAL1 = 1;
    sbit  OSCCAL1_bit at OSCCAL.B1;
    const register unsigned short int OSCCAL2 = 2;
    sbit  OSCCAL2_bit at OSCCAL.B2;
    const register unsigned short int OSCCAL3 = 3;
    sbit  OSCCAL3_bit at OSCCAL.B3;
    const register unsigned short int OSCCAL4 = 4;
    sbit  OSCCAL4_bit at OSCCAL.B4;
    const register unsigned short int OSCCAL5 = 5;
    sbit  OSCCAL5_bit at OSCCAL.B5;
    const register unsigned short int OSCCAL6 = 6;
    sbit  OSCCAL6_bit at OSCCAL.B6;
    const register unsigned short int OSCCAL7 = 7;
    sbit  OSCCAL7_bit at OSCCAL.B7;

sfr data unsigned char volatile CLKPR                     absolute 0x0061;
    const register unsigned short int CLKPCE = 7;
    sbit  CLKPCE_bit at CLKPR.B7;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPS3_bit at CLKPR.B3;

sfr io   unsigned char volatile SREG                      absolute 0x005F;
    const register unsigned short int SREG_I = 7;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_C_bit at SREG.B0;

sfr io   unsigned int  volatile SP                        absolute 0x005D;
sfr io   unsigned char volatile SPL                       absolute 0x005D;
sfr io   unsigned char volatile SPMCSR                    absolute 0x0057;
    const register unsigned short int SPMIE = 7;
    sbit  SPMIE_bit at SPMCSR.B7;
    const register unsigned short int RWWSB = 6;
    sbit  RWWSB_bit at SPMCSR.B6;
    const register unsigned short int SIGRD = 5;
    sbit  SIGRD_bit at SPMCSR.B5;
    const register unsigned short int RWWSRE = 4;
    sbit  RWWSRE_bit at SPMCSR.B4;
    const register unsigned short int BLBSET = 3;
    sbit  BLBSET_bit at SPMCSR.B3;
    const register unsigned short int PGWRT = 2;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGERS = 1;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int SPMEN = 0;
    sbit  SPMEN_bit at SPMCSR.B0;

sfr io   unsigned char volatile MCUCR                     absolute 0x0055;
    const register unsigned short int BODS = 6;
    sbit  BODS_bit at MCUCR.B6;
    const register unsigned short int BODSE = 5;
    sbit  BODSE_bit at MCUCR.B5;
    const register unsigned short int PUD = 4;
    sbit  PUD_bit at MCUCR.B4;
    const register unsigned short int IVSEL = 1;
    sbit  IVSEL_bit at MCUCR.B1;
    const register unsigned short int IVCE = 0;
    sbit  IVCE_bit at MCUCR.B0;

sfr io   unsigned char volatile MCUSR                     absolute 0x0054;
    const register unsigned short int WDRF = 3;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int BORF = 2;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int EXTRF = 1;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int PORF = 0;
    sbit  PORF_bit at MCUSR.B0;

sfr io   unsigned char SMCR                      absolute 0x0053;
    const register unsigned short int SM0 = 1;
    sbit  SM0_bit at SMCR.B1;
    const register unsigned short int SM1 = 2;
    sbit  SM1_bit at SMCR.B2;
    const register unsigned short int SM2 = 3;
    sbit  SM2_bit at SMCR.B3;
    const register unsigned short int SE = 0;
    sbit  SE_bit at SMCR.B0;

sfr io   unsigned char volatile GPIOR2                    absolute 0x004B;
sfr io   unsigned char volatile GPIOR1                    absolute 0x004A;
sfr io   unsigned char volatile GPIOR0                    absolute 0x003E;
sfr data unsigned char volatile DEVID0                    absolute 0x00F0;
sfr data unsigned char volatile DEVID1                    absolute 0x00F1;
sfr data unsigned char volatile DEVID2                    absolute 0x00F2;
sfr data unsigned char volatile DEVID3                    absolute 0x00F3;
sfr data unsigned char volatile DEVID4                    absolute 0x00F4;
sfr data unsigned char volatile DEVID5                    absolute 0x00F5;
sfr data unsigned char volatile DEVID6                    absolute 0x00F6;
sfr data unsigned char volatile DEVID7                    absolute 0x00F7;
sfr data unsigned char volatile DEVID8                    absolute 0x00F8;
sfr io   unsigned char volatile EXTENDED_                 absolute 0x0002;
    const register unsigned short int BOOTSZ0 = 1;
    sbit  BOOTSZ0_bit at EXTENDED_.B1;
    const register unsigned short int BOOTSZ1 = 2;
    sbit  BOOTSZ1_bit at EXTENDED_.B2;
    const register unsigned short int BOOTRST = 0;
    sbit  BOOTRST_bit at EXTENDED_.B0;

sfr io   unsigned char volatile HIGH                      absolute 0x0001;
    const register unsigned short int RSTDISBL = 7;
    sbit  RSTDISBL_bit at HIGH.B7;
    const register unsigned short int DWEN = 6;
    sbit  DWEN_bit at HIGH.B6;
    const register unsigned short int SPIEN = 5;
    sbit  SPIEN_bit at HIGH.B5;
    const register unsigned short int WDTON = 4;
    sbit  WDTON_bit at HIGH.B4;
    const register unsigned short int EESAVE = 3;
    sbit  EESAVE_bit at HIGH.B3;
    const register unsigned short int BODLEVEL0 = 0;
    sbit  BODLEVEL0_bit at HIGH.B0;
    const register unsigned short int BODLEVEL1 = 1;
    sbit  BODLEVEL1_bit at HIGH.B1;
    const register unsigned short int BODLEVEL2 = 2;
    sbit  BODLEVEL2_bit at HIGH.B2;

sfr io   unsigned char volatile LOW                       absolute 0x0000;
    const register unsigned short int CKDIV8 = 7;
    sbit  CKDIV8_bit at LOW.B7;
    const register unsigned short int CKOUT = 6;
    sbit  CKOUT_bit at LOW.B6;
    const register unsigned short int SUT_CKSEL0 = 0;
    sbit  SUT_CKSEL0_bit at LOW.B0;
    const register unsigned short int SUT_CKSEL1 = 1;
    sbit  SUT_CKSEL1_bit at LOW.B1;
    const register unsigned short int SUT_CKSEL2 = 2;
    sbit  SUT_CKSEL2_bit at LOW.B2;
    const register unsigned short int SUT_CKSEL3 = 3;
    sbit  SUT_CKSEL3_bit at LOW.B3;
    const register unsigned short int SUT_CKSEL4 = 4;
    sbit  SUT_CKSEL4_bit at LOW.B4;
    const register unsigned short int SUT_CKSEL5 = 5;
    sbit  SUT_CKSEL5_bit at LOW.B5;

sfr io   unsigned char volatile LOCKBIT                   absolute 0x0000;
    const register unsigned short int LB0 = 0;
    sbit  LB0_bit at LOCKBIT.B0;
    const register unsigned short int LB1 = 1;
    sbit  LB1_bit at LOCKBIT.B1;
    const register unsigned short int BLB00 = 2;
    sbit  BLB00_bit at LOCKBIT.B2;
    const register unsigned short int BLB01 = 3;
    sbit  BLB01_bit at LOCKBIT.B3;
    const register unsigned short int BLB10 = 4;
    sbit  BLB10_bit at LOCKBIT.B4;
    const register unsigned short int BLB11 = 5;
    sbit  BLB11_bit at LOCKBIT.B5;

