// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00004000;

// Flash page size in program words
const int __FLASH_PAGE_SIZE = 64;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;

const unsigned int IVT_ADDR_RESET            = 0x0000;
const unsigned int IVT_ADDR_BPINT            = 0x0002;
const unsigned int IVT_ADDR_VREGMON          = 0x0004;
const unsigned int IVT_ADDR_INT0             = 0x0006;
const unsigned int IVT_ADDR_INT1             = 0x0008;
const unsigned int IVT_ADDR_INT2             = 0x000A;
const unsigned int IVT_ADDR_INT3             = 0x000C;
const unsigned int IVT_ADDR_PCINT0           = 0x000E;
const unsigned int IVT_ADDR_PCINT1           = 0x0010;
const unsigned int IVT_ADDR_WDT              = 0x0012;
const unsigned int IVT_ADDR_BGSCD            = 0x0014;
const unsigned int IVT_ADDR_CHDET            = 0x0016;
const unsigned int IVT_ADDR_TIMER1_IC        = 0x0018;
const unsigned int IVT_ADDR_TIMER1_COMPA     = 0x001A;
const unsigned int IVT_ADDR_TIMER1_COMPB     = 0x001C;
const unsigned int IVT_ADDR_TIMER1_OVF       = 0x001E;
const unsigned int IVT_ADDR_TIMER0_IC        = 0x0020;
const unsigned int IVT_ADDR_TIMER0_COMPA     = 0x0022;
const unsigned int IVT_ADDR_TIMER0_COMPB     = 0x0024;
const unsigned int IVT_ADDR_TIMER0_OVF       = 0x0026;
const unsigned int IVT_ADDR_TWIBUSCD         = 0x0028;
const unsigned int IVT_ADDR_TWI              = 0x002A;
const unsigned int IVT_ADDR_SPI_STC          = 0x002C;
const unsigned int IVT_ADDR_VADC             = 0x002E;
const unsigned int IVT_ADDR_CCADC_CONV       = 0x0030;
const unsigned int IVT_ADDR_CCADC_REG_CUR    = 0x0032;
const unsigned int IVT_ADDR_CCADC_ACC        = 0x0034;
const unsigned int IVT_ADDR_EE_READY         = 0x0036;
const unsigned int IVT_ADDR_SPM              = 0x0038;


sfr data unsigned short volatile BPPLR absolute 0xFE;
    sbit  BPPL_bit at BPPLR.B0;
    const register unsigned short int BPPL = 0;
    sbit  BPPLE_bit at BPPLR.B1;
    const register unsigned short int BPPLE = 1;

sfr data unsigned short volatile BPCR absolute 0xFD;
    sbit  CHCD_bit at BPCR.B0;
    const register unsigned short int CHCD = 0;
    sbit  DHCD_bit at BPCR.B1;
    const register unsigned short int DHCD = 1;
    sbit  COCD_bit at BPCR.B2;
    const register unsigned short int COCD = 2;
    sbit  DOCD_bit at BPCR.B3;
    const register unsigned short int DOCD = 3;
    sbit  SCD_bit at BPCR.B4;
    const register unsigned short int SCD = 4;
    sbit  EPID_bit at BPCR.B5;
    const register unsigned short int EPID = 5;

sfr data unsigned short volatile BPHCTR absolute 0xFC;
    sbit  HCPT0_bit at BPHCTR.B0;
    const register unsigned short int HCPT0 = 0;
    sbit  HCPT1_bit at BPHCTR.B1;
    const register unsigned short int HCPT1 = 1;
    sbit  HCPT2_bit at BPHCTR.B2;
    const register unsigned short int HCPT2 = 2;
    sbit  HCPT3_bit at BPHCTR.B3;
    const register unsigned short int HCPT3 = 3;
    sbit  HCPT4_bit at BPHCTR.B4;
    const register unsigned short int HCPT4 = 4;
    sbit  HCPT5_bit at BPHCTR.B5;
    const register unsigned short int HCPT5 = 5;

sfr data unsigned short volatile BPOCTR absolute 0xFB;
    sbit  OCPT0_bit at BPOCTR.B0;
    const register unsigned short int OCPT0 = 0;
    sbit  OCPT1_bit at BPOCTR.B1;
    const register unsigned short int OCPT1 = 1;
    sbit  OCPT2_bit at BPOCTR.B2;
    const register unsigned short int OCPT2 = 2;
    sbit  OCPT3_bit at BPOCTR.B3;
    const register unsigned short int OCPT3 = 3;
    sbit  OCPT4_bit at BPOCTR.B4;
    const register unsigned short int OCPT4 = 4;
    sbit  OCPT5_bit at BPOCTR.B5;
    const register unsigned short int OCPT5 = 5;

sfr data unsigned short volatile BPSCTR absolute 0xFA;
    sbit  SCPT0_bit at BPSCTR.B0;
    const register unsigned short int SCPT0 = 0;
    sbit  SCPT1_bit at BPSCTR.B1;
    const register unsigned short int SCPT1 = 1;
    sbit  SCPT2_bit at BPSCTR.B2;
    const register unsigned short int SCPT2 = 2;
    sbit  SCPT3_bit at BPSCTR.B3;
    const register unsigned short int SCPT3 = 3;
    sbit  SCPT4_bit at BPSCTR.B4;
    const register unsigned short int SCPT4 = 4;
    sbit  SCPT5_bit at BPSCTR.B5;
    const register unsigned short int SCPT5 = 5;
    sbit  SCPT6_bit at BPSCTR.B6;
    const register unsigned short int SCPT6 = 6;

sfr data unsigned short volatile BPCHCD absolute 0xF9;
    sbit  CHCDL0_bit at BPCHCD.B0;
    const register unsigned short int CHCDL0 = 0;
    sbit  CHCDL1_bit at BPCHCD.B1;
    const register unsigned short int CHCDL1 = 1;
    sbit  CHCDL2_bit at BPCHCD.B2;
    const register unsigned short int CHCDL2 = 2;
    sbit  CHCDL3_bit at BPCHCD.B3;
    const register unsigned short int CHCDL3 = 3;
    sbit  CHCDL4_bit at BPCHCD.B4;
    const register unsigned short int CHCDL4 = 4;
    sbit  CHCDL5_bit at BPCHCD.B5;
    const register unsigned short int CHCDL5 = 5;
    sbit  CHCDL6_bit at BPCHCD.B6;
    const register unsigned short int CHCDL6 = 6;
    sbit  CHCDL7_bit at BPCHCD.B7;
    const register unsigned short int CHCDL7 = 7;

sfr data unsigned short volatile BPDHCD absolute 0xF8;
    sbit  DHCDL0_bit at BPDHCD.B0;
    const register unsigned short int DHCDL0 = 0;
    sbit  DHCDL1_bit at BPDHCD.B1;
    const register unsigned short int DHCDL1 = 1;
    sbit  DHCDL2_bit at BPDHCD.B2;
    const register unsigned short int DHCDL2 = 2;
    sbit  DHCDL3_bit at BPDHCD.B3;
    const register unsigned short int DHCDL3 = 3;
    sbit  DHCDL4_bit at BPDHCD.B4;
    const register unsigned short int DHCDL4 = 4;
    sbit  DHCDL5_bit at BPDHCD.B5;
    const register unsigned short int DHCDL5 = 5;
    sbit  DHCDL6_bit at BPDHCD.B6;
    const register unsigned short int DHCDL6 = 6;
    sbit  DHCDL7_bit at BPDHCD.B7;
    const register unsigned short int DHCDL7 = 7;

sfr data unsigned short volatile BPCOCD absolute 0xF7;
    sbit  COCDL0_bit at BPCOCD.B0;
    const register unsigned short int COCDL0 = 0;
    sbit  COCDL1_bit at BPCOCD.B1;
    const register unsigned short int COCDL1 = 1;
    sbit  COCDL2_bit at BPCOCD.B2;
    const register unsigned short int COCDL2 = 2;
    sbit  COCDL3_bit at BPCOCD.B3;
    const register unsigned short int COCDL3 = 3;
    sbit  COCDL4_bit at BPCOCD.B4;
    const register unsigned short int COCDL4 = 4;
    sbit  COCDL5_bit at BPCOCD.B5;
    const register unsigned short int COCDL5 = 5;
    sbit  COCDL6_bit at BPCOCD.B6;
    const register unsigned short int COCDL6 = 6;
    sbit  COCDL7_bit at BPCOCD.B7;
    const register unsigned short int COCDL7 = 7;

sfr data unsigned short volatile BPDOCD absolute 0xF6;
    sbit  DOCDL0_bit at BPDOCD.B0;
    const register unsigned short int DOCDL0 = 0;
    sbit  DOCDL1_bit at BPDOCD.B1;
    const register unsigned short int DOCDL1 = 1;
    sbit  DOCDL2_bit at BPDOCD.B2;
    const register unsigned short int DOCDL2 = 2;
    sbit  DOCDL3_bit at BPDOCD.B3;
    const register unsigned short int DOCDL3 = 3;
    sbit  DOCDL4_bit at BPDOCD.B4;
    const register unsigned short int DOCDL4 = 4;
    sbit  DOCDL5_bit at BPDOCD.B5;
    const register unsigned short int DOCDL5 = 5;
    sbit  DOCDL6_bit at BPDOCD.B6;
    const register unsigned short int DOCDL6 = 6;
    sbit  DOCDL7_bit at BPDOCD.B7;
    const register unsigned short int DOCDL7 = 7;

sfr data unsigned short volatile BPSCD absolute 0xF5;
    sbit  SCDL0_bit at BPSCD.B0;
    const register unsigned short int SCDL0 = 0;
    sbit  SCDL1_bit at BPSCD.B1;
    const register unsigned short int SCDL1 = 1;
    sbit  SCDL2_bit at BPSCD.B2;
    const register unsigned short int SCDL2 = 2;
    sbit  SCDL3_bit at BPSCD.B3;
    const register unsigned short int SCDL3 = 3;
    sbit  SCDL4_bit at BPSCD.B4;
    const register unsigned short int SCDL4 = 4;
    sbit  SCDL5_bit at BPSCD.B5;
    const register unsigned short int SCDL5 = 5;
    sbit  SCDL6_bit at BPSCD.B6;
    const register unsigned short int SCDL6 = 6;
    sbit  SCDL7_bit at BPSCD.B7;
    const register unsigned short int SCDL7 = 7;

sfr data unsigned short volatile BPIFR absolute 0xF3;
    sbit  CHCIF_bit at BPIFR.B0;
    const register unsigned short int CHCIF = 0;
    sbit  DHCIF_bit at BPIFR.B1;
    const register unsigned short int DHCIF = 1;
    sbit  COCIF_bit at BPIFR.B2;
    const register unsigned short int COCIF = 2;
    sbit  DOCIF_bit at BPIFR.B3;
    const register unsigned short int DOCIF = 3;
    sbit  SCIF_bit at BPIFR.B4;
    const register unsigned short int SCIF = 4;

sfr data unsigned short volatile BPIMSK absolute 0xF2;
    sbit  CHCIE_bit at BPIMSK.B0;
    const register unsigned short int CHCIE = 0;
    sbit  DHCIE_bit at BPIMSK.B1;
    const register unsigned short int DHCIE = 1;
    sbit  COCIE_bit at BPIMSK.B2;
    const register unsigned short int COCIE = 2;
    sbit  DOCIE_bit at BPIMSK.B3;
    const register unsigned short int DOCIE = 3;
    sbit  SCIE_bit at BPIMSK.B4;
    const register unsigned short int SCIE = 4;

sfr data unsigned short volatile CBCR absolute 0xF1;
    sbit  CBE1_bit at CBCR.B0;
    const register unsigned short int CBE1 = 0;
    sbit  CBE2_bit at CBCR.B1;
    const register unsigned short int CBE2 = 1;
    sbit  CBE3_bit at CBCR.B2;
    const register unsigned short int CBE3 = 2;
    sbit  CBE4_bit at CBCR.B3;
    const register unsigned short int CBE4 = 3;

sfr data unsigned short volatile FCSR absolute 0xF0;
    sbit  CFE_bit at FCSR.B0;
    const register unsigned short int CFE = 0;
    sbit  DFE_bit at FCSR.B1;
    const register unsigned short int DFE = 1;
    sbit  CPS_bit at FCSR.B2;
    const register unsigned short int CPS = 2;
    sbit  DUVRD_bit at FCSR.B3;
    const register unsigned short int DUVRD = 3;

sfr data unsigned short volatile CADRDC absolute 0xEA;
    sbit  CADRDC0_bit at CADRDC.B0;
    const register unsigned short int CADRDC0 = 0;
    sbit  CADRDC1_bit at CADRDC.B1;
    const register unsigned short int CADRDC1 = 1;
    sbit  CADRDC2_bit at CADRDC.B2;
    const register unsigned short int CADRDC2 = 2;
    sbit  CADRDC3_bit at CADRDC.B3;
    const register unsigned short int CADRDC3 = 3;
    sbit  CADRDC4_bit at CADRDC.B4;
    const register unsigned short int CADRDC4 = 4;
    sbit  CADRDC5_bit at CADRDC.B5;
    const register unsigned short int CADRDC5 = 5;
    sbit  CADRDC6_bit at CADRDC.B6;
    const register unsigned short int CADRDC6 = 6;
    sbit  CADRDC7_bit at CADRDC.B7;
    const register unsigned short int CADRDC7 = 7;

sfr data unsigned short volatile CADRCC absolute 0xE9;
    sbit  CADRCC0_bit at CADRCC.B0;
    const register unsigned short int CADRCC0 = 0;
    sbit  CADRCC1_bit at CADRCC.B1;
    const register unsigned short int CADRCC1 = 1;
    sbit  CADRCC2_bit at CADRCC.B2;
    const register unsigned short int CADRCC2 = 2;
    sbit  CADRCC3_bit at CADRCC.B3;
    const register unsigned short int CADRCC3 = 3;
    sbit  CADRCC4_bit at CADRCC.B4;
    const register unsigned short int CADRCC4 = 4;
    sbit  CADRCC5_bit at CADRCC.B5;
    const register unsigned short int CADRCC5 = 5;
    sbit  CADRCC6_bit at CADRCC.B6;
    const register unsigned short int CADRCC6 = 6;
    sbit  CADRCC7_bit at CADRCC.B7;
    const register unsigned short int CADRCC7 = 7;

sfr data unsigned short volatile CADCSRC absolute 0xE8;
    sbit  CADVSE_bit at CADCSRC.B0;
    const register unsigned short int CADVSE = 0;

sfr data unsigned short volatile CADCSRB absolute 0xE7;
    sbit  CADICIF_bit at CADCSRB.B0;
    const register unsigned short int CADICIF = 0;
    sbit  CADRCIF_bit at CADCSRB.B1;
    const register unsigned short int CADRCIF = 1;
    sbit  CADACIF_bit at CADCSRB.B2;
    const register unsigned short int CADACIF = 2;
    sbit  CADICIE_bit at CADCSRB.B4;
    const register unsigned short int CADICIE = 4;
    sbit  CADRCIE_bit at CADCSRB.B5;
    const register unsigned short int CADRCIE = 5;
    sbit  CADACIE_bit at CADCSRB.B6;
    const register unsigned short int CADACIE = 6;

sfr data unsigned short volatile CADCSRA absolute 0xE6;
    sbit  CADSE_bit at CADCSRA.B0;
    const register unsigned short int CADSE = 0;
    sbit  CADSI0_bit at CADCSRA.B1;
    const register unsigned short int CADSI0 = 1;
    sbit  CADSI1_bit at CADCSRA.B2;
    const register unsigned short int CADSI1 = 2;
    sbit  CADAS0_bit at CADCSRA.B3;
    const register unsigned short int CADAS0 = 3;
    sbit  CADAS1_bit at CADCSRA.B4;
    const register unsigned short int CADAS1 = 4;
    sbit  CADUB_bit at CADCSRA.B5;
    const register unsigned short int CADUB = 5;
    sbit  CADPOL_bit at CADCSRA.B6;
    const register unsigned short int CADPOL = 6;
    sbit  CADEN_bit at CADCSRA.B7;
    const register unsigned short int CADEN = 7;

sfr data unsigned short volatile CADICH absolute 0xE5;
    sbit  CADICH0_bit at CADICH.B0;
    const register unsigned short int CADICH0 = 0;
    sbit  CADICH1_bit at CADICH.B1;
    const register unsigned short int CADICH1 = 1;
    sbit  CADICH2_bit at CADICH.B2;
    const register unsigned short int CADICH2 = 2;
    sbit  CADICH3_bit at CADICH.B3;
    const register unsigned short int CADICH3 = 3;
    sbit  CADICH4_bit at CADICH.B4;
    const register unsigned short int CADICH4 = 4;
    sbit  CADICH5_bit at CADICH.B5;
    const register unsigned short int CADICH5 = 5;
    sbit  CADICH6_bit at CADICH.B6;
    const register unsigned short int CADICH6 = 6;
    sbit  CADICH7_bit at CADICH.B7;
    const register unsigned short int CADICH7 = 7;

sfr data unsigned short volatile CADICL absolute 0xE4;
    sbit  CADICL0_bit at CADICL.B0;
    const register unsigned short int CADICL0 = 0;
    sbit  CADICL1_bit at CADICL.B1;
    const register unsigned short int CADICL1 = 1;
    sbit  CADICL2_bit at CADICL.B2;
    const register unsigned short int CADICL2 = 2;
    sbit  CADICL3_bit at CADICL.B3;
    const register unsigned short int CADICL3 = 3;
    sbit  CADICL4_bit at CADICL.B4;
    const register unsigned short int CADICL4 = 4;
    sbit  CADICL5_bit at CADICL.B5;
    const register unsigned short int CADICL5 = 5;
    sbit  CADICL6_bit at CADICL.B6;
    const register unsigned short int CADICL6 = 6;
    sbit  CADICL7_bit at CADICL.B7;
    const register unsigned short int CADICL7 = 7;

sfr data unsigned short volatile CADAC3 absolute 0xE3;
    sbit  CADAC24_bit at CADAC3.B0;
    const register unsigned short int CADAC24 = 0;
    sbit  CADAC25_bit at CADAC3.B1;
    const register unsigned short int CADAC25 = 1;
    sbit  CADAC26_bit at CADAC3.B2;
    const register unsigned short int CADAC26 = 2;
    sbit  CADAC27_bit at CADAC3.B3;
    const register unsigned short int CADAC27 = 3;
    sbit  CADAC28_bit at CADAC3.B4;
    const register unsigned short int CADAC28 = 4;
    sbit  CADAC29_bit at CADAC3.B5;
    const register unsigned short int CADAC29 = 5;
    sbit  CADAC30_bit at CADAC3.B6;
    const register unsigned short int CADAC30 = 6;
    sbit  CADAC31_bit at CADAC3.B7;
    const register unsigned short int CADAC31 = 7;

sfr data unsigned short volatile CADAC2 absolute 0xE2;
    sbit  CADAC16_bit at CADAC2.B0;
    const register unsigned short int CADAC16 = 0;
    sbit  CADAC17_bit at CADAC2.B1;
    const register unsigned short int CADAC17 = 1;
    sbit  CADAC18_bit at CADAC2.B2;
    const register unsigned short int CADAC18 = 2;
    sbit  CADAC19_bit at CADAC2.B3;
    const register unsigned short int CADAC19 = 3;
    sbit  CADAC20_bit at CADAC2.B4;
    const register unsigned short int CADAC20 = 4;
    sbit  CADAC21_bit at CADAC2.B5;
    const register unsigned short int CADAC21 = 5;
    sbit  CADAC22_bit at CADAC2.B6;
    const register unsigned short int CADAC22 = 6;
    sbit  CADAC23_bit at CADAC2.B7;
    const register unsigned short int CADAC23 = 7;

sfr data unsigned short volatile CADAC1 absolute 0xE1;
    sbit  CADAC08_bit at CADAC1.B0;
    const register unsigned short int CADAC08 = 0;
    sbit  CADAC09_bit at CADAC1.B1;
    const register unsigned short int CADAC09 = 1;
    sbit  CADAC10_bit at CADAC1.B2;
    const register unsigned short int CADAC10 = 2;
    sbit  CADAC11_bit at CADAC1.B3;
    const register unsigned short int CADAC11 = 3;
    sbit  CADAC12_bit at CADAC1.B4;
    const register unsigned short int CADAC12 = 4;
    sbit  CADAC13_bit at CADAC1.B5;
    const register unsigned short int CADAC13 = 5;
    sbit  CADAC14_bit at CADAC1.B6;
    const register unsigned short int CADAC14 = 6;
    sbit  CADAC15_bit at CADAC1.B7;
    const register unsigned short int CADAC15 = 7;

sfr data unsigned short volatile CADAC0 absolute 0xE0;
    sbit  CADAC00_bit at CADAC0.B0;
    const register unsigned short int CADAC00 = 0;
    sbit  CADAC01_bit at CADAC0.B1;
    const register unsigned short int CADAC01 = 1;
    sbit  CADAC02_bit at CADAC0.B2;
    const register unsigned short int CADAC02 = 2;
    sbit  CADAC03_bit at CADAC0.B3;
    const register unsigned short int CADAC03 = 3;
    sbit  CADAC04_bit at CADAC0.B4;
    const register unsigned short int CADAC04 = 4;
    sbit  CADAC05_bit at CADAC0.B5;
    const register unsigned short int CADAC05 = 5;
    sbit  CADAC06_bit at CADAC0.B6;
    const register unsigned short int CADAC06 = 6;
    sbit  CADAC07_bit at CADAC0.B7;
    const register unsigned short int CADAC07 = 7;

sfr data unsigned short volatile CHGDCSR absolute 0xD4;
    sbit  CHGDIE_bit at CHGDCSR.B0;
    const register unsigned short int CHGDIE = 0;
    sbit  CHGDIF_bit at CHGDCSR.B1;
    const register unsigned short int CHGDIF = 1;
    sbit  CHGDISC0_bit at CHGDCSR.B2;
    const register unsigned short int CHGDISC0 = 2;
    sbit  CHGDISC1_bit at CHGDCSR.B3;
    const register unsigned short int CHGDISC1 = 3;
    sbit  BATTPVL_bit at CHGDCSR.B4;
    const register unsigned short int BATTPVL = 4;

sfr data unsigned short volatile BGCSR absolute 0xD2;
    sbit  BGSCDIE_bit at BGCSR.B0;
    const register unsigned short int BGSCDIE = 0;
    sbit  BGSCDIF_bit at BGCSR.B1;
    const register unsigned short int BGSCDIF = 1;
    sbit  BGSCDE_bit at BGCSR.B4;
    const register unsigned short int BGSCDE = 4;
    sbit  BGD_bit at BGCSR.B5;
    const register unsigned short int BGD = 5;

sfr data unsigned short volatile BGCRR absolute 0xD1;
    sbit  BGCR0_bit at BGCRR.B0;
    const register unsigned short int BGCR0 = 0;
    sbit  BGCR1_bit at BGCRR.B1;
    const register unsigned short int BGCR1 = 1;
    sbit  BGCR2_bit at BGCRR.B2;
    const register unsigned short int BGCR2 = 2;
    sbit  BGCR3_bit at BGCRR.B3;
    const register unsigned short int BGCR3 = 3;
    sbit  BGCR4_bit at BGCRR.B4;
    const register unsigned short int BGCR4 = 4;
    sbit  BGCR5_bit at BGCRR.B5;
    const register unsigned short int BGCR5 = 5;
    sbit  BGCR6_bit at BGCRR.B6;
    const register unsigned short int BGCR6 = 6;
    sbit  BGCR7_bit at BGCRR.B7;
    const register unsigned short int BGCR7 = 7;

sfr data unsigned short volatile BGCCR absolute 0xD0;
    sbit  BGCC0_bit at BGCCR.B0;
    const register unsigned short int BGCC0 = 0;
    sbit  BGCC1_bit at BGCCR.B1;
    const register unsigned short int BGCC1 = 1;
    sbit  BGCC2_bit at BGCCR.B2;
    const register unsigned short int BGCC2 = 2;
    sbit  BGCC3_bit at BGCCR.B3;
    const register unsigned short int BGCC3 = 3;
    sbit  BGCC4_bit at BGCCR.B4;
    const register unsigned short int BGCC4 = 4;
    sbit  BGCC5_bit at BGCCR.B5;
    const register unsigned short int BGCC5 = 5;

sfr data unsigned short volatile ROCR absolute 0xC8;
    sbit  ROCWIE_bit at ROCR.B0;
    const register unsigned short int ROCWIE = 0;
    sbit  ROCWIF_bit at ROCR.B1;
    const register unsigned short int ROCWIF = 1;
    sbit  ROCD_bit at ROCR.B4;
    const register unsigned short int ROCD = 4;
    sbit  ROCS_bit at ROCR.B7;
    const register unsigned short int ROCS = 7;

sfr data unsigned short volatile TWBCSR absolute 0xBE;
    sbit  TWBCIP_bit at TWBCSR.B0;
    const register unsigned short int TWBCIP = 0;
    sbit  TWBDT0_bit at TWBCSR.B1;
    const register unsigned short int TWBDT0 = 1;
    sbit  TWBDT1_bit at TWBCSR.B2;
    const register unsigned short int TWBDT1 = 2;
    sbit  TWBCIE_bit at TWBCSR.B6;
    const register unsigned short int TWBCIE = 6;
    sbit  TWBCIF_bit at TWBCSR.B7;
    const register unsigned short int TWBCIF = 7;

sfr data unsigned short TWAMR absolute 0xBD;
    sbit  TWAM0_bit at TWAMR.B1;
    const register unsigned short int TWAM0 = 1;
    sbit  TWAM1_bit at TWAMR.B2;
    const register unsigned short int TWAM1 = 2;
    sbit  TWAM2_bit at TWAMR.B3;
    const register unsigned short int TWAM2 = 3;
    sbit  TWAM3_bit at TWAMR.B4;
    const register unsigned short int TWAM3 = 4;
    sbit  TWAM4_bit at TWAMR.B5;
    const register unsigned short int TWAM4 = 5;
    sbit  TWAM5_bit at TWAMR.B6;
    const register unsigned short int TWAM5 = 6;
    sbit  TWAM6_bit at TWAMR.B7;
    const register unsigned short int TWAM6 = 7;

sfr data unsigned short volatile TWCR absolute 0xBC;
    sbit  TWIE_bit at TWCR.B0;
    const register unsigned short int TWIE = 0;
    sbit  TWEN_bit at TWCR.B2;
    const register unsigned short int TWEN = 2;
    sbit  TWWC_bit at TWCR.B3;
    const register unsigned short int TWWC = 3;
    sbit  TWSTO_bit at TWCR.B4;
    const register unsigned short int TWSTO = 4;
    sbit  TWSTA_bit at TWCR.B5;
    const register unsigned short int TWSTA = 5;
    sbit  TWEA_bit at TWCR.B6;
    const register unsigned short int TWEA = 6;
    sbit  TWINT_bit at TWCR.B7;
    const register unsigned short int TWINT = 7;

sfr data unsigned short volatile TWDR absolute 0xBB;
    sbit  TWD0_bit at TWDR.B0;
    const register unsigned short int TWD0 = 0;
    sbit  TWD1_bit at TWDR.B1;
    const register unsigned short int TWD1 = 1;
    sbit  TWD2_bit at TWDR.B2;
    const register unsigned short int TWD2 = 2;
    sbit  TWD3_bit at TWDR.B3;
    const register unsigned short int TWD3 = 3;
    sbit  TWD4_bit at TWDR.B4;
    const register unsigned short int TWD4 = 4;
    sbit  TWD5_bit at TWDR.B5;
    const register unsigned short int TWD5 = 5;
    sbit  TWD6_bit at TWDR.B6;
    const register unsigned short int TWD6 = 6;
    sbit  TWD7_bit at TWDR.B7;
    const register unsigned short int TWD7 = 7;

sfr data unsigned short TWAR absolute 0xBA;
    sbit  TWGCE_bit at TWAR.B0;
    const register unsigned short int TWGCE = 0;
    sbit  TWA0_bit at TWAR.B1;
    const register unsigned short int TWA0 = 1;
    sbit  TWA1_bit at TWAR.B2;
    const register unsigned short int TWA1 = 2;
    sbit  TWA2_bit at TWAR.B3;
    const register unsigned short int TWA2 = 3;
    sbit  TWA3_bit at TWAR.B4;
    const register unsigned short int TWA3 = 4;
    sbit  TWA4_bit at TWAR.B5;
    const register unsigned short int TWA4 = 5;
    sbit  TWA5_bit at TWAR.B6;
    const register unsigned short int TWA5 = 6;
    sbit  TWA6_bit at TWAR.B7;
    const register unsigned short int TWA6 = 7;

sfr data unsigned short volatile TWSR absolute 0xB9;
    sbit  TWPS0_bit at TWSR.B0;
    const register unsigned short int TWPS0 = 0;
    sbit  TWPS1_bit at TWSR.B1;
    const register unsigned short int TWPS1 = 1;
    sbit  TWS3_bit at TWSR.B3;
    const register unsigned short int TWS3 = 3;
    sbit  TWS4_bit at TWSR.B4;
    const register unsigned short int TWS4 = 4;
    sbit  TWS5_bit at TWSR.B5;
    const register unsigned short int TWS5 = 5;
    sbit  TWS6_bit at TWSR.B6;
    const register unsigned short int TWS6 = 6;
    sbit  TWS7_bit at TWSR.B7;
    const register unsigned short int TWS7 = 7;

sfr data unsigned short TWBR absolute 0xB8;
    sbit  TWBR0_bit at TWBR.B0;
    const register unsigned short int TWBR0 = 0;
    sbit  TWBR1_bit at TWBR.B1;
    const register unsigned short int TWBR1 = 1;
    sbit  TWBR2_bit at TWBR.B2;
    const register unsigned short int TWBR2 = 2;
    sbit  TWBR3_bit at TWBR.B3;
    const register unsigned short int TWBR3 = 3;
    sbit  TWBR4_bit at TWBR.B4;
    const register unsigned short int TWBR4 = 4;
    sbit  TWBR5_bit at TWBR.B5;
    const register unsigned short int TWBR5 = 5;
    sbit  TWBR6_bit at TWBR.B6;
    const register unsigned short int TWBR6 = 6;
    sbit  TWBR7_bit at TWBR.B7;
    const register unsigned short int TWBR7 = 7;

sfr data unsigned short volatile OCR1B absolute 0x89;
    sbit  OCR1B0_bit at OCR1B.B0;
    const register unsigned short int OCR1B0 = 0;
    sbit  OCR1B1_bit at OCR1B.B1;
    const register unsigned short int OCR1B1 = 1;
    sbit  OCR1B2_bit at OCR1B.B2;
    const register unsigned short int OCR1B2 = 2;
    sbit  OCR1B3_bit at OCR1B.B3;
    const register unsigned short int OCR1B3 = 3;
    sbit  OCR1B4_bit at OCR1B.B4;
    const register unsigned short int OCR1B4 = 4;
    sbit  OCR1B5_bit at OCR1B.B5;
    const register unsigned short int OCR1B5 = 5;
    sbit  OCR1B6_bit at OCR1B.B6;
    const register unsigned short int OCR1B6 = 6;
    sbit  OCR1B7_bit at OCR1B.B7;
    const register unsigned short int OCR1B7 = 7;

sfr data unsigned short volatile OCR1A absolute 0x88;
    sbit  OCR1A0_bit at OCR1A.B0;
    const register unsigned short int OCR1A0 = 0;
    sbit  OCR1A1_bit at OCR1A.B1;
    const register unsigned short int OCR1A1 = 1;
    sbit  OCR1A2_bit at OCR1A.B2;
    const register unsigned short int OCR1A2 = 2;
    sbit  OCR1A3_bit at OCR1A.B3;
    const register unsigned short int OCR1A3 = 3;
    sbit  OCR1A4_bit at OCR1A.B4;
    const register unsigned short int OCR1A4 = 4;
    sbit  OCR1A5_bit at OCR1A.B5;
    const register unsigned short int OCR1A5 = 5;
    sbit  OCR1A6_bit at OCR1A.B6;
    const register unsigned short int OCR1A6 = 6;
    sbit  OCR1A7_bit at OCR1A.B7;
    const register unsigned short int OCR1A7 = 7;

sfr data unsigned short volatile TCNT1H absolute 0x85;
    sbit  TCNT1H0_bit at TCNT1H.B0;
    const register unsigned short int TCNT1H0 = 0;
    sbit  TCNT1H1_bit at TCNT1H.B1;
    const register unsigned short int TCNT1H1 = 1;
    sbit  TCNT1H2_bit at TCNT1H.B2;
    const register unsigned short int TCNT1H2 = 2;
    sbit  TCNT1H3_bit at TCNT1H.B3;
    const register unsigned short int TCNT1H3 = 3;
    sbit  TCNT1H4_bit at TCNT1H.B4;
    const register unsigned short int TCNT1H4 = 4;
    sbit  TCNT1H5_bit at TCNT1H.B5;
    const register unsigned short int TCNT1H5 = 5;
    sbit  TCNT1H6_bit at TCNT1H.B6;
    const register unsigned short int TCNT1H6 = 6;
    sbit  TCNT1H7_bit at TCNT1H.B7;
    const register unsigned short int TCNT1H7 = 7;

sfr data unsigned short volatile TCNT1L absolute 0x84;
    sbit  TCNT1L0_bit at TCNT1L.B0;
    const register unsigned short int TCNT1L0 = 0;
    sbit  TCNT1L1_bit at TCNT1L.B1;
    const register unsigned short int TCNT1L1 = 1;
    sbit  TCNT1L2_bit at TCNT1L.B2;
    const register unsigned short int TCNT1L2 = 2;
    sbit  TCNT1L3_bit at TCNT1L.B3;
    const register unsigned short int TCNT1L3 = 3;
    sbit  TCNT1L4_bit at TCNT1L.B4;
    const register unsigned short int TCNT1L4 = 4;
    sbit  TCNT1L5_bit at TCNT1L.B5;
    const register unsigned short int TCNT1L5 = 5;
    sbit  TCNT1L6_bit at TCNT1L.B6;
    const register unsigned short int TCNT1L6 = 6;
    sbit  TCNT1L7_bit at TCNT1L.B7;
    const register unsigned short int TCNT1L7 = 7;

sfr data unsigned short TCCR1B absolute 0x81;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS10 = 0;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS11 = 1;
    sbit  CS12_bit at TCCR1B.B2;
    const register unsigned short int CS12 = 2;

sfr data unsigned short TCCR1A absolute 0x80;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM10 = 0;
    sbit  ICS1_bit at TCCR1A.B3;
    const register unsigned short int ICS1 = 3;
    sbit  ICES1_bit at TCCR1A.B4;
    const register unsigned short int ICES1 = 4;
    sbit  ICNC1_bit at TCCR1A.B5;
    const register unsigned short int ICNC1 = 5;
    sbit  ICEN1_bit at TCCR1A.B6;
    const register unsigned short int ICEN1 = 6;
    sbit  TCW1_bit at TCCR1A.B7;
    const register unsigned short int TCW1 = 7;

sfr data unsigned short DIDR0 absolute 0x7E;
    sbit  PA0DID_bit at DIDR0.B0;
    const register unsigned short int PA0DID = 0;
    sbit  PA1DID_bit at DIDR0.B1;
    const register unsigned short int PA1DID = 1;

sfr data unsigned short volatile VADMUX absolute 0x7C;
    sbit  VADMUX0_bit at VADMUX.B0;
    const register unsigned short int VADMUX0 = 0;
    sbit  VADMUX1_bit at VADMUX.B1;
    const register unsigned short int VADMUX1 = 1;
    sbit  VADMUX2_bit at VADMUX.B2;
    const register unsigned short int VADMUX2 = 2;
    sbit  VADMUX3_bit at VADMUX.B3;
    const register unsigned short int VADMUX3 = 3;

sfr data unsigned short volatile VADCSR absolute 0x7A;
    sbit  VADCCIE_bit at VADCSR.B0;
    const register unsigned short int VADCCIE = 0;
    sbit  VADCCIF_bit at VADCSR.B1;
    const register unsigned short int VADCCIF = 1;
    sbit  VADSC_bit at VADCSR.B2;
    const register unsigned short int VADSC = 2;
    sbit  VADEN_bit at VADCSR.B3;
    const register unsigned short int VADEN = 3;

sfr data unsigned short volatile VADCH absolute 0x79;
    sbit  VADC8_bit at VADCH.B0;
    const register unsigned short int VADC8 = 0;
    sbit  VADC9_bit at VADCH.B1;
    const register unsigned short int VADC9 = 1;
    sbit  VADC10_bit at VADCH.B2;
    const register unsigned short int VADC10 = 2;
    sbit  VADC11_bit at VADCH.B3;
    const register unsigned short int VADC11 = 3;

sfr data unsigned short volatile VADCL absolute 0x78;
    sbit  VADC0_bit at VADCL.B0;
    const register unsigned short int VADC0 = 0;
    sbit  VADC1_bit at VADCL.B1;
    const register unsigned short int VADC1 = 1;
    sbit  VADC2_bit at VADCL.B2;
    const register unsigned short int VADC2 = 2;
    sbit  VADC3_bit at VADCL.B3;
    const register unsigned short int VADC3 = 3;
    sbit  VADC4_bit at VADCL.B4;
    const register unsigned short int VADC4 = 4;
    sbit  VADC5_bit at VADCL.B5;
    const register unsigned short int VADC5 = 5;
    sbit  VADC6_bit at VADCL.B6;
    const register unsigned short int VADC6 = 6;
    sbit  VADC7_bit at VADCL.B7;
    const register unsigned short int VADC7 = 7;

sfr data unsigned short TIMSK1 absolute 0x6F;
    sbit  TOIE1_bit at TIMSK1.B0;
    const register unsigned short int TOIE1 = 0;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1B = 2;
    sbit  ICIE1_bit at TIMSK1.B3;
    const register unsigned short int ICIE1 = 3;

sfr data unsigned short TIMSK0 absolute 0x6E;
    sbit  TOIE0_bit at TIMSK0.B0;
    const register unsigned short int TOIE0 = 0;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0B = 2;
    sbit  ICIE0_bit at TIMSK0.B3;
    const register unsigned short int ICIE0 = 3;

sfr data unsigned short PCMSK1 absolute 0x6C;
    sbit  PCINT4_bit at PCMSK1.B0;
    const register unsigned short int PCINT4 = 0;
    sbit  PCINT5_bit at PCMSK1.B1;
    const register unsigned short int PCINT5 = 1;
    sbit  PCINT6_bit at PCMSK1.B2;
    const register unsigned short int PCINT6 = 2;
    sbit  PCINT7_bit at PCMSK1.B3;
    const register unsigned short int PCINT7 = 3;
    sbit  PCINT8_bit at PCMSK1.B4;
    const register unsigned short int PCINT8 = 4;
    sbit  PCINT9_bit at PCMSK1.B5;
    const register unsigned short int PCINT9 = 5;
    sbit  PCINT10_bit at PCMSK1.B6;
    const register unsigned short int PCINT10 = 6;
    sbit  PCINT11_bit at PCMSK1.B7;
    const register unsigned short int PCINT11 = 7;

sfr data unsigned short PCMSK0 absolute 0x6B;
    sbit  PCINT0_bit at PCMSK0.B0;
    const register unsigned short int PCINT0 = 0;
    sbit  PCINT1_bit at PCMSK0.B1;
    const register unsigned short int PCINT1 = 1;
    sbit  PCINT2_bit at PCMSK0.B2;
    const register unsigned short int PCINT2 = 2;
    sbit  PCINT3_bit at PCMSK0.B3;
    const register unsigned short int PCINT3 = 3;

sfr data unsigned short volatile EICRA absolute 0x69;
    sbit  ISC00_bit at EICRA.B0;
    const register unsigned short int ISC00 = 0;
    sbit  ISC01_bit at EICRA.B1;
    const register unsigned short int ISC01 = 1;
    sbit  ISC10_bit at EICRA.B2;
    const register unsigned short int ISC10 = 2;
    sbit  ISC11_bit at EICRA.B3;
    const register unsigned short int ISC11 = 3;
    sbit  ISC20_bit at EICRA.B4;
    const register unsigned short int ISC20 = 4;
    sbit  ISC21_bit at EICRA.B5;
    const register unsigned short int ISC21 = 5;
    sbit  ISC30_bit at EICRA.B6;
    const register unsigned short int ISC30 = 6;
    sbit  ISC31_bit at EICRA.B7;
    const register unsigned short int ISC31 = 7;

sfr data unsigned short PCICR absolute 0x68;
    sbit  PCIE0_bit at PCICR.B0;
    const register unsigned short int PCIE0 = 0;
    sbit  PCIE1_bit at PCICR.B1;
    const register unsigned short int PCIE1 = 1;

sfr data unsigned short volatile FOSCCAL absolute 0x66;
    sbit  FCAL0_bit at FOSCCAL.B0;
    const register unsigned short int FCAL0 = 0;
    sbit  FCAL1_bit at FOSCCAL.B1;
    const register unsigned short int FCAL1 = 1;
    sbit  FCAL2_bit at FOSCCAL.B2;
    const register unsigned short int FCAL2 = 2;
    sbit  FCAL3_bit at FOSCCAL.B3;
    const register unsigned short int FCAL3 = 3;
    sbit  FCAL4_bit at FOSCCAL.B4;
    const register unsigned short int FCAL4 = 4;
    sbit  FCAL5_bit at FOSCCAL.B5;
    const register unsigned short int FCAL5 = 5;
    sbit  FCAL6_bit at FOSCCAL.B6;
    const register unsigned short int FCAL6 = 6;
    sbit  FCAL7_bit at FOSCCAL.B7;
    const register unsigned short int FCAL7 = 7;

sfr data unsigned short PRR0 absolute 0x64;
    sbit  PRVADC_bit at PRR0.B0;
    const register unsigned short int PRVADC = 0;
    sbit  PRTIM0_bit at PRR0.B1;
    const register unsigned short int PRTIM0 = 1;
    sbit  PRTIM1_bit at PRR0.B2;
    const register unsigned short int PRTIM1 = 2;
    sbit  PRSPI_bit at PRR0.B3;
    const register unsigned short int PRSPI = 3;
    sbit  PRVRM_bit at PRR0.B5;
    const register unsigned short int PRVRM = 5;
    sbit  PRTWI_bit at PRR0.B6;
    const register unsigned short int PRTWI = 6;

sfr data unsigned short volatile CLKPR absolute 0x61;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPCE_bit at CLKPR.B7;
    const register unsigned short int CLKPCE = 7;

sfr data unsigned short volatile WDTCSR absolute 0x60;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP0 = 0;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP1 = 1;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP2 = 2;
    sbit  WDE_bit at WDTCSR.B3;
    const register unsigned short int WDE = 3;
    sbit  WDCE_bit at WDTCSR.B4;
    const register unsigned short int WDCE = 4;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDP3 = 5;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDIE = 6;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIF = 7;

sfr io unsigned short volatile SREG absolute 0x5F;
    sbit  SREG_C_bit at SREG.B0;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_I = 7;

sfr io unsigned short volatile SPH absolute 0x5E;
    sbit  SP8_bit at SPH.B0;
    const register unsigned short int SP8 = 0;
    sbit  SP9_bit at SPH.B1;
    const register unsigned short int SP9 = 1;
    sbit  SP10_bit at SPH.B2;
    const register unsigned short int SP10 = 2;
    sbit  SP11_bit at SPH.B3;
    const register unsigned short int SP11 = 3;
    sbit  SP12_bit at SPH.B4;
    const register unsigned short int SP12 = 4;
    sbit  SP13_bit at SPH.B5;
    const register unsigned short int SP13 = 5;
    sbit  SP14_bit at SPH.B6;
    const register unsigned short int SP14 = 6;
    sbit  SP15_bit at SPH.B7;
    const register unsigned short int SP15 = 7;

sfr io unsigned short volatile SPL absolute 0x5D;
    sbit  SP0_bit at SPL.B0;
    const register unsigned short int SP0 = 0;
    sbit  SP1_bit at SPL.B1;
    const register unsigned short int SP1 = 1;
    sbit  SP2_bit at SPL.B2;
    const register unsigned short int SP2 = 2;
    sbit  SP3_bit at SPL.B3;
    const register unsigned short int SP3 = 3;
    sbit  SP4_bit at SPL.B4;
    const register unsigned short int SP4 = 4;
    sbit  SP5_bit at SPL.B5;
    const register unsigned short int SP5 = 5;
    sbit  SP6_bit at SPL.B6;
    const register unsigned short int SP6 = 6;
    sbit  SP7_bit at SPL.B7;
    const register unsigned short int SP7 = 7;

sfr io unsigned short volatile SPMCSR absolute 0x57;
    sbit  SPMEN_bit at SPMCSR.B0;
    const register unsigned short int SPMEN = 0;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int PGERS = 1;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGWRT = 2;
    sbit  LBSET_bit at SPMCSR.B3;
    const register unsigned short int LBSET = 3;
    sbit  RWWSRE_bit at SPMCSR.B4;
    const register unsigned short int RWWSRE = 4;
    sbit  SIGRD_bit at SPMCSR.B5;
    const register unsigned short int SIGRD = 5;
    sbit  RWWSB_bit at SPMCSR.B6;
    const register unsigned short int RWWSB = 6;
    sbit  SPMIE_bit at SPMCSR.B7;
    const register unsigned short int SPMIE = 7;

sfr io unsigned short volatile MCUCR absolute 0x55;
    sbit  IVCE_bit at MCUCR.B0;
    const register unsigned short int IVCE = 0;
    sbit  IVSEL_bit at MCUCR.B1;
    const register unsigned short int IVSEL = 1;
    sbit  PUD_bit at MCUCR.B4;
    const register unsigned short int PUD = 4;
    sbit  CKOE_bit at MCUCR.B5;
    const register unsigned short int CKOE = 5;

sfr io unsigned short volatile MCUSR absolute 0x54;
    sbit  PORF_bit at MCUSR.B0;
    const register unsigned short int PORF = 0;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int EXTRF = 1;
    sbit  BODRF_bit at MCUSR.B2;
    const register unsigned short int BODRF = 2;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int WDRF = 3;
    sbit  OCDRF_bit at MCUSR.B4;
    const register unsigned short int OCDRF = 4;

sfr io unsigned short SMCR absolute 0x53;
    sbit  SE_bit at SMCR.B0;
    const register unsigned short int SE = 0;
    sbit  SM0_bit at SMCR.B1;
    const register unsigned short int SM0 = 1;
    sbit  SM1_bit at SMCR.B2;
    const register unsigned short int SM1 = 2;
    sbit  SM2_bit at SMCR.B3;
    const register unsigned short int SM2 = 3;

sfr io unsigned short volatile DWDR absolute 0x51;

sfr io unsigned short volatile SPDR absolute 0x4E;
    sbit  SPDR0_bit at SPDR.B0;
    const register unsigned short int SPDR0 = 0;
    sbit  SPDR1_bit at SPDR.B1;
    const register unsigned short int SPDR1 = 1;
    sbit  SPDR2_bit at SPDR.B2;
    const register unsigned short int SPDR2 = 2;
    sbit  SPDR3_bit at SPDR.B3;
    const register unsigned short int SPDR3 = 3;
    sbit  SPDR4_bit at SPDR.B4;
    const register unsigned short int SPDR4 = 4;
    sbit  SPDR5_bit at SPDR.B5;
    const register unsigned short int SPDR5 = 5;
    sbit  SPDR6_bit at SPDR.B6;
    const register unsigned short int SPDR6 = 6;
    sbit  SPDR7_bit at SPDR.B7;
    const register unsigned short int SPDR7 = 7;

sfr io unsigned short volatile SPSR absolute 0x4D;
    sbit  SPI2X_bit at SPSR.B0;
    const register unsigned short int SPI2X = 0;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int WCOL = 6;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int SPIF = 7;

sfr io unsigned short SPCR absolute 0x4C;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR0 = 0;
    sbit  SPR1_bit at SPCR.B1;
    const register unsigned short int SPR1 = 1;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int CPHA = 2;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPOL = 3;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int MSTR = 4;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int DORD = 5;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int SPE = 6;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPIE = 7;

sfr io unsigned short volatile GPIOR2 absolute 0x4B;
    sbit  GPIOR20_bit at GPIOR2.B0;
    const register unsigned short int GPIOR20 = 0;
    sbit  GPIOR21_bit at GPIOR2.B1;
    const register unsigned short int GPIOR21 = 1;
    sbit  GPIOR22_bit at GPIOR2.B2;
    const register unsigned short int GPIOR22 = 2;
    sbit  GPIOR23_bit at GPIOR2.B3;
    const register unsigned short int GPIOR23 = 3;
    sbit  GPIOR24_bit at GPIOR2.B4;
    const register unsigned short int GPIOR24 = 4;
    sbit  GPIOR25_bit at GPIOR2.B5;
    const register unsigned short int GPIOR25 = 5;
    sbit  GPIOR26_bit at GPIOR2.B6;
    const register unsigned short int GPIOR26 = 6;
    sbit  GPIOR27_bit at GPIOR2.B7;
    const register unsigned short int GPIOR27 = 7;

sfr io unsigned short volatile GPIOR1 absolute 0x4A;
    sbit  GPIOR10_bit at GPIOR1.B0;
    const register unsigned short int GPIOR10 = 0;
    sbit  GPIOR11_bit at GPIOR1.B1;
    const register unsigned short int GPIOR11 = 1;
    sbit  GPIOR12_bit at GPIOR1.B2;
    const register unsigned short int GPIOR12 = 2;
    sbit  GPIOR13_bit at GPIOR1.B3;
    const register unsigned short int GPIOR13 = 3;
    sbit  GPIOR14_bit at GPIOR1.B4;
    const register unsigned short int GPIOR14 = 4;
    sbit  GPIOR15_bit at GPIOR1.B5;
    const register unsigned short int GPIOR15 = 5;
    sbit  GPIOR16_bit at GPIOR1.B6;
    const register unsigned short int GPIOR16 = 6;
    sbit  GPIOR17_bit at GPIOR1.B7;
    const register unsigned short int GPIOR17 = 7;

sfr io unsigned short OCR0B absolute 0x49;
    sbit  OCR0B0_bit at OCR0B.B0;
    const register unsigned short int OCR0B0 = 0;
    sbit  OCR0B1_bit at OCR0B.B1;
    const register unsigned short int OCR0B1 = 1;
    sbit  OCR0B2_bit at OCR0B.B2;
    const register unsigned short int OCR0B2 = 2;
    sbit  OCR0B3_bit at OCR0B.B3;
    const register unsigned short int OCR0B3 = 3;
    sbit  OCR0B4_bit at OCR0B.B4;
    const register unsigned short int OCR0B4 = 4;
    sbit  OCR0B5_bit at OCR0B.B5;
    const register unsigned short int OCR0B5 = 5;
    sbit  OCR0B6_bit at OCR0B.B6;
    const register unsigned short int OCR0B6 = 6;
    sbit  OCR0B7_bit at OCR0B.B7;
    const register unsigned short int OCR0B7 = 7;

sfr io unsigned short OCR0A absolute 0x48;
    sbit  OCR0A0_bit at OCR0A.B0;
    const register unsigned short int OCR0A0 = 0;
    sbit  OCR0A1_bit at OCR0A.B1;
    const register unsigned short int OCR0A1 = 1;
    sbit  OCR0A2_bit at OCR0A.B2;
    const register unsigned short int OCR0A2 = 2;
    sbit  OCR0A3_bit at OCR0A.B3;
    const register unsigned short int OCR0A3 = 3;
    sbit  OCR0A4_bit at OCR0A.B4;
    const register unsigned short int OCR0A4 = 4;
    sbit  OCR0A5_bit at OCR0A.B5;
    const register unsigned short int OCR0A5 = 5;
    sbit  OCR0A6_bit at OCR0A.B6;
    const register unsigned short int OCR0A6 = 6;
    sbit  OCR0A7_bit at OCR0A.B7;
    const register unsigned short int OCR0A7 = 7;

sfr io unsigned short volatile TCNT0H absolute 0x47;
    sbit  TCNT0H0_bit at TCNT0H.B0;
    const register unsigned short int TCNT0H0 = 0;
    sbit  TCNT0H1_bit at TCNT0H.B1;
    const register unsigned short int TCNT0H1 = 1;
    sbit  TCNT0H2_bit at TCNT0H.B2;
    const register unsigned short int TCNT0H2 = 2;
    sbit  TCNT0H3_bit at TCNT0H.B3;
    const register unsigned short int TCNT0H3 = 3;
    sbit  TCNT0H4_bit at TCNT0H.B4;
    const register unsigned short int TCNT0H4 = 4;
    sbit  TCNT0H5_bit at TCNT0H.B5;
    const register unsigned short int TCNT0H5 = 5;
    sbit  TCNT0H6_bit at TCNT0H.B6;
    const register unsigned short int TCNT0H6 = 6;
    sbit  TCNT0H7_bit at TCNT0H.B7;
    const register unsigned short int TCNT0H7 = 7;

sfr io unsigned short volatile TCNT0L absolute 0x46;
    sbit  TCNT0L0_bit at TCNT0L.B0;
    const register unsigned short int TCNT0L0 = 0;
    sbit  TCNT0L1_bit at TCNT0L.B1;
    const register unsigned short int TCNT0L1 = 1;
    sbit  TCNT0L2_bit at TCNT0L.B2;
    const register unsigned short int TCNT0L2 = 2;
    sbit  TCNT0L3_bit at TCNT0L.B3;
    const register unsigned short int TCNT0L3 = 3;
    sbit  TCNT0L4_bit at TCNT0L.B4;
    const register unsigned short int TCNT0L4 = 4;
    sbit  TCNT0L5_bit at TCNT0L.B5;
    const register unsigned short int TCNT0L5 = 5;
    sbit  TCNT0L6_bit at TCNT0L.B6;
    const register unsigned short int TCNT0L6 = 6;
    sbit  TCNT0L7_bit at TCNT0L.B7;
    const register unsigned short int TCNT0L7 = 7;

sfr io unsigned short TCCR0B absolute 0x45;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS00 = 0;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS01 = 1;
    sbit  CS02_bit at TCCR0B.B2;
    const register unsigned short int CS02 = 2;

sfr io unsigned short TCCR0A absolute 0x44;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM00 = 0;
    sbit  ICS0_bit at TCCR0A.B3;
    const register unsigned short int ICS0 = 3;
    sbit  ICES0_bit at TCCR0A.B4;
    const register unsigned short int ICES0 = 4;
    sbit  ICNC0_bit at TCCR0A.B5;
    const register unsigned short int ICNC0 = 5;
    sbit  ICEN0_bit at TCCR0A.B6;
    const register unsigned short int ICEN0 = 6;
    sbit  TCW0_bit at TCCR0A.B7;
    const register unsigned short int TCW0 = 7;

sfr io unsigned short volatile GTCCR absolute 0x43;
    sbit  PSRSYNC_bit at GTCCR.B0;
    const register unsigned short int PSRSYNC = 0;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int TSM = 7;

sfr io unsigned short EEARH absolute 0x42;
    sbit  EEAR8_bit at EEARH.B0;
    const register unsigned short int EEAR8 = 0;
    sbit  EEAR9_bit at EEARH.B1;
    const register unsigned short int EEAR9 = 1;

sfr io unsigned short EEARL absolute 0x41;
    sbit  EEAR0_bit at EEARL.B0;
    const register unsigned short int EEAR0 = 0;
    sbit  EEAR1_bit at EEARL.B1;
    const register unsigned short int EEAR1 = 1;
    sbit  EEAR2_bit at EEARL.B2;
    const register unsigned short int EEAR2 = 2;
    sbit  EEAR3_bit at EEARL.B3;
    const register unsigned short int EEAR3 = 3;
    sbit  EEAR4_bit at EEARL.B4;
    const register unsigned short int EEAR4 = 4;
    sbit  EEAR5_bit at EEARL.B5;
    const register unsigned short int EEAR5 = 5;
    sbit  EEAR6_bit at EEARL.B6;
    const register unsigned short int EEAR6 = 6;
    sbit  EEAR7_bit at EEARL.B7;
    const register unsigned short int EEAR7 = 7;

sfr io unsigned short volatile EEDR absolute 0x40;
    sbit  EEDR0_bit at EEDR.B0;
    const register unsigned short int EEDR0 = 0;
    sbit  EEDR1_bit at EEDR.B1;
    const register unsigned short int EEDR1 = 1;
    sbit  EEDR2_bit at EEDR.B2;
    const register unsigned short int EEDR2 = 2;
    sbit  EEDR3_bit at EEDR.B3;
    const register unsigned short int EEDR3 = 3;
    sbit  EEDR4_bit at EEDR.B4;
    const register unsigned short int EEDR4 = 4;
    sbit  EEDR5_bit at EEDR.B5;
    const register unsigned short int EEDR5 = 5;
    sbit  EEDR6_bit at EEDR.B6;
    const register unsigned short int EEDR6 = 6;
    sbit  EEDR7_bit at EEDR.B7;
    const register unsigned short int EEDR7 = 7;

sfr io unsigned short volatile EECR absolute 0x3F;
    sbit  EERE_bit at EECR.B0;
    const register unsigned short int EERE = 0;
    sbit  EEPE_bit at EECR.B1;
    const register unsigned short int EEPE = 1;
    sbit  EEMPE_bit at EECR.B2;
    const register unsigned short int EEMPE = 2;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EERIE = 3;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EEPM1 = 5;

sfr io unsigned short volatile GPIOR0 absolute 0x3E;
    sbit  GPIOR00_bit at GPIOR0.B0;
    const register unsigned short int GPIOR00 = 0;
    sbit  GPIOR01_bit at GPIOR0.B1;
    const register unsigned short int GPIOR01 = 1;
    sbit  GPIOR02_bit at GPIOR0.B2;
    const register unsigned short int GPIOR02 = 2;
    sbit  GPIOR03_bit at GPIOR0.B3;
    const register unsigned short int GPIOR03 = 3;
    sbit  GPIOR04_bit at GPIOR0.B4;
    const register unsigned short int GPIOR04 = 4;
    sbit  GPIOR05_bit at GPIOR0.B5;
    const register unsigned short int GPIOR05 = 5;
    sbit  GPIOR06_bit at GPIOR0.B6;
    const register unsigned short int GPIOR06 = 6;
    sbit  GPIOR07_bit at GPIOR0.B7;
    const register unsigned short int GPIOR07 = 7;

sfr io unsigned short EIMSK absolute 0x3D;
    sbit  INT0_bit at EIMSK.B0;
    const register unsigned short int INT0 = 0;
    sbit  INT1_bit at EIMSK.B1;
    const register unsigned short int INT1 = 1;
    sbit  INT2_bit at EIMSK.B2;
    const register unsigned short int INT2 = 2;
    sbit  INT3_bit at EIMSK.B3;
    const register unsigned short int INT3 = 3;

sfr io unsigned short volatile EIFR absolute 0x3C;
    sbit  INTF0_bit at EIFR.B0;
    const register unsigned short int INTF0 = 0;
    sbit  INTF1_bit at EIFR.B1;
    const register unsigned short int INTF1 = 1;
    sbit  INTF2_bit at EIFR.B2;
    const register unsigned short int INTF2 = 2;
    sbit  INTF3_bit at EIFR.B3;
    const register unsigned short int INTF3 = 3;

sfr io unsigned short volatile PCIFR absolute 0x3B;
    sbit  PCIF0_bit at PCIFR.B0;
    const register unsigned short int PCIF0 = 0;
    sbit  PCIF1_bit at PCIFR.B1;
    const register unsigned short int PCIF1 = 1;

sfr io unsigned short volatile OSICSR absolute 0x37;
    sbit  OSIEN_bit at OSICSR.B0;
    const register unsigned short int OSIEN = 0;
    sbit  OSIST_bit at OSICSR.B1;
    const register unsigned short int OSIST = 1;
    sbit  OSISEL0_bit at OSICSR.B4;
    const register unsigned short int OSISEL0 = 4;

sfr io unsigned short volatile TIFR1 absolute 0x36;
    sbit  TOV1_bit at TIFR1.B0;
    const register unsigned short int TOV1 = 0;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1B = 2;
    sbit  ICF1_bit at TIFR1.B3;
    const register unsigned short int ICF1 = 3;

sfr io unsigned short volatile TIFR0 absolute 0x35;
    sbit  TOV0_bit at TIFR0.B0;
    const register unsigned short int TOV0 = 0;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0B = 2;
    sbit  ICF0_bit at TIFR0.B3;
    const register unsigned short int ICF0 = 3;

sfr io unsigned short PORTC absolute 0x28;
    sbit  PORTC0_bit at PORTC.B0;
    const register unsigned short int PORTC0 = 0;
    sbit  PORTC1_bit at PORTC.B1;
    const register unsigned short int PORTC1 = 1;
    sbit  PORTC2_bit at PORTC.B2;
    const register unsigned short int PORTC2 = 2;
    sbit  PORTC3_bit at PORTC.B3;
    const register unsigned short int PORTC3 = 3;
    sbit  PORTC4_bit at PORTC.B4;
    const register unsigned short int PORTC4 = 4;
    sbit  PORTC5_bit at PORTC.B5;
    const register unsigned short int PORTC5 = 5;

sfr io unsigned short volatile PINC absolute 0x26;
    sbit  PINC0_bit at PINC.B0;
    const register unsigned short int PINC0 = 0;
    sbit  PINC1_bit at PINC.B1;
    const register unsigned short int PINC1 = 1;
    sbit  PINC2_bit at PINC.B2;
    const register unsigned short int PINC2 = 2;
    sbit  PINC3_bit at PINC.B3;
    const register unsigned short int PINC3 = 3;
    sbit  PINC4_bit at PINC.B4;
    const register unsigned short int PINC4 = 4;

sfr io unsigned short PORTB absolute 0x25;
    sbit  PORTB0_bit at PORTB.B0;
    const register unsigned short int PORTB0 = 0;
    sbit  PORTB1_bit at PORTB.B1;
    const register unsigned short int PORTB1 = 1;
    sbit  PORTB2_bit at PORTB.B2;
    const register unsigned short int PORTB2 = 2;
    sbit  PORTB3_bit at PORTB.B3;
    const register unsigned short int PORTB3 = 3;
    sbit  PORTB4_bit at PORTB.B4;
    const register unsigned short int PORTB4 = 4;
    sbit  PORTB5_bit at PORTB.B5;
    const register unsigned short int PORTB5 = 5;
    sbit  PORTB6_bit at PORTB.B6;
    const register unsigned short int PORTB6 = 6;
    sbit  PORTB7_bit at PORTB.B7;
    const register unsigned short int PORTB7 = 7;

sfr io unsigned short DDRB absolute 0x24;
    sbit  DDB0_bit at DDRB.B0;
    const register unsigned short int DDB0 = 0;
    sbit  DDB1_bit at DDRB.B1;
    const register unsigned short int DDB1 = 1;
    sbit  DDB2_bit at DDRB.B2;
    const register unsigned short int DDB2 = 2;
    sbit  DDB3_bit at DDRB.B3;
    const register unsigned short int DDB3 = 3;
    sbit  DDB4_bit at DDRB.B4;
    const register unsigned short int DDB4 = 4;
    sbit  DDB5_bit at DDRB.B5;
    const register unsigned short int DDB5 = 5;
    sbit  DDB6_bit at DDRB.B6;
    const register unsigned short int DDB6 = 6;
    sbit  DDB7_bit at DDRB.B7;
    const register unsigned short int DDB7 = 7;

sfr io unsigned short volatile PINB absolute 0x23;
    sbit  PINB0_bit at PINB.B0;
    const register unsigned short int PINB0 = 0;
    sbit  PINB1_bit at PINB.B1;
    const register unsigned short int PINB1 = 1;
    sbit  PINB2_bit at PINB.B2;
    const register unsigned short int PINB2 = 2;
    sbit  PINB3_bit at PINB.B3;
    const register unsigned short int PINB3 = 3;
    sbit  PINB4_bit at PINB.B4;
    const register unsigned short int PINB4 = 4;
    sbit  PINB5_bit at PINB.B5;
    const register unsigned short int PINB5 = 5;
    sbit  PINB6_bit at PINB.B6;
    const register unsigned short int PINB6 = 6;
    sbit  PINB7_bit at PINB.B7;
    const register unsigned short int PINB7 = 7;

sfr io unsigned short PORTA absolute 0x22;
    sbit  PORTA0_bit at PORTA.B0;
    const register unsigned short int PORTA0 = 0;
    sbit  PORTA1_bit at PORTA.B1;
    const register unsigned short int PORTA1 = 1;
    sbit  PORTA2_bit at PORTA.B2;
    const register unsigned short int PORTA2 = 2;
    sbit  PORTA3_bit at PORTA.B3;
    const register unsigned short int PORTA3 = 3;

sfr io unsigned short DDRA absolute 0x21;
    sbit  DDA0_bit at DDRA.B0;
    const register unsigned short int DDA0 = 0;
    sbit  DDA1_bit at DDRA.B1;
    const register unsigned short int DDA1 = 1;
    sbit  DDA2_bit at DDRA.B2;
    const register unsigned short int DDA2 = 2;
    sbit  DDA3_bit at DDRA.B3;
    const register unsigned short int DDA3 = 3;

sfr io unsigned short volatile PINA absolute 0x20;
    sbit  PINA0_bit at PINA.B0;
    const register unsigned short int PINA0 = 0;
    sbit  PINA1_bit at PINA.B1;
    const register unsigned short int PINA1 = 1;
    sbit  PINA2_bit at PINA.B2;
    const register unsigned short int PINA2 = 2;
    sbit  PINA3_bit at PINA.B3;
    const register unsigned short int PINA3 = 3;
