// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00008000;

// Flash page size in program words
const int __FLASH_PAGE_SIZE = 64;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;

const unsigned int IVT_ADDR_RESET            = 0x0000;
const unsigned int IVT_ADDR_INT0             = 0x0002;
const unsigned int IVT_ADDR_INT1             = 0x0004;
const unsigned int IVT_ADDR_INT2             = 0x0006;
const unsigned int IVT_ADDR_TIMER2_COMP      = 0x0008;
const unsigned int IVT_ADDR_TIMER2_OVF       = 0x000A;
const unsigned int IVT_ADDR_TIMER1_CAPT      = 0x000C;
const unsigned int IVT_ADDR_TIMER1_COMPA     = 0x000E;
const unsigned int IVT_ADDR_TIMER1_COMPB     = 0x0010;
const unsigned int IVT_ADDR_TIMER1_OVF       = 0x0012;
const unsigned int IVT_ADDR_TIMER0_COMP      = 0x0014;
const unsigned int IVT_ADDR_TIMER0_OVF       = 0x0016;
const unsigned int IVT_ADDR_SPI__STC         = 0x0018;
const unsigned int IVT_ADDR_USART__RXC       = 0x001A;
const unsigned int IVT_ADDR_USART__UDRE      = 0x001C;
const unsigned int IVT_ADDR_USART__TXC       = 0x001E;
const unsigned int IVT_ADDR_ADC              = 0x0020;
const unsigned int IVT_ADDR_EE_RDY           = 0x0022;
const unsigned int IVT_ADDR_ANA_COMP         = 0x0024;
const unsigned int IVT_ADDR_TWI              = 0x0026;
const unsigned int IVT_ADDR_SPM_RDY          = 0x0028;


sfr io unsigned short volatile SREG absolute 0x5F;
    sbit  SREG_C_bit at SREG.B0;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_I = 7;

sfr io unsigned short volatile SPH absolute 0x5E;
    sbit  SP8_bit at SPH.B0;
    const register unsigned short int SP8 = 0;
    sbit  SP9_bit at SPH.B1;
    const register unsigned short int SP9 = 1;
    sbit  SP10_bit at SPH.B2;
    const register unsigned short int SP10 = 2;
    sbit  SP11_bit at SPH.B3;
    const register unsigned short int SP11 = 3;

sfr io unsigned short volatile SPL absolute 0x5D;
    sbit  SP0_bit at SPL.B0;
    const register unsigned short int SP0 = 0;
    sbit  SP1_bit at SPL.B1;
    const register unsigned short int SP1 = 1;
    sbit  SP2_bit at SPL.B2;
    const register unsigned short int SP2 = 2;
    sbit  SP3_bit at SPL.B3;
    const register unsigned short int SP3 = 3;
    sbit  SP4_bit at SPL.B4;
    const register unsigned short int SP4 = 4;
    sbit  SP5_bit at SPL.B5;
    const register unsigned short int SP5 = 5;
    sbit  SP6_bit at SPL.B6;
    const register unsigned short int SP6 = 6;
    sbit  SP7_bit at SPL.B7;
    const register unsigned short int SP7 = 7;

sfr io unsigned short volatile OCR0 absolute 0x5C;
    sbit  OCR0_0_bit at OCR0.B0;
    const register unsigned short int OCR0_0 = 0;
    sbit  OCR0_1_bit at OCR0.B1;
    const register unsigned short int OCR0_1 = 1;
    sbit  OCR0_2_bit at OCR0.B2;
    const register unsigned short int OCR0_2 = 2;
    sbit  OCR0_3_bit at OCR0.B3;
    const register unsigned short int OCR0_3 = 3;
    sbit  OCR0_4_bit at OCR0.B4;
    const register unsigned short int OCR0_4 = 4;
    sbit  OCR0_5_bit at OCR0.B5;
    const register unsigned short int OCR0_5 = 5;
    sbit  OCR0_6_bit at OCR0.B6;
    const register unsigned short int OCR0_6 = 6;
    sbit  OCR0_7_bit at OCR0.B7;
    const register unsigned short int OCR0_7 = 7;

sfr io unsigned short volatile GICR absolute 0x5B;
    sbit  IVCE_bit at GICR.B0;
    const register unsigned short int IVCE = 0;
    sbit  IVSEL_bit at GICR.B1;
    const register unsigned short int IVSEL = 1;
    sbit  INT2_bit at GICR.B5;
    const register unsigned short int INT2 = 5;
    sbit  INT0_bit at GICR.B6;
    const register unsigned short int INT0 = 6;
    sbit  INT1_bit at GICR.B7;
    const register unsigned short int INT1 = 7;

sfr io unsigned short volatile GIFR absolute 0x5A;
    sbit  INTF2_bit at GIFR.B5;
    const register unsigned short int INTF2 = 5;
    sbit  INTF0_bit at GIFR.B6;
    const register unsigned short int INTF0 = 6;
    sbit  INTF1_bit at GIFR.B7;
    const register unsigned short int INTF1 = 7;

sfr io unsigned short TIMSK absolute 0x59;
    sbit  TOIE0_bit at TIMSK.B0;
    const register unsigned short int TOIE0 = 0;
    sbit  OCIE0_bit at TIMSK.B1;
    const register unsigned short int OCIE0 = 1;
    sbit  TOIE2_bit at TIMSK.B6;
    const register unsigned short int TOIE2 = 6;
    sbit  OCIE2_bit at TIMSK.B7;
    const register unsigned short int OCIE2 = 7;
    sbit  TOIE1_bit at TIMSK.B2;
    const register unsigned short int TOIE1 = 2;
    sbit  OCIE1B_bit at TIMSK.B3;
    const register unsigned short int OCIE1B = 3;
    sbit  OCIE1A_bit at TIMSK.B4;
    const register unsigned short int OCIE1A = 4;
    sbit  TICIE1_bit at TIMSK.B5;
    const register unsigned short int TICIE1 = 5;

sfr io unsigned short volatile TIFR absolute 0x58;
    sbit  TOV0_bit at TIFR.B0;
    const register unsigned short int TOV0 = 0;
    sbit  OCF0_bit at TIFR.B1;
    const register unsigned short int OCF0 = 1;
    sbit  TOV2_bit at TIFR.B6;
    const register unsigned short int TOV2 = 6;
    sbit  OCF2_bit at TIFR.B7;
    const register unsigned short int OCF2 = 7;
    sbit  TOV1_bit at TIFR.B2;
    const register unsigned short int TOV1 = 2;
    sbit  OCF1B_bit at TIFR.B3;
    const register unsigned short int OCF1B = 3;
    sbit  OCF1A_bit at TIFR.B4;
    const register unsigned short int OCF1A = 4;
    sbit  ICF1_bit at TIFR.B5;
    const register unsigned short int ICF1 = 5;

sfr io unsigned short volatile SPMCSR absolute 0x57;
sfr io unsigned short volatile SPMCR absolute 0x57;
    sbit  SPMEN_bit at SPMCR.B0;
    const register unsigned short int SPMEN = 0;
    sbit  PGERS_bit at SPMCR.B1;
    const register unsigned short int PGERS = 1;
    sbit  PGWRT_bit at SPMCR.B2;
    const register unsigned short int PGWRT = 2;
    sbit  BLBSET_bit at SPMCR.B3;
    const register unsigned short int BLBSET = 3;
    sbit  RWWSRE_bit at SPMCR.B4;
    const register unsigned short int RWWSRE = 4;
    sbit  RWWSB_bit at SPMCR.B6;
    const register unsigned short int RWWSB = 6;
    sbit  SPMIE_bit at SPMCR.B7;
    const register unsigned short int SPMIE = 7;

sfr io unsigned short volatile TWCR absolute 0x56;
    sbit  TWIE_bit at TWCR.B0;
    const register unsigned short int TWIE = 0;
    sbit  TWEN_bit at TWCR.B2;
    const register unsigned short int TWEN = 2;
    sbit  TWWC_bit at TWCR.B3;
    const register unsigned short int TWWC = 3;
    sbit  TWSTO_bit at TWCR.B4;
    const register unsigned short int TWSTO = 4;
    sbit  TWSTA_bit at TWCR.B5;
    const register unsigned short int TWSTA = 5;
    sbit  TWEA_bit at TWCR.B6;
    const register unsigned short int TWEA = 6;
    sbit  TWINT_bit at TWCR.B7;
    const register unsigned short int TWINT = 7;

sfr io unsigned short volatile MCUCR absolute 0x55;
    sbit  ISC00_bit at MCUCR.B0;
    const register unsigned short int ISC00 = 0;
    sbit  ISC01_bit at MCUCR.B1;
    const register unsigned short int ISC01 = 1;
    sbit  ISC10_bit at MCUCR.B2;
    const register unsigned short int ISC10 = 2;
    sbit  ISC11_bit at MCUCR.B3;
    const register unsigned short int ISC11 = 3;
    sbit  SM0_bit at MCUCR.B4;
    const register unsigned short int SM0 = 4;
    sbit  SM1_bit at MCUCR.B5;
    const register unsigned short int SM1 = 5;
    sbit  SM2_bit at MCUCR.B6;
    const register unsigned short int SM2 = 6;
    sbit  SE_bit at MCUCR.B7;
    const register unsigned short int SE = 7;

sfr io unsigned short volatile MCUCSR absolute 0x54;
    sbit  ISC2_bit at MCUCSR.B6;
    const register unsigned short int ISC2 = 6;
    sbit  PORF_bit at MCUCSR.B0;
    const register unsigned short int PORF = 0;
    sbit  EXTRF_bit at MCUCSR.B1;
    const register unsigned short int EXTRF = 1;
    sbit  BORF_bit at MCUCSR.B2;
    const register unsigned short int BORF = 2;
    sbit  WDRF_bit at MCUCSR.B3;
    const register unsigned short int WDRF = 3;
    sbit  JTRF_bit at MCUCSR.B4;
    const register unsigned short int JTRF = 4;
    sbit  JTD_bit at MCUCSR.B7;
    const register unsigned short int JTD = 7;

sfr io unsigned short TCCR0 absolute 0x53;
    sbit  CS00_bit at TCCR0.B0;
    const register unsigned short int CS00 = 0;
    sbit  CS01_bit at TCCR0.B1;
    const register unsigned short int CS01 = 1;
    sbit  CS02_bit at TCCR0.B2;
    const register unsigned short int CS02 = 2;
    sbit  WGM01_bit at TCCR0.B3;
    const register unsigned short int WGM01 = 3;
    sbit  COM00_bit at TCCR0.B4;
    const register unsigned short int COM00 = 4;
    sbit  COM01_bit at TCCR0.B5;
    const register unsigned short int COM01 = 5;
    sbit  WGM00_bit at TCCR0.B6;
    const register unsigned short int WGM00 = 6;
    sbit  FOC0_bit at TCCR0.B7;
    const register unsigned short int FOC0 = 7;

sfr io unsigned short volatile TCNT0 absolute 0x52;
    sbit  TCNT0_0_bit at TCNT0.B0;
    const register unsigned short int TCNT0_0 = 0;
    sbit  TCNT0_1_bit at TCNT0.B1;
    const register unsigned short int TCNT0_1 = 1;
    sbit  TCNT0_2_bit at TCNT0.B2;
    const register unsigned short int TCNT0_2 = 2;
    sbit  TCNT0_3_bit at TCNT0.B3;
    const register unsigned short int TCNT0_3 = 3;
    sbit  TCNT0_4_bit at TCNT0.B4;
    const register unsigned short int TCNT0_4 = 4;
    sbit  TCNT0_5_bit at TCNT0.B5;
    const register unsigned short int TCNT0_5 = 5;
    sbit  TCNT0_6_bit at TCNT0.B6;
    const register unsigned short int TCNT0_6 = 6;
    sbit  TCNT0_7_bit at TCNT0.B7;
    const register unsigned short int TCNT0_7 = 7;

sfr io unsigned short OSCCAL absolute 0x51;
    sbit  CAL0_bit at OSCCAL.B0;
    const register unsigned short int CAL0 = 0;
    sbit  CAL1_bit at OSCCAL.B1;
    const register unsigned short int CAL1 = 1;
    sbit  CAL2_bit at OSCCAL.B2;
    const register unsigned short int CAL2 = 2;
    sbit  CAL3_bit at OSCCAL.B3;
    const register unsigned short int CAL3 = 3;
    sbit  CAL4_bit at OSCCAL.B4;
    const register unsigned short int CAL4 = 4;
    sbit  CAL5_bit at OSCCAL.B5;
    const register unsigned short int CAL5 = 5;
    sbit  CAL6_bit at OSCCAL.B6;
    const register unsigned short int CAL6 = 6;
    sbit  CAL7_bit at OSCCAL.B7;
    const register unsigned short int CAL7 = 7;

sfr io unsigned short volatile OCDR absolute 0x51;

sfr io unsigned short volatile SFIOR absolute 0x50;
    sbit  ACME_bit at SFIOR.B3;
    const register unsigned short int ACME = 3;
    sbit  ADTS0_bit at SFIOR.B5;
    const register unsigned short int ADTS0 = 5;
    sbit  ADTS1_bit at SFIOR.B6;
    const register unsigned short int ADTS1 = 6;
    sbit  ADTS2_bit at SFIOR.B7;
    const register unsigned short int ADTS2 = 7;
    sbit  PSR10_bit at SFIOR.B0;
    const register unsigned short int PSR10 = 0;
    sbit  PSR2_bit at SFIOR.B1;
    const register unsigned short int PSR2 = 1;
    sbit  PUD_bit at SFIOR.B2;
    const register unsigned short int PUD = 2;

sfr io unsigned short TCCR1A absolute 0x4F;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM10 = 0;
    sbit  WGM11_bit at TCCR1A.B1;
    const register unsigned short int WGM11 = 1;
    sbit  FOC1B_bit at TCCR1A.B2;
    const register unsigned short int FOC1B = 2;
    sbit  FOC1A_bit at TCCR1A.B3;
    const register unsigned short int FOC1A = 3;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1A1 = 7;

sfr io unsigned short TCCR1B absolute 0x4E;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS10 = 0;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS11 = 1;
    sbit  CS12_bit at TCCR1B.B2;
    const register unsigned short int CS12 = 2;
    sbit  WGM12_bit at TCCR1B.B3;
    const register unsigned short int WGM12 = 3;
    sbit  WGM13_bit at TCCR1B.B4;
    const register unsigned short int WGM13 = 4;
    sbit  ICES1_bit at TCCR1B.B6;
    const register unsigned short int ICES1 = 6;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICNC1 = 7;

sfr io unsigned short volatile TCNT1H absolute 0x4D;
    sbit  TCNT1H0_bit at TCNT1H.B0;
    const register unsigned short int TCNT1H0 = 0;
    sbit  TCNT1H1_bit at TCNT1H.B1;
    const register unsigned short int TCNT1H1 = 1;
    sbit  TCNT1H2_bit at TCNT1H.B2;
    const register unsigned short int TCNT1H2 = 2;
    sbit  TCNT1H3_bit at TCNT1H.B3;
    const register unsigned short int TCNT1H3 = 3;
    sbit  TCNT1H4_bit at TCNT1H.B4;
    const register unsigned short int TCNT1H4 = 4;
    sbit  TCNT1H5_bit at TCNT1H.B5;
    const register unsigned short int TCNT1H5 = 5;
    sbit  TCNT1H6_bit at TCNT1H.B6;
    const register unsigned short int TCNT1H6 = 6;
    sbit  TCNT1H7_bit at TCNT1H.B7;
    const register unsigned short int TCNT1H7 = 7;

sfr io unsigned short volatile TCNT1L absolute 0x4C;
    sbit  TCNT1L0_bit at TCNT1L.B0;
    const register unsigned short int TCNT1L0 = 0;
    sbit  TCNT1L1_bit at TCNT1L.B1;
    const register unsigned short int TCNT1L1 = 1;
    sbit  TCNT1L2_bit at TCNT1L.B2;
    const register unsigned short int TCNT1L2 = 2;
    sbit  TCNT1L3_bit at TCNT1L.B3;
    const register unsigned short int TCNT1L3 = 3;
    sbit  TCNT1L4_bit at TCNT1L.B4;
    const register unsigned short int TCNT1L4 = 4;
    sbit  TCNT1L5_bit at TCNT1L.B5;
    const register unsigned short int TCNT1L5 = 5;
    sbit  TCNT1L6_bit at TCNT1L.B6;
    const register unsigned short int TCNT1L6 = 6;
    sbit  TCNT1L7_bit at TCNT1L.B7;
    const register unsigned short int TCNT1L7 = 7;

sfr io unsigned short OCR1AH absolute 0x4B;
    sbit  OCR1AH0_bit at OCR1AH.B0;
    const register unsigned short int OCR1AH0 = 0;
    sbit  OCR1AH1_bit at OCR1AH.B1;
    const register unsigned short int OCR1AH1 = 1;
    sbit  OCR1AH2_bit at OCR1AH.B2;
    const register unsigned short int OCR1AH2 = 2;
    sbit  OCR1AH3_bit at OCR1AH.B3;
    const register unsigned short int OCR1AH3 = 3;
    sbit  OCR1AH4_bit at OCR1AH.B4;
    const register unsigned short int OCR1AH4 = 4;
    sbit  OCR1AH5_bit at OCR1AH.B5;
    const register unsigned short int OCR1AH5 = 5;
    sbit  OCR1AH6_bit at OCR1AH.B6;
    const register unsigned short int OCR1AH6 = 6;
    sbit  OCR1AH7_bit at OCR1AH.B7;
    const register unsigned short int OCR1AH7 = 7;

sfr io unsigned short OCR1AL absolute 0x4A;
    sbit  OCR1AL0_bit at OCR1AL.B0;
    const register unsigned short int OCR1AL0 = 0;
    sbit  OCR1AL1_bit at OCR1AL.B1;
    const register unsigned short int OCR1AL1 = 1;
    sbit  OCR1AL2_bit at OCR1AL.B2;
    const register unsigned short int OCR1AL2 = 2;
    sbit  OCR1AL3_bit at OCR1AL.B3;
    const register unsigned short int OCR1AL3 = 3;
    sbit  OCR1AL4_bit at OCR1AL.B4;
    const register unsigned short int OCR1AL4 = 4;
    sbit  OCR1AL5_bit at OCR1AL.B5;
    const register unsigned short int OCR1AL5 = 5;
    sbit  OCR1AL6_bit at OCR1AL.B6;
    const register unsigned short int OCR1AL6 = 6;
    sbit  OCR1AL7_bit at OCR1AL.B7;
    const register unsigned short int OCR1AL7 = 7;

sfr io unsigned short OCR1BH absolute 0x49;
    sbit  OCR1BH0_bit at OCR1BH.B0;
    const register unsigned short int OCR1BH0 = 0;
    sbit  OCR1BH1_bit at OCR1BH.B1;
    const register unsigned short int OCR1BH1 = 1;
    sbit  OCR1BH2_bit at OCR1BH.B2;
    const register unsigned short int OCR1BH2 = 2;
    sbit  OCR1BH3_bit at OCR1BH.B3;
    const register unsigned short int OCR1BH3 = 3;
    sbit  OCR1BH4_bit at OCR1BH.B4;
    const register unsigned short int OCR1BH4 = 4;
    sbit  OCR1BH5_bit at OCR1BH.B5;
    const register unsigned short int OCR1BH5 = 5;
    sbit  OCR1BH6_bit at OCR1BH.B6;
    const register unsigned short int OCR1BH6 = 6;
    sbit  OCR1BH7_bit at OCR1BH.B7;
    const register unsigned short int OCR1BH7 = 7;

sfr io unsigned short OCR1BL absolute 0x48;
    sbit  OCR1BL0_bit at OCR1BL.B0;
    const register unsigned short int OCR1BL0 = 0;
    sbit  OCR1BL1_bit at OCR1BL.B1;
    const register unsigned short int OCR1BL1 = 1;
    sbit  OCR1BL2_bit at OCR1BL.B2;
    const register unsigned short int OCR1BL2 = 2;
    sbit  OCR1BL3_bit at OCR1BL.B3;
    const register unsigned short int OCR1BL3 = 3;
    sbit  OCR1BL4_bit at OCR1BL.B4;
    const register unsigned short int OCR1BL4 = 4;
    sbit  OCR1BL5_bit at OCR1BL.B5;
    const register unsigned short int OCR1BL5 = 5;
    sbit  OCR1BL6_bit at OCR1BL.B6;
    const register unsigned short int OCR1BL6 = 6;
    sbit  OCR1BL7_bit at OCR1BL.B7;
    const register unsigned short int OCR1BL7 = 7;

sfr io unsigned short volatile ICR1H absolute 0x47;
    sbit  ICR1H0_bit at ICR1H.B0;
    const register unsigned short int ICR1H0 = 0;
    sbit  ICR1H1_bit at ICR1H.B1;
    const register unsigned short int ICR1H1 = 1;
    sbit  ICR1H2_bit at ICR1H.B2;
    const register unsigned short int ICR1H2 = 2;
    sbit  ICR1H3_bit at ICR1H.B3;
    const register unsigned short int ICR1H3 = 3;
    sbit  ICR1H4_bit at ICR1H.B4;
    const register unsigned short int ICR1H4 = 4;
    sbit  ICR1H5_bit at ICR1H.B5;
    const register unsigned short int ICR1H5 = 5;
    sbit  ICR1H6_bit at ICR1H.B6;
    const register unsigned short int ICR1H6 = 6;
    sbit  ICR1H7_bit at ICR1H.B7;
    const register unsigned short int ICR1H7 = 7;

sfr io unsigned short volatile ICR1L absolute 0x46;
    sbit  ICR1L0_bit at ICR1L.B0;
    const register unsigned short int ICR1L0 = 0;
    sbit  ICR1L1_bit at ICR1L.B1;
    const register unsigned short int ICR1L1 = 1;
    sbit  ICR1L2_bit at ICR1L.B2;
    const register unsigned short int ICR1L2 = 2;
    sbit  ICR1L3_bit at ICR1L.B3;
    const register unsigned short int ICR1L3 = 3;
    sbit  ICR1L4_bit at ICR1L.B4;
    const register unsigned short int ICR1L4 = 4;
    sbit  ICR1L5_bit at ICR1L.B5;
    const register unsigned short int ICR1L5 = 5;
    sbit  ICR1L6_bit at ICR1L.B6;
    const register unsigned short int ICR1L6 = 6;
    sbit  ICR1L7_bit at ICR1L.B7;
    const register unsigned short int ICR1L7 = 7;

sfr io unsigned short volatile TCCR2 absolute 0x45;
    sbit  CS20_bit at TCCR2.B0;
    const register unsigned short int CS20 = 0;
    sbit  CS21_bit at TCCR2.B1;
    const register unsigned short int CS21 = 1;
    sbit  CS22_bit at TCCR2.B2;
    const register unsigned short int CS22 = 2;
    sbit  WGM21_bit at TCCR2.B3;
    const register unsigned short int WGM21 = 3;
    sbit  COM20_bit at TCCR2.B4;
    const register unsigned short int COM20 = 4;
    sbit  COM21_bit at TCCR2.B5;
    const register unsigned short int COM21 = 5;
    sbit  WGM20_bit at TCCR2.B6;
    const register unsigned short int WGM20 = 6;
    sbit  FOC2_bit at TCCR2.B7;
    const register unsigned short int FOC2 = 7;

sfr io unsigned short volatile TCNT2 absolute 0x44;
    sbit  TCNT2_0_bit at TCNT2.B0;
    const register unsigned short int TCNT2_0 = 0;
    sbit  TCNT2_1_bit at TCNT2.B1;
    const register unsigned short int TCNT2_1 = 1;
    sbit  TCNT2_2_bit at TCNT2.B2;
    const register unsigned short int TCNT2_2 = 2;
    sbit  TCNT2_3_bit at TCNT2.B3;
    const register unsigned short int TCNT2_3 = 3;
    sbit  TCNT2_4_bit at TCNT2.B4;
    const register unsigned short int TCNT2_4 = 4;
    sbit  TCNT2_5_bit at TCNT2.B5;
    const register unsigned short int TCNT2_5 = 5;
    sbit  TCNT2_6_bit at TCNT2.B6;
    const register unsigned short int TCNT2_6 = 6;
    sbit  TCNT2_7_bit at TCNT2.B7;
    const register unsigned short int TCNT2_7 = 7;

sfr io unsigned short OCR2 absolute 0x43;
    sbit  OCR2_0_bit at OCR2.B0;
    const register unsigned short int OCR2_0 = 0;
    sbit  OCR2_1_bit at OCR2.B1;
    const register unsigned short int OCR2_1 = 1;
    sbit  OCR2_2_bit at OCR2.B2;
    const register unsigned short int OCR2_2 = 2;
    sbit  OCR2_3_bit at OCR2.B3;
    const register unsigned short int OCR2_3 = 3;
    sbit  OCR2_4_bit at OCR2.B4;
    const register unsigned short int OCR2_4 = 4;
    sbit  OCR2_5_bit at OCR2.B5;
    const register unsigned short int OCR2_5 = 5;
    sbit  OCR2_6_bit at OCR2.B6;
    const register unsigned short int OCR2_6 = 6;
    sbit  OCR2_7_bit at OCR2.B7;
    const register unsigned short int OCR2_7 = 7;

sfr io unsigned short volatile ASSR absolute 0x42;
    sbit  TCR2UB_bit at ASSR.B0;
    const register unsigned short int TCR2UB = 0;
    sbit  OCR2UB_bit at ASSR.B1;
    const register unsigned short int OCR2UB = 1;
    sbit  TCN2UB_bit at ASSR.B2;
    const register unsigned short int TCN2UB = 2;
    sbit  AS2_bit at ASSR.B3;
    const register unsigned short int AS2 = 3;

sfr io unsigned short volatile WDTCR absolute 0x41;
    sbit  WDP0_bit at WDTCR.B0;
    const register unsigned short int WDP0 = 0;
    sbit  WDP1_bit at WDTCR.B1;
    const register unsigned short int WDP1 = 1;
    sbit  WDP2_bit at WDTCR.B2;
    const register unsigned short int WDP2 = 2;
    sbit  WDE_bit at WDTCR.B3;
    const register unsigned short int WDE = 3;
    sbit  WDTOE_bit at WDTCR.B4;
    const register unsigned short int WDTOE = 4;

sfr io unsigned short UBRRH absolute 0x40;
    sbit  UBRR8_bit at UBRRH.B0;
    const register unsigned short int UBRR8 = 0;
    sbit  UBRR9_bit at UBRRH.B1;
    const register unsigned short int UBRR9 = 1;
    sbit  UBRR10_bit at UBRRH.B2;
    const register unsigned short int UBRR10 = 2;
    sbit  UBRR11_bit at UBRRH.B3;
    const register unsigned short int UBRR11 = 3;

sfr io unsigned short volatile UCSR0C absolute 0x40;
sfr io unsigned short volatile UCSRC absolute 0x40;
    sbit  UCPOL_bit at UCSRC.B0;
    const register unsigned short int UCPOL = 0;
    sbit  UCSZ0_bit at UCSRC.B1;
    const register unsigned short int UCSZ0 = 1;
    sbit  UCSZ1_bit at UCSRC.B2;
    const register unsigned short int UCSZ1 = 2;
    sbit  USBS_bit at UCSRC.B3;
    const register unsigned short int USBS = 3;
    sbit  UPM0_bit at UCSRC.B4;
    const register unsigned short int UPM0 = 4;
    sbit  UPM1_bit at UCSRC.B5;
    const register unsigned short int UPM1 = 5;
    sbit  UMSEL_bit at UCSRC.B6;
    const register unsigned short int UMSEL = 6;
    sbit  URSEL_bit at UCSRC.B7;
    const register unsigned short int URSEL = 7;

sfr io unsigned short EEARH absolute 0x3F;
    sbit  EEAR8_bit at EEARH.B0;
    const register unsigned short int EEAR8 = 0;
    sbit  EEAR9_bit at EEARH.B1;
    const register unsigned short int EEAR9 = 1;

sfr io unsigned short EEARL absolute 0x3E;
    sbit  EEAR00_bit at EEARL.B0;
    const register unsigned short int EEAR00 = 0;
    sbit  EEAR1_bit at EEARL.B1;
    const register unsigned short int EEAR1 = 1;
    sbit  EEAR2_bit at EEARL.B2;
    const register unsigned short int EEAR2 = 2;
    sbit  EEAR3_bit at EEARL.B3;
    const register unsigned short int EEAR3 = 3;
    sbit  EEAR4_bit at EEARL.B4;
    const register unsigned short int EEAR4 = 4;
    sbit  EEAR5_bit at EEARL.B5;
    const register unsigned short int EEAR5 = 5;
    sbit  EEAR6_bit at EEARL.B6;
    const register unsigned short int EEAR6 = 6;
    sbit  EEAR7_bit at EEARL.B7;
    const register unsigned short int EEAR7 = 7;

sfr io unsigned short volatile EEDR absolute 0x3D;
    sbit  EEDR0_bit at EEDR.B0;
    const register unsigned short int EEDR0 = 0;
    sbit  EEDR1_bit at EEDR.B1;
    const register unsigned short int EEDR1 = 1;
    sbit  EEDR2_bit at EEDR.B2;
    const register unsigned short int EEDR2 = 2;
    sbit  EEDR3_bit at EEDR.B3;
    const register unsigned short int EEDR3 = 3;
    sbit  EEDR4_bit at EEDR.B4;
    const register unsigned short int EEDR4 = 4;
    sbit  EEDR5_bit at EEDR.B5;
    const register unsigned short int EEDR5 = 5;
    sbit  EEDR6_bit at EEDR.B6;
    const register unsigned short int EEDR6 = 6;
    sbit  EEDR7_bit at EEDR.B7;
    const register unsigned short int EEDR7 = 7;

sfr io unsigned short volatile EECR absolute 0x3C;
    sbit  EERE_bit at EECR.B0;
    const register unsigned short int EERE = 0;
    sbit  EEWE_bit at EECR.B1;
    const register unsigned short int EEWE = 1;
    sbit  EEMWE_bit at EECR.B2;
    const register unsigned short int EEMWE = 2;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EERIE = 3;

sfr io unsigned short PORTA absolute 0x3B;
    sbit  PORTA0_bit at PORTA.B0;
    const register unsigned short int PORTA0 = 0;
    sbit  PORTA1_bit at PORTA.B1;
    const register unsigned short int PORTA1 = 1;
    sbit  PORTA2_bit at PORTA.B2;
    const register unsigned short int PORTA2 = 2;
    sbit  PORTA3_bit at PORTA.B3;
    const register unsigned short int PORTA3 = 3;
    sbit  PORTA4_bit at PORTA.B4;
    const register unsigned short int PORTA4 = 4;
    sbit  PORTA5_bit at PORTA.B5;
    const register unsigned short int PORTA5 = 5;
    sbit  PORTA6_bit at PORTA.B6;
    const register unsigned short int PORTA6 = 6;
    sbit  PORTA7_bit at PORTA.B7;
    const register unsigned short int PORTA7 = 7;

sfr io unsigned short DDRA absolute 0x3A;
    sbit  DDA0_bit at DDRA.B0;
    const register unsigned short int DDA0 = 0;
    sbit  DDA1_bit at DDRA.B1;
    const register unsigned short int DDA1 = 1;
    sbit  DDA2_bit at DDRA.B2;
    const register unsigned short int DDA2 = 2;
    sbit  DDA3_bit at DDRA.B3;
    const register unsigned short int DDA3 = 3;
    sbit  DDA4_bit at DDRA.B4;
    const register unsigned short int DDA4 = 4;
    sbit  DDA5_bit at DDRA.B5;
    const register unsigned short int DDA5 = 5;
    sbit  DDA6_bit at DDRA.B6;
    const register unsigned short int DDA6 = 6;
    sbit  DDA7_bit at DDRA.B7;
    const register unsigned short int DDA7 = 7;

sfr io unsigned short volatile PINA absolute 0x39;
    sbit  PINA0_bit at PINA.B0;
    const register unsigned short int PINA0 = 0;
    sbit  PINA1_bit at PINA.B1;
    const register unsigned short int PINA1 = 1;
    sbit  PINA2_bit at PINA.B2;
    const register unsigned short int PINA2 = 2;
    sbit  PINA3_bit at PINA.B3;
    const register unsigned short int PINA3 = 3;
    sbit  PINA4_bit at PINA.B4;
    const register unsigned short int PINA4 = 4;
    sbit  PINA5_bit at PINA.B5;
    const register unsigned short int PINA5 = 5;
    sbit  PINA6_bit at PINA.B6;
    const register unsigned short int PINA6 = 6;
    sbit  PINA7_bit at PINA.B7;
    const register unsigned short int PINA7 = 7;

sfr io unsigned short PORTB absolute 0x38;
    sbit  PORTB0_bit at PORTB.B0;
    const register unsigned short int PORTB0 = 0;
    sbit  PORTB1_bit at PORTB.B1;
    const register unsigned short int PORTB1 = 1;
    sbit  PORTB2_bit at PORTB.B2;
    const register unsigned short int PORTB2 = 2;
    sbit  PORTB3_bit at PORTB.B3;
    const register unsigned short int PORTB3 = 3;
    sbit  PORTB4_bit at PORTB.B4;
    const register unsigned short int PORTB4 = 4;
    sbit  PORTB5_bit at PORTB.B5;
    const register unsigned short int PORTB5 = 5;
    sbit  PORTB6_bit at PORTB.B6;
    const register unsigned short int PORTB6 = 6;
    sbit  PORTB7_bit at PORTB.B7;
    const register unsigned short int PORTB7 = 7;

sfr io unsigned short DDRB absolute 0x37;
    sbit  DDB0_bit at DDRB.B0;
    const register unsigned short int DDB0 = 0;
    sbit  DDB1_bit at DDRB.B1;
    const register unsigned short int DDB1 = 1;
    sbit  DDB2_bit at DDRB.B2;
    const register unsigned short int DDB2 = 2;
    sbit  DDB3_bit at DDRB.B3;
    const register unsigned short int DDB3 = 3;
    sbit  DDB4_bit at DDRB.B4;
    const register unsigned short int DDB4 = 4;
    sbit  DDB5_bit at DDRB.B5;
    const register unsigned short int DDB5 = 5;
    sbit  DDB6_bit at DDRB.B6;
    const register unsigned short int DDB6 = 6;
    sbit  DDB7_bit at DDRB.B7;
    const register unsigned short int DDB7 = 7;

sfr io unsigned short volatile PINB absolute 0x36;
    sbit  PINB0_bit at PINB.B0;
    const register unsigned short int PINB0 = 0;
    sbit  PINB1_bit at PINB.B1;
    const register unsigned short int PINB1 = 1;
    sbit  PINB2_bit at PINB.B2;
    const register unsigned short int PINB2 = 2;
    sbit  PINB3_bit at PINB.B3;
    const register unsigned short int PINB3 = 3;
    sbit  PINB4_bit at PINB.B4;
    const register unsigned short int PINB4 = 4;
    sbit  PINB5_bit at PINB.B5;
    const register unsigned short int PINB5 = 5;
    sbit  PINB6_bit at PINB.B6;
    const register unsigned short int PINB6 = 6;
    sbit  PINB7_bit at PINB.B7;
    const register unsigned short int PINB7 = 7;

sfr io unsigned short PORTC absolute 0x35;
    sbit  PORTC0_bit at PORTC.B0;
    const register unsigned short int PORTC0 = 0;
    sbit  PORTC1_bit at PORTC.B1;
    const register unsigned short int PORTC1 = 1;
    sbit  PORTC2_bit at PORTC.B2;
    const register unsigned short int PORTC2 = 2;
    sbit  PORTC3_bit at PORTC.B3;
    const register unsigned short int PORTC3 = 3;
    sbit  PORTC4_bit at PORTC.B4;
    const register unsigned short int PORTC4 = 4;
    sbit  PORTC5_bit at PORTC.B5;
    const register unsigned short int PORTC5 = 5;
    sbit  PORTC6_bit at PORTC.B6;
    const register unsigned short int PORTC6 = 6;
    sbit  PORTC7_bit at PORTC.B7;
    const register unsigned short int PORTC7 = 7;

sfr io unsigned short DDRC absolute 0x34;
    sbit  DDC0_bit at DDRC.B0;
    const register unsigned short int DDC0 = 0;
    sbit  DDC1_bit at DDRC.B1;
    const register unsigned short int DDC1 = 1;
    sbit  DDC2_bit at DDRC.B2;
    const register unsigned short int DDC2 = 2;
    sbit  DDC3_bit at DDRC.B3;
    const register unsigned short int DDC3 = 3;
    sbit  DDC4_bit at DDRC.B4;
    const register unsigned short int DDC4 = 4;
    sbit  DDC5_bit at DDRC.B5;
    const register unsigned short int DDC5 = 5;
    sbit  DDC6_bit at DDRC.B6;
    const register unsigned short int DDC6 = 6;
    sbit  DDC7_bit at DDRC.B7;
    const register unsigned short int DDC7 = 7;

sfr io unsigned short volatile PINC absolute 0x33;
    sbit  PINC0_bit at PINC.B0;
    const register unsigned short int PINC0 = 0;
    sbit  PINC1_bit at PINC.B1;
    const register unsigned short int PINC1 = 1;
    sbit  PINC2_bit at PINC.B2;
    const register unsigned short int PINC2 = 2;
    sbit  PINC3_bit at PINC.B3;
    const register unsigned short int PINC3 = 3;
    sbit  PINC4_bit at PINC.B4;
    const register unsigned short int PINC4 = 4;
    sbit  PINC5_bit at PINC.B5;
    const register unsigned short int PINC5 = 5;
    sbit  PINC6_bit at PINC.B6;
    const register unsigned short int PINC6 = 6;
    sbit  PINC7_bit at PINC.B7;
    const register unsigned short int PINC7 = 7;

sfr io unsigned short PORTD absolute 0x32;
    sbit  PORTD0_bit at PORTD.B0;
    const register unsigned short int PORTD0 = 0;
    sbit  PORTD1_bit at PORTD.B1;
    const register unsigned short int PORTD1 = 1;
    sbit  PORTD2_bit at PORTD.B2;
    const register unsigned short int PORTD2 = 2;
    sbit  PORTD3_bit at PORTD.B3;
    const register unsigned short int PORTD3 = 3;
    sbit  PORTD4_bit at PORTD.B4;
    const register unsigned short int PORTD4 = 4;
    sbit  PORTD5_bit at PORTD.B5;
    const register unsigned short int PORTD5 = 5;
    sbit  PORTD6_bit at PORTD.B6;
    const register unsigned short int PORTD6 = 6;
    sbit  PORTD7_bit at PORTD.B7;
    const register unsigned short int PORTD7 = 7;

sfr io unsigned short DDRD absolute 0x31;
    sbit  DDD0_bit at DDRD.B0;
    const register unsigned short int DDD0 = 0;
    sbit  DDD1_bit at DDRD.B1;
    const register unsigned short int DDD1 = 1;
    sbit  DDD2_bit at DDRD.B2;
    const register unsigned short int DDD2 = 2;
    sbit  DDD3_bit at DDRD.B3;
    const register unsigned short int DDD3 = 3;
    sbit  DDD4_bit at DDRD.B4;
    const register unsigned short int DDD4 = 4;
    sbit  DDD5_bit at DDRD.B5;
    const register unsigned short int DDD5 = 5;
    sbit  DDD6_bit at DDRD.B6;
    const register unsigned short int DDD6 = 6;
    sbit  DDD7_bit at DDRD.B7;
    const register unsigned short int DDD7 = 7;

sfr io unsigned short volatile PIND absolute 0x30;
    sbit  PIND0_bit at PIND.B0;
    const register unsigned short int PIND0 = 0;
    sbit  PIND1_bit at PIND.B1;
    const register unsigned short int PIND1 = 1;
    sbit  PIND2_bit at PIND.B2;
    const register unsigned short int PIND2 = 2;
    sbit  PIND3_bit at PIND.B3;
    const register unsigned short int PIND3 = 3;
    sbit  PIND4_bit at PIND.B4;
    const register unsigned short int PIND4 = 4;
    sbit  PIND5_bit at PIND.B5;
    const register unsigned short int PIND5 = 5;
    sbit  PIND6_bit at PIND.B6;
    const register unsigned short int PIND6 = 6;
    sbit  PIND7_bit at PIND.B7;
    const register unsigned short int PIND7 = 7;

sfr io unsigned short volatile SPDR absolute 0x2F;
    sbit  SPDR0_bit at SPDR.B0;
    const register unsigned short int SPDR0 = 0;
    sbit  SPDR1_bit at SPDR.B1;
    const register unsigned short int SPDR1 = 1;
    sbit  SPDR2_bit at SPDR.B2;
    const register unsigned short int SPDR2 = 2;
    sbit  SPDR3_bit at SPDR.B3;
    const register unsigned short int SPDR3 = 3;
    sbit  SPDR4_bit at SPDR.B4;
    const register unsigned short int SPDR4 = 4;
    sbit  SPDR5_bit at SPDR.B5;
    const register unsigned short int SPDR5 = 5;
    sbit  SPDR6_bit at SPDR.B6;
    const register unsigned short int SPDR6 = 6;
    sbit  SPDR7_bit at SPDR.B7;
    const register unsigned short int SPDR7 = 7;

sfr io unsigned short volatile SPSR absolute 0x2E;
    sbit  SPI2X_bit at SPSR.B0;
    const register unsigned short int SPI2X = 0;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int WCOL = 6;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int SPIF = 7;

sfr io unsigned short SPCR absolute 0x2D;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR0 = 0;
    sbit  SPR1_bit at SPCR.B1;
    const register unsigned short int SPR1 = 1;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int CPHA = 2;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPOL = 3;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int MSTR = 4;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int DORD = 5;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int SPE = 6;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPIE = 7;

sfr io unsigned short volatile UDR0 absolute 0x2C;
sfr io unsigned short volatile UDR absolute 0x2C;
    sbit  UDR0__bit at UDR.B0;
    const register unsigned short int UDR0_ = 0;
    sbit  UDR1_bit at UDR.B1;
    const register unsigned short int UDR1 = 1;
    sbit  UDR2_bit at UDR.B2;
    const register unsigned short int UDR2 = 2;
    sbit  UDR3_bit at UDR.B3;
    const register unsigned short int UDR3 = 3;
    sbit  UDR4_bit at UDR.B4;
    const register unsigned short int UDR4 = 4;
    sbit  UDR5_bit at UDR.B5;
    const register unsigned short int UDR5 = 5;
    sbit  UDR6_bit at UDR.B6;
    const register unsigned short int UDR6 = 6;
    sbit  UDR7_bit at UDR.B7;
    const register unsigned short int UDR7 = 7;

sfr io unsigned short volatile UCSRA absolute 0x2B;
    sbit  MPCM_bit at UCSRA.B0;
    const register unsigned short int MPCM = 0;
    sbit  U2X_bit at UCSRA.B1;
    const register unsigned short int U2X = 1;
    sbit  UPE_bit at UCSRA.B2;
    const register unsigned short int UPE = 2;
    sbit  DOR_bit at UCSRA.B3;
    const register unsigned short int DOR = 3;
    sbit  FE_bit at UCSRA.B4;
    const register unsigned short int FE = 4;
    sbit  UDRE0_bit at UCSRA.B5;
    const register unsigned short int UDRE0 = 5;
    sbit  UDRE_bit at UCSRA.B5;
    const register unsigned short int UDRE = 5;
    sbit  TXC0_bit at UCSRA.B6;
    const register unsigned short int TXC0 = 6;
    sbit  TXC_bit at UCSRA.B6;
    const register unsigned short int TXC = 6;
    sbit  RXC0_bit at UCSRA.B7;
    const register unsigned short int RXC0 = 7;
    sbit  RXC_bit at UCSRA.B7;
    const register unsigned short int RXC = 7;

sfr io unsigned short volatile UCSR0B absolute 0x2A;
sfr io unsigned short volatile UCSRB absolute 0x2A;
    sbit  TXB8_bit at UCSRB.B0;
    const register unsigned short int TXB8 = 0;
    sbit  RXB8_bit at UCSRB.B1;
    const register unsigned short int RXB8 = 1;
    sbit  UCSZ2_bit at UCSRB.B2;
    const register unsigned short int UCSZ2 = 2;
    sbit  TXEN_bit at UCSRB.B3;
    const register unsigned short int TXEN = 3;
    sbit  RXEN_bit at UCSRB.B4;
    const register unsigned short int RXEN = 4;
    sbit  UDRIE_bit at UCSRB.B5;
    const register unsigned short int UDRIE = 5;
    sbit  TXCIE_bit at UCSRB.B6;
    const register unsigned short int TXCIE = 6;
    sbit  RXCIE_bit at UCSRB.B7;
    const register unsigned short int RXCIE = 7;

sfr io unsigned short UBRRL absolute 0x29;
    sbit  UBRR0_bit at UBRRL.B0;
    const register unsigned short int UBRR0 = 0;
    sbit  UBRR1_bit at UBRRL.B1;
    const register unsigned short int UBRR1 = 1;
    sbit  UBRR2_bit at UBRRL.B2;
    const register unsigned short int UBRR2 = 2;
    sbit  UBRR3_bit at UBRRL.B3;
    const register unsigned short int UBRR3 = 3;
    sbit  UBRR4_bit at UBRRL.B4;
    const register unsigned short int UBRR4 = 4;
    sbit  UBRR5_bit at UBRRL.B5;
    const register unsigned short int UBRR5 = 5;
    sbit  UBRR6_bit at UBRRL.B6;
    const register unsigned short int UBRR6 = 6;
    sbit  UBRR7_bit at UBRRL.B7;
    const register unsigned short int UBRR7 = 7;

sfr io unsigned short volatile ACSR absolute 0x28;
    sbit  ACIS0_bit at ACSR.B0;
    const register unsigned short int ACIS0 = 0;
    sbit  ACIS1_bit at ACSR.B1;
    const register unsigned short int ACIS1 = 1;
    sbit  ACIC_bit at ACSR.B2;
    const register unsigned short int ACIC = 2;
    sbit  ACIE_bit at ACSR.B3;
    const register unsigned short int ACIE = 3;
    sbit  ACI_bit at ACSR.B4;
    const register unsigned short int ACI = 4;
    sbit  ACO_bit at ACSR.B5;
    const register unsigned short int ACO = 5;
    sbit  ACBG_bit at ACSR.B6;
    const register unsigned short int ACBG = 6;
    sbit  ACD_bit at ACSR.B7;
    const register unsigned short int ACD = 7;

sfr io unsigned short ADMUX absolute 0x27;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX0 = 0;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX1 = 1;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX2 = 2;
    sbit  MUX3_bit at ADMUX.B3;
    const register unsigned short int MUX3 = 3;
    sbit  MUX4_bit at ADMUX.B4;
    const register unsigned short int MUX4 = 4;
    sbit  ADLAR_bit at ADMUX.B5;
    const register unsigned short int ADLAR = 5;
    sbit  REFS0_bit at ADMUX.B6;
    const register unsigned short int REFS0 = 6;
    sbit  REFS1_bit at ADMUX.B7;
    const register unsigned short int REFS1 = 7;

sfr io unsigned short volatile ADCSRA absolute 0x26;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS2_bit at ADCSRA.B2;
    const register unsigned short int ADPS2 = 2;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADIE = 3;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIF = 4;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADATE = 5;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADSC = 6;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADEN = 7;

sfr io unsigned short volatile ADCH absolute 0x25;
    sbit  ADCH0_bit at ADCH.B0;
    const register unsigned short int ADCH0 = 0;
    sbit  ADCH1_bit at ADCH.B1;
    const register unsigned short int ADCH1 = 1;
    sbit  ADCH2_bit at ADCH.B2;
    const register unsigned short int ADCH2 = 2;
    sbit  ADCH3_bit at ADCH.B3;
    const register unsigned short int ADCH3 = 3;
    sbit  ADCH4_bit at ADCH.B4;
    const register unsigned short int ADCH4 = 4;
    sbit  ADCH5_bit at ADCH.B5;
    const register unsigned short int ADCH5 = 5;
    sbit  ADCH6_bit at ADCH.B6;
    const register unsigned short int ADCH6 = 6;
    sbit  ADCH7_bit at ADCH.B7;
    const register unsigned short int ADCH7 = 7;

sfr io unsigned short volatile ADCL absolute 0x24;
    sbit  ADCL0_bit at ADCL.B0;
    const register unsigned short int ADCL0 = 0;
    sbit  ADCL1_bit at ADCL.B1;
    const register unsigned short int ADCL1 = 1;
    sbit  ADCL2_bit at ADCL.B2;
    const register unsigned short int ADCL2 = 2;
    sbit  ADCL3_bit at ADCL.B3;
    const register unsigned short int ADCL3 = 3;
    sbit  ADCL4_bit at ADCL.B4;
    const register unsigned short int ADCL4 = 4;
    sbit  ADCL5_bit at ADCL.B5;
    const register unsigned short int ADCL5 = 5;
    sbit  ADCL6_bit at ADCL.B6;
    const register unsigned short int ADCL6 = 6;
    sbit  ADCL7_bit at ADCL.B7;
    const register unsigned short int ADCL7 = 7;

sfr io unsigned short volatile TWDR absolute 0x23;
    sbit  TWD0_bit at TWDR.B0;
    const register unsigned short int TWD0 = 0;
    sbit  TWD1_bit at TWDR.B1;
    const register unsigned short int TWD1 = 1;
    sbit  TWD2_bit at TWDR.B2;
    const register unsigned short int TWD2 = 2;
    sbit  TWD3_bit at TWDR.B3;
    const register unsigned short int TWD3 = 3;
    sbit  TWD4_bit at TWDR.B4;
    const register unsigned short int TWD4 = 4;
    sbit  TWD5_bit at TWDR.B5;
    const register unsigned short int TWD5 = 5;
    sbit  TWD6_bit at TWDR.B6;
    const register unsigned short int TWD6 = 6;
    sbit  TWD7_bit at TWDR.B7;
    const register unsigned short int TWD7 = 7;

sfr io unsigned short TWAR absolute 0x22;
    sbit  TWGCE_bit at TWAR.B0;
    const register unsigned short int TWGCE = 0;
    sbit  TWA0_bit at TWAR.B1;
    const register unsigned short int TWA0 = 1;
    sbit  TWA1_bit at TWAR.B2;
    const register unsigned short int TWA1 = 2;
    sbit  TWA2_bit at TWAR.B3;
    const register unsigned short int TWA2 = 3;
    sbit  TWA3_bit at TWAR.B4;
    const register unsigned short int TWA3 = 4;
    sbit  TWA4_bit at TWAR.B5;
    const register unsigned short int TWA4 = 5;
    sbit  TWA5_bit at TWAR.B6;
    const register unsigned short int TWA5 = 6;
    sbit  TWA6_bit at TWAR.B7;
    const register unsigned short int TWA6 = 7;

sfr io unsigned short volatile TWSR absolute 0x21;
    sbit  TWPS0_bit at TWSR.B0;
    const register unsigned short int TWPS0 = 0;
    sbit  TWPS1_bit at TWSR.B1;
    const register unsigned short int TWPS1 = 1;
    sbit  TWS3_bit at TWSR.B3;
    const register unsigned short int TWS3 = 3;
    sbit  TWS4_bit at TWSR.B4;
    const register unsigned short int TWS4 = 4;
    sbit  TWS5_bit at TWSR.B5;
    const register unsigned short int TWS5 = 5;
    sbit  TWS6_bit at TWSR.B6;
    const register unsigned short int TWS6 = 6;
    sbit  TWS7_bit at TWSR.B7;
    const register unsigned short int TWS7 = 7;

sfr io unsigned short TWBR absolute 0x20;
    sbit  TWBR0_bit at TWBR.B0;
    const register unsigned short int TWBR0 = 0;
    sbit  TWBR1_bit at TWBR.B1;
    const register unsigned short int TWBR1 = 1;
    sbit  TWBR2_bit at TWBR.B2;
    const register unsigned short int TWBR2 = 2;
    sbit  TWBR3_bit at TWBR.B3;
    const register unsigned short int TWBR3 = 3;
    sbit  TWBR4_bit at TWBR.B4;
    const register unsigned short int TWBR4 = 4;
    sbit  TWBR5_bit at TWBR.B5;
    const register unsigned short int TWBR5 = 5;
    sbit  TWBR6_bit at TWBR.B6;
    const register unsigned short int TWBR6 = 6;
    sbit  TWBR7_bit at TWBR.B7;
    const register unsigned short int TWBR7 = 7;
