// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00010000;

// Flash page size in program words
const int __FLASH_PAGE_SIZE = 128;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;

const unsigned int IVT_ADDR_RESET            = 0x0000;
const unsigned int IVT_ADDR_ANACOMP0         = 0x0002;
const unsigned int IVT_ADDR_ANACOMP1         = 0x0004;
const unsigned int IVT_ADDR_ANACOMP2         = 0x0006;
const unsigned int IVT_ADDR_ANACOMP3         = 0x0008;
const unsigned int IVT_ADDR_PSC_FAULT        = 0x000A;
const unsigned int IVT_ADDR_PSC_EC           = 0x000C;
const unsigned int IVT_ADDR_INT0             = 0x000E;
const unsigned int IVT_ADDR_INT1             = 0x0010;
const unsigned int IVT_ADDR_INT2             = 0x0012;
const unsigned int IVT_ADDR_INT3             = 0x0014;
const unsigned int IVT_ADDR_TIMER1_CAPT      = 0x0016;
const unsigned int IVT_ADDR_TIMER1_COMPA     = 0x0018;
const unsigned int IVT_ADDR_TIMER1_COMPB     = 0x001A;
const unsigned int IVT_ADDR_TIMER1_OVF       = 0x001C;
const unsigned int IVT_ADDR_TIMER0_COMPA     = 0x001E;
const unsigned int IVT_ADDR_TIMER0_COMPB     = 0x0020;
const unsigned int IVT_ADDR_TIMER0_OVF       = 0x0022;
const unsigned int IVT_ADDR_CAN_INT          = 0x0024;
const unsigned int IVT_ADDR_CAN_TOVF         = 0x0026;
const unsigned int IVT_ADDR_LIN_TC           = 0x0028;
const unsigned int IVT_ADDR_LIN_ERR          = 0x002A;
const unsigned int IVT_ADDR_PCINT0           = 0x002C;
const unsigned int IVT_ADDR_PCINT1           = 0x002E;
const unsigned int IVT_ADDR_PCINT2           = 0x0030;
const unsigned int IVT_ADDR_PCINT3           = 0x0032;
const unsigned int IVT_ADDR_SPI__STC         = 0x0034;
const unsigned int IVT_ADDR_ADC              = 0x0036;
const unsigned int IVT_ADDR_WDT              = 0x0038;
const unsigned int IVT_ADDR_EE_READY         = 0x003A;
const unsigned int IVT_ADDR_SPM_READY        = 0x003C;


sfr data unsigned short volatile CANMSG absolute 0xFA;
    sbit  MSG0_bit at CANMSG.B0;
    const register unsigned short int MSG0 = 0;
    sbit  MSG1_bit at CANMSG.B1;
    const register unsigned short int MSG1 = 1;
    sbit  MSG2_bit at CANMSG.B2;
    const register unsigned short int MSG2 = 2;
    sbit  MSG3_bit at CANMSG.B3;
    const register unsigned short int MSG3 = 3;
    sbit  MSG4_bit at CANMSG.B4;
    const register unsigned short int MSG4 = 4;
    sbit  MSG5_bit at CANMSG.B5;
    const register unsigned short int MSG5 = 5;
    sbit  MSG6_bit at CANMSG.B6;
    const register unsigned short int MSG6 = 6;
    sbit  MSG7_bit at CANMSG.B7;
    const register unsigned short int MSG7 = 7;

sfr data unsigned short volatile CANSTMH absolute 0xF9;
    sbit  TIMSTM8_bit at CANSTMH.B0;
    const register unsigned short int TIMSTM8 = 0;
    sbit  TIMSTM9_bit at CANSTMH.B1;
    const register unsigned short int TIMSTM9 = 1;
    sbit  TIMSTM10_bit at CANSTMH.B2;
    const register unsigned short int TIMSTM10 = 2;
    sbit  TIMSTM11_bit at CANSTMH.B3;
    const register unsigned short int TIMSTM11 = 3;
    sbit  TIMSTM12_bit at CANSTMH.B4;
    const register unsigned short int TIMSTM12 = 4;
    sbit  TIMSTM13_bit at CANSTMH.B5;
    const register unsigned short int TIMSTM13 = 5;
    sbit  TIMSTM14_bit at CANSTMH.B6;
    const register unsigned short int TIMSTM14 = 6;
    sbit  TIMSTM15_bit at CANSTMH.B7;
    const register unsigned short int TIMSTM15 = 7;

sfr data unsigned short volatile CANSTML absolute 0xF8;
    sbit  TIMSTM0_bit at CANSTML.B0;
    const register unsigned short int TIMSTM0 = 0;
    sbit  TIMSTM1_bit at CANSTML.B1;
    const register unsigned short int TIMSTM1 = 1;
    sbit  TIMSTM2_bit at CANSTML.B2;
    const register unsigned short int TIMSTM2 = 2;
    sbit  TIMSTM3_bit at CANSTML.B3;
    const register unsigned short int TIMSTM3 = 3;
    sbit  TIMSTM4_bit at CANSTML.B4;
    const register unsigned short int TIMSTM4 = 4;
    sbit  TIMSTM5_bit at CANSTML.B5;
    const register unsigned short int TIMSTM5 = 5;
    sbit  TIMSTM6_bit at CANSTML.B6;
    const register unsigned short int TIMSTM6 = 6;
    sbit  TIMSTM7_bit at CANSTML.B7;
    const register unsigned short int TIMSTM7 = 7;

sfr data unsigned short volatile CANIDM1 absolute 0xF7;
    sbit  IDMSK21_bit at CANIDM1.B0;
    const register unsigned short int IDMSK21 = 0;
    sbit  IDMSK22_bit at CANIDM1.B1;
    const register unsigned short int IDMSK22 = 1;
    sbit  IDMSK23_bit at CANIDM1.B2;
    const register unsigned short int IDMSK23 = 2;
    sbit  IDMSK24_bit at CANIDM1.B3;
    const register unsigned short int IDMSK24 = 3;
    sbit  IDMSK25_bit at CANIDM1.B4;
    const register unsigned short int IDMSK25 = 4;
    sbit  IDMSK26_bit at CANIDM1.B5;
    const register unsigned short int IDMSK26 = 5;
    sbit  IDMSK27_bit at CANIDM1.B6;
    const register unsigned short int IDMSK27 = 6;
    sbit  IDMSK28_bit at CANIDM1.B7;
    const register unsigned short int IDMSK28 = 7;

sfr data unsigned short volatile CANIDM2 absolute 0xF6;
    sbit  IDMSK13_bit at CANIDM2.B0;
    const register unsigned short int IDMSK13 = 0;
    sbit  IDMSK14_bit at CANIDM2.B1;
    const register unsigned short int IDMSK14 = 1;
    sbit  IDMSK15_bit at CANIDM2.B2;
    const register unsigned short int IDMSK15 = 2;
    sbit  IDMSK16_bit at CANIDM2.B3;
    const register unsigned short int IDMSK16 = 3;
    sbit  IDMSK17_bit at CANIDM2.B4;
    const register unsigned short int IDMSK17 = 4;
    sbit  IDMSK18_bit at CANIDM2.B5;
    const register unsigned short int IDMSK18 = 5;
    sbit  IDMSK19_bit at CANIDM2.B6;
    const register unsigned short int IDMSK19 = 6;
    sbit  IDMSK20_bit at CANIDM2.B7;
    const register unsigned short int IDMSK20 = 7;

sfr data unsigned short volatile CANIDM3 absolute 0xF5;
    sbit  IDMSK5_bit at CANIDM3.B0;
    const register unsigned short int IDMSK5 = 0;
    sbit  IDMSK6_bit at CANIDM3.B1;
    const register unsigned short int IDMSK6 = 1;
    sbit  IDMSK7_bit at CANIDM3.B2;
    const register unsigned short int IDMSK7 = 2;
    sbit  IDMSK8_bit at CANIDM3.B3;
    const register unsigned short int IDMSK8 = 3;
    sbit  IDMSK9_bit at CANIDM3.B4;
    const register unsigned short int IDMSK9 = 4;
    sbit  IDMSK10_bit at CANIDM3.B5;
    const register unsigned short int IDMSK10 = 5;
    sbit  IDMSK11_bit at CANIDM3.B6;
    const register unsigned short int IDMSK11 = 6;
    sbit  IDMSK12_bit at CANIDM3.B7;
    const register unsigned short int IDMSK12 = 7;

sfr data unsigned short volatile CANIDM4 absolute 0xF4;
    sbit  IDEMSK_bit at CANIDM4.B0;
    const register unsigned short int IDEMSK = 0;
    sbit  RTRMSK_bit at CANIDM4.B2;
    const register unsigned short int RTRMSK = 2;
    sbit  IDMSK0_bit at CANIDM4.B3;
    const register unsigned short int IDMSK0 = 3;
    sbit  IDMSK1_bit at CANIDM4.B4;
    const register unsigned short int IDMSK1 = 4;
    sbit  IDMSK2_bit at CANIDM4.B5;
    const register unsigned short int IDMSK2 = 5;
    sbit  IDMSK3_bit at CANIDM4.B6;
    const register unsigned short int IDMSK3 = 6;
    sbit  IDMSK4_bit at CANIDM4.B7;
    const register unsigned short int IDMSK4 = 7;

sfr data unsigned short volatile CANIDT1 absolute 0xF3;
    sbit  IDT21_bit at CANIDT1.B0;
    const register unsigned short int IDT21 = 0;
    sbit  IDT22_bit at CANIDT1.B1;
    const register unsigned short int IDT22 = 1;
    sbit  IDT23_bit at CANIDT1.B2;
    const register unsigned short int IDT23 = 2;
    sbit  IDT24_bit at CANIDT1.B3;
    const register unsigned short int IDT24 = 3;
    sbit  IDT25_bit at CANIDT1.B4;
    const register unsigned short int IDT25 = 4;
    sbit  IDT26_bit at CANIDT1.B5;
    const register unsigned short int IDT26 = 5;
    sbit  IDT27_bit at CANIDT1.B6;
    const register unsigned short int IDT27 = 6;
    sbit  IDT28_bit at CANIDT1.B7;
    const register unsigned short int IDT28 = 7;

sfr data unsigned short volatile CANIDT2 absolute 0xF2;
    sbit  IDT13_bit at CANIDT2.B0;
    const register unsigned short int IDT13 = 0;
    sbit  IDT14_bit at CANIDT2.B1;
    const register unsigned short int IDT14 = 1;
    sbit  IDT15_bit at CANIDT2.B2;
    const register unsigned short int IDT15 = 2;
    sbit  IDT16_bit at CANIDT2.B3;
    const register unsigned short int IDT16 = 3;
    sbit  IDT17_bit at CANIDT2.B4;
    const register unsigned short int IDT17 = 4;
    sbit  IDT18_bit at CANIDT2.B5;
    const register unsigned short int IDT18 = 5;
    sbit  IDT19_bit at CANIDT2.B6;
    const register unsigned short int IDT19 = 6;
    sbit  IDT20_bit at CANIDT2.B7;
    const register unsigned short int IDT20 = 7;

sfr data unsigned short volatile CANIDT3 absolute 0xF1;
    sbit  IDT5_bit at CANIDT3.B0;
    const register unsigned short int IDT5 = 0;
    sbit  IDT6_bit at CANIDT3.B1;
    const register unsigned short int IDT6 = 1;
    sbit  IDT7_bit at CANIDT3.B2;
    const register unsigned short int IDT7 = 2;
    sbit  IDT8_bit at CANIDT3.B3;
    const register unsigned short int IDT8 = 3;
    sbit  IDT9_bit at CANIDT3.B4;
    const register unsigned short int IDT9 = 4;
    sbit  IDT10_bit at CANIDT3.B5;
    const register unsigned short int IDT10 = 5;
    sbit  IDT11_bit at CANIDT3.B6;
    const register unsigned short int IDT11 = 6;
    sbit  IDT12_bit at CANIDT3.B7;
    const register unsigned short int IDT12 = 7;

sfr data unsigned short volatile CANIDT4 absolute 0xF0;
    sbit  RB0TAG_bit at CANIDT4.B0;
    const register unsigned short int RB0TAG = 0;
    sbit  RB1TAG_bit at CANIDT4.B1;
    const register unsigned short int RB1TAG = 1;
    sbit  RTRTAG_bit at CANIDT4.B2;
    const register unsigned short int RTRTAG = 2;
    sbit  IDT0_bit at CANIDT4.B3;
    const register unsigned short int IDT0 = 3;
    sbit  IDT1_bit at CANIDT4.B4;
    const register unsigned short int IDT1 = 4;
    sbit  IDT2_bit at CANIDT4.B5;
    const register unsigned short int IDT2 = 5;
    sbit  IDT3_bit at CANIDT4.B6;
    const register unsigned short int IDT3 = 6;
    sbit  IDT4_bit at CANIDT4.B7;
    const register unsigned short int IDT4 = 7;

sfr data unsigned short volatile CANCDMOB absolute 0xEF;
    sbit  DLC0_bit at CANCDMOB.B0;
    const register unsigned short int DLC0 = 0;
    sbit  DLC1_bit at CANCDMOB.B1;
    const register unsigned short int DLC1 = 1;
    sbit  DLC2_bit at CANCDMOB.B2;
    const register unsigned short int DLC2 = 2;
    sbit  DLC3_bit at CANCDMOB.B3;
    const register unsigned short int DLC3 = 3;
    sbit  IDE_bit at CANCDMOB.B4;
    const register unsigned short int IDE = 4;
    sbit  RPLV_bit at CANCDMOB.B5;
    const register unsigned short int RPLV = 5;
    sbit  CONMOB0_bit at CANCDMOB.B6;
    const register unsigned short int CONMOB0 = 6;
    sbit  CONMOB1_bit at CANCDMOB.B7;
    const register unsigned short int CONMOB1 = 7;

sfr data unsigned short volatile CANSTMOB absolute 0xEE;
    sbit  AERR_bit at CANSTMOB.B0;
    const register unsigned short int AERR = 0;
    sbit  FERR_bit at CANSTMOB.B1;
    const register unsigned short int FERR = 1;
    sbit  CERR_bit at CANSTMOB.B2;
    const register unsigned short int CERR = 2;
    sbit  SERR_bit at CANSTMOB.B3;
    const register unsigned short int SERR = 3;
    sbit  BERR_bit at CANSTMOB.B4;
    const register unsigned short int BERR = 4;
    sbit  RXOK_bit at CANSTMOB.B5;
    const register unsigned short int RXOK = 5;
    sbit  TXOK_bit at CANSTMOB.B6;
    const register unsigned short int TXOK = 6;
    sbit  DLCW_bit at CANSTMOB.B7;
    const register unsigned short int DLCW = 7;

sfr data unsigned short volatile CANPAGE absolute 0xED;
    sbit  INDX0_bit at CANPAGE.B0;
    const register unsigned short int INDX0 = 0;
    sbit  INDX1_bit at CANPAGE.B1;
    const register unsigned short int INDX1 = 1;
    sbit  INDX2_bit at CANPAGE.B2;
    const register unsigned short int INDX2 = 2;
    sbit  AINC_bit at CANPAGE.B3;
    const register unsigned short int AINC = 3;
    sbit  MOBNB0_bit at CANPAGE.B4;
    const register unsigned short int MOBNB0 = 4;
    sbit  MOBNB1_bit at CANPAGE.B5;
    const register unsigned short int MOBNB1 = 5;
    sbit  MOBNB2_bit at CANPAGE.B6;
    const register unsigned short int MOBNB2 = 6;
    sbit  MOBNB3_bit at CANPAGE.B7;
    const register unsigned short int MOBNB3 = 7;

sfr data unsigned short volatile CANHPMOB absolute 0xEC;
    sbit  CGP0_bit at CANHPMOB.B0;
    const register unsigned short int CGP0 = 0;
    sbit  CGP1_bit at CANHPMOB.B1;
    const register unsigned short int CGP1 = 1;
    sbit  CGP2_bit at CANHPMOB.B2;
    const register unsigned short int CGP2 = 2;
    sbit  CGP3_bit at CANHPMOB.B3;
    const register unsigned short int CGP3 = 3;
    sbit  HPMOB0_bit at CANHPMOB.B4;
    const register unsigned short int HPMOB0 = 4;
    sbit  HPMOB1_bit at CANHPMOB.B5;
    const register unsigned short int HPMOB1 = 5;
    sbit  HPMOB2_bit at CANHPMOB.B6;
    const register unsigned short int HPMOB2 = 6;
    sbit  HPMOB3_bit at CANHPMOB.B7;
    const register unsigned short int HPMOB3 = 7;

sfr data unsigned short volatile CANREC absolute 0xEB;
    sbit  REC0_bit at CANREC.B0;
    const register unsigned short int REC0 = 0;
    sbit  REC1_bit at CANREC.B1;
    const register unsigned short int REC1 = 1;
    sbit  REC2_bit at CANREC.B2;
    const register unsigned short int REC2 = 2;
    sbit  REC3_bit at CANREC.B3;
    const register unsigned short int REC3 = 3;
    sbit  REC4_bit at CANREC.B4;
    const register unsigned short int REC4 = 4;
    sbit  REC5_bit at CANREC.B5;
    const register unsigned short int REC5 = 5;
    sbit  REC6_bit at CANREC.B6;
    const register unsigned short int REC6 = 6;
    sbit  REC7_bit at CANREC.B7;
    const register unsigned short int REC7 = 7;

sfr data unsigned short volatile CANTEC absolute 0xEA;
    sbit  TEC0_bit at CANTEC.B0;
    const register unsigned short int TEC0 = 0;
    sbit  TEC1_bit at CANTEC.B1;
    const register unsigned short int TEC1 = 1;
    sbit  TEC2_bit at CANTEC.B2;
    const register unsigned short int TEC2 = 2;
    sbit  TEC3_bit at CANTEC.B3;
    const register unsigned short int TEC3 = 3;
    sbit  TEC4_bit at CANTEC.B4;
    const register unsigned short int TEC4 = 4;
    sbit  TEC5_bit at CANTEC.B5;
    const register unsigned short int TEC5 = 5;
    sbit  TEC6_bit at CANTEC.B6;
    const register unsigned short int TEC6 = 6;
    sbit  TEC7_bit at CANTEC.B7;
    const register unsigned short int TEC7 = 7;

sfr data unsigned short volatile CANTTCH absolute 0xE9;
    sbit  TIMTCC8_bit at CANTTCH.B0;
    const register unsigned short int TIMTCC8 = 0;
    sbit  TIMTCC9_bit at CANTTCH.B1;
    const register unsigned short int TIMTCC9 = 1;
    sbit  TIMTCC10_bit at CANTTCH.B2;
    const register unsigned short int TIMTCC10 = 2;
    sbit  TIMTCC11_bit at CANTTCH.B3;
    const register unsigned short int TIMTCC11 = 3;
    sbit  TIMTCC12_bit at CANTTCH.B4;
    const register unsigned short int TIMTCC12 = 4;
    sbit  TIMTCC13_bit at CANTTCH.B5;
    const register unsigned short int TIMTCC13 = 5;
    sbit  TIMTCC14_bit at CANTTCH.B6;
    const register unsigned short int TIMTCC14 = 6;
    sbit  TIMTCC15_bit at CANTTCH.B7;
    const register unsigned short int TIMTCC15 = 7;

sfr data unsigned short volatile CANTTCL absolute 0xE8;
    sbit  TIMTCC0_bit at CANTTCL.B0;
    const register unsigned short int TIMTCC0 = 0;
    sbit  TIMTCC1_bit at CANTTCL.B1;
    const register unsigned short int TIMTCC1 = 1;
    sbit  TIMTCC2_bit at CANTTCL.B2;
    const register unsigned short int TIMTCC2 = 2;
    sbit  TIMTCC3_bit at CANTTCL.B3;
    const register unsigned short int TIMTCC3 = 3;
    sbit  TIMTCC4_bit at CANTTCL.B4;
    const register unsigned short int TIMTCC4 = 4;
    sbit  TIMTCC5_bit at CANTTCL.B5;
    const register unsigned short int TIMTCC5 = 5;
    sbit  TIMTCC6_bit at CANTTCL.B6;
    const register unsigned short int TIMTCC6 = 6;
    sbit  TIMTCC7_bit at CANTTCL.B7;
    const register unsigned short int TIMTCC7 = 7;

sfr data unsigned short volatile CANTIMH absolute 0xE7;
    sbit  CANTIM8_bit at CANTIMH.B0;
    const register unsigned short int CANTIM8 = 0;
    sbit  CANTIM9_bit at CANTIMH.B1;
    const register unsigned short int CANTIM9 = 1;
    sbit  CANTIM10_bit at CANTIMH.B2;
    const register unsigned short int CANTIM10 = 2;
    sbit  CANTIM11_bit at CANTIMH.B3;
    const register unsigned short int CANTIM11 = 3;
    sbit  CANTIM12_bit at CANTIMH.B4;
    const register unsigned short int CANTIM12 = 4;
    sbit  CANTIM13_bit at CANTIMH.B5;
    const register unsigned short int CANTIM13 = 5;
    sbit  CANTIM14_bit at CANTIMH.B6;
    const register unsigned short int CANTIM14 = 6;
    sbit  CANTIM15_bit at CANTIMH.B7;
    const register unsigned short int CANTIM15 = 7;

sfr data unsigned short volatile CANTIML absolute 0xE6;
    sbit  CANTIM0_bit at CANTIML.B0;
    const register unsigned short int CANTIM0 = 0;
    sbit  CANTIM1_bit at CANTIML.B1;
    const register unsigned short int CANTIM1 = 1;
    sbit  CANTIM2_bit at CANTIML.B2;
    const register unsigned short int CANTIM2 = 2;
    sbit  CANTIM3_bit at CANTIML.B3;
    const register unsigned short int CANTIM3 = 3;
    sbit  CANTIM4_bit at CANTIML.B4;
    const register unsigned short int CANTIM4 = 4;
    sbit  CANTIM5_bit at CANTIML.B5;
    const register unsigned short int CANTIM5 = 5;
    sbit  CANTIM6_bit at CANTIML.B6;
    const register unsigned short int CANTIM6 = 6;
    sbit  CANTIM7_bit at CANTIML.B7;
    const register unsigned short int CANTIM7 = 7;

sfr data unsigned short volatile CANTCON absolute 0xE5;
    sbit  TPRSC0_bit at CANTCON.B0;
    const register unsigned short int TPRSC0 = 0;
    sbit  TPRSC1_bit at CANTCON.B1;
    const register unsigned short int TPRSC1 = 1;
    sbit  TPRSC2_bit at CANTCON.B2;
    const register unsigned short int TPRSC2 = 2;
    sbit  TPRSC3_bit at CANTCON.B3;
    const register unsigned short int TPRSC3 = 3;
    sbit  TPRSC4_bit at CANTCON.B4;
    const register unsigned short int TPRSC4 = 4;
    sbit  TPRSC5_bit at CANTCON.B5;
    const register unsigned short int TPRSC5 = 5;
    sbit  TPRSC6_bit at CANTCON.B6;
    const register unsigned short int TPRSC6 = 6;
    sbit  TPRSC7_bit at CANTCON.B7;
    const register unsigned short int TPRSC7 = 7;

sfr data unsigned short volatile CANBT3 absolute 0xE4;
    sbit  SMP_bit at CANBT3.B0;
    const register unsigned short int SMP = 0;
    sbit  PHS10_bit at CANBT3.B1;
    const register unsigned short int PHS10 = 1;
    sbit  PHS11_bit at CANBT3.B2;
    const register unsigned short int PHS11 = 2;
    sbit  PHS12_bit at CANBT3.B3;
    const register unsigned short int PHS12 = 3;
    sbit  PHS20_bit at CANBT3.B4;
    const register unsigned short int PHS20 = 4;
    sbit  PHS21_bit at CANBT3.B5;
    const register unsigned short int PHS21 = 5;
    sbit  PHS22_bit at CANBT3.B6;
    const register unsigned short int PHS22 = 6;

sfr data unsigned short volatile CANBT2 absolute 0xE3;
    sbit  PRS0_bit at CANBT2.B1;
    const register unsigned short int PRS0 = 1;
    sbit  PRS1_bit at CANBT2.B2;
    const register unsigned short int PRS1 = 2;
    sbit  PRS2_bit at CANBT2.B3;
    const register unsigned short int PRS2 = 3;
    sbit  SJW0_bit at CANBT2.B5;
    const register unsigned short int SJW0 = 5;
    sbit  SJW1_bit at CANBT2.B6;
    const register unsigned short int SJW1 = 6;

sfr data unsigned short volatile CANBT1 absolute 0xE2;
    sbit  BRP0_bit at CANBT1.B1;
    const register unsigned short int BRP0 = 1;
    sbit  BRP1_bit at CANBT1.B2;
    const register unsigned short int BRP1 = 2;
    sbit  BRP2_bit at CANBT1.B3;
    const register unsigned short int BRP2 = 3;
    sbit  BRP3_bit at CANBT1.B4;
    const register unsigned short int BRP3 = 4;
    sbit  BRP4_bit at CANBT1.B5;
    const register unsigned short int BRP4 = 5;
    sbit  BRP5_bit at CANBT1.B6;
    const register unsigned short int BRP5 = 6;

sfr data unsigned short volatile CANSIT1 absolute 0xE1;

sfr data unsigned short volatile CANSIT2 absolute 0xE0;
    sbit  SIT0_bit at CANSIT2.B0;
    const register unsigned short int SIT0 = 0;
    sbit  SIT1_bit at CANSIT2.B1;
    const register unsigned short int SIT1 = 1;
    sbit  SIT2_bit at CANSIT2.B2;
    const register unsigned short int SIT2 = 2;
    sbit  SIT3_bit at CANSIT2.B3;
    const register unsigned short int SIT3 = 3;
    sbit  SIT4_bit at CANSIT2.B4;
    const register unsigned short int SIT4 = 4;
    sbit  SIT5_bit at CANSIT2.B5;
    const register unsigned short int SIT5 = 5;

sfr data unsigned short volatile CANIE1 absolute 0xDF;

sfr data unsigned short volatile CANIE2 absolute 0xDE;
    sbit  IEMOB0_bit at CANIE2.B0;
    const register unsigned short int IEMOB0 = 0;
    sbit  IEMOB1_bit at CANIE2.B1;
    const register unsigned short int IEMOB1 = 1;
    sbit  IEMOB2_bit at CANIE2.B2;
    const register unsigned short int IEMOB2 = 2;
    sbit  IEMOB3_bit at CANIE2.B3;
    const register unsigned short int IEMOB3 = 3;
    sbit  IEMOB4_bit at CANIE2.B4;
    const register unsigned short int IEMOB4 = 4;
    sbit  IEMOB5_bit at CANIE2.B5;
    const register unsigned short int IEMOB5 = 5;

sfr data unsigned short volatile CANEN1 absolute 0xDD;

sfr data unsigned short volatile CANEN2 absolute 0xDC;
    sbit  ENMOB0_bit at CANEN2.B0;
    const register unsigned short int ENMOB0 = 0;
    sbit  ENMOB1_bit at CANEN2.B1;
    const register unsigned short int ENMOB1 = 1;
    sbit  ENMOB2_bit at CANEN2.B2;
    const register unsigned short int ENMOB2 = 2;
    sbit  ENMOB3_bit at CANEN2.B3;
    const register unsigned short int ENMOB3 = 3;
    sbit  ENMOB4_bit at CANEN2.B4;
    const register unsigned short int ENMOB4 = 4;
    sbit  ENMOB5_bit at CANEN2.B5;
    const register unsigned short int ENMOB5 = 5;

sfr data unsigned short volatile CANGIE absolute 0xDB;
    sbit  ENOVRT_bit at CANGIE.B0;
    const register unsigned short int ENOVRT = 0;
    sbit  ENERG_bit at CANGIE.B1;
    const register unsigned short int ENERG = 1;
    sbit  ENBX_bit at CANGIE.B2;
    const register unsigned short int ENBX = 2;
    sbit  ENERR_bit at CANGIE.B3;
    const register unsigned short int ENERR = 3;
    sbit  ENTX_bit at CANGIE.B4;
    const register unsigned short int ENTX = 4;
    sbit  ENRX_bit at CANGIE.B5;
    const register unsigned short int ENRX = 5;
    sbit  ENBOFF_bit at CANGIE.B6;
    const register unsigned short int ENBOFF = 6;
    sbit  ENIT_bit at CANGIE.B7;
    const register unsigned short int ENIT = 7;

sfr data unsigned short volatile CANGIT absolute 0xDA;
    sbit  AERG_bit at CANGIT.B0;
    const register unsigned short int AERG = 0;
    sbit  FERG_bit at CANGIT.B1;
    const register unsigned short int FERG = 1;
    sbit  CERG_bit at CANGIT.B2;
    const register unsigned short int CERG = 2;
    sbit  SERG_bit at CANGIT.B3;
    const register unsigned short int SERG = 3;
    sbit  BXOK_bit at CANGIT.B4;
    const register unsigned short int BXOK = 4;
    sbit  OVRTIM_bit at CANGIT.B5;
    const register unsigned short int OVRTIM = 5;
    sbit  BOFFIT_bit at CANGIT.B6;
    const register unsigned short int BOFFIT = 6;
    sbit  CANIT_bit at CANGIT.B7;
    const register unsigned short int CANIT = 7;

sfr data unsigned short volatile CANGSTA absolute 0xD9;
    sbit  ERRP_bit at CANGSTA.B0;
    const register unsigned short int ERRP = 0;
    sbit  BOFF_bit at CANGSTA.B1;
    const register unsigned short int BOFF = 1;
    sbit  ENFG_bit at CANGSTA.B2;
    const register unsigned short int ENFG = 2;
    sbit  RXBSY_bit at CANGSTA.B3;
    const register unsigned short int RXBSY = 3;
    sbit  TXBSY_bit at CANGSTA.B4;
    const register unsigned short int TXBSY = 4;
    sbit  OVFG_bit at CANGSTA.B6;
    const register unsigned short int OVFG = 6;

sfr data unsigned short volatile CANGCON absolute 0xD8;
    sbit  SWRES_bit at CANGCON.B0;
    const register unsigned short int SWRES = 0;
    sbit  ENASTB_bit at CANGCON.B1;
    const register unsigned short int ENASTB = 1;
    sbit  TEST_bit at CANGCON.B2;
    const register unsigned short int TEST = 2;
    sbit  LISTEN_bit at CANGCON.B3;
    const register unsigned short int LISTEN = 3;
    sbit  SYNTTC_bit at CANGCON.B4;
    const register unsigned short int SYNTTC = 4;
    sbit  TTC_bit at CANGCON.B5;
    const register unsigned short int TTC = 5;
    sbit  OVRQ_bit at CANGCON.B6;
    const register unsigned short int OVRQ = 6;
    sbit  ABRQ_bit at CANGCON.B7;
    const register unsigned short int ABRQ = 7;

sfr data unsigned short volatile LINDAT absolute 0xD2;
    sbit  LDATA0_bit at LINDAT.B0;
    const register unsigned short int LDATA0 = 0;
    sbit  LDATA1_bit at LINDAT.B1;
    const register unsigned short int LDATA1 = 1;
    sbit  LDATA2_bit at LINDAT.B2;
    const register unsigned short int LDATA2 = 2;
    sbit  LDATA3_bit at LINDAT.B3;
    const register unsigned short int LDATA3 = 3;
    sbit  LDATA4_bit at LINDAT.B4;
    const register unsigned short int LDATA4 = 4;
    sbit  LDATA5_bit at LINDAT.B5;
    const register unsigned short int LDATA5 = 5;
    sbit  LDATA6_bit at LINDAT.B6;
    const register unsigned short int LDATA6 = 6;
    sbit  LDATA7_bit at LINDAT.B7;
    const register unsigned short int LDATA7 = 7;

sfr data unsigned short volatile LINSEL absolute 0xD1;
    sbit  LINDX0_bit at LINSEL.B0;
    const register unsigned short int LINDX0 = 0;
    sbit  LINDX1_bit at LINSEL.B1;
    const register unsigned short int LINDX1 = 1;
    sbit  LINDX2_bit at LINSEL.B2;
    const register unsigned short int LINDX2 = 2;
    sbit  LAINC_bit at LINSEL.B3;
    const register unsigned short int LAINC = 3;

sfr data unsigned short volatile LINIDR absolute 0xD0;
    sbit  LID0_bit at LINIDR.B0;
    const register unsigned short int LID0 = 0;
    sbit  LID1_bit at LINIDR.B1;
    const register unsigned short int LID1 = 1;
    sbit  LID2_bit at LINIDR.B2;
    const register unsigned short int LID2 = 2;
    sbit  LID3_bit at LINIDR.B3;
    const register unsigned short int LID3 = 3;
    sbit  LID4_bit at LINIDR.B4;
    const register unsigned short int LID4 = 4;
    sbit  LID5_bit at LINIDR.B5;
    const register unsigned short int LID5 = 5;
    sbit  LP0_bit at LINIDR.B6;
    const register unsigned short int LP0 = 6;
    sbit  LP1_bit at LINIDR.B7;
    const register unsigned short int LP1 = 7;

sfr data unsigned short volatile LINDLR absolute 0xCF;
    sbit  LRXDL0_bit at LINDLR.B0;
    const register unsigned short int LRXDL0 = 0;
    sbit  LRXDL1_bit at LINDLR.B1;
    const register unsigned short int LRXDL1 = 1;
    sbit  LRXDL2_bit at LINDLR.B2;
    const register unsigned short int LRXDL2 = 2;
    sbit  LRXDL3_bit at LINDLR.B3;
    const register unsigned short int LRXDL3 = 3;
    sbit  LTXDL0_bit at LINDLR.B4;
    const register unsigned short int LTXDL0 = 4;
    sbit  LTXDL1_bit at LINDLR.B5;
    const register unsigned short int LTXDL1 = 5;
    sbit  LTXDL2_bit at LINDLR.B6;
    const register unsigned short int LTXDL2 = 6;
    sbit  LTXDL3_bit at LINDLR.B7;
    const register unsigned short int LTXDL3 = 7;

sfr data unsigned short volatile LINBRRH absolute 0xCE;
    sbit  LDIV8_bit at LINBRRH.B0;
    const register unsigned short int LDIV8 = 0;
    sbit  LDIV9_bit at LINBRRH.B1;
    const register unsigned short int LDIV9 = 1;
    sbit  LDIV10_bit at LINBRRH.B2;
    const register unsigned short int LDIV10 = 2;
    sbit  LDIV11_bit at LINBRRH.B3;
    const register unsigned short int LDIV11 = 3;

sfr data unsigned short volatile LINBRRL absolute 0xCD;
    sbit  LDIV0_bit at LINBRRL.B0;
    const register unsigned short int LDIV0 = 0;
    sbit  LDIV1_bit at LINBRRL.B1;
    const register unsigned short int LDIV1 = 1;
    sbit  LDIV2_bit at LINBRRL.B2;
    const register unsigned short int LDIV2 = 2;
    sbit  LDIV3_bit at LINBRRL.B3;
    const register unsigned short int LDIV3 = 3;
    sbit  LDIV4_bit at LINBRRL.B4;
    const register unsigned short int LDIV4 = 4;
    sbit  LDIV5_bit at LINBRRL.B5;
    const register unsigned short int LDIV5 = 5;
    sbit  LDIV6_bit at LINBRRL.B6;
    const register unsigned short int LDIV6 = 6;
    sbit  LDIV7_bit at LINBRRL.B7;
    const register unsigned short int LDIV7 = 7;

sfr data unsigned short volatile LINBTR absolute 0xCC;
    sbit  LBT0_bit at LINBTR.B0;
    const register unsigned short int LBT0 = 0;
    sbit  LBT1_bit at LINBTR.B1;
    const register unsigned short int LBT1 = 1;
    sbit  LBT2_bit at LINBTR.B2;
    const register unsigned short int LBT2 = 2;
    sbit  LBT3_bit at LINBTR.B3;
    const register unsigned short int LBT3 = 3;
    sbit  LBT4_bit at LINBTR.B4;
    const register unsigned short int LBT4 = 4;
    sbit  LBT5_bit at LINBTR.B5;
    const register unsigned short int LBT5 = 5;
    sbit  LDISR_bit at LINBTR.B7;
    const register unsigned short int LDISR = 7;

sfr data unsigned short volatile LINERR absolute 0xCB;
    sbit  LBERR_bit at LINERR.B0;
    const register unsigned short int LBERR = 0;
    sbit  LCERR_bit at LINERR.B1;
    const register unsigned short int LCERR = 1;
    sbit  LPERR_bit at LINERR.B2;
    const register unsigned short int LPERR = 2;
    sbit  LSERR_bit at LINERR.B3;
    const register unsigned short int LSERR = 3;
    sbit  LFERR_bit at LINERR.B4;
    const register unsigned short int LFERR = 4;
    sbit  LOVERR_bit at LINERR.B5;
    const register unsigned short int LOVERR = 5;
    sbit  LTOERR_bit at LINERR.B6;
    const register unsigned short int LTOERR = 6;
    sbit  LABORT_bit at LINERR.B7;
    const register unsigned short int LABORT = 7;

sfr data unsigned short volatile LINENIR absolute 0xCA;
    sbit  LENRXOK_bit at LINENIR.B0;
    const register unsigned short int LENRXOK = 0;
    sbit  LENTXOK_bit at LINENIR.B1;
    const register unsigned short int LENTXOK = 1;
    sbit  LENIDOK_bit at LINENIR.B2;
    const register unsigned short int LENIDOK = 2;
    sbit  LENERR_bit at LINENIR.B3;
    const register unsigned short int LENERR = 3;

sfr data unsigned short volatile LINSIR absolute 0xC9;
    sbit  LRXOK_bit at LINSIR.B0;
    const register unsigned short int LRXOK = 0;
    sbit  LTXOK_bit at LINSIR.B1;
    const register unsigned short int LTXOK = 1;
    sbit  LIDOK_bit at LINSIR.B2;
    const register unsigned short int LIDOK = 2;
    sbit  LERR_bit at LINSIR.B3;
    const register unsigned short int LERR = 3;
    sbit  LBUSY_bit at LINSIR.B4;
    const register unsigned short int LBUSY = 4;
    sbit  LIDST0_bit at LINSIR.B5;
    const register unsigned short int LIDST0 = 5;
    sbit  LIDST1_bit at LINSIR.B6;
    const register unsigned short int LIDST1 = 6;
    sbit  LIDST2_bit at LINSIR.B7;
    const register unsigned short int LIDST2 = 7;

sfr data unsigned short volatile LINCR absolute 0xC8;
    sbit  LCMD0_bit at LINCR.B0;
    const register unsigned short int LCMD0 = 0;
    sbit  LCMD1_bit at LINCR.B1;
    const register unsigned short int LCMD1 = 1;
    sbit  LCMD2_bit at LINCR.B2;
    const register unsigned short int LCMD2 = 2;
    sbit  LENA_bit at LINCR.B3;
    const register unsigned short int LENA = 3;
    sbit  LCONF0_bit at LINCR.B4;
    const register unsigned short int LCONF0 = 4;
    sbit  LCONF1_bit at LINCR.B5;
    const register unsigned short int LCONF1 = 5;
    sbit  LIN13_bit at LINCR.B6;
    const register unsigned short int LIN13 = 6;
    sbit  LSWRES_bit at LINCR.B7;
    const register unsigned short int LSWRES = 7;

sfr data unsigned short volatile AC3CON absolute 0x97;
    sbit  AC3M0_bit at AC3CON.B0;
    const register unsigned short int AC3M0 = 0;
    sbit  AC3M1_bit at AC3CON.B1;
    const register unsigned short int AC3M1 = 1;
    sbit  AC3M2_bit at AC3CON.B2;
    const register unsigned short int AC3M2 = 2;
    sbit  AC3IS0_bit at AC3CON.B4;
    const register unsigned short int AC3IS0 = 4;
    sbit  AC3IS1_bit at AC3CON.B5;
    const register unsigned short int AC3IS1 = 5;
    sbit  AC3IE_bit at AC3CON.B6;
    const register unsigned short int AC3IE = 6;
    sbit  AC3EN_bit at AC3CON.B7;
    const register unsigned short int AC3EN = 7;

sfr data unsigned short volatile AC2CON absolute 0x96;
    sbit  AC2M0_bit at AC2CON.B0;
    const register unsigned short int AC2M0 = 0;
    sbit  AC2M1_bit at AC2CON.B1;
    const register unsigned short int AC2M1 = 1;
    sbit  AC2M2_bit at AC2CON.B2;
    const register unsigned short int AC2M2 = 2;
    sbit  AC2IS0_bit at AC2CON.B4;
    const register unsigned short int AC2IS0 = 4;
    sbit  AC2IS1_bit at AC2CON.B5;
    const register unsigned short int AC2IS1 = 5;
    sbit  AC2IE_bit at AC2CON.B6;
    const register unsigned short int AC2IE = 6;
    sbit  AC2EN_bit at AC2CON.B7;
    const register unsigned short int AC2EN = 7;

sfr data unsigned short volatile AC1CON absolute 0x95;
    sbit  AC1M0_bit at AC1CON.B0;
    const register unsigned short int AC1M0 = 0;
    sbit  AC1M1_bit at AC1CON.B1;
    const register unsigned short int AC1M1 = 1;
    sbit  AC1M2_bit at AC1CON.B2;
    const register unsigned short int AC1M2 = 2;
    sbit  AC1ICE_bit at AC1CON.B3;
    const register unsigned short int AC1ICE = 3;
    sbit  AC1IS0_bit at AC1CON.B4;
    const register unsigned short int AC1IS0 = 4;
    sbit  AC1IS1_bit at AC1CON.B5;
    const register unsigned short int AC1IS1 = 5;
    sbit  AC1IE_bit at AC1CON.B6;
    const register unsigned short int AC1IE = 6;
    sbit  AC1EN_bit at AC1CON.B7;
    const register unsigned short int AC1EN = 7;

sfr data unsigned short volatile AC0CON absolute 0x94;
    sbit  AC0M0_bit at AC0CON.B0;
    const register unsigned short int AC0M0 = 0;
    sbit  AC0M1_bit at AC0CON.B1;
    const register unsigned short int AC0M1 = 1;
    sbit  AC0M2_bit at AC0CON.B2;
    const register unsigned short int AC0M2 = 2;
    sbit  ACCKSEL_bit at AC0CON.B3;
    const register unsigned short int ACCKSEL = 3;
    sbit  AC0IS0_bit at AC0CON.B4;
    const register unsigned short int AC0IS0 = 4;
    sbit  AC0IS1_bit at AC0CON.B5;
    const register unsigned short int AC0IS1 = 5;
    sbit  AC0IE_bit at AC0CON.B6;
    const register unsigned short int AC0IE = 6;
    sbit  AC0EN_bit at AC0CON.B7;
    const register unsigned short int AC0EN = 7;

sfr data unsigned short volatile DACH absolute 0x92;
    sbit  DACH0_bit at DACH.B0;
    const register unsigned short int DACH0 = 0;
    sbit  DACH1_bit at DACH.B1;
    const register unsigned short int DACH1 = 1;
    sbit  DACH2_bit at DACH.B2;
    const register unsigned short int DACH2 = 2;
    sbit  DACH3_bit at DACH.B3;
    const register unsigned short int DACH3 = 3;
    sbit  DACH4_bit at DACH.B4;
    const register unsigned short int DACH4 = 4;
    sbit  DACH5_bit at DACH.B5;
    const register unsigned short int DACH5 = 5;
    sbit  DACH6_bit at DACH.B6;
    const register unsigned short int DACH6 = 6;
    sbit  DACH7_bit at DACH.B7;
    const register unsigned short int DACH7 = 7;

sfr data unsigned short volatile DACL absolute 0x91;
    sbit  DACL0_bit at DACL.B0;
    const register unsigned short int DACL0 = 0;
    sbit  DACL1_bit at DACL.B1;
    const register unsigned short int DACL1 = 1;
    sbit  DACL2_bit at DACL.B2;
    const register unsigned short int DACL2 = 2;
    sbit  DACL3_bit at DACL.B3;
    const register unsigned short int DACL3 = 3;
    sbit  DACL4_bit at DACL.B4;
    const register unsigned short int DACL4 = 4;
    sbit  DACL5_bit at DACL.B5;
    const register unsigned short int DACL5 = 5;
    sbit  DACL6_bit at DACL.B6;
    const register unsigned short int DACL6 = 6;
    sbit  DACL7_bit at DACL.B7;
    const register unsigned short int DACL7 = 7;

sfr data unsigned short volatile DACON absolute 0x90;
    sbit  DAEN_bit at DACON.B0;
    const register unsigned short int DAEN = 0;
    sbit  DALA_bit at DACON.B2;
    const register unsigned short int DALA = 2;
    sbit  DATS0_bit at DACON.B4;
    const register unsigned short int DATS0 = 4;
    sbit  DATS1_bit at DACON.B5;
    const register unsigned short int DATS1 = 5;
    sbit  DATS2_bit at DACON.B6;
    const register unsigned short int DATS2 = 6;
    sbit  DAATE_bit at DACON.B7;
    const register unsigned short int DAATE = 7;

sfr data unsigned short OCR1BH absolute 0x8B;
    sbit  OCR1BH0_bit at OCR1BH.B0;
    const register unsigned short int OCR1BH0 = 0;
    sbit  OCR1BH1_bit at OCR1BH.B1;
    const register unsigned short int OCR1BH1 = 1;
    sbit  OCR1BH2_bit at OCR1BH.B2;
    const register unsigned short int OCR1BH2 = 2;
    sbit  OCR1BH3_bit at OCR1BH.B3;
    const register unsigned short int OCR1BH3 = 3;
    sbit  OCR1BH4_bit at OCR1BH.B4;
    const register unsigned short int OCR1BH4 = 4;
    sbit  OCR1BH5_bit at OCR1BH.B5;
    const register unsigned short int OCR1BH5 = 5;
    sbit  OCR1BH6_bit at OCR1BH.B6;
    const register unsigned short int OCR1BH6 = 6;
    sbit  OCR1BH7_bit at OCR1BH.B7;
    const register unsigned short int OCR1BH7 = 7;

sfr data unsigned short OCR1BL absolute 0x8A;
    sbit  OCR1BL0_bit at OCR1BL.B0;
    const register unsigned short int OCR1BL0 = 0;
    sbit  OCR1BL1_bit at OCR1BL.B1;
    const register unsigned short int OCR1BL1 = 1;
    sbit  OCR1BL2_bit at OCR1BL.B2;
    const register unsigned short int OCR1BL2 = 2;
    sbit  OCR1BL3_bit at OCR1BL.B3;
    const register unsigned short int OCR1BL3 = 3;
    sbit  OCR1BL4_bit at OCR1BL.B4;
    const register unsigned short int OCR1BL4 = 4;
    sbit  OCR1BL5_bit at OCR1BL.B5;
    const register unsigned short int OCR1BL5 = 5;
    sbit  OCR1BL6_bit at OCR1BL.B6;
    const register unsigned short int OCR1BL6 = 6;
    sbit  OCR1BL7_bit at OCR1BL.B7;
    const register unsigned short int OCR1BL7 = 7;

sfr data unsigned short OCR1AH absolute 0x89;
    sbit  OCR1AH0_bit at OCR1AH.B0;
    const register unsigned short int OCR1AH0 = 0;
    sbit  OCR1AH1_bit at OCR1AH.B1;
    const register unsigned short int OCR1AH1 = 1;
    sbit  OCR1AH2_bit at OCR1AH.B2;
    const register unsigned short int OCR1AH2 = 2;
    sbit  OCR1AH3_bit at OCR1AH.B3;
    const register unsigned short int OCR1AH3 = 3;
    sbit  OCR1AH4_bit at OCR1AH.B4;
    const register unsigned short int OCR1AH4 = 4;
    sbit  OCR1AH5_bit at OCR1AH.B5;
    const register unsigned short int OCR1AH5 = 5;
    sbit  OCR1AH6_bit at OCR1AH.B6;
    const register unsigned short int OCR1AH6 = 6;
    sbit  OCR1AH7_bit at OCR1AH.B7;
    const register unsigned short int OCR1AH7 = 7;

sfr data unsigned short OCR1AL absolute 0x88;
    sbit  OCR1AL0_bit at OCR1AL.B0;
    const register unsigned short int OCR1AL0 = 0;
    sbit  OCR1AL1_bit at OCR1AL.B1;
    const register unsigned short int OCR1AL1 = 1;
    sbit  OCR1AL2_bit at OCR1AL.B2;
    const register unsigned short int OCR1AL2 = 2;
    sbit  OCR1AL3_bit at OCR1AL.B3;
    const register unsigned short int OCR1AL3 = 3;
    sbit  OCR1AL4_bit at OCR1AL.B4;
    const register unsigned short int OCR1AL4 = 4;
    sbit  OCR1AL5_bit at OCR1AL.B5;
    const register unsigned short int OCR1AL5 = 5;
    sbit  OCR1AL6_bit at OCR1AL.B6;
    const register unsigned short int OCR1AL6 = 6;
    sbit  OCR1AL7_bit at OCR1AL.B7;
    const register unsigned short int OCR1AL7 = 7;

sfr data unsigned short volatile ICR1H absolute 0x87;
    sbit  ICR1H0_bit at ICR1H.B0;
    const register unsigned short int ICR1H0 = 0;
    sbit  ICR1H1_bit at ICR1H.B1;
    const register unsigned short int ICR1H1 = 1;
    sbit  ICR1H2_bit at ICR1H.B2;
    const register unsigned short int ICR1H2 = 2;
    sbit  ICR1H3_bit at ICR1H.B3;
    const register unsigned short int ICR1H3 = 3;
    sbit  ICR1H4_bit at ICR1H.B4;
    const register unsigned short int ICR1H4 = 4;
    sbit  ICR1H5_bit at ICR1H.B5;
    const register unsigned short int ICR1H5 = 5;
    sbit  ICR1H6_bit at ICR1H.B6;
    const register unsigned short int ICR1H6 = 6;
    sbit  ICR1H7_bit at ICR1H.B7;
    const register unsigned short int ICR1H7 = 7;

sfr data unsigned short volatile ICR1L absolute 0x86;
    sbit  ICR1L0_bit at ICR1L.B0;
    const register unsigned short int ICR1L0 = 0;
    sbit  ICR1L1_bit at ICR1L.B1;
    const register unsigned short int ICR1L1 = 1;
    sbit  ICR1L2_bit at ICR1L.B2;
    const register unsigned short int ICR1L2 = 2;
    sbit  ICR1L3_bit at ICR1L.B3;
    const register unsigned short int ICR1L3 = 3;
    sbit  ICR1L4_bit at ICR1L.B4;
    const register unsigned short int ICR1L4 = 4;
    sbit  ICR1L5_bit at ICR1L.B5;
    const register unsigned short int ICR1L5 = 5;
    sbit  ICR1L6_bit at ICR1L.B6;
    const register unsigned short int ICR1L6 = 6;
    sbit  ICR1L7_bit at ICR1L.B7;
    const register unsigned short int ICR1L7 = 7;

sfr data unsigned short volatile TCNT1H absolute 0x85;
    sbit  TCNT1H0_bit at TCNT1H.B0;
    const register unsigned short int TCNT1H0 = 0;
    sbit  TCNT1H1_bit at TCNT1H.B1;
    const register unsigned short int TCNT1H1 = 1;
    sbit  TCNT1H2_bit at TCNT1H.B2;
    const register unsigned short int TCNT1H2 = 2;
    sbit  TCNT1H3_bit at TCNT1H.B3;
    const register unsigned short int TCNT1H3 = 3;
    sbit  TCNT1H4_bit at TCNT1H.B4;
    const register unsigned short int TCNT1H4 = 4;
    sbit  TCNT1H5_bit at TCNT1H.B5;
    const register unsigned short int TCNT1H5 = 5;
    sbit  TCNT1H6_bit at TCNT1H.B6;
    const register unsigned short int TCNT1H6 = 6;
    sbit  TCNT1H7_bit at TCNT1H.B7;
    const register unsigned short int TCNT1H7 = 7;

sfr data unsigned short volatile TCNT1L absolute 0x84;
    sbit  TCNT1L0_bit at TCNT1L.B0;
    const register unsigned short int TCNT1L0 = 0;
    sbit  TCNT1L1_bit at TCNT1L.B1;
    const register unsigned short int TCNT1L1 = 1;
    sbit  TCNT1L2_bit at TCNT1L.B2;
    const register unsigned short int TCNT1L2 = 2;
    sbit  TCNT1L3_bit at TCNT1L.B3;
    const register unsigned short int TCNT1L3 = 3;
    sbit  TCNT1L4_bit at TCNT1L.B4;
    const register unsigned short int TCNT1L4 = 4;
    sbit  TCNT1L5_bit at TCNT1L.B5;
    const register unsigned short int TCNT1L5 = 5;
    sbit  TCNT1L6_bit at TCNT1L.B6;
    const register unsigned short int TCNT1L6 = 6;
    sbit  TCNT1L7_bit at TCNT1L.B7;
    const register unsigned short int TCNT1L7 = 7;

sfr data unsigned short volatile TCCR1C absolute 0x82;
    sbit  FOC1B_bit at TCCR1C.B6;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1A = 7;

sfr data unsigned short TCCR1B absolute 0x81;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS10 = 0;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS11 = 1;
    sbit  CS12_bit at TCCR1B.B2;
    const register unsigned short int CS12 = 2;
    sbit  WGM12_bit at TCCR1B.B3;
    const register unsigned short int WGM12 = 3;
    sbit  WGM13_bit at TCCR1B.B4;
    const register unsigned short int WGM13 = 4;
    sbit  ICES1_bit at TCCR1B.B6;
    const register unsigned short int ICES1 = 6;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICNC1 = 7;

sfr data unsigned short TCCR1A absolute 0x80;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM10 = 0;
    sbit  WGM11_bit at TCCR1A.B1;
    const register unsigned short int WGM11 = 1;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1A1 = 7;

sfr data unsigned short DIDR1 absolute 0x7F;
    sbit  ADC8D_bit at DIDR1.B0;
    const register unsigned short int ADC8D = 0;
    sbit  ADC9D_bit at DIDR1.B1;
    const register unsigned short int ADC9D = 1;
    sbit  ADC10D_bit at DIDR1.B2;
    const register unsigned short int ADC10D = 2;
    sbit  AMP0ND_bit at DIDR1.B3;
    const register unsigned short int AMP0ND = 3;
    sbit  AMP0PD_bit at DIDR1.B4;
    const register unsigned short int AMP0PD = 4;
    sbit  ACMP0D_bit at DIDR1.B5;
    const register unsigned short int ACMP0D = 5;
    sbit  AMP2PD_bit at DIDR1.B6;
    const register unsigned short int AMP2PD = 6;

sfr data unsigned short DIDR0 absolute 0x7E;
    sbit  ADC0D_bit at DIDR0.B0;
    const register unsigned short int ADC0D = 0;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC1D = 1;
    sbit  ADC2D_bit at DIDR0.B2;
    const register unsigned short int ADC2D = 2;
    sbit  ADC3D_bit at DIDR0.B3;
    const register unsigned short int ADC3D = 3;
    sbit  ADC4D_bit at DIDR0.B4;
    const register unsigned short int ADC4D = 4;
    sbit  ADC5D_bit at DIDR0.B5;
    const register unsigned short int ADC5D = 5;
    sbit  ADC6D_bit at DIDR0.B6;
    const register unsigned short int ADC6D = 6;
    sbit  ADC7D_bit at DIDR0.B7;
    const register unsigned short int ADC7D = 7;

sfr data unsigned short ADMUX absolute 0x7C;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX0 = 0;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX1 = 1;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX2 = 2;
    sbit  MUX3_bit at ADMUX.B3;
    const register unsigned short int MUX3 = 3;
    sbit  MUX4_bit at ADMUX.B4;
    const register unsigned short int MUX4 = 4;
    sbit  ADLAR_bit at ADMUX.B5;
    const register unsigned short int ADLAR = 5;
    sbit  REFS0_bit at ADMUX.B6;
    const register unsigned short int REFS0 = 6;
    sbit  REFS1_bit at ADMUX.B7;
    const register unsigned short int REFS1 = 7;

sfr data unsigned short ADCSRB absolute 0x7B;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS2_bit at ADCSRB.B2;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS3_bit at ADCSRB.B3;
    const register unsigned short int ADTS3 = 3;
    sbit  AREFEN_bit at ADCSRB.B5;
    const register unsigned short int AREFEN = 5;
    sbit  ISRCEN_bit at ADCSRB.B6;
    const register unsigned short int ISRCEN = 6;
    sbit  ADHSM_bit at ADCSRB.B7;
    const register unsigned short int ADHSM = 7;

sfr data unsigned short volatile ADCSRA absolute 0x7A;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS2_bit at ADCSRA.B2;
    const register unsigned short int ADPS2 = 2;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADIE = 3;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIF = 4;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADATE = 5;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADSC = 6;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADEN = 7;

sfr data unsigned short volatile ADCH absolute 0x79;
    sbit  ADCH0_bit at ADCH.B0;
    const register unsigned short int ADCH0 = 0;
    sbit  ADCH1_bit at ADCH.B1;
    const register unsigned short int ADCH1 = 1;
    sbit  ADCH2_bit at ADCH.B2;
    const register unsigned short int ADCH2 = 2;
    sbit  ADCH3_bit at ADCH.B3;
    const register unsigned short int ADCH3 = 3;
    sbit  ADCH4_bit at ADCH.B4;
    const register unsigned short int ADCH4 = 4;
    sbit  ADCH5_bit at ADCH.B5;
    const register unsigned short int ADCH5 = 5;
    sbit  ADCH6_bit at ADCH.B6;
    const register unsigned short int ADCH6 = 6;
    sbit  ADCH7_bit at ADCH.B7;
    const register unsigned short int ADCH7 = 7;

sfr data unsigned short volatile ADCL absolute 0x78;
    sbit  ADCL0_bit at ADCL.B0;
    const register unsigned short int ADCL0 = 0;
    sbit  ADCL1_bit at ADCL.B1;
    const register unsigned short int ADCL1 = 1;
    sbit  ADCL2_bit at ADCL.B2;
    const register unsigned short int ADCL2 = 2;
    sbit  ADCL3_bit at ADCL.B3;
    const register unsigned short int ADCL3 = 3;
    sbit  ADCL4_bit at ADCL.B4;
    const register unsigned short int ADCL4 = 4;
    sbit  ADCL5_bit at ADCL.B5;
    const register unsigned short int ADCL5 = 5;
    sbit  ADCL6_bit at ADCL.B6;
    const register unsigned short int ADCL6 = 6;
    sbit  ADCL7_bit at ADCL.B7;
    const register unsigned short int ADCL7 = 7;

sfr data unsigned short volatile AMP2CSR absolute 0x77;
    sbit  AMP2TS0_bit at AMP2CSR.B0;
    const register unsigned short int AMP2TS0 = 0;
    sbit  AMP2TS1_bit at AMP2CSR.B1;
    const register unsigned short int AMP2TS1 = 1;
    sbit  AMP2TS2_bit at AMP2CSR.B2;
    const register unsigned short int AMP2TS2 = 2;
    sbit  AMPCMP2_bit at AMP2CSR.B3;
    const register unsigned short int AMPCMP2 = 3;
    sbit  AMP2G0_bit at AMP2CSR.B4;
    const register unsigned short int AMP2G0 = 4;
    sbit  AMP2G1_bit at AMP2CSR.B5;
    const register unsigned short int AMP2G1 = 5;
    sbit  AMP2IS_bit at AMP2CSR.B6;
    const register unsigned short int AMP2IS = 6;
    sbit  AMP2EN_bit at AMP2CSR.B7;
    const register unsigned short int AMP2EN = 7;

sfr data unsigned short volatile AMP1CSR absolute 0x76;
    sbit  AMP1TS0_bit at AMP1CSR.B0;
    const register unsigned short int AMP1TS0 = 0;
    sbit  AMP1TS1_bit at AMP1CSR.B1;
    const register unsigned short int AMP1TS1 = 1;
    sbit  AMP1TS2_bit at AMP1CSR.B2;
    const register unsigned short int AMP1TS2 = 2;
    sbit  AMPCMP1_bit at AMP1CSR.B3;
    const register unsigned short int AMPCMP1 = 3;
    sbit  AMP1G0_bit at AMP1CSR.B4;
    const register unsigned short int AMP1G0 = 4;
    sbit  AMP1G1_bit at AMP1CSR.B5;
    const register unsigned short int AMP1G1 = 5;
    sbit  AMP1IS_bit at AMP1CSR.B6;
    const register unsigned short int AMP1IS = 6;
    sbit  AMP1EN_bit at AMP1CSR.B7;
    const register unsigned short int AMP1EN = 7;

sfr data unsigned short volatile AMP0CSR absolute 0x75;
    sbit  AMP0TS0_bit at AMP0CSR.B0;
    const register unsigned short int AMP0TS0 = 0;
    sbit  AMP0TS1_bit at AMP0CSR.B1;
    const register unsigned short int AMP0TS1 = 1;
    sbit  AMP0TS2_bit at AMP0CSR.B2;
    const register unsigned short int AMP0TS2 = 2;
    sbit  AMPCMP0_bit at AMP0CSR.B3;
    const register unsigned short int AMPCMP0 = 3;
    sbit  AMP0G0_bit at AMP0CSR.B4;
    const register unsigned short int AMP0G0 = 4;
    sbit  AMP0G1_bit at AMP0CSR.B5;
    const register unsigned short int AMP0G1 = 5;
    sbit  AMP0IS_bit at AMP0CSR.B6;
    const register unsigned short int AMP0IS = 6;
    sbit  AMP0EN_bit at AMP0CSR.B7;
    const register unsigned short int AMP0EN = 7;

sfr data unsigned short TIMSK1 absolute 0x6F;
    sbit  TOIE1_bit at TIMSK1.B0;
    const register unsigned short int TOIE1 = 0;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1B = 2;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int ICIE1 = 5;

sfr data unsigned short TIMSK0 absolute 0x6E;
    sbit  TOIE0_bit at TIMSK0.B0;
    const register unsigned short int TOIE0 = 0;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0B = 2;

sfr data unsigned short volatile PCMSK3 absolute 0x6D;
    sbit  PCINT24_bit at PCMSK3.B0;
    const register unsigned short int PCINT24 = 0;
    sbit  PCINT25_bit at PCMSK3.B1;
    const register unsigned short int PCINT25 = 1;
    sbit  PCINT26_bit at PCMSK3.B2;
    const register unsigned short int PCINT26 = 2;

sfr data unsigned short PCMSK2 absolute 0x6C;
    sbit  PCINT16_bit at PCMSK2.B0;
    const register unsigned short int PCINT16 = 0;
    sbit  PCINT17_bit at PCMSK2.B1;
    const register unsigned short int PCINT17 = 1;
    sbit  PCINT18_bit at PCMSK2.B2;
    const register unsigned short int PCINT18 = 2;
    sbit  PCINT19_bit at PCMSK2.B3;
    const register unsigned short int PCINT19 = 3;
    sbit  PCINT20_bit at PCMSK2.B4;
    const register unsigned short int PCINT20 = 4;
    sbit  PCINT21_bit at PCMSK2.B5;
    const register unsigned short int PCINT21 = 5;
    sbit  PCINT22_bit at PCMSK2.B6;
    const register unsigned short int PCINT22 = 6;
    sbit  PCINT23_bit at PCMSK2.B7;
    const register unsigned short int PCINT23 = 7;

sfr data unsigned short PCMSK1 absolute 0x6B;
    sbit  PCINT8_bit at PCMSK1.B0;
    const register unsigned short int PCINT8 = 0;
    sbit  PCINT9_bit at PCMSK1.B1;
    const register unsigned short int PCINT9 = 1;
    sbit  PCINT10_bit at PCMSK1.B2;
    const register unsigned short int PCINT10 = 2;
    sbit  PCINT11_bit at PCMSK1.B3;
    const register unsigned short int PCINT11 = 3;
    sbit  PCINT12_bit at PCMSK1.B4;
    const register unsigned short int PCINT12 = 4;
    sbit  PCINT13_bit at PCMSK1.B5;
    const register unsigned short int PCINT13 = 5;
    sbit  PCINT14_bit at PCMSK1.B6;
    const register unsigned short int PCINT14 = 6;
    sbit  PCINT15_bit at PCMSK1.B7;
    const register unsigned short int PCINT15 = 7;

sfr data unsigned short PCMSK0 absolute 0x6A;
    sbit  PCINT0_bit at PCMSK0.B0;
    const register unsigned short int PCINT0 = 0;
    sbit  PCINT1_bit at PCMSK0.B1;
    const register unsigned short int PCINT1 = 1;
    sbit  PCINT2_bit at PCMSK0.B2;
    const register unsigned short int PCINT2 = 2;
    sbit  PCINT3_bit at PCMSK0.B3;
    const register unsigned short int PCINT3 = 3;
    sbit  PCINT4_bit at PCMSK0.B4;
    const register unsigned short int PCINT4 = 4;
    sbit  PCINT5_bit at PCMSK0.B5;
    const register unsigned short int PCINT5 = 5;
    sbit  PCINT6_bit at PCMSK0.B6;
    const register unsigned short int PCINT6 = 6;
    sbit  PCINT7_bit at PCMSK0.B7;
    const register unsigned short int PCINT7 = 7;

sfr data unsigned short volatile EICRA absolute 0x69;
    sbit  ISC00_bit at EICRA.B0;
    const register unsigned short int ISC00 = 0;
    sbit  ISC01_bit at EICRA.B1;
    const register unsigned short int ISC01 = 1;
    sbit  ISC10_bit at EICRA.B2;
    const register unsigned short int ISC10 = 2;
    sbit  ISC11_bit at EICRA.B3;
    const register unsigned short int ISC11 = 3;
    sbit  ISC20_bit at EICRA.B4;
    const register unsigned short int ISC20 = 4;
    sbit  ISC21_bit at EICRA.B5;
    const register unsigned short int ISC21 = 5;
    sbit  ISC30_bit at EICRA.B6;
    const register unsigned short int ISC30 = 6;
    sbit  ISC31_bit at EICRA.B7;
    const register unsigned short int ISC31 = 7;

sfr data unsigned short PCICR absolute 0x68;
    sbit  PCIE0_bit at PCICR.B0;
    const register unsigned short int PCIE0 = 0;
    sbit  PCIE1_bit at PCICR.B1;
    const register unsigned short int PCIE1 = 1;
    sbit  PCIE2_bit at PCICR.B2;
    const register unsigned short int PCIE2 = 2;
    sbit  PCIE3_bit at PCICR.B3;
    const register unsigned short int PCIE3 = 3;

sfr data unsigned short OSCCAL absolute 0x66;
    sbit  CAL0_bit at OSCCAL.B0;
    const register unsigned short int CAL0 = 0;
    sbit  CAL1_bit at OSCCAL.B1;
    const register unsigned short int CAL1 = 1;
    sbit  CAL2_bit at OSCCAL.B2;
    const register unsigned short int CAL2 = 2;
    sbit  CAL3_bit at OSCCAL.B3;
    const register unsigned short int CAL3 = 3;
    sbit  CAL4_bit at OSCCAL.B4;
    const register unsigned short int CAL4 = 4;
    sbit  CAL5_bit at OSCCAL.B5;
    const register unsigned short int CAL5 = 5;
    sbit  CAL6_bit at OSCCAL.B6;
    const register unsigned short int CAL6 = 6;

sfr data unsigned short volatile PRR absolute 0x64;
    sbit  PRADC_bit at PRR.B0;
    const register unsigned short int PRADC = 0;
    sbit  PRLIN_bit at PRR.B1;
    const register unsigned short int PRLIN = 1;
    sbit  PRSPI_bit at PRR.B2;
    const register unsigned short int PRSPI = 2;
    sbit  PRTIM0_bit at PRR.B3;
    const register unsigned short int PRTIM0 = 3;
    sbit  PRTIM1_bit at PRR.B4;
    const register unsigned short int PRTIM1 = 4;
    sbit  PRPSC_bit at PRR.B5;
    const register unsigned short int PRPSC = 5;
    sbit  PRCAN_bit at PRR.B6;
    const register unsigned short int PRCAN = 6;

sfr data unsigned short volatile CLKPR absolute 0x61;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS3_bit at CLKPR.B3;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPCE_bit at CLKPR.B7;
    const register unsigned short int CLKPCE = 7;

sfr data unsigned short volatile WDTCSR absolute 0x60;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP0 = 0;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP1 = 1;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP2 = 2;
    sbit  WDE_bit at WDTCSR.B3;
    const register unsigned short int WDE = 3;
    sbit  WDCE_bit at WDTCSR.B4;
    const register unsigned short int WDCE = 4;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDP3 = 5;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDIE = 6;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIF = 7;

sfr io unsigned short volatile SREG absolute 0x5F;
    sbit  SREG_C_bit at SREG.B0;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_I = 7;

sfr io unsigned short volatile SPH absolute 0x5E;
    sbit  SP8_bit at SPH.B0;
    const register unsigned short int SP8 = 0;
    sbit  SP9_bit at SPH.B1;
    const register unsigned short int SP9 = 1;
    sbit  SP10_bit at SPH.B2;
    const register unsigned short int SP10 = 2;
    sbit  SP11_bit at SPH.B3;
    const register unsigned short int SP11 = 3;
    sbit  SP12_bit at SPH.B4;
    const register unsigned short int SP12 = 4;
    sbit  SP13_bit at SPH.B5;
    const register unsigned short int SP13 = 5;
    sbit  SP14_bit at SPH.B6;
    const register unsigned short int SP14 = 6;
    sbit  SP15_bit at SPH.B7;
    const register unsigned short int SP15 = 7;

sfr io unsigned short volatile SPL absolute 0x5D;
    sbit  SP0_bit at SPL.B0;
    const register unsigned short int SP0 = 0;
    sbit  SP1_bit at SPL.B1;
    const register unsigned short int SP1 = 1;
    sbit  SP2_bit at SPL.B2;
    const register unsigned short int SP2 = 2;
    sbit  SP3_bit at SPL.B3;
    const register unsigned short int SP3 = 3;
    sbit  SP4_bit at SPL.B4;
    const register unsigned short int SP4 = 4;
    sbit  SP5_bit at SPL.B5;
    const register unsigned short int SP5 = 5;
    sbit  SP6_bit at SPL.B6;
    const register unsigned short int SP6 = 6;
    sbit  SP7_bit at SPL.B7;
    const register unsigned short int SP7 = 7;

sfr io unsigned short volatile SPMCSR absolute 0x57;
    sbit  SPMEN_bit at SPMCSR.B0;
    const register unsigned short int SPMEN = 0;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int PGERS = 1;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGWRT = 2;
    sbit  BLBSET_bit at SPMCSR.B3;
    const register unsigned short int BLBSET = 3;
    sbit  RWWSRE_bit at SPMCSR.B4;
    const register unsigned short int RWWSRE = 4;
    sbit  SIGRD_bit at SPMCSR.B5;
    const register unsigned short int SIGRD = 5;
    sbit  RWWSB_bit at SPMCSR.B6;
    const register unsigned short int RWWSB = 6;
    sbit  SPMIE_bit at SPMCSR.B7;
    const register unsigned short int SPMIE = 7;

sfr io unsigned short volatile MCUCR absolute 0x55;
    sbit  IVCE_bit at MCUCR.B0;
    const register unsigned short int IVCE = 0;
    sbit  IVSEL_bit at MCUCR.B1;
    const register unsigned short int IVSEL = 1;
    sbit  PUD_bit at MCUCR.B4;
    const register unsigned short int PUD = 4;
    sbit  SPIPS_bit at MCUCR.B7;
    const register unsigned short int SPIPS = 7;

sfr io unsigned short volatile MCUSR absolute 0x54;
    sbit  PORF_bit at MCUSR.B0;
    const register unsigned short int PORF = 0;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int EXTRF = 1;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int BORF = 2;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int WDRF = 3;

sfr io unsigned short SMCR absolute 0x53;
    sbit  SE_bit at SMCR.B0;
    const register unsigned short int SE = 0;
    sbit  SM0_bit at SMCR.B1;
    const register unsigned short int SM0 = 1;
    sbit  SM1_bit at SMCR.B2;
    const register unsigned short int SM1 = 2;
    sbit  SM2_bit at SMCR.B3;
    const register unsigned short int SM2 = 3;

sfr io unsigned short volatile DWDR absolute 0x51;

sfr io unsigned short volatile ACSR absolute 0x50;
    sbit  AC0O_bit at ACSR.B0;
    const register unsigned short int AC0O = 0;
    sbit  AC1O_bit at ACSR.B1;
    const register unsigned short int AC1O = 1;
    sbit  AC2O_bit at ACSR.B2;
    const register unsigned short int AC2O = 2;
    sbit  AC3O_bit at ACSR.B3;
    const register unsigned short int AC3O = 3;
    sbit  AC0IF_bit at ACSR.B4;
    const register unsigned short int AC0IF = 4;
    sbit  AC1IF_bit at ACSR.B5;
    const register unsigned short int AC1IF = 5;
    sbit  AC2IF_bit at ACSR.B6;
    const register unsigned short int AC2IF = 6;
    sbit  AC3IF_bit at ACSR.B7;
    const register unsigned short int AC3IF = 7;

sfr io unsigned short volatile SPDR absolute 0x4E;
    sbit  SPDR0_bit at SPDR.B0;
    const register unsigned short int SPDR0 = 0;
    sbit  SPDR1_bit at SPDR.B1;
    const register unsigned short int SPDR1 = 1;
    sbit  SPDR2_bit at SPDR.B2;
    const register unsigned short int SPDR2 = 2;
    sbit  SPDR3_bit at SPDR.B3;
    const register unsigned short int SPDR3 = 3;
    sbit  SPDR4_bit at SPDR.B4;
    const register unsigned short int SPDR4 = 4;
    sbit  SPDR5_bit at SPDR.B5;
    const register unsigned short int SPDR5 = 5;
    sbit  SPDR6_bit at SPDR.B6;
    const register unsigned short int SPDR6 = 6;
    sbit  SPDR7_bit at SPDR.B7;
    const register unsigned short int SPDR7 = 7;

sfr io unsigned short volatile SPSR absolute 0x4D;
    sbit  SPI2X_bit at SPSR.B0;
    const register unsigned short int SPI2X = 0;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int WCOL = 6;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int SPIF = 7;

sfr io unsigned short SPCR absolute 0x4C;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR0 = 0;
    sbit  SPR1_bit at SPCR.B1;
    const register unsigned short int SPR1 = 1;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int CPHA = 2;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPOL = 3;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int MSTR = 4;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int DORD = 5;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int SPE = 6;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPIE = 7;

sfr io unsigned short volatile PLLCSR absolute 0x49;
    sbit  PLOCK_bit at PLLCSR.B0;
    const register unsigned short int PLOCK = 0;
    sbit  PLLE_bit at PLLCSR.B1;
    const register unsigned short int PLLE = 1;
    sbit  PLLF_bit at PLLCSR.B2;
    const register unsigned short int PLLF = 2;

sfr io unsigned short OCR0B absolute 0x48;
    sbit  OCR0B_0_bit at OCR0B.B0;
    const register unsigned short int OCR0B_0 = 0;
    sbit  OCR0B_1_bit at OCR0B.B1;
    const register unsigned short int OCR0B_1 = 1;
    sbit  OCR0B_2_bit at OCR0B.B2;
    const register unsigned short int OCR0B_2 = 2;
    sbit  OCR0B_3_bit at OCR0B.B3;
    const register unsigned short int OCR0B_3 = 3;
    sbit  OCR0B_4_bit at OCR0B.B4;
    const register unsigned short int OCR0B_4 = 4;
    sbit  OCR0B_5_bit at OCR0B.B5;
    const register unsigned short int OCR0B_5 = 5;
    sbit  OCR0B_6_bit at OCR0B.B6;
    const register unsigned short int OCR0B_6 = 6;
    sbit  OCR0B_7_bit at OCR0B.B7;
    const register unsigned short int OCR0B_7 = 7;

sfr io unsigned short OCR0A absolute 0x47;
    sbit  OCR0A_0_bit at OCR0A.B0;
    const register unsigned short int OCR0A_0 = 0;
    sbit  OCR0A_1_bit at OCR0A.B1;
    const register unsigned short int OCR0A_1 = 1;
    sbit  OCR0A_2_bit at OCR0A.B2;
    const register unsigned short int OCR0A_2 = 2;
    sbit  OCR0A_3_bit at OCR0A.B3;
    const register unsigned short int OCR0A_3 = 3;
    sbit  OCR0A_4_bit at OCR0A.B4;
    const register unsigned short int OCR0A_4 = 4;
    sbit  OCR0A_5_bit at OCR0A.B5;
    const register unsigned short int OCR0A_5 = 5;
    sbit  OCR0A_6_bit at OCR0A.B6;
    const register unsigned short int OCR0A_6 = 6;
    sbit  OCR0A_7_bit at OCR0A.B7;
    const register unsigned short int OCR0A_7 = 7;

sfr io unsigned short volatile TCNT0 absolute 0x46;
    sbit  TCNT0_0_bit at TCNT0.B0;
    const register unsigned short int TCNT0_0 = 0;
    sbit  TCNT0_1_bit at TCNT0.B1;
    const register unsigned short int TCNT0_1 = 1;
    sbit  TCNT0_2_bit at TCNT0.B2;
    const register unsigned short int TCNT0_2 = 2;
    sbit  TCNT0_3_bit at TCNT0.B3;
    const register unsigned short int TCNT0_3 = 3;
    sbit  TCNT0_4_bit at TCNT0.B4;
    const register unsigned short int TCNT0_4 = 4;
    sbit  TCNT0_5_bit at TCNT0.B5;
    const register unsigned short int TCNT0_5 = 5;
    sbit  TCNT0_6_bit at TCNT0.B6;
    const register unsigned short int TCNT0_6 = 6;
    sbit  TCNT0_7_bit at TCNT0.B7;
    const register unsigned short int TCNT0_7 = 7;

sfr io unsigned short TCCR0B absolute 0x45;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS00 = 0;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS01 = 1;
    sbit  CS02_bit at TCCR0B.B2;
    const register unsigned short int CS02 = 2;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int WGM02 = 3;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0A = 7;

sfr io unsigned short TCCR0A absolute 0x44;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM00 = 0;
    sbit  WGM01_bit at TCCR0A.B1;
    const register unsigned short int WGM01 = 1;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0A1 = 7;

sfr io unsigned short volatile GTCCR absolute 0x43;
    sbit  PSR10_bit at GTCCR.B0;
    const register unsigned short int PSR10 = 0;
    sbit  ICPSEL1_bit at GTCCR.B6;
    const register unsigned short int ICPSEL1 = 6;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int TSM = 7;
    sbit  PSRSYNC_bit at GTCCR.B0;
    const register unsigned short int PSRSYNC = 0;

sfr io unsigned short EEARH absolute 0x42;
    sbit  EEAR8_bit at EEARH.B0;
    const register unsigned short int EEAR8 = 0;
    sbit  EEAR9_bit at EEARH.B1;
    const register unsigned short int EEAR9 = 1;
    sbit  EEAR10_bit at EEARH.B2;
    const register unsigned short int EEAR10 = 2;

sfr io unsigned short EEARL absolute 0x41;
    sbit  EEAR0_bit at EEARL.B0;
    const register unsigned short int EEAR0 = 0;
    sbit  EEAR1_bit at EEARL.B1;
    const register unsigned short int EEAR1 = 1;
    sbit  EEAR2_bit at EEARL.B2;
    const register unsigned short int EEAR2 = 2;
    sbit  EEAR3_bit at EEARL.B3;
    const register unsigned short int EEAR3 = 3;
    sbit  EEAR4_bit at EEARL.B4;
    const register unsigned short int EEAR4 = 4;
    sbit  EEAR5_bit at EEARL.B5;
    const register unsigned short int EEAR5 = 5;
    sbit  EEAR6_bit at EEARL.B6;
    const register unsigned short int EEAR6 = 6;
    sbit  EEAR7_bit at EEARL.B7;
    const register unsigned short int EEAR7 = 7;

sfr io unsigned short volatile EEDR absolute 0x40;
    sbit  EEDR0_bit at EEDR.B0;
    const register unsigned short int EEDR0 = 0;
    sbit  EEDR1_bit at EEDR.B1;
    const register unsigned short int EEDR1 = 1;
    sbit  EEDR2_bit at EEDR.B2;
    const register unsigned short int EEDR2 = 2;
    sbit  EEDR3_bit at EEDR.B3;
    const register unsigned short int EEDR3 = 3;
    sbit  EEDR4_bit at EEDR.B4;
    const register unsigned short int EEDR4 = 4;
    sbit  EEDR5_bit at EEDR.B5;
    const register unsigned short int EEDR5 = 5;
    sbit  EEDR6_bit at EEDR.B6;
    const register unsigned short int EEDR6 = 6;
    sbit  EEDR7_bit at EEDR.B7;
    const register unsigned short int EEDR7 = 7;

sfr io unsigned short volatile EECR absolute 0x3F;
    sbit  EERE_bit at EECR.B0;
    const register unsigned short int EERE = 0;
    sbit  EEWE_bit at EECR.B1;
    const register unsigned short int EEWE = 1;
    sbit  EEMWE_bit at EECR.B2;
    const register unsigned short int EEMWE = 2;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EERIE = 3;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EEPM1 = 5;

sfr io unsigned short volatile GPIOR0 absolute 0x3E;
    sbit  GPIOR00_bit at GPIOR0.B0;
    const register unsigned short int GPIOR00 = 0;
    sbit  GPIOR01_bit at GPIOR0.B1;
    const register unsigned short int GPIOR01 = 1;
    sbit  GPIOR02_bit at GPIOR0.B2;
    const register unsigned short int GPIOR02 = 2;
    sbit  GPIOR03_bit at GPIOR0.B3;
    const register unsigned short int GPIOR03 = 3;
    sbit  GPIOR04_bit at GPIOR0.B4;
    const register unsigned short int GPIOR04 = 4;
    sbit  GPIOR05_bit at GPIOR0.B5;
    const register unsigned short int GPIOR05 = 5;
    sbit  GPIOR06_bit at GPIOR0.B6;
    const register unsigned short int GPIOR06 = 6;
    sbit  GPIOR07_bit at GPIOR0.B7;
    const register unsigned short int GPIOR07 = 7;

sfr io unsigned short EIMSK absolute 0x3D;
    sbit  INT0_bit at EIMSK.B0;
    const register unsigned short int INT0 = 0;
    sbit  INT1_bit at EIMSK.B1;
    const register unsigned short int INT1 = 1;
    sbit  INT2_bit at EIMSK.B2;
    const register unsigned short int INT2 = 2;
    sbit  INT3_bit at EIMSK.B3;
    const register unsigned short int INT3 = 3;

sfr io unsigned short volatile EIFR absolute 0x3C;
    sbit  INTF0_bit at EIFR.B0;
    const register unsigned short int INTF0 = 0;
    sbit  INTF1_bit at EIFR.B1;
    const register unsigned short int INTF1 = 1;
    sbit  INTF2_bit at EIFR.B2;
    const register unsigned short int INTF2 = 2;
    sbit  INTF3_bit at EIFR.B3;
    const register unsigned short int INTF3 = 3;

sfr io unsigned short volatile PCIFR absolute 0x3B;
    sbit  PCIF0_bit at PCIFR.B0;
    const register unsigned short int PCIF0 = 0;
    sbit  PCIF1_bit at PCIFR.B1;
    const register unsigned short int PCIF1 = 1;
    sbit  PCIF2_bit at PCIFR.B2;
    const register unsigned short int PCIF2 = 2;
    sbit  PCIF3_bit at PCIFR.B3;
    const register unsigned short int PCIF3 = 3;

sfr io unsigned short volatile GPIOR2 absolute 0x3A;
    sbit  GPIOR20_bit at GPIOR2.B0;
    const register unsigned short int GPIOR20 = 0;
    sbit  GPIOR21_bit at GPIOR2.B1;
    const register unsigned short int GPIOR21 = 1;
    sbit  GPIOR22_bit at GPIOR2.B2;
    const register unsigned short int GPIOR22 = 2;
    sbit  GPIOR23_bit at GPIOR2.B3;
    const register unsigned short int GPIOR23 = 3;
    sbit  GPIOR24_bit at GPIOR2.B4;
    const register unsigned short int GPIOR24 = 4;
    sbit  GPIOR25_bit at GPIOR2.B5;
    const register unsigned short int GPIOR25 = 5;
    sbit  GPIOR26_bit at GPIOR2.B6;
    const register unsigned short int GPIOR26 = 6;
    sbit  GPIOR27_bit at GPIOR2.B7;
    const register unsigned short int GPIOR27 = 7;

sfr io unsigned short volatile GPIOR1 absolute 0x39;
    sbit  GPIOR10_bit at GPIOR1.B0;
    const register unsigned short int GPIOR10 = 0;
    sbit  GPIOR11_bit at GPIOR1.B1;
    const register unsigned short int GPIOR11 = 1;
    sbit  GPIOR12_bit at GPIOR1.B2;
    const register unsigned short int GPIOR12 = 2;
    sbit  GPIOR13_bit at GPIOR1.B3;
    const register unsigned short int GPIOR13 = 3;
    sbit  GPIOR14_bit at GPIOR1.B4;
    const register unsigned short int GPIOR14 = 4;
    sbit  GPIOR15_bit at GPIOR1.B5;
    const register unsigned short int GPIOR15 = 5;
    sbit  GPIOR16_bit at GPIOR1.B6;
    const register unsigned short int GPIOR16 = 6;
    sbit  GPIOR17_bit at GPIOR1.B7;
    const register unsigned short int GPIOR17 = 7;

sfr io unsigned short volatile TIFR1 absolute 0x36;
    sbit  TOV1_bit at TIFR1.B0;
    const register unsigned short int TOV1 = 0;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1B = 2;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int ICF1 = 5;

sfr io unsigned short volatile TIFR0 absolute 0x35;
    sbit  TOV0_bit at TIFR0.B0;
    const register unsigned short int TOV0 = 0;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0B = 2;

sfr io unsigned short PORTE absolute 0x2E;
    sbit  PORTE0_bit at PORTE.B0;
    const register unsigned short int PORTE0 = 0;
    sbit  PORTE1_bit at PORTE.B1;
    const register unsigned short int PORTE1 = 1;
    sbit  PORTE2_bit at PORTE.B2;
    const register unsigned short int PORTE2 = 2;

sfr io unsigned short DDRE absolute 0x2D;
    sbit  DDE0_bit at DDRE.B0;
    const register unsigned short int DDE0 = 0;
    sbit  DDE1_bit at DDRE.B1;
    const register unsigned short int DDE1 = 1;
    sbit  DDE2_bit at DDRE.B2;
    const register unsigned short int DDE2 = 2;

sfr io unsigned short volatile PINE absolute 0x2C;
    sbit  PINE0_bit at PINE.B0;
    const register unsigned short int PINE0 = 0;
    sbit  PINE1_bit at PINE.B1;
    const register unsigned short int PINE1 = 1;
    sbit  PINE2_bit at PINE.B2;
    const register unsigned short int PINE2 = 2;

sfr io unsigned short PORTD absolute 0x2B;
    sbit  PORTD0_bit at PORTD.B0;
    const register unsigned short int PORTD0 = 0;
    sbit  PORTD1_bit at PORTD.B1;
    const register unsigned short int PORTD1 = 1;
    sbit  PORTD2_bit at PORTD.B2;
    const register unsigned short int PORTD2 = 2;
    sbit  PORTD3_bit at PORTD.B3;
    const register unsigned short int PORTD3 = 3;
    sbit  PORTD4_bit at PORTD.B4;
    const register unsigned short int PORTD4 = 4;
    sbit  PORTD5_bit at PORTD.B5;
    const register unsigned short int PORTD5 = 5;
    sbit  PORTD6_bit at PORTD.B6;
    const register unsigned short int PORTD6 = 6;
    sbit  PORTD7_bit at PORTD.B7;
    const register unsigned short int PORTD7 = 7;

sfr io unsigned short DDRD absolute 0x2A;
    sbit  DDD0_bit at DDRD.B0;
    const register unsigned short int DDD0 = 0;
    sbit  DDD1_bit at DDRD.B1;
    const register unsigned short int DDD1 = 1;
    sbit  DDD2_bit at DDRD.B2;
    const register unsigned short int DDD2 = 2;
    sbit  DDD3_bit at DDRD.B3;
    const register unsigned short int DDD3 = 3;
    sbit  DDD4_bit at DDRD.B4;
    const register unsigned short int DDD4 = 4;
    sbit  DDD5_bit at DDRD.B5;
    const register unsigned short int DDD5 = 5;
    sbit  DDD6_bit at DDRD.B6;
    const register unsigned short int DDD6 = 6;
    sbit  DDD7_bit at DDRD.B7;
    const register unsigned short int DDD7 = 7;

sfr io unsigned short volatile PIND absolute 0x29;
    sbit  PIND0_bit at PIND.B0;
    const register unsigned short int PIND0 = 0;
    sbit  PIND1_bit at PIND.B1;
    const register unsigned short int PIND1 = 1;
    sbit  PIND2_bit at PIND.B2;
    const register unsigned short int PIND2 = 2;
    sbit  PIND3_bit at PIND.B3;
    const register unsigned short int PIND3 = 3;
    sbit  PIND4_bit at PIND.B4;
    const register unsigned short int PIND4 = 4;
    sbit  PIND5_bit at PIND.B5;
    const register unsigned short int PIND5 = 5;
    sbit  PIND6_bit at PIND.B6;
    const register unsigned short int PIND6 = 6;
    sbit  PIND7_bit at PIND.B7;
    const register unsigned short int PIND7 = 7;

sfr io unsigned short PORTC absolute 0x28;
    sbit  PORTC0_bit at PORTC.B0;
    const register unsigned short int PORTC0 = 0;
    sbit  PORTC1_bit at PORTC.B1;
    const register unsigned short int PORTC1 = 1;
    sbit  PORTC2_bit at PORTC.B2;
    const register unsigned short int PORTC2 = 2;
    sbit  PORTC3_bit at PORTC.B3;
    const register unsigned short int PORTC3 = 3;
    sbit  PORTC4_bit at PORTC.B4;
    const register unsigned short int PORTC4 = 4;
    sbit  PORTC5_bit at PORTC.B5;
    const register unsigned short int PORTC5 = 5;
    sbit  PORTC6_bit at PORTC.B6;
    const register unsigned short int PORTC6 = 6;
    sbit  PORTC7_bit at PORTC.B7;
    const register unsigned short int PORTC7 = 7;

sfr io unsigned short DDRC absolute 0x27;
    sbit  DDC0_bit at DDRC.B0;
    const register unsigned short int DDC0 = 0;
    sbit  DDC1_bit at DDRC.B1;
    const register unsigned short int DDC1 = 1;
    sbit  DDC2_bit at DDRC.B2;
    const register unsigned short int DDC2 = 2;
    sbit  DDC3_bit at DDRC.B3;
    const register unsigned short int DDC3 = 3;
    sbit  DDC4_bit at DDRC.B4;
    const register unsigned short int DDC4 = 4;
    sbit  DDC5_bit at DDRC.B5;
    const register unsigned short int DDC5 = 5;
    sbit  DDC6_bit at DDRC.B6;
    const register unsigned short int DDC6 = 6;
    sbit  DDC7_bit at DDRC.B7;
    const register unsigned short int DDC7 = 7;

sfr io unsigned short volatile PINC absolute 0x26;
    sbit  PINC0_bit at PINC.B0;
    const register unsigned short int PINC0 = 0;
    sbit  PINC1_bit at PINC.B1;
    const register unsigned short int PINC1 = 1;
    sbit  PINC2_bit at PINC.B2;
    const register unsigned short int PINC2 = 2;
    sbit  PINC3_bit at PINC.B3;
    const register unsigned short int PINC3 = 3;
    sbit  PINC4_bit at PINC.B4;
    const register unsigned short int PINC4 = 4;
    sbit  PINC5_bit at PINC.B5;
    const register unsigned short int PINC5 = 5;
    sbit  PINC6_bit at PINC.B6;
    const register unsigned short int PINC6 = 6;
    sbit  PINC7_bit at PINC.B7;
    const register unsigned short int PINC7 = 7;

sfr io unsigned short PORTB absolute 0x25;
    sbit  PORTB0_bit at PORTB.B0;
    const register unsigned short int PORTB0 = 0;
    sbit  PORTB1_bit at PORTB.B1;
    const register unsigned short int PORTB1 = 1;
    sbit  PORTB2_bit at PORTB.B2;
    const register unsigned short int PORTB2 = 2;
    sbit  PORTB3_bit at PORTB.B3;
    const register unsigned short int PORTB3 = 3;
    sbit  PORTB4_bit at PORTB.B4;
    const register unsigned short int PORTB4 = 4;
    sbit  PORTB5_bit at PORTB.B5;
    const register unsigned short int PORTB5 = 5;
    sbit  PORTB6_bit at PORTB.B6;
    const register unsigned short int PORTB6 = 6;
    sbit  PORTB7_bit at PORTB.B7;
    const register unsigned short int PORTB7 = 7;

sfr io unsigned short DDRB absolute 0x24;
    sbit  DDB0_bit at DDRB.B0;
    const register unsigned short int DDB0 = 0;
    sbit  DDB1_bit at DDRB.B1;
    const register unsigned short int DDB1 = 1;
    sbit  DDB2_bit at DDRB.B2;
    const register unsigned short int DDB2 = 2;
    sbit  DDB3_bit at DDRB.B3;
    const register unsigned short int DDB3 = 3;
    sbit  DDB4_bit at DDRB.B4;
    const register unsigned short int DDB4 = 4;
    sbit  DDB5_bit at DDRB.B5;
    const register unsigned short int DDB5 = 5;
    sbit  DDB6_bit at DDRB.B6;
    const register unsigned short int DDB6 = 6;
    sbit  DDB7_bit at DDRB.B7;
    const register unsigned short int DDB7 = 7;

sfr io unsigned short volatile PINB absolute 0x23;
    sbit  PINB0_bit at PINB.B0;
    const register unsigned short int PINB0 = 0;
    sbit  PINB1_bit at PINB.B1;
    const register unsigned short int PINB1 = 1;
    sbit  PINB2_bit at PINB.B2;
    const register unsigned short int PINB2 = 2;
    sbit  PINB3_bit at PINB.B3;
    const register unsigned short int PINB3 = 3;
    sbit  PINB4_bit at PINB.B4;
    const register unsigned short int PINB4 = 4;
    sbit  PINB5_bit at PINB.B5;
    const register unsigned short int PINB5 = 5;
    sbit  PINB6_bit at PINB.B6;
    const register unsigned short int PINB6 = 6;
    sbit  PINB7_bit at PINB.B7;
    const register unsigned short int PINB7 = 7;
