// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00001000;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;


// Interrupt Vector Table Constants
const unsigned short IVT_ADDR_INT0 = 0x0001;
const unsigned short IVT_ADDR_PCINT0 = 0x0002;
const unsigned short IVT_ADDR_PCINT1 = 0x0003;
const unsigned short IVT_ADDR_WDT = 0x0004;
const unsigned short IVT_ADDR_TIMER1_CAPT = 0x0005;
const unsigned short IVT_ADDR_TIMER1_COMPA = 0x0006;
const unsigned short IVT_ADDR_TIMER1_COMPB = 0x0007;
const unsigned short IVT_ADDR_TIMER1_OVF = 0x0008;
const unsigned short IVT_ADDR_TIMER0_COMPA = 0x0009;
const unsigned short IVT_ADDR_TIMER0_COMPB = 0x000A;
const unsigned short IVT_ADDR_TIMER0_OVF = 0x000B;
const unsigned short IVT_ADDR_ANA_COMP0 = 0x000C;
const unsigned short IVT_ADDR_ADC = 0x000D;
const unsigned short IVT_ADDR_EE_RDY = 0x000E;
const unsigned short IVT_ADDR_ANA_COMP1 = 0x000F;
const unsigned short IVT_ADDR_TIMER2_CAPT = 0x0010;
const unsigned short IVT_ADDR_TIMER2_COMPA = 0x0011;
const unsigned short IVT_ADDR_TIMER2_COMPB = 0x0012;
const unsigned short IVT_ADDR_TIMER2_OVF = 0x0013;
const unsigned short IVT_ADDR_SPI = 0x0014;
const unsigned short IVT_ADDR_USART0_START = 0x0015;
const unsigned short IVT_ADDR_USART0_RX = 0x0016;
const unsigned short IVT_ADDR_USART0_UDRE = 0x0017;
const unsigned short IVT_ADDR_USART0_TX = 0x0018;
const unsigned short IVT_ADDR_USART1_START = 0x0019;
const unsigned short IVT_ADDR_USART1_RX = 0x001A;
const unsigned short IVT_ADDR_USART1_UDRE = 0x001B;
const unsigned short IVT_ADDR_USART1_TX = 0x001C;
const unsigned short IVT_ADDR_TWI_SLAVE = 0x001D;

sfr data unsigned char volatile PORTCR                    absolute 0x0064;
    const register unsigned short int BBMB = 1;
    sbit  BBMB_bit at PORTCR.B1;

sfr data unsigned char volatile PUEB                      absolute 0x0062;
sfr io   unsigned char DDRB                      absolute 0x0037;
sfr io   unsigned char volatile PINB                      absolute 0x0036;
sfr io   unsigned char PORTB                     absolute 0x0038;
sfr data unsigned char volatile PORTCR_PORTA              absolute 0x0064;
    const register unsigned short int BBMA = 0;
    sbit  BBMA_bit at PORTCR_PORTA.B0;

sfr data unsigned char volatile PUEA                      absolute 0x0063;
sfr io   unsigned char PORTA                     absolute 0x003B;
sfr io   unsigned char DDRA                      absolute 0x003A;
sfr io   unsigned char volatile PINA                      absolute 0x0039;
sfr data unsigned char volatile PHDE                      absolute 0x006A;
    const register unsigned short int PHDEA0 = 0;
    sbit  PHDEA0_bit at PHDE.B0;
    const register unsigned short int PHDEA1 = 1;
    sbit  PHDEA1_bit at PHDE.B1;

sfr data unsigned char volatile UDR1                      absolute 0x0090;
sfr data unsigned char volatile UCSR1A                    absolute 0x0096;
    const register unsigned short int RXC1 = 7;
    sbit  RXC1_bit at UCSR1A.B7;
    const register unsigned short int TXC1 = 6;
    sbit  TXC1_bit at UCSR1A.B6;
    const register unsigned short int UDRE1 = 5;
    sbit  UDRE1_bit at UCSR1A.B5;
    const register unsigned short int FE1 = 4;
    sbit  FE1_bit at UCSR1A.B4;
    const register unsigned short int DOR1 = 3;
    sbit  DOR1_bit at UCSR1A.B3;
    const register unsigned short int UPE1 = 2;
    sbit  UPE1_bit at UCSR1A.B2;
    const register unsigned short int U2X1 = 1;
    sbit  U2X1_bit at UCSR1A.B1;
    const register unsigned short int MPCM1 = 0;
    sbit  MPCM1_bit at UCSR1A.B0;

sfr data unsigned char volatile UCSR1B                    absolute 0x0095;
    const register unsigned short int RXCIE1 = 7;
    sbit  RXCIE1_bit at UCSR1B.B7;
    const register unsigned short int TXCIE1 = 6;
    sbit  TXCIE1_bit at UCSR1B.B6;
    const register unsigned short int UDRIE1 = 5;
    sbit  UDRIE1_bit at UCSR1B.B5;
    const register unsigned short int RXEN1 = 4;
    sbit  RXEN1_bit at UCSR1B.B4;
    const register unsigned short int TXEN1 = 3;
    sbit  TXEN1_bit at UCSR1B.B3;
    const register unsigned short int UCSZ12 = 2;
    sbit  UCSZ12_bit at UCSR1B.B2;
    const register unsigned short int RXB81 = 1;
    sbit  RXB81_bit at UCSR1B.B1;
    const register unsigned short int TXB81 = 0;
    sbit  TXB81_bit at UCSR1B.B0;

sfr data unsigned char volatile UCSR1C                    absolute 0x0094;
    const register unsigned short int UMSEL10 = 6;
    sbit  UMSEL10_bit at UCSR1C.B6;
    const register unsigned short int UMSEL11 = 7;
    sbit  UMSEL11_bit at UCSR1C.B7;
    const register unsigned short int UPM10 = 4;
    sbit  UPM10_bit at UCSR1C.B4;
    const register unsigned short int UPM11 = 5;
    sbit  UPM11_bit at UCSR1C.B5;
    const register unsigned short int USBS1 = 3;
    sbit  USBS1_bit at UCSR1C.B3;
    const register unsigned short int UCSZ10 = 1;
    sbit  UCSZ10_bit at UCSR1C.B1;
    const register unsigned short int UCSZ11 = 2;
    sbit  UCSZ11_bit at UCSR1C.B2;
    const register unsigned short int UCPOL1 = 0;
    sbit  UCPOL1_bit at UCSR1C.B0;

sfr data unsigned char volatile UCSR1D                    absolute 0x0093;
    const register unsigned short int RXSIE1 = 7;
    sbit  RXSIE1_bit at UCSR1D.B7;
    const register unsigned short int RXS1 = 6;
    sbit  RXS1_bit at UCSR1D.B6;
    const register unsigned short int SFDE1 = 5;
    sbit  SFDE1_bit at UCSR1D.B5;

sfr data unsigned int  UBRR1                     absolute 0x0091;
sfr data unsigned char UBRR1L                    absolute 0x0091;
sfr data unsigned char UBRR1H                    absolute 0x0092;
sfr data unsigned char volatile UDR0                      absolute 0x0080;
sfr data unsigned char volatile UCSR0A                    absolute 0x0086;
    const register unsigned short int RXC0 = 7;
    sbit  RXC0_bit at UCSR0A.B7;
    const register unsigned short int TXC0 = 6;
    sbit  TXC0_bit at UCSR0A.B6;
    const register unsigned short int UDRE0 = 5;
    sbit  UDRE0_bit at UCSR0A.B5;
    const register unsigned short int FE0 = 4;
    sbit  FE0_bit at UCSR0A.B4;
    const register unsigned short int DOR0 = 3;
    sbit  DOR0_bit at UCSR0A.B3;
    const register unsigned short int UPE0 = 2;
    sbit  UPE0_bit at UCSR0A.B2;
    const register unsigned short int U2X0 = 1;
    sbit  U2X0_bit at UCSR0A.B1;
    const register unsigned short int MPCM0 = 0;
    sbit  MPCM0_bit at UCSR0A.B0;

sfr data unsigned char volatile UCSR0B                    absolute 0x0085;
    const register unsigned short int RXCIE0 = 7;
    sbit  RXCIE0_bit at UCSR0B.B7;
    const register unsigned short int TXCIE0 = 6;
    sbit  TXCIE0_bit at UCSR0B.B6;
    const register unsigned short int UDRIE0 = 5;
    sbit  UDRIE0_bit at UCSR0B.B5;
    const register unsigned short int RXEN0 = 4;
    sbit  RXEN0_bit at UCSR0B.B4;
    const register unsigned short int TXEN0 = 3;
    sbit  TXEN0_bit at UCSR0B.B3;
    const register unsigned short int UCSZ02 = 2;
    sbit  UCSZ02_bit at UCSR0B.B2;
    const register unsigned short int RXB80 = 1;
    sbit  RXB80_bit at UCSR0B.B1;
    const register unsigned short int TXB80 = 0;
    sbit  TXB80_bit at UCSR0B.B0;

sfr data unsigned char volatile UCSR0C                    absolute 0x0084;
    const register unsigned short int UMSEL00 = 6;
    sbit  UMSEL00_bit at UCSR0C.B6;
    const register unsigned short int UMSEL01 = 7;
    sbit  UMSEL01_bit at UCSR0C.B7;
    const register unsigned short int UPM00 = 4;
    sbit  UPM00_bit at UCSR0C.B4;
    const register unsigned short int UPM01 = 5;
    sbit  UPM01_bit at UCSR0C.B5;
    const register unsigned short int USBS0 = 3;
    sbit  USBS0_bit at UCSR0C.B3;
    const register unsigned short int UCSZ00 = 1;
    sbit  UCSZ00_bit at UCSR0C.B1;
    const register unsigned short int UCSZ01 = 2;
    sbit  UCSZ01_bit at UCSR0C.B2;
    const register unsigned short int UCPOL0 = 0;
    sbit  UCPOL0_bit at UCSR0C.B0;

sfr data unsigned char volatile UCSR0D                    absolute 0x0083;
    const register unsigned short int RXSIE0 = 7;
    sbit  RXSIE0_bit at UCSR0D.B7;
    const register unsigned short int RXS0 = 6;
    sbit  RXS0_bit at UCSR0D.B6;
    const register unsigned short int SFDE0 = 5;
    sbit  SFDE0_bit at UCSR0D.B5;

sfr data unsigned int  UBRR0                     absolute 0x0081;
sfr data unsigned char UBRR0L                    absolute 0x0081;
sfr data unsigned char UBRR0H                    absolute 0x0082;
sfr data unsigned char volatile REMAP                     absolute 0x0065;
    const register unsigned short int U0MAP = 0;
    sbit  U0MAP_bit at REMAP.B0;

sfr io   unsigned char volatile WDTCSR                    absolute 0x0041;
    const register unsigned short int WDIF = 7;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIE = 6;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDP0 = 0;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP1 = 1;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP2 = 2;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP3 = 5;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDE = 3;
    sbit  WDE_bit at WDTCSR.B3;

sfr data unsigned char volatile TWSCRA                    absolute 0x00A5;
    const register unsigned short int TWSHE = 7;
    sbit  TWSHE_bit at TWSCRA.B7;
    const register unsigned short int TWDIE = 5;
    sbit  TWDIE_bit at TWSCRA.B5;
    const register unsigned short int TWASIE = 4;
    sbit  TWASIE_bit at TWSCRA.B4;
    const register unsigned short int TWEN = 3;
    sbit  TWEN_bit at TWSCRA.B3;
    const register unsigned short int TWSIE = 2;
    sbit  TWSIE_bit at TWSCRA.B2;
    const register unsigned short int TWPME = 1;
    sbit  TWPME_bit at TWSCRA.B1;
    const register unsigned short int TWSME = 0;
    sbit  TWSME_bit at TWSCRA.B0;

sfr data unsigned char volatile TWSCRB                    absolute 0x00A4;
    const register unsigned short int TWHNM = 3;
    sbit  TWHNM_bit at TWSCRB.B3;
    const register unsigned short int TWAA = 2;
    sbit  TWAA_bit at TWSCRB.B2;
    const register unsigned short int TWCMD0 = 0;
    sbit  TWCMD0_bit at TWSCRB.B0;
    const register unsigned short int TWCMD1 = 1;
    sbit  TWCMD1_bit at TWSCRB.B1;

sfr data unsigned char volatile TWSSRA                    absolute 0x00A3;
    const register unsigned short int TWDIF = 7;
    sbit  TWDIF_bit at TWSSRA.B7;
    const register unsigned short int TWASIF = 6;
    sbit  TWASIF_bit at TWSSRA.B6;
    const register unsigned short int TWCH = 5;
    sbit  TWCH_bit at TWSSRA.B5;
    const register unsigned short int TWRA = 4;
    sbit  TWRA_bit at TWSSRA.B4;
    const register unsigned short int TWC = 3;
    sbit  TWC_bit at TWSSRA.B3;
    const register unsigned short int TWBE = 2;
    sbit  TWBE_bit at TWSSRA.B2;
    const register unsigned short int TWDIR = 1;
    sbit  TWDIR_bit at TWSSRA.B1;
    const register unsigned short int TWAS = 0;
    sbit  TWAS_bit at TWSSRA.B0;

sfr data unsigned char volatile TWSA                      absolute 0x00A2;
sfr data unsigned char volatile TWSD                      absolute 0x00A0;
    const register unsigned short int TWSD0 = 0;
    sbit  TWSD0_bit at TWSD.B0;
    const register unsigned short int TWSD1 = 1;
    sbit  TWSD1_bit at TWSD.B1;
    const register unsigned short int TWSD2 = 2;
    sbit  TWSD2_bit at TWSD.B2;
    const register unsigned short int TWSD3 = 3;
    sbit  TWSD3_bit at TWSD.B3;
    const register unsigned short int TWSD4 = 4;
    sbit  TWSD4_bit at TWSD.B4;
    const register unsigned short int TWSD5 = 5;
    sbit  TWSD5_bit at TWSD.B5;
    const register unsigned short int TWSD6 = 6;
    sbit  TWSD6_bit at TWSD.B6;
    const register unsigned short int TWSD7 = 7;
    sbit  TWSD7_bit at TWSD.B7;

sfr data unsigned char volatile TWSAM                     absolute 0x00A1;
    const register unsigned short int TWSAM0 = 1;
    sbit  TWSAM0_bit at TWSAM.B1;
    const register unsigned short int TWSAM1 = 2;
    sbit  TWSAM1_bit at TWSAM.B2;
    const register unsigned short int TWSAM2 = 3;
    sbit  TWSAM2_bit at TWSAM.B3;
    const register unsigned short int TWSAM3 = 4;
    sbit  TWSAM3_bit at TWSAM.B4;
    const register unsigned short int TWSAM4 = 5;
    sbit  TWSAM4_bit at TWSAM.B5;
    const register unsigned short int TWSAM5 = 6;
    sbit  TWSAM5_bit at TWSAM.B6;
    const register unsigned short int TWSAM6 = 7;
    sbit  TWSAM6_bit at TWSAM.B7;
    const register unsigned short int TWAE = 0;
    sbit  TWAE_bit at TWSAM.B0;

sfr io   unsigned char volatile ADMUXA                    absolute 0x0029;
    const register unsigned short int MUX0 = 0;
    sbit  MUX0_bit at ADMUXA.B0;
    const register unsigned short int MUX1 = 1;
    sbit  MUX1_bit at ADMUXA.B1;
    const register unsigned short int MUX2 = 2;
    sbit  MUX2_bit at ADMUXA.B2;
    const register unsigned short int MUX3 = 3;
    sbit  MUX3_bit at ADMUXA.B3;
    const register unsigned short int MUX4 = 4;
    sbit  MUX4_bit at ADMUXA.B4;
    const register unsigned short int MUX5 = 5;
    sbit  MUX5_bit at ADMUXA.B5;

sfr io   unsigned char volatile ADMUXB                    absolute 0x0028;
    const register unsigned short int REFS0 = 5;
    sbit  REFS0_bit at ADMUXB.B5;
    const register unsigned short int REFS1 = 6;
    sbit  REFS1_bit at ADMUXB.B6;
    const register unsigned short int REFS2 = 7;
    sbit  REFS2_bit at ADMUXB.B7;
    const register unsigned short int GSEL0 = 0;
    sbit  GSEL0_bit at ADMUXB.B0;
    const register unsigned short int GSEL1 = 1;
    sbit  GSEL1_bit at ADMUXB.B1;

sfr io   unsigned char volatile ADCSRA                    absolute 0x0025;
    const register unsigned short int ADEN = 7;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADSC = 6;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADATE = 5;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADIF = 4;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIE = 3;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS2 = 2;
    sbit  ADPS2_bit at ADCSRA.B2;

sfr io   unsigned int  volatile ADC                       absolute 0x0026;
sfr io   unsigned char volatile ADCL                      absolute 0x0026;
sfr io   unsigned char volatile ADCH                      absolute 0x0027;
sfr io   unsigned char ADCSRB                    absolute 0x0024;
    const register unsigned short int ADLAR = 3;
    sbit  ADLAR_bit at ADCSRB.B3;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS2_bit at ADCSRB.B2;

sfr data unsigned char DIDR1                     absolute 0x0061;
    const register unsigned short int ADC9D = 3;
    sbit  ADC9D_bit at DIDR1.B3;
    const register unsigned short int ADC8D = 2;
    sbit  ADC8D_bit at DIDR1.B2;
    const register unsigned short int ADC10D = 1;
    sbit  ADC10D_bit at DIDR1.B1;
    const register unsigned short int ADC11D = 0;
    sbit  ADC11D_bit at DIDR1.B0;

sfr data unsigned char DIDR0                     absolute 0x0060;
    const register unsigned short int ADC7D = 7;
    sbit  ADC7D_bit at DIDR0.B7;
    const register unsigned short int ADC6D = 6;
    sbit  ADC6D_bit at DIDR0.B6;
    const register unsigned short int ADC5D = 5;
    sbit  ADC5D_bit at DIDR0.B5;
    const register unsigned short int ADC4D = 4;
    sbit  ADC4D_bit at DIDR0.B4;
    const register unsigned short int ADC3D = 3;
    sbit  ADC3D_bit at DIDR0.B3;
    const register unsigned short int ADC2D = 2;
    sbit  ADC2D_bit at DIDR0.B2;
    const register unsigned short int ADC1D = 1;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC0D = 0;
    sbit  ADC0D_bit at DIDR0.B0;

sfr io   unsigned char volatile ACSR0B                    absolute 0x002B;
    const register unsigned short int HSEL0 = 7;
    sbit  HSEL0_bit at ACSR0B.B7;
    const register unsigned short int HLEV0 = 6;
    sbit  HLEV0_bit at ACSR0B.B6;
    const register unsigned short int ACOE0 = 4;
    sbit  ACOE0_bit at ACSR0B.B4;
    const register unsigned short int ACNMUX0 = 2;
    sbit  ACNMUX0_bit at ACSR0B.B2;
    const register unsigned short int ACNMUX1 = 3;
    sbit  ACNMUX1_bit at ACSR0B.B3;
    const register unsigned short int ACPMUX0 = 0;
    sbit  ACPMUX0_bit at ACSR0B.B0;
    const register unsigned short int ACPMUX1 = 1;
    sbit  ACPMUX1_bit at ACSR0B.B1;

sfr io   unsigned char volatile ACSR0A                    absolute 0x002A;
    const register unsigned short int ACD0 = 7;
    sbit  ACD0_bit at ACSR0A.B7;
    const register unsigned short int ACPMUX2 = 6;
    sbit  ACPMUX2_bit at ACSR0A.B6;
    const register unsigned short int ACO0 = 5;
    sbit  ACO0_bit at ACSR0A.B5;
    const register unsigned short int ACI0 = 4;
    sbit  ACI0_bit at ACSR0A.B4;
    const register unsigned short int ACIE0 = 3;
    sbit  ACIE0_bit at ACSR0A.B3;
    const register unsigned short int ACIC0 = 2;
    sbit  ACIC0_bit at ACSR0A.B2;
    const register unsigned short int ACIS00 = 0;
    sbit  ACIS00_bit at ACSR0A.B0;
    const register unsigned short int ACIS01 = 1;
    sbit  ACIS01_bit at ACSR0A.B1;

sfr io   unsigned char volatile ACSR1B                    absolute 0x002D;
    const register unsigned short int HSEL1 = 7;
    sbit  HSEL1_bit at ACSR1B.B7;
    const register unsigned short int HLEV1 = 6;
    sbit  HLEV1_bit at ACSR1B.B6;
    const register unsigned short int ACOE1 = 4;
    sbit  ACOE1_bit at ACSR1B.B4;
    const register unsigned short int ACME1 = 2;
    sbit  ACME1_bit at ACSR1B.B2;

sfr io   unsigned char volatile ACSR1A                    absolute 0x002C;
    const register unsigned short int ACD1 = 7;
    sbit  ACD1_bit at ACSR1A.B7;
    const register unsigned short int ACBG1 = 6;
    sbit  ACBG1_bit at ACSR1A.B6;
    const register unsigned short int ACO1 = 5;
    sbit  ACO1_bit at ACSR1A.B5;
    const register unsigned short int ACI1 = 4;
    sbit  ACI1_bit at ACSR1A.B4;
    const register unsigned short int ACIE1 = 3;
    sbit  ACIE1_bit at ACSR1A.B3;
    const register unsigned short int ACIC1 = 2;
    sbit  ACIC1_bit at ACSR1A.B2;
    const register unsigned short int ACIS10 = 0;
    sbit  ACIS10_bit at ACSR1A.B0;
    const register unsigned short int ACIS11 = 1;
    sbit  ACIS11_bit at ACSR1A.B1;

sfr io   unsigned int  volatile EEAR                      absolute 0x003E;
sfr io   unsigned char volatile EEARL                     absolute 0x003E;
sfr io   unsigned char volatile EEARH                     absolute 0x003F;
sfr io   unsigned char volatile EEDR                      absolute 0x003D;
sfr io   unsigned char volatile EECR                      absolute 0x003C;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM1 = 5;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EERIE = 3;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EEMPE = 2;
    sbit  EEMPE_bit at EECR.B2;
    const register unsigned short int EEPE = 1;
    sbit  EEPE_bit at EECR.B1;
    const register unsigned short int EERE = 0;
    sbit  EERE_bit at EECR.B0;

sfr io   unsigned char TIMSK1                    absolute 0x002F;
    const register unsigned short int ICIE1 = 5;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int OCIE1B = 2;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int TOIE1 = 0;
    sbit  TOIE1_bit at TIMSK1.B0;

sfr io   unsigned char volatile TIFR1                     absolute 0x002E;
    const register unsigned short int ICF1 = 5;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int OCF1B = 2;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int TOV1 = 0;
    sbit  TOV1_bit at TIFR1.B0;

sfr io   unsigned char TCCR1A                    absolute 0x004F;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A1 = 7;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int WGM10 = 0;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM11 = 1;
    sbit  WGM11_bit at TCCR1A.B1;

sfr io   unsigned char TCCR1B                    absolute 0x004E;
    const register unsigned short int ICNC1 = 7;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICES1 = 6;
    sbit  ICES1_bit at TCCR1B.B6;
    sbit  WGM10_TCCR1B_bit at TCCR1B.B3;
    sbit  WGM11_TCCR1B_bit at TCCR1B.B4;
    const register unsigned short int CS10 = 0;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS11 = 1;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS12 = 2;
    sbit  CS12_bit at TCCR1B.B2;

sfr io   unsigned char volatile TCCR1C                    absolute 0x0042;
    const register unsigned short int FOC1A = 7;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1B_bit at TCCR1C.B6;

sfr io   unsigned int  volatile TCNT1                     absolute 0x004C;
sfr io   unsigned char volatile TCNT1L                    absolute 0x004C;
sfr io   unsigned char volatile TCNT1H                    absolute 0x004D;
sfr io   unsigned int  volatile OCR1A                     absolute 0x004A;
sfr io   unsigned char volatile OCR1AL                    absolute 0x004A;
sfr io   unsigned char volatile OCR1AH                    absolute 0x004B;
sfr io   unsigned int  volatile OCR1B                     absolute 0x0048;
sfr io   unsigned char volatile OCR1BL                    absolute 0x0048;
sfr io   unsigned char volatile OCR1BH                    absolute 0x0049;
sfr io   unsigned int  volatile ICR1                      absolute 0x0044;
sfr io   unsigned char volatile GTCCR                     absolute 0x0043;
    const register unsigned short int TSM = 7;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int PSR = 0;
    sbit  PSR_bit at GTCCR.B0;

sfr io   unsigned char TIMSK2                    absolute 0x0031;
    const register unsigned short int ICIE2 = 5;
    sbit  ICIE2_bit at TIMSK2.B5;
    const register unsigned short int OCIE2B = 2;
    sbit  OCIE2B_bit at TIMSK2.B2;
    const register unsigned short int OCIE2A = 1;
    sbit  OCIE2A_bit at TIMSK2.B1;
    const register unsigned short int TOIE2 = 0;
    sbit  TOIE2_bit at TIMSK2.B0;

sfr io   unsigned char volatile TIFR2                     absolute 0x0030;
    const register unsigned short int ICF2 = 5;
    sbit  ICF2_bit at TIFR2.B5;
    const register unsigned short int OCF2B = 2;
    sbit  OCF2B_bit at TIFR2.B2;
    const register unsigned short int OCF2A = 1;
    sbit  OCF2A_bit at TIFR2.B1;
    const register unsigned short int TOV2 = 0;
    sbit  TOV2_bit at TIFR2.B0;

sfr data unsigned char TCCR2A                    absolute 0x00CA;
    const register unsigned short int COM2A0 = 6;
    sbit  COM2A0_bit at TCCR2A.B6;
    const register unsigned short int COM2A1 = 7;
    sbit  COM2A1_bit at TCCR2A.B7;
    const register unsigned short int COM2B0 = 4;
    sbit  COM2B0_bit at TCCR2A.B4;
    const register unsigned short int COM2B1 = 5;
    sbit  COM2B1_bit at TCCR2A.B5;
    const register unsigned short int WGM20 = 0;
    sbit  WGM20_bit at TCCR2A.B0;
    const register unsigned short int WGM21 = 1;
    sbit  WGM21_bit at TCCR2A.B1;

sfr data unsigned char TCCR2B                    absolute 0x00C9;
    const register unsigned short int ICNC2 = 7;
    sbit  ICNC2_bit at TCCR2B.B7;
    const register unsigned short int ICES2 = 6;
    sbit  ICES2_bit at TCCR2B.B6;
    sbit  WGM20_TCCR2B_bit at TCCR2B.B3;
    sbit  WGM21_TCCR2B_bit at TCCR2B.B4;
    const register unsigned short int CS20 = 0;
    sbit  CS20_bit at TCCR2B.B0;
    const register unsigned short int CS21 = 1;
    sbit  CS21_bit at TCCR2B.B1;
    const register unsigned short int CS22 = 2;
    sbit  CS22_bit at TCCR2B.B2;

sfr data unsigned char volatile TCCR2C                    absolute 0x00C8;
    const register unsigned short int FOC2A = 7;
    sbit  FOC2A_bit at TCCR2C.B7;
    const register unsigned short int FOC2B = 6;
    sbit  FOC2B_bit at TCCR2C.B6;

sfr data unsigned int  volatile TCNT2                     absolute 0x00C6;
sfr data unsigned char volatile TCNT2L                    absolute 0x00C6;
sfr data unsigned char volatile TCNT2H                    absolute 0x00C7;
sfr data unsigned int  OCR2A                     absolute 0x00C4;
sfr data unsigned char OCR2AL                    absolute 0x00C4;
sfr data unsigned char OCR2AH                    absolute 0x00C5;
sfr data unsigned int  OCR2B                     absolute 0x00C2;
sfr data unsigned char OCR2BL                    absolute 0x00C2;
sfr data unsigned char OCR2BH                    absolute 0x00C3;
sfr data unsigned int  volatile ICR2                      absolute 0x00C0;
sfr io   unsigned char volatile GTCCR_TC2                 absolute 0x0043;
    sbit  TSM_GTCCR_TC2_bit at GTCCR_TC2.B7;
    sbit  PSR_GTCCR_TC2_bit at GTCCR_TC2.B0;

sfr io   unsigned char TIMSK0                    absolute 0x0059;
    const register unsigned short int OCIE0B = 2;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int TOIE0 = 0;
    sbit  TOIE0_bit at TIMSK0.B0;

sfr io   unsigned char volatile TIFR0                     absolute 0x0058;
    const register unsigned short int OCF0B = 2;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int TOV0 = 0;
    sbit  TOV0_bit at TIFR0.B0;

sfr io   unsigned char TCCR0A                    absolute 0x0050;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A1 = 7;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int WGM00 = 0;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM01 = 1;
    sbit  WGM01_bit at TCCR0A.B1;

sfr io   unsigned char TCCR0B                    absolute 0x0053;
    const register unsigned short int FOC0A = 7;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int WGM02 = 3;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int CS00 = 0;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS01 = 1;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS02 = 2;
    sbit  CS02_bit at TCCR0B.B2;

sfr io   unsigned char volatile TCNT0                     absolute 0x0052;
sfr io   unsigned char volatile TCNT0L                    absolute 0x0052;
sfr io   unsigned char volatile TCNT0H                    absolute 0x0053;
sfr io   unsigned char OCR0A                     absolute 0x0056;
sfr io   unsigned char OCR0B                     absolute 0x005C;
sfr io   unsigned char volatile GTCCR_TC0                 absolute 0x0043;
    sbit  TSM_GTCCR_TC0_bit at GTCCR_TC0.B7;
    sbit  PSR_GTCCR_TC0_bit at GTCCR_TC0.B0;

sfr io   unsigned char volatile MCUCR                     absolute 0x0055;
    const register unsigned short int ISC01 = 1;
    sbit  ISC01_bit at MCUCR.B1;
    const register unsigned short int ISC00 = 0;
    sbit  ISC00_bit at MCUCR.B0;

sfr io   unsigned char volatile GIMSK                     absolute 0x005B;
    const register unsigned short int INT0 = 6;
    sbit  INT0_bit at GIMSK.B6;
    const register unsigned short int PCIE0 = 4;
    sbit  PCIE0_bit at GIMSK.B4;
    const register unsigned short int PCIE1 = 5;
    sbit  PCIE1_bit at GIMSK.B5;

sfr io   unsigned char volatile GIFR                      absolute 0x005A;
    const register unsigned short int INTF0 = 6;
    sbit  INTF0_bit at GIFR.B6;
    const register unsigned short int PCIF0 = 4;
    sbit  PCIF0_bit at GIFR.B4;
    const register unsigned short int PCIF1 = 5;
    sbit  PCIF1_bit at GIFR.B5;

sfr io   unsigned char PCMSK1                    absolute 0x0040;
    const register unsigned short int PCINT8 = 0;
    sbit  PCINT8_bit at PCMSK1.B0;
    const register unsigned short int PCINT9 = 1;
    sbit  PCINT9_bit at PCMSK1.B1;
    const register unsigned short int PCINT10 = 2;
    sbit  PCINT10_bit at PCMSK1.B2;
    const register unsigned short int PCINT11 = 3;
    sbit  PCINT11_bit at PCMSK1.B3;

sfr io   unsigned char PCMSK0                    absolute 0x0032;
    const register unsigned short int PCINT0 = 0;
    sbit  PCINT0_bit at PCMSK0.B0;
    const register unsigned short int PCINT1 = 1;
    sbit  PCINT1_bit at PCMSK0.B1;
    const register unsigned short int PCINT2 = 2;
    sbit  PCINT2_bit at PCMSK0.B2;
    const register unsigned short int PCINT3 = 3;
    sbit  PCINT3_bit at PCMSK0.B3;
    const register unsigned short int PCINT4 = 4;
    sbit  PCINT4_bit at PCMSK0.B4;
    const register unsigned short int PCINT5 = 5;
    sbit  PCINT5_bit at PCMSK0.B5;
    const register unsigned short int PCINT6 = 6;
    sbit  PCINT6_bit at PCMSK0.B6;
    const register unsigned short int PCINT7 = 7;
    sbit  PCINT7_bit at PCMSK0.B7;

sfr data unsigned char volatile PRR                       absolute 0x0070;
    const register unsigned short int PRTWI = 7;
    sbit  PRTWI_bit at PRR.B7;
    const register unsigned short int PRUSART1 = 6;
    sbit  PRUSART1_bit at PRR.B6;
    const register unsigned short int PRUSART0 = 5;
    sbit  PRUSART0_bit at PRR.B5;
    const register unsigned short int PRSPI = 4;
    sbit  PRSPI_bit at PRR.B4;
    const register unsigned short int PRTIM2 = 3;
    sbit  PRTIM2_bit at PRR.B3;
    const register unsigned short int PRTIM1 = 2;
    sbit  PRTIM1_bit at PRR.B2;
    const register unsigned short int PRTIM0 = 1;
    sbit  PRTIM0_bit at PRR.B1;
    const register unsigned short int PRADC = 0;
    sbit  PRADC_bit at PRR.B0;

sfr data unsigned char volatile CCP                       absolute 0x0071;
sfr data unsigned char volatile CLKPR                     absolute 0x0073;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPS3_bit at CLKPR.B3;

sfr data unsigned char volatile CLKCR                     absolute 0x0072;
    const register unsigned short int OSCRDY = 7;
    sbit  OSCRDY_bit at CLKCR.B7;
    const register unsigned short int CSTR_ = 6;
    sbit  CSTR_bit at CLKCR.B6;
    const register unsigned short int CKOUTC = 5;
    sbit  CKOUTC_bit at CLKCR.B5;
    const register unsigned short int SUT = 4;
    sbit  SUT_bit at CLKCR.B4;
    const register unsigned short int CKSEL0 = 0;
    sbit  CKSEL0_bit at CLKCR.B0;
    const register unsigned short int CKSEL1 = 1;
    sbit  CKSEL1_bit at CLKCR.B1;
    const register unsigned short int CKSEL2 = 2;
    sbit  CKSEL2_bit at CLKCR.B2;
    const register unsigned short int CKSEL3 = 3;
    sbit  CKSEL3_bit at CLKCR.B3;

sfr io   unsigned char volatile SREG                      absolute 0x005F;
    const register unsigned short int SREG_I = 7;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_C_bit at SREG.B0;

sfr io   unsigned int  volatile SP                        absolute 0x005D;
sfr io   unsigned char volatile SPL                       absolute 0x005D;
sfr io   unsigned char volatile MCUCR_CPU                 absolute 0x0055;
    const register unsigned short int SE = 5;
    sbit  SE_bit at MCUCR_CPU.B5;
    const register unsigned short int SM0 = 3;
    sbit  SM0_bit at MCUCR_CPU.B3;
    const register unsigned short int SM1 = 4;
    sbit  SM1_bit at MCUCR_CPU.B4;
    sbit  ISC00_MCUCR_CPU_bit at MCUCR_CPU.B0;
    sbit  ISC01_MCUCR_CPU_bit at MCUCR_CPU.B1;

sfr io   unsigned char volatile MCUSR                     absolute 0x0054;
    const register unsigned short int WDRF = 3;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int BORF = 2;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int EXTRF = 1;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int PORF = 0;
    sbit  PORF_bit at MCUSR.B0;

sfr io   unsigned char volatile GPIOR2                    absolute 0x0035;
sfr io   unsigned char volatile GPIOR1                    absolute 0x0034;
sfr io   unsigned char volatile GPIOR0                    absolute 0x0033;
sfr io   unsigned char volatile SPMCSR                    absolute 0x0057;
    const register unsigned short int RSIG = 5;
    sbit  RSIG_bit at SPMCSR.B5;
    const register unsigned short int CTPB = 4;
    sbit  CTPB_bit at SPMCSR.B4;
    const register unsigned short int RFLB = 3;
    sbit  RFLB_bit at SPMCSR.B3;
    const register unsigned short int PGWRT = 2;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGERS = 1;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int SPMEN = 0;
    sbit  SPMEN_bit at SPMCSR.B0;

sfr data unsigned char volatile OSCCAL0                   absolute 0x0074;
sfr data unsigned char volatile OSCCAL1                   absolute 0x0077;
sfr data unsigned char volatile OSCTCAL0A                 absolute 0x0075;
sfr data unsigned char volatile OSCTCAL0B                 absolute 0x0076;
sfr data unsigned char volatile TOCPMSA1                  absolute 0x0068;
    const register unsigned short int TOCC7S0 = 6;
    sbit  TOCC7S0_bit at TOCPMSA1.B6;
    const register unsigned short int TOCC7S1 = 7;
    sbit  TOCC7S1_bit at TOCPMSA1.B7;
    const register unsigned short int TOCC6S0 = 4;
    sbit  TOCC6S0_bit at TOCPMSA1.B4;
    const register unsigned short int TOCC6S1 = 5;
    sbit  TOCC6S1_bit at TOCPMSA1.B5;
    const register unsigned short int TOCC5S0 = 2;
    sbit  TOCC5S0_bit at TOCPMSA1.B2;
    const register unsigned short int TOCC5S1 = 3;
    sbit  TOCC5S1_bit at TOCPMSA1.B3;
    const register unsigned short int TOCC4S0 = 0;
    sbit  TOCC4S0_bit at TOCPMSA1.B0;
    const register unsigned short int TOCC4S1 = 1;
    sbit  TOCC4S1_bit at TOCPMSA1.B1;

sfr data unsigned char volatile TOCPMSA0                  absolute 0x0067;
    const register unsigned short int TOCC3S0 = 6;
    sbit  TOCC3S0_bit at TOCPMSA0.B6;
    const register unsigned short int TOCC3S1 = 7;
    sbit  TOCC3S1_bit at TOCPMSA0.B7;
    const register unsigned short int TOCC2S0 = 4;
    sbit  TOCC2S0_bit at TOCPMSA0.B4;
    const register unsigned short int TOCC2S1 = 5;
    sbit  TOCC2S1_bit at TOCPMSA0.B5;
    const register unsigned short int TOCC1S0 = 2;
    sbit  TOCC1S0_bit at TOCPMSA0.B2;
    const register unsigned short int TOCC1S1 = 3;
    sbit  TOCC1S1_bit at TOCPMSA0.B3;
    const register unsigned short int TOCC0S0 = 0;
    sbit  TOCC0S0_bit at TOCPMSA0.B0;
    const register unsigned short int TOCC0S1 = 1;
    sbit  TOCC0S1_bit at TOCPMSA0.B1;

sfr data unsigned char volatile TOCPMCOE                  absolute 0x0066;
    const register unsigned short int TOCC7OE = 7;
    sbit  TOCC7OE_bit at TOCPMCOE.B7;
    const register unsigned short int TOCC6OE = 6;
    sbit  TOCC6OE_bit at TOCPMCOE.B6;
    const register unsigned short int TOCC5OE = 5;
    sbit  TOCC5OE_bit at TOCPMCOE.B5;
    const register unsigned short int TOCC4OE = 4;
    sbit  TOCC4OE_bit at TOCPMCOE.B4;
    const register unsigned short int TOCC3OE = 3;
    sbit  TOCC3OE_bit at TOCPMCOE.B3;
    const register unsigned short int TOCC2OE = 2;
    sbit  TOCC2OE_bit at TOCPMCOE.B2;
    const register unsigned short int TOCC1OE = 1;
    sbit  TOCC1OE_bit at TOCPMCOE.B1;
    const register unsigned short int TOCC0OE = 0;
    sbit  TOCC0OE_bit at TOCPMCOE.B0;

sfr data unsigned char SPCR                      absolute 0x00B2;
    const register unsigned short int SPIE = 7;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPE = 6;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int DORD = 5;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int MSTR = 4;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int CPOL = 3;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPHA = 2;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int SPR0 = 0;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR1 = 1;
    sbit  SPR1_bit at SPCR.B1;

sfr data unsigned char volatile SPSR                      absolute 0x00B1;
    const register unsigned short int SPIF = 7;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int WCOL = 6;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int SPI2X = 0;
    sbit  SPI2X_bit at SPSR.B0;

sfr data unsigned char volatile SPDR                      absolute 0x00B0;
sfr data unsigned char volatile REMAP_SPI                 absolute 0x0065;
    const register unsigned short int SPIMAP = 1;
    sbit  SPIMAP_bit at REMAP_SPI.B1;

sfr io   unsigned char volatile EXTENDED_                 absolute 0x0002;
    const register unsigned short int ULPOSCSEL0 = 5;
    sbit  ULPOSCSEL0_bit at EXTENDED_.B5;
    const register unsigned short int ULPOSCSEL1 = 6;
    sbit  ULPOSCSEL1_bit at EXTENDED_.B6;
    const register unsigned short int ULPOSCSEL2 = 7;
    sbit  ULPOSCSEL2_bit at EXTENDED_.B7;
    const register unsigned short int BODPD0 = 3;
    sbit  BODPD0_bit at EXTENDED_.B3;
    const register unsigned short int BODPD1 = 4;
    sbit  BODPD1_bit at EXTENDED_.B4;
    const register unsigned short int BODACT0 = 1;
    sbit  BODACT0_bit at EXTENDED_.B1;
    const register unsigned short int BODACT1 = 2;
    sbit  BODACT1_bit at EXTENDED_.B2;
    const register unsigned short int SELFPRGEN = 0;
    sbit  SELFPRGEN_bit at EXTENDED_.B0;

sfr io   unsigned char volatile HIGH                      absolute 0x0001;
    const register unsigned short int RSTDISBL = 7;
    sbit  RSTDISBL_bit at HIGH.B7;
    const register unsigned short int DWEN = 6;
    sbit  DWEN_bit at HIGH.B6;
    const register unsigned short int SPIEN = 5;
    sbit  SPIEN_bit at HIGH.B5;
    const register unsigned short int WDTON = 4;
    sbit  WDTON_bit at HIGH.B4;
    const register unsigned short int EESAVE = 3;
    sbit  EESAVE_bit at HIGH.B3;
    const register unsigned short int BODLEVEL0 = 0;
    sbit  BODLEVEL0_bit at HIGH.B0;
    const register unsigned short int BODLEVEL1 = 1;
    sbit  BODLEVEL1_bit at HIGH.B1;
    const register unsigned short int BODLEVEL2 = 2;
    sbit  BODLEVEL2_bit at HIGH.B2;

sfr io   unsigned char volatile LOW                       absolute 0x0000;
    const register unsigned short int CKDIV8 = 7;
    sbit  CKDIV8_bit at LOW.B7;
    const register unsigned short int CKOUT = 6;
    sbit  CKOUT_bit at LOW.B6;
    const register unsigned short int SUT_CKSEL0 = 0;
    sbit  SUT_CKSEL0_bit at LOW.B0;
    const register unsigned short int SUT_CKSEL1 = 1;
    sbit  SUT_CKSEL1_bit at LOW.B1;
    const register unsigned short int SUT_CKSEL2 = 2;
    sbit  SUT_CKSEL2_bit at LOW.B2;
    const register unsigned short int SUT_CKSEL3 = 3;
    sbit  SUT_CKSEL3_bit at LOW.B3;
    const register unsigned short int SUT_CKSEL4 = 4;
    sbit  SUT_CKSEL4_bit at LOW.B4;

sfr io   unsigned char volatile LOCKBIT                   absolute 0x0000;
    const register unsigned short int LB0 = 0;
    sbit  LB0_bit at LOCKBIT.B0;
    const register unsigned short int LB1 = 1;
    sbit  LB1_bit at LOCKBIT.B1;

