// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00004000;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;


// Interrupt Vector Table Constants
const unsigned short IVT_ADDR_INT0 = 0x0002;
const unsigned short IVT_ADDR_PCINT0 = 0x0004;
const unsigned short IVT_ADDR_PCINT1 = 0x0006;
const unsigned short IVT_ADDR_PCINT2 = 0x0008;
const unsigned short IVT_ADDR_WDT = 0x000A;
const unsigned short IVT_ADDR_TIMER1_CAPT = 0x000C;
const unsigned short IVT_ADDR_TIM1_CAPT = 0x000C;
const unsigned short IVT_ADDR_TIMER1_COMPA = 0x000E;
const unsigned short IVT_ADDR_TIM1_COMPA = 0x000E;
const unsigned short IVT_ADDR_TIMER1_COMPB = 0x0010;
const unsigned short IVT_ADDR_TIM1_COMPB = 0x0010;
const unsigned short IVT_ADDR_TIMER1_OVF = 0x0012;
const unsigned short IVT_ADDR_TIM1_OVF = 0x0012;
const unsigned short IVT_ADDR_TIMER0_COMPA = 0x0014;
const unsigned short IVT_ADDR_TIM0_COMPA = 0x0014;
const unsigned short IVT_ADDR_TIMER0_COMPB = 0x0016;
const unsigned short IVT_ADDR_TIM0_COMPB = 0x0016;
const unsigned short IVT_ADDR_TIMER0_OVF = 0x0018;
const unsigned short IVT_ADDR_TIM0_OVF = 0x0018;
const unsigned short IVT_ADDR_ANA_COMP = 0x001A;
const unsigned short IVT_ADDR_ADC = 0x001C;
const unsigned short IVT_ADDR_ADC_READY = 0x001C;
const unsigned short IVT_ADDR_USART0_START = 0x001E;
const unsigned short IVT_ADDR_USART0_RXS = 0x001E;
const unsigned short IVT_ADDR_USART0_RX = 0x0020;
const unsigned short IVT_ADDR_USART0_RXC = 0x0020;
const unsigned short IVT_ADDR_USART0_UDRE = 0x0022;
const unsigned short IVT_ADDR_USART0_DRE = 0x0022;
const unsigned short IVT_ADDR_USART0_TX = 0x0024;
const unsigned short IVT_ADDR_USART0_TXC = 0x0024;
const unsigned short IVT_ADDR_USART1_START = 0x0026;
const unsigned short IVT_ADDR_USART1_RXS = 0x0026;
const unsigned short IVT_ADDR_USART1_RX = 0x0028;
const unsigned short IVT_ADDR_USART1_RXC = 0x0028;
const unsigned short IVT_ADDR_USART1_UDRE = 0x002A;
const unsigned short IVT_ADDR_USART1_DRE = 0x002A;
const unsigned short IVT_ADDR_USART1_TX = 0x002C;
const unsigned short IVT_ADDR_USART1_TXC = 0x002C;
const unsigned short IVT_ADDR_USI_START = 0x002E;
const unsigned short IVT_ADDR_USI_STR = 0x002E;
const unsigned short IVT_ADDR_USI_OVERFLOW = 0x0030;
const unsigned short IVT_ADDR_USI_OVF = 0x0030;
const unsigned short IVT_ADDR_TWI_SLAVE = 0x0032;
const unsigned short IVT_ADDR_TWI = 0x0032;
const unsigned short IVT_ADDR_EE_RDY = 0x0034;
const unsigned short IVT_ADDR_QTRIP = 0x0036;

sfr data unsigned char volatile TWSCRA                    absolute 0x007F;
    const register unsigned short int TWSHE = 7;
    sbit  TWSHE_bit at TWSCRA.B7;
    const register unsigned short int TWDIE = 5;
    sbit  TWDIE_bit at TWSCRA.B5;
    const register unsigned short int TWASIE = 4;
    sbit  TWASIE_bit at TWSCRA.B4;
    const register unsigned short int TWEN = 3;
    sbit  TWEN_bit at TWSCRA.B3;
    const register unsigned short int TWSIE = 2;
    sbit  TWSIE_bit at TWSCRA.B2;
    const register unsigned short int TWPME = 1;
    sbit  TWPME_bit at TWSCRA.B1;
    const register unsigned short int TWSME = 0;
    sbit  TWSME_bit at TWSCRA.B0;

sfr data unsigned char volatile TWSCRB                    absolute 0x007E;
    const register unsigned short int TWAA = 2;
    sbit  TWAA_bit at TWSCRB.B2;
    const register unsigned short int TWCMD0 = 0;
    sbit  TWCMD0_bit at TWSCRB.B0;
    const register unsigned short int TWCMD1 = 1;
    sbit  TWCMD1_bit at TWSCRB.B1;

sfr data unsigned char volatile TWSSRA                    absolute 0x007D;
    const register unsigned short int TWDIF = 7;
    sbit  TWDIF_bit at TWSSRA.B7;
    const register unsigned short int TWASIF = 6;
    sbit  TWASIF_bit at TWSSRA.B6;
    const register unsigned short int TWCH = 5;
    sbit  TWCH_bit at TWSSRA.B5;
    const register unsigned short int TWRA = 4;
    sbit  TWRA_bit at TWSSRA.B4;
    const register unsigned short int TWC = 3;
    sbit  TWC_bit at TWSSRA.B3;
    const register unsigned short int TWBE = 2;
    sbit  TWBE_bit at TWSSRA.B2;
    const register unsigned short int TWDIR = 1;
    sbit  TWDIR_bit at TWSSRA.B1;
    const register unsigned short int TWAS = 0;
    sbit  TWAS_bit at TWSSRA.B0;

sfr data unsigned char volatile TWSA                      absolute 0x007C;
    const register unsigned short int TWSA0 = 0;
    sbit  TWSA0_bit at TWSA.B0;
    const register unsigned short int TWSA1 = 1;
    sbit  TWSA1_bit at TWSA.B1;
    const register unsigned short int TWSA2 = 2;
    sbit  TWSA2_bit at TWSA.B2;
    const register unsigned short int TWSA3 = 3;
    sbit  TWSA3_bit at TWSA.B3;
    const register unsigned short int TWSA4 = 4;
    sbit  TWSA4_bit at TWSA.B4;
    const register unsigned short int TWSA5 = 5;
    sbit  TWSA5_bit at TWSA.B5;
    const register unsigned short int TWSA6 = 6;
    sbit  TWSA6_bit at TWSA.B6;
    const register unsigned short int TWSA7 = 7;
    sbit  TWSA7_bit at TWSA.B7;

sfr data unsigned char volatile TWSD                      absolute 0x007A;
    const register unsigned short int TWSD0 = 0;
    sbit  TWSD0_bit at TWSD.B0;
    const register unsigned short int TWSD1 = 1;
    sbit  TWSD1_bit at TWSD.B1;
    const register unsigned short int TWSD2 = 2;
    sbit  TWSD2_bit at TWSD.B2;
    const register unsigned short int TWSD3 = 3;
    sbit  TWSD3_bit at TWSD.B3;
    const register unsigned short int TWSD4 = 4;
    sbit  TWSD4_bit at TWSD.B4;
    const register unsigned short int TWSD5 = 5;
    sbit  TWSD5_bit at TWSD.B5;
    const register unsigned short int TWSD6 = 6;
    sbit  TWSD6_bit at TWSD.B6;
    const register unsigned short int TWSD7 = 7;
    sbit  TWSD7_bit at TWSD.B7;

sfr data unsigned char volatile TWSAM                     absolute 0x007B;
sfr io   unsigned char volatile PORTCR                    absolute 0x0033;
    const register unsigned short int BBMB = 1;
    sbit  BBMB_bit at PORTCR.B1;

sfr io   unsigned char volatile PUEB                      absolute 0x002E;
    const register unsigned short int PUEB0 = 0;
    sbit  PUEB0_bit at PUEB.B0;
    const register unsigned short int PUEB1 = 1;
    sbit  PUEB1_bit at PUEB.B1;
    const register unsigned short int PUEB2 = 2;
    sbit  PUEB2_bit at PUEB.B2;
    const register unsigned short int PUEB3 = 3;
    sbit  PUEB3_bit at PUEB.B3;

sfr io   unsigned char DDRB                      absolute 0x002C;
sfr io   unsigned char volatile PINB                      absolute 0x002B;
sfr io   unsigned char PORTB                     absolute 0x002D;
sfr io   unsigned char volatile PORTCR_PORTC              absolute 0x0033;
    const register unsigned short int BBMC = 2;
    sbit  BBMC_bit at PORTCR_PORTC.B2;

sfr io   unsigned char volatile PUEC                      absolute 0x002A;
    const register unsigned short int PUEC0 = 0;
    sbit  PUEC0_bit at PUEC.B0;
    const register unsigned short int PUEC1 = 1;
    sbit  PUEC1_bit at PUEC.B1;
    const register unsigned short int PUEC2 = 2;
    sbit  PUEC2_bit at PUEC.B2;
    const register unsigned short int PUEC3 = 3;
    sbit  PUEC3_bit at PUEC.B3;
    const register unsigned short int PUEC4 = 4;
    sbit  PUEC4_bit at PUEC.B4;
    const register unsigned short int PUEC5 = 5;
    sbit  PUEC5_bit at PUEC.B5;

sfr io   unsigned char PORTC                     absolute 0x0029;
sfr io   unsigned char DDRC                      absolute 0x0028;
sfr io   unsigned char volatile PINC                      absolute 0x0027;
sfr io   unsigned char volatile PORTCR_PORTA              absolute 0x0033;
    const register unsigned short int BBMA = 0;
    sbit  BBMA_bit at PORTCR_PORTA.B0;

sfr io   unsigned char volatile PUEA                      absolute 0x0032;
    const register unsigned short int PUEA0 = 0;
    sbit  PUEA0_bit at PUEA.B0;
    const register unsigned short int PUEA1 = 1;
    sbit  PUEA1_bit at PUEA.B1;
    const register unsigned short int PUEA2 = 2;
    sbit  PUEA2_bit at PUEA.B2;
    const register unsigned short int PUEA3 = 3;
    sbit  PUEA3_bit at PUEA.B3;
    const register unsigned short int PUEA4 = 4;
    sbit  PUEA4_bit at PUEA.B4;
    const register unsigned short int PUEA5 = 5;
    sbit  PUEA5_bit at PUEA.B5;
    const register unsigned short int PUEA6 = 6;
    sbit  PUEA6_bit at PUEA.B6;
    const register unsigned short int PUEA7 = 7;
    sbit  PUEA7_bit at PUEA.B7;

sfr io   unsigned char PORTA                     absolute 0x0031;
sfr io   unsigned char DDRA                      absolute 0x0030;
sfr io   unsigned char volatile PINA                      absolute 0x002F;
sfr io   unsigned char ADMUX                     absolute 0x0024;
    const register unsigned short int REFS0 = 6;
    sbit  REFS0_bit at ADMUX.B6;
    const register unsigned short int REFS1 = 7;
    sbit  REFS1_bit at ADMUX.B7;
    const register unsigned short int REFEN = 5;
    sbit  REFEN_bit at ADMUX.B5;
    const register unsigned short int ADC0EN = 4;
    sbit  ADC0EN_bit at ADMUX.B4;
    const register unsigned short int MUX0 = 0;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX1 = 1;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX2 = 2;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX3 = 3;
    sbit  MUX3_bit at ADMUX.B3;

sfr io   unsigned char volatile ADCSRA                    absolute 0x0023;
    const register unsigned short int ADEN = 7;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADSC = 6;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADATE = 5;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADIF = 4;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIE = 3;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS2 = 2;
    sbit  ADPS2_bit at ADCSRA.B2;

sfr io   unsigned int  volatile ADC                       absolute 0x0020;
sfr io   unsigned char volatile ADCL                      absolute 0x0020;
sfr io   unsigned char volatile ADCH                      absolute 0x0021;
sfr io   unsigned char ADCSRB                    absolute 0x0022;
    const register unsigned short int VDEN = 7;
    sbit  VDEN_bit at ADCSRB.B7;
    const register unsigned short int VDPD = 6;
    sbit  VDPD_bit at ADCSRB.B6;
    const register unsigned short int ADLAR = 3;
    sbit  ADLAR_bit at ADCSRB.B3;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS2_bit at ADCSRB.B2;

sfr data unsigned char DIDR2                     absolute 0x0062;
    const register unsigned short int ADC11D = 2;
    sbit  ADC11D_bit at DIDR2.B2;
    const register unsigned short int ADC10D = 1;
    sbit  ADC10D_bit at DIDR2.B1;
    const register unsigned short int ADC9D = 0;
    sbit  ADC9D_bit at DIDR2.B0;

sfr data unsigned char DIDR1                     absolute 0x0061;
    const register unsigned short int ADC8D = 3;
    sbit  ADC8D_bit at DIDR1.B3;
    const register unsigned short int ADC7D = 2;
    sbit  ADC7D_bit at DIDR1.B2;
    const register unsigned short int ADC6D = 1;
    sbit  ADC6D_bit at DIDR1.B1;
    const register unsigned short int ADC5D = 0;
    sbit  ADC5D_bit at DIDR1.B0;

sfr data unsigned char DIDR0                     absolute 0x0060;
    const register unsigned short int ADC4D = 7;
    sbit  ADC4D_bit at DIDR0.B7;
    const register unsigned short int ADC3D = 6;
    sbit  ADC3D_bit at DIDR0.B6;
    const register unsigned short int ADC2D = 5;
    sbit  ADC2D_bit at DIDR0.B5;
    const register unsigned short int ADC1D = 4;
    sbit  ADC1D_bit at DIDR0.B4;
    const register unsigned short int ADC0D = 3;
    sbit  ADC0D_bit at DIDR0.B3;
    const register unsigned short int AIN1D = 2;
    sbit  AIN1D_bit at DIDR0.B2;
    const register unsigned short int AIN0D = 1;
    sbit  AIN0D_bit at DIDR0.B1;
    const register unsigned short int AREFD = 0;
    sbit  AREFD_bit at DIDR0.B0;

sfr io   unsigned char volatile ACSRB                     absolute 0x0025;
    const register unsigned short int HSEL = 7;
    sbit  HSEL_bit at ACSRB.B7;
    const register unsigned short int HLEV = 6;
    sbit  HLEV_bit at ACSRB.B6;
    const register unsigned short int ACLP = 5;
    sbit  ACLP_bit at ACSRB.B5;
    const register unsigned short int ACCE = 3;
    sbit  ACCE_bit at ACSRB.B3;
    const register unsigned short int ACME = 2;
    sbit  ACME_bit at ACSRB.B2;
    const register unsigned short int ACIRS0 = 0;
    sbit  ACIRS0_bit at ACSRB.B0;
    const register unsigned short int ACIRS1 = 1;
    sbit  ACIRS1_bit at ACSRB.B1;

sfr io   unsigned char volatile ACSRA                     absolute 0x0026;
    const register unsigned short int ACD = 7;
    sbit  ACD_bit at ACSRA.B7;
    const register unsigned short int ACBG = 6;
    sbit  ACBG_bit at ACSRA.B6;
    const register unsigned short int ACO = 5;
    sbit  ACO_bit at ACSRA.B5;
    const register unsigned short int ACI = 4;
    sbit  ACI_bit at ACSRA.B4;
    const register unsigned short int ACIE = 3;
    sbit  ACIE_bit at ACSRA.B3;
    const register unsigned short int ACIC = 2;
    sbit  ACIC_bit at ACSRA.B2;
    const register unsigned short int ACIS0 = 0;
    sbit  ACIS0_bit at ACSRA.B0;
    const register unsigned short int ACIS1 = 1;
    sbit  ACIS1_bit at ACSRA.B1;

sfr io   unsigned int  volatile EEAR                      absolute 0x003E;
sfr io   unsigned char volatile EEARL                     absolute 0x003E;
sfr io   unsigned char volatile EEARH                     absolute 0x003F;
sfr io   unsigned char volatile EEDR                      absolute 0x003D;
sfr io   unsigned char volatile EECR                      absolute 0x003C;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM1 = 5;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EERIE = 3;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EEMPE = 2;
    sbit  EEMPE_bit at EECR.B2;
    const register unsigned short int EEPE = 1;
    sbit  EEPE_bit at EECR.B1;
    const register unsigned short int EERE = 0;
    sbit  EERE_bit at EECR.B0;

sfr io   unsigned char TIMSK                     absolute 0x005A;
    const register unsigned short int TOIE1 = 7;
    sbit  TOIE1_bit at TIMSK.B7;
    const register unsigned short int OCIE1A = 6;
    sbit  OCIE1A_bit at TIMSK.B6;
    const register unsigned short int OCIE1B = 5;
    sbit  OCIE1B_bit at TIMSK.B5;
    const register unsigned short int ICIE1 = 3;
    sbit  ICIE1_bit at TIMSK.B3;

sfr io   unsigned char volatile TIFR                      absolute 0x0059;
    const register unsigned short int TOV1 = 7;
    sbit  TOV1_bit at TIFR.B7;
    const register unsigned short int OCF1A = 6;
    sbit  OCF1A_bit at TIFR.B6;
    const register unsigned short int OCF1B = 5;
    sbit  OCF1B_bit at TIFR.B5;
    const register unsigned short int ICF1 = 3;
    sbit  ICF1_bit at TIFR.B3;

sfr data unsigned char TCCR1A                    absolute 0x0072;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A1 = 7;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int WGM10 = 0;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM11 = 1;
    sbit  WGM11_bit at TCCR1A.B1;

sfr data unsigned char TCCR1B                    absolute 0x0071;
    const register unsigned short int ICNC1 = 7;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICES1 = 6;
    sbit  ICES1_bit at TCCR1B.B6;
    sbit  WGM10_TCCR1B_bit at TCCR1B.B3;
    sbit  WGM11_TCCR1B_bit at TCCR1B.B4;
    const register unsigned short int CS10 = 0;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS11 = 1;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS12 = 2;
    sbit  CS12_bit at TCCR1B.B2;

sfr data unsigned char volatile TCCR1C                    absolute 0x0070;
    const register unsigned short int FOC1A = 7;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1B_bit at TCCR1C.B6;

sfr data unsigned int  volatile TCNT1                     absolute 0x006E;
sfr data unsigned char volatile TCNT1L                    absolute 0x006E;
sfr data unsigned char volatile TCNT1H                    absolute 0x006F;
sfr data unsigned int  volatile OCR1A                     absolute 0x006C;
sfr data unsigned char volatile OCR1AL                    absolute 0x006C;
sfr data unsigned char volatile OCR1AH                    absolute 0x006D;
sfr data unsigned int  volatile OCR1B                     absolute 0x006A;
sfr data unsigned char volatile OCR1BL                    absolute 0x006A;
sfr data unsigned char volatile OCR1BH                    absolute 0x006B;
sfr data unsigned int  volatile ICR1                      absolute 0x0068;
sfr data unsigned char volatile GTCCR                     absolute 0x0067;
    const register unsigned short int TSM = 7;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int PSR10 = 0;
    sbit  PSR10_bit at GTCCR.B0;

sfr io   unsigned char volatile TIMSK_TC0                 absolute 0x005A;
    const register unsigned short int OCIE0B = 2;
    sbit  OCIE0B_bit at TIMSK_TC0.B2;
    const register unsigned short int TOIE0 = 1;
    sbit  TOIE0_bit at TIMSK_TC0.B1;
    const register unsigned short int OCIE0A = 0;
    sbit  OCIE0A_bit at TIMSK_TC0.B0;

sfr io   unsigned char volatile TIFR_TC0                  absolute 0x0059;
    const register unsigned short int OCF0B = 2;
    sbit  OCF0B_bit at TIFR_TC0.B2;
    const register unsigned short int TOV0 = 1;
    sbit  TOV0_bit at TIFR_TC0.B1;
    const register unsigned short int OCF0A = 0;
    sbit  OCF0A_bit at TIFR_TC0.B0;

sfr io   unsigned char OCR0B                     absolute 0x0037;
sfr io   unsigned char OCR0A                     absolute 0x0038;
sfr io   unsigned char TCCR0A                    absolute 0x003B;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A1 = 7;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int WGM00 = 0;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM01 = 1;
    sbit  WGM01_bit at TCCR0A.B1;

sfr io   unsigned char volatile TCNT0                     absolute 0x0039;
sfr io   unsigned char volatile TCNT0L                    absolute 0x0039;
sfr io   unsigned char volatile TCNT0H                    absolute 0x003A;
sfr io   unsigned char TCCR0B                    absolute 0x003A;
    const register unsigned short int FOC0A = 7;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int WGM02 = 3;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int CS00 = 0;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS01 = 1;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS02 = 2;
    sbit  CS02_bit at TCCR0B.B2;

sfr data unsigned char volatile GTCCR_TC0                 absolute 0x0067;
    sbit  TSM_GTCCR_TC0_bit at GTCCR_TC0.B7;
    sbit  PSR10_GTCCR_TC0_bit at GTCCR_TC0.B0;

sfr io   unsigned char PCMSK2                    absolute 0x0049;
    const register unsigned short int PCINT0 = 0;
    sbit  PCINT0_bit at PCMSK2.B0;
    const register unsigned short int PCINT1 = 1;
    sbit  PCINT1_bit at PCMSK2.B1;
    const register unsigned short int PCINT2 = 2;
    sbit  PCINT2_bit at PCMSK2.B2;
    const register unsigned short int PCINT3 = 3;
    sbit  PCINT3_bit at PCMSK2.B3;
    const register unsigned short int PCINT4 = 4;
    sbit  PCINT4_bit at PCMSK2.B4;
    const register unsigned short int PCINT5 = 5;
    sbit  PCINT5_bit at PCMSK2.B5;

sfr io   unsigned char PCMSK1                    absolute 0x0048;
    sbit  PCINT0_PCMSK1_bit at PCMSK1.B0;
    sbit  PCINT1_PCMSK1_bit at PCMSK1.B1;
    sbit  PCINT2_PCMSK1_bit at PCMSK1.B2;
    sbit  PCINT3_PCMSK1_bit at PCMSK1.B3;

sfr io   unsigned char PCMSK0                    absolute 0x0047;
    sbit  PCINT0_PCMSK0_bit at PCMSK0.B0;
    sbit  PCINT1_PCMSK0_bit at PCMSK0.B1;
    sbit  PCINT2_PCMSK0_bit at PCMSK0.B2;
    sbit  PCINT3_PCMSK0_bit at PCMSK0.B3;
    sbit  PCINT4_PCMSK0_bit at PCMSK0.B4;
    sbit  PCINT5_PCMSK0_bit at PCMSK0.B5;
    const register unsigned short int PCINT6 = 6;
    sbit  PCINT6_bit at PCMSK0.B6;
    const register unsigned short int PCINT7 = 7;
    sbit  PCINT7_bit at PCMSK0.B7;

sfr io   unsigned char volatile GIFR                      absolute 0x005B;
    const register unsigned short int INTF0 = 6;
    sbit  INTF0_bit at GIFR.B6;
    const register unsigned short int PCIF0 = 3;
    sbit  PCIF0_bit at GIFR.B3;
    const register unsigned short int PCIF1 = 4;
    sbit  PCIF1_bit at GIFR.B4;
    const register unsigned short int PCIF2 = 5;
    sbit  PCIF2_bit at GIFR.B5;

sfr io   unsigned char volatile GIMSK                     absolute 0x005C;
    const register unsigned short int INT0 = 6;
    sbit  INT0_bit at GIMSK.B6;
    const register unsigned short int PCIE0 = 3;
    sbit  PCIE0_bit at GIMSK.B3;
    const register unsigned short int PCIE1 = 4;
    sbit  PCIE1_bit at GIMSK.B4;
    const register unsigned short int PCIE2 = 5;
    sbit  PCIE2_bit at GIMSK.B5;

sfr io   unsigned char volatile PRR                       absolute 0x0054;
    const register unsigned short int PRTWI = 6;
    sbit  PRTWI_bit at PRR.B6;
    const register unsigned short int PRTIM1 = 5;
    sbit  PRTIM1_bit at PRR.B5;
    const register unsigned short int PRTIM0 = 4;
    sbit  PRTIM0_bit at PRR.B4;
    const register unsigned short int PRUSI = 3;
    sbit  PRUSI_bit at PRR.B3;
    const register unsigned short int PRUSART1 = 2;
    sbit  PRUSART1_bit at PRR.B2;
    const register unsigned short int PRUSART0 = 1;
    sbit  PRUSART0_bit at PRR.B1;
    const register unsigned short int PRADC = 0;
    sbit  PRADC_bit at PRR.B0;

sfr io   unsigned char volatile CCP                       absolute 0x004F;
sfr data unsigned char volatile OSCCAL0                   absolute 0x0063;
sfr data unsigned char volatile OSCCAL1                   absolute 0x0066;
sfr data unsigned char volatile OSCTCAL0A                 absolute 0x0064;
sfr data unsigned char volatile OSCTCAL0B                 absolute 0x0065;
sfr io   unsigned char volatile CLKPR                     absolute 0x0053;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPS3_bit at CLKPR.B3;

sfr io   unsigned char volatile CLKSR                     absolute 0x0052;
    const register unsigned short int OSCRDY = 7;
    sbit  OSCRDY_bit at CLKSR.B7;
    const register unsigned short int CSTR_ = 6;
    sbit  CSTR_bit at CLKSR.B6;
    const register unsigned short int CKOUT_IO = 5;
    sbit  CKOUT_IO_bit at CLKSR.B5;
    const register unsigned short int SUT = 4;
    sbit  SUT_bit at CLKSR.B4;
    const register unsigned short int CKSEL0 = 0;
    sbit  CKSEL0_bit at CLKSR.B0;
    const register unsigned short int CKSEL1 = 1;
    sbit  CKSEL1_bit at CLKSR.B1;
    const register unsigned short int CKSEL2 = 2;
    sbit  CKSEL2_bit at CLKSR.B2;
    const register unsigned short int CKSEL3 = 3;
    sbit  CKSEL3_bit at CLKSR.B3;

sfr io   unsigned char volatile SREG                      absolute 0x005F;
    const register unsigned short int SREG_I = 7;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_C_bit at SREG.B0;

sfr io   unsigned int  volatile SP                        absolute 0x005D;
sfr io   unsigned char volatile SPL                       absolute 0x005D;
sfr io   unsigned char volatile MCUCR                     absolute 0x0056;
    const register unsigned short int SM0 = 5;
    sbit  SM0_bit at MCUCR.B5;
    const register unsigned short int SM1 = 6;
    sbit  SM1_bit at MCUCR.B6;
    const register unsigned short int SE = 4;
    sbit  SE_bit at MCUCR.B4;
    const register unsigned short int ISC00 = 0;
    sbit  ISC00_bit at MCUCR.B0;
    const register unsigned short int ISC01 = 1;
    sbit  ISC01_bit at MCUCR.B1;

sfr io   unsigned char volatile MCUSR                     absolute 0x0055;
    const register unsigned short int WDRF = 3;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int BORF = 2;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int EXTRF = 1;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int PORF = 0;
    sbit  PORF_bit at MCUSR.B0;

sfr io   unsigned char volatile GPIOR2                    absolute 0x0036;
sfr io   unsigned char volatile GPIOR1                    absolute 0x0035;
sfr io   unsigned char volatile GPIOR0                    absolute 0x0034;
sfr io   unsigned char volatile SPMCSR                    absolute 0x0057;
    const register unsigned short int RSIG = 5;
    sbit  RSIG_bit at SPMCSR.B5;
    const register unsigned short int CTPB = 4;
    sbit  CTPB_bit at SPMCSR.B4;
    const register unsigned short int RFLB = 3;
    sbit  RFLB_bit at SPMCSR.B3;
    const register unsigned short int PGWRT = 2;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGERS = 1;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int SPMEN = 0;
    sbit  SPMEN_bit at SPMCSR.B0;

sfr io   unsigned char volatile USIBR                     absolute 0x004D;
sfr io   unsigned char volatile USIDR                     absolute 0x004C;
sfr io   unsigned char volatile USISR                     absolute 0x004B;
    const register unsigned short int USISIF = 7;
    sbit  USISIF_bit at USISR.B7;
    const register unsigned short int USIOIF = 6;
    sbit  USIOIF_bit at USISR.B6;
    const register unsigned short int USIPF = 5;
    sbit  USIPF_bit at USISR.B5;
    const register unsigned short int USIDC = 4;
    sbit  USIDC_bit at USISR.B4;
    const register unsigned short int USICNT0 = 0;
    sbit  USICNT0_bit at USISR.B0;
    const register unsigned short int USICNT1 = 1;
    sbit  USICNT1_bit at USISR.B1;
    const register unsigned short int USICNT2 = 2;
    sbit  USICNT2_bit at USISR.B2;
    const register unsigned short int USICNT3 = 3;
    sbit  USICNT3_bit at USISR.B3;

sfr io   unsigned char volatile USICR                     absolute 0x004A;
    const register unsigned short int USISIE = 7;
    sbit  USISIE_bit at USICR.B7;
    const register unsigned short int USIOIE = 6;
    sbit  USIOIE_bit at USICR.B6;
    const register unsigned short int USIWM0 = 4;
    sbit  USIWM0_bit at USICR.B4;
    const register unsigned short int USIWM1 = 5;
    sbit  USIWM1_bit at USICR.B5;
    const register unsigned short int USICS0 = 2;
    sbit  USICS0_bit at USICR.B2;
    const register unsigned short int USICS1 = 3;
    sbit  USICS1_bit at USICR.B3;
    const register unsigned short int USICLK = 1;
    sbit  USICLK_bit at USICR.B1;
    const register unsigned short int USITC = 0;
    sbit  USITC_bit at USICR.B0;

sfr io   unsigned char volatile UDR0                      absolute 0x0040;
sfr io   unsigned char volatile UCSR0A                    absolute 0x0046;
    const register unsigned short int RXC0 = 7;
    sbit  RXC0_bit at UCSR0A.B7;
    const register unsigned short int TXC0 = 6;
    sbit  TXC0_bit at UCSR0A.B6;
    const register unsigned short int UDRE0 = 5;
    sbit  UDRE0_bit at UCSR0A.B5;
    const register unsigned short int FE0 = 4;
    sbit  FE0_bit at UCSR0A.B4;
    const register unsigned short int DOR0 = 3;
    sbit  DOR0_bit at UCSR0A.B3;
    const register unsigned short int UPE0 = 2;
    sbit  UPE0_bit at UCSR0A.B2;
    const register unsigned short int U2X0 = 1;
    sbit  U2X0_bit at UCSR0A.B1;
    const register unsigned short int MPCM0 = 0;
    sbit  MPCM0_bit at UCSR0A.B0;

sfr io   unsigned char volatile UCSR0B                    absolute 0x0045;
    const register unsigned short int RXCIE0 = 7;
    sbit  RXCIE0_bit at UCSR0B.B7;
    const register unsigned short int TXCIE0 = 6;
    sbit  TXCIE0_bit at UCSR0B.B6;
    const register unsigned short int UDRIE0 = 5;
    sbit  UDRIE0_bit at UCSR0B.B5;
    const register unsigned short int RXEN0 = 4;
    sbit  RXEN0_bit at UCSR0B.B4;
    const register unsigned short int TXEN0 = 3;
    sbit  TXEN0_bit at UCSR0B.B3;
    const register unsigned short int UCSZ02 = 2;
    sbit  UCSZ02_bit at UCSR0B.B2;
    const register unsigned short int RXB80 = 1;
    sbit  RXB80_bit at UCSR0B.B1;
    const register unsigned short int TXB80 = 0;
    sbit  TXB80_bit at UCSR0B.B0;

sfr io   unsigned char volatile UCSR0C                    absolute 0x0044;
    const register unsigned short int UMSEL00 = 6;
    sbit  UMSEL00_bit at UCSR0C.B6;
    const register unsigned short int UMSEL01 = 7;
    sbit  UMSEL01_bit at UCSR0C.B7;
    const register unsigned short int UPM00 = 4;
    sbit  UPM00_bit at UCSR0C.B4;
    const register unsigned short int UPM01 = 5;
    sbit  UPM01_bit at UCSR0C.B5;
    const register unsigned short int USBS0 = 3;
    sbit  USBS0_bit at UCSR0C.B3;
    const register unsigned short int UCSZ00 = 1;
    sbit  UCSZ00_bit at UCSR0C.B1;
    const register unsigned short int UCSZ01 = 2;
    sbit  UCSZ01_bit at UCSR0C.B2;
    const register unsigned short int UCPOL0 = 0;
    sbit  UCPOL0_bit at UCSR0C.B0;

sfr io   unsigned char volatile UCSR0D                    absolute 0x0043;
    const register unsigned short int RXSIE0 = 7;
    sbit  RXSIE0_bit at UCSR0D.B7;
    const register unsigned short int RXS0 = 6;
    sbit  RXS0_bit at UCSR0D.B6;
    const register unsigned short int SFDE0 = 5;
    sbit  SFDE0_bit at UCSR0D.B5;

sfr io   unsigned int  UBRR0                     absolute 0x0041;
sfr io   unsigned char UBRR0L                    absolute 0x0041;
sfr io   unsigned char UBRR0H                    absolute 0x0042;
sfr data unsigned char volatile UDR1                      absolute 0x0073;
sfr data unsigned char volatile UCSR1A                    absolute 0x0079;
    const register unsigned short int RXC1 = 7;
    sbit  RXC1_bit at UCSR1A.B7;
    const register unsigned short int TXC1 = 6;
    sbit  TXC1_bit at UCSR1A.B6;
    const register unsigned short int UDRE1 = 5;
    sbit  UDRE1_bit at UCSR1A.B5;
    const register unsigned short int FE1 = 4;
    sbit  FE1_bit at UCSR1A.B4;
    const register unsigned short int DOR1 = 3;
    sbit  DOR1_bit at UCSR1A.B3;
    const register unsigned short int UPE1 = 2;
    sbit  UPE1_bit at UCSR1A.B2;
    const register unsigned short int U2X1 = 1;
    sbit  U2X1_bit at UCSR1A.B1;
    const register unsigned short int MPCM1 = 0;
    sbit  MPCM1_bit at UCSR1A.B0;

sfr data unsigned char volatile UCSR1B                    absolute 0x0078;
    const register unsigned short int RXCIE1 = 7;
    sbit  RXCIE1_bit at UCSR1B.B7;
    const register unsigned short int TXCIE1 = 6;
    sbit  TXCIE1_bit at UCSR1B.B6;
    const register unsigned short int UDRIE1 = 5;
    sbit  UDRIE1_bit at UCSR1B.B5;
    const register unsigned short int RXEN1 = 4;
    sbit  RXEN1_bit at UCSR1B.B4;
    const register unsigned short int TXEN1 = 3;
    sbit  TXEN1_bit at UCSR1B.B3;
    const register unsigned short int UCSZ12 = 2;
    sbit  UCSZ12_bit at UCSR1B.B2;
    const register unsigned short int RXB81 = 1;
    sbit  RXB81_bit at UCSR1B.B1;
    const register unsigned short int TXB81 = 0;
    sbit  TXB81_bit at UCSR1B.B0;

sfr data unsigned char volatile UCSR1C                    absolute 0x0077;
    const register unsigned short int UMSEL10 = 6;
    sbit  UMSEL10_bit at UCSR1C.B6;
    const register unsigned short int UMSEL11 = 7;
    sbit  UMSEL11_bit at UCSR1C.B7;
    const register unsigned short int UPM10 = 4;
    sbit  UPM10_bit at UCSR1C.B4;
    const register unsigned short int UPM11 = 5;
    sbit  UPM11_bit at UCSR1C.B5;
    const register unsigned short int USBS1 = 3;
    sbit  USBS1_bit at UCSR1C.B3;
    const register unsigned short int UCSZ10 = 1;
    sbit  UCSZ10_bit at UCSR1C.B1;
    const register unsigned short int UCSZ11 = 2;
    sbit  UCSZ11_bit at UCSR1C.B2;
    const register unsigned short int UCPOL1 = 0;
    sbit  UCPOL1_bit at UCSR1C.B0;

sfr data unsigned char volatile UCSR1D                    absolute 0x0076;
    const register unsigned short int RXSIE1 = 7;
    sbit  RXSIE1_bit at UCSR1D.B7;
    const register unsigned short int RXS1 = 6;
    sbit  RXS1_bit at UCSR1D.B6;
    const register unsigned short int SFDE1 = 5;
    sbit  SFDE1_bit at UCSR1D.B5;

sfr data unsigned int  UBRR1                     absolute 0x0074;
sfr data unsigned char UBRR1L                    absolute 0x0074;
sfr data unsigned char UBRR1H                    absolute 0x0075;
sfr io   unsigned char volatile WDTCSR                    absolute 0x0050;
    const register unsigned short int WDIF = 7;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIE = 6;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDP0 = 0;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP1 = 1;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP2 = 2;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP3 = 5;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDE = 3;
    sbit  WDE_bit at WDTCSR.B3;

sfr io   unsigned char volatile EXTENDED_                 absolute 0x0002;
    const register unsigned short int BODPD0 = 3;
    sbit  BODPD0_bit at EXTENDED_.B3;
    const register unsigned short int BODPD1 = 4;
    sbit  BODPD1_bit at EXTENDED_.B4;
    const register unsigned short int BODACT0 = 1;
    sbit  BODACT0_bit at EXTENDED_.B1;
    const register unsigned short int BODACT1 = 2;
    sbit  BODACT1_bit at EXTENDED_.B2;
    const register unsigned short int SELFPRGEN = 0;
    sbit  SELFPRGEN_bit at EXTENDED_.B0;

sfr io   unsigned char volatile HIGH                      absolute 0x0001;
    const register unsigned short int RSTDISBL = 7;
    sbit  RSTDISBL_bit at HIGH.B7;
    const register unsigned short int DWEN = 6;
    sbit  DWEN_bit at HIGH.B6;
    const register unsigned short int SPIEN = 5;
    sbit  SPIEN_bit at HIGH.B5;
    const register unsigned short int WDTON = 4;
    sbit  WDTON_bit at HIGH.B4;
    const register unsigned short int EESAVE = 3;
    sbit  EESAVE_bit at HIGH.B3;
    const register unsigned short int BODLEVEL0 = 0;
    sbit  BODLEVEL0_bit at HIGH.B0;
    const register unsigned short int BODLEVEL1 = 1;
    sbit  BODLEVEL1_bit at HIGH.B1;
    const register unsigned short int BODLEVEL2 = 2;
    sbit  BODLEVEL2_bit at HIGH.B2;

sfr io   unsigned char volatile LOW                       absolute 0x0000;
    const register unsigned short int CKDIV8 = 7;
    sbit  CKDIV8_bit at LOW.B7;
    const register unsigned short int CKOUT = 6;
    sbit  CKOUT_bit at LOW.B6;
    const register unsigned short int SUT_CKSEL0 = 0;
    sbit  SUT_CKSEL0_bit at LOW.B0;
    const register unsigned short int SUT_CKSEL1 = 1;
    sbit  SUT_CKSEL1_bit at LOW.B1;
    const register unsigned short int SUT_CKSEL2 = 2;
    sbit  SUT_CKSEL2_bit at LOW.B2;
    const register unsigned short int SUT_CKSEL3 = 3;
    sbit  SUT_CKSEL3_bit at LOW.B3;
    const register unsigned short int SUT_CKSEL4 = 4;
    sbit  SUT_CKSEL4_bit at LOW.B4;

sfr io   unsigned char volatile LOCKBIT                   absolute 0x0000;
    const register unsigned short int LB0 = 0;
    sbit  LB0_bit at LOCKBIT.B0;
    const register unsigned short int LB1 = 1;
    sbit  LB1_bit at LOCKBIT.B1;

