// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00000800;

// Flash page size in program words
const int __FLASH_PAGE_SIZE = 16;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;

const unsigned int IVT_ADDR_RESET            = 0x0000;
const unsigned int IVT_ADDR_EXT_INT0         = 0x0001;
const unsigned int IVT_ADDR_PCINT0           = 0x0002;
const unsigned int IVT_ADDR_PCINT1           = 0x0003;
const unsigned int IVT_ADDR_WATCHDOG         = 0x0004;
const unsigned int IVT_ADDR_TIM1_CAPT        = 0x0005;
const unsigned int IVT_ADDR_TIM1_COMPA       = 0x0006;
const unsigned int IVT_ADDR_TIM1_COMPB       = 0x0007;
const unsigned int IVT_ADDR_TIM1_OVF         = 0x0008;
const unsigned int IVT_ADDR_TIM0_COMPA       = 0x0009;
const unsigned int IVT_ADDR_TIM0_COMPB       = 0x000A;
const unsigned int IVT_ADDR_TIM0_OVF         = 0x000B;
const unsigned int IVT_ADDR_ANA_COMP         = 0x000C;
const unsigned int IVT_ADDR_ADC              = 0x000D;
const unsigned int IVT_ADDR_EE_RDY           = 0x000E;
const unsigned int IVT_ADDR_USI_STR          = 0x000F;
const unsigned int IVT_ADDR_USI_OVF          = 0x0010;


sfr io unsigned short volatile SREG absolute 0x5F;
    sbit  SREG_C_bit at SREG.B0;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_I = 7;

sfr io unsigned short volatile SPL absolute 0x5D;
    sbit  SP0_bit at SPL.B0;
    const register unsigned short int SP0 = 0;
    sbit  SP1_bit at SPL.B1;
    const register unsigned short int SP1 = 1;
    sbit  SP2_bit at SPL.B2;
    const register unsigned short int SP2 = 2;
    sbit  SP3_bit at SPL.B3;
    const register unsigned short int SP3 = 3;
    sbit  SP4_bit at SPL.B4;
    const register unsigned short int SP4 = 4;
    sbit  SP5_bit at SPL.B5;
    const register unsigned short int SP5 = 5;
    sbit  SP6_bit at SPL.B6;
    const register unsigned short int SP6 = 6;
    sbit  SP7_bit at SPL.B7;
    const register unsigned short int SP7 = 7;

sfr io unsigned short OCR0B absolute 0x5C;
    sbit  OCR0_0_bit at OCR0B.B0;
    const register unsigned short int OCR0_0 = 0;
    sbit  OCR0_1_bit at OCR0B.B1;
    const register unsigned short int OCR0_1 = 1;
    sbit  OCR0_2_bit at OCR0B.B2;
    const register unsigned short int OCR0_2 = 2;
    sbit  OCR0_3_bit at OCR0B.B3;
    const register unsigned short int OCR0_3 = 3;
    sbit  OCR0_4_bit at OCR0B.B4;
    const register unsigned short int OCR0_4 = 4;
    sbit  OCR0_5_bit at OCR0B.B5;
    const register unsigned short int OCR0_5 = 5;
    sbit  OCR0_6_bit at OCR0B.B6;
    const register unsigned short int OCR0_6 = 6;
    sbit  OCR0_7_bit at OCR0B.B7;
    const register unsigned short int OCR0_7 = 7;

sfr io unsigned short volatile GIMSK absolute 0x5B;
    sbit  PCIE0_bit at GIMSK.B4;
    const register unsigned short int PCIE0 = 4;
    sbit  PCIE1_bit at GIMSK.B5;
    const register unsigned short int PCIE1 = 5;
    sbit  INT0_bit at GIMSK.B6;
    const register unsigned short int INT0 = 6;

sfr io unsigned short volatile GIFR absolute 0x5A;
    sbit  PCIF0_bit at GIFR.B4;
    const register unsigned short int PCIF0 = 4;
    sbit  PCIF1_bit at GIFR.B5;
    const register unsigned short int PCIF1 = 5;
    sbit  INTF0_bit at GIFR.B6;
    const register unsigned short int INTF0 = 6;

sfr io unsigned short TIMSK0 absolute 0x59;
    sbit  TOIE0_bit at TIMSK0.B0;
    const register unsigned short int TOIE0 = 0;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0B = 2;

sfr io unsigned short volatile TIFR0 absolute 0x58;
    sbit  TOV0_bit at TIFR0.B0;
    const register unsigned short int TOV0 = 0;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0B = 2;

sfr io unsigned short volatile SPMCSR absolute 0x57;
    sbit  SPMEN_bit at SPMCSR.B0;
    const register unsigned short int SPMEN = 0;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int PGERS = 1;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGWRT = 2;
    sbit  RFLB_bit at SPMCSR.B3;
    const register unsigned short int RFLB = 3;
    sbit  CTPB_bit at SPMCSR.B4;
    const register unsigned short int CTPB = 4;

sfr io unsigned short OCR0A absolute 0x56;
    sbit  OCR0A_0_bit at OCR0A.B0;
    const register unsigned short int OCR0A_0 = 0;
    sbit  OCR0A_1_bit at OCR0A.B1;
    const register unsigned short int OCR0A_1 = 1;
    sbit  OCR0A_2_bit at OCR0A.B2;
    const register unsigned short int OCR0A_2 = 2;
    sbit  OCR0A_3_bit at OCR0A.B3;
    const register unsigned short int OCR0A_3 = 3;
    sbit  OCR0A_4_bit at OCR0A.B4;
    const register unsigned short int OCR0A_4 = 4;
    sbit  OCR0A_5_bit at OCR0A.B5;
    const register unsigned short int OCR0A_5 = 5;
    sbit  OCR0A_6_bit at OCR0A.B6;
    const register unsigned short int OCR0A_6 = 6;
    sbit  OCR0A_7_bit at OCR0A.B7;
    const register unsigned short int OCR0A_7 = 7;

sfr io unsigned short volatile MCUCR absolute 0x55;
    sbit  ISC00_bit at MCUCR.B0;
    const register unsigned short int ISC00 = 0;
    sbit  ISC01_bit at MCUCR.B1;
    const register unsigned short int ISC01 = 1;
    sbit  SM0_bit at MCUCR.B3;
    const register unsigned short int SM0 = 3;
    sbit  SM1_bit at MCUCR.B4;
    const register unsigned short int SM1 = 4;
    sbit  SE_bit at MCUCR.B5;
    const register unsigned short int SE = 5;
    sbit  PUD_bit at MCUCR.B6;
    const register unsigned short int PUD = 6;

sfr io unsigned short volatile MCUSR absolute 0x54;
    sbit  PORF_bit at MCUSR.B0;
    const register unsigned short int PORF = 0;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int EXTRF = 1;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int BORF = 2;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int WDRF = 3;

sfr io unsigned short TCCR0B absolute 0x53;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS00 = 0;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS01 = 1;
    sbit  CS02_bit at TCCR0B.B2;
    const register unsigned short int CS02 = 2;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int WGM02 = 3;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0A = 7;

sfr io unsigned short volatile TCNT0 absolute 0x52;
    sbit  TCNT0_0_bit at TCNT0.B0;
    const register unsigned short int TCNT0_0 = 0;
    sbit  TCNT0_1_bit at TCNT0.B1;
    const register unsigned short int TCNT0_1 = 1;
    sbit  TCNT0_2_bit at TCNT0.B2;
    const register unsigned short int TCNT0_2 = 2;
    sbit  TCNT0_3_bit at TCNT0.B3;
    const register unsigned short int TCNT0_3 = 3;
    sbit  TCNT0_4_bit at TCNT0.B4;
    const register unsigned short int TCNT0_4 = 4;
    sbit  TCNT0_5_bit at TCNT0.B5;
    const register unsigned short int TCNT0_5 = 5;
    sbit  TCNT0_6_bit at TCNT0.B6;
    const register unsigned short int TCNT0_6 = 6;
    sbit  TCNT0_7_bit at TCNT0.B7;
    const register unsigned short int TCNT0_7 = 7;

sfr io unsigned short OSCCAL absolute 0x51;
    sbit  CAL0_bit at OSCCAL.B0;
    const register unsigned short int CAL0 = 0;
    sbit  CAL1_bit at OSCCAL.B1;
    const register unsigned short int CAL1 = 1;
    sbit  CAL2_bit at OSCCAL.B2;
    const register unsigned short int CAL2 = 2;
    sbit  CAL3_bit at OSCCAL.B3;
    const register unsigned short int CAL3 = 3;
    sbit  CAL4_bit at OSCCAL.B4;
    const register unsigned short int CAL4 = 4;
    sbit  CAL5_bit at OSCCAL.B5;
    const register unsigned short int CAL5 = 5;
    sbit  CAL6_bit at OSCCAL.B6;
    const register unsigned short int CAL6 = 6;
    sbit  CAL7_bit at OSCCAL.B7;
    const register unsigned short int CAL7 = 7;

sfr io unsigned short TCCR0A absolute 0x50;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM00 = 0;
    sbit  WGM01_bit at TCCR0A.B1;
    const register unsigned short int WGM01 = 1;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0A1 = 7;

sfr io unsigned short TCCR1A absolute 0x4F;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM10 = 0;
    sbit  WGM11_bit at TCCR1A.B1;
    const register unsigned short int WGM11 = 1;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1A1 = 7;

sfr io unsigned short TCCR1B absolute 0x4E;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS10 = 0;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS11 = 1;
    sbit  CS12_bit at TCCR1B.B2;
    const register unsigned short int CS12 = 2;
    sbit  WGM12_bit at TCCR1B.B3;
    const register unsigned short int WGM12 = 3;
    sbit  WGM13_bit at TCCR1B.B4;
    const register unsigned short int WGM13 = 4;
    sbit  ICES1_bit at TCCR1B.B6;
    const register unsigned short int ICES1 = 6;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICNC1 = 7;

sfr io unsigned short volatile TCNT1H absolute 0x4D;
    sbit  TCNT1H0_bit at TCNT1H.B0;
    const register unsigned short int TCNT1H0 = 0;
    sbit  TCNT1H1_bit at TCNT1H.B1;
    const register unsigned short int TCNT1H1 = 1;
    sbit  TCNT1H2_bit at TCNT1H.B2;
    const register unsigned short int TCNT1H2 = 2;
    sbit  TCNT1H3_bit at TCNT1H.B3;
    const register unsigned short int TCNT1H3 = 3;
    sbit  TCNT1H4_bit at TCNT1H.B4;
    const register unsigned short int TCNT1H4 = 4;
    sbit  TCNT1H5_bit at TCNT1H.B5;
    const register unsigned short int TCNT1H5 = 5;
    sbit  TCNT1H6_bit at TCNT1H.B6;
    const register unsigned short int TCNT1H6 = 6;
    sbit  TCNT1H7_bit at TCNT1H.B7;
    const register unsigned short int TCNT1H7 = 7;

sfr io unsigned short volatile TCNT1L absolute 0x4C;
    sbit  TCNT1L0_bit at TCNT1L.B0;
    const register unsigned short int TCNT1L0 = 0;
    sbit  TCNT1L1_bit at TCNT1L.B1;
    const register unsigned short int TCNT1L1 = 1;
    sbit  TCNT1L2_bit at TCNT1L.B2;
    const register unsigned short int TCNT1L2 = 2;
    sbit  TCNT1L3_bit at TCNT1L.B3;
    const register unsigned short int TCNT1L3 = 3;
    sbit  TCNT1L4_bit at TCNT1L.B4;
    const register unsigned short int TCNT1L4 = 4;
    sbit  TCNT1L5_bit at TCNT1L.B5;
    const register unsigned short int TCNT1L5 = 5;
    sbit  TCNT1L6_bit at TCNT1L.B6;
    const register unsigned short int TCNT1L6 = 6;
    sbit  TCNT1L7_bit at TCNT1L.B7;
    const register unsigned short int TCNT1L7 = 7;

sfr io unsigned short OCR1AH absolute 0x4B;
    sbit  OCR1AH0_bit at OCR1AH.B0;
    const register unsigned short int OCR1AH0 = 0;
    sbit  OCR1AH1_bit at OCR1AH.B1;
    const register unsigned short int OCR1AH1 = 1;
    sbit  OCR1AH2_bit at OCR1AH.B2;
    const register unsigned short int OCR1AH2 = 2;
    sbit  OCR1AH3_bit at OCR1AH.B3;
    const register unsigned short int OCR1AH3 = 3;
    sbit  OCR1AH4_bit at OCR1AH.B4;
    const register unsigned short int OCR1AH4 = 4;
    sbit  OCR1AH5_bit at OCR1AH.B5;
    const register unsigned short int OCR1AH5 = 5;
    sbit  OCR1AH6_bit at OCR1AH.B6;
    const register unsigned short int OCR1AH6 = 6;
    sbit  OCR1AH7_bit at OCR1AH.B7;
    const register unsigned short int OCR1AH7 = 7;

sfr io unsigned short OCR1AL absolute 0x4A;
    sbit  OCR1AL0_bit at OCR1AL.B0;
    const register unsigned short int OCR1AL0 = 0;
    sbit  OCR1AL1_bit at OCR1AL.B1;
    const register unsigned short int OCR1AL1 = 1;
    sbit  OCR1AL2_bit at OCR1AL.B2;
    const register unsigned short int OCR1AL2 = 2;
    sbit  OCR1AL3_bit at OCR1AL.B3;
    const register unsigned short int OCR1AL3 = 3;
    sbit  OCR1AL4_bit at OCR1AL.B4;
    const register unsigned short int OCR1AL4 = 4;
    sbit  OCR1AL5_bit at OCR1AL.B5;
    const register unsigned short int OCR1AL5 = 5;
    sbit  OCR1AL6_bit at OCR1AL.B6;
    const register unsigned short int OCR1AL6 = 6;
    sbit  OCR1AL7_bit at OCR1AL.B7;
    const register unsigned short int OCR1AL7 = 7;

sfr io unsigned short OCR1BH absolute 0x49;
    sbit  OCR1BH0_bit at OCR1BH.B0;
    const register unsigned short int OCR1BH0 = 0;
    sbit  OCR1BH1_bit at OCR1BH.B1;
    const register unsigned short int OCR1BH1 = 1;
    sbit  OCR1BH2_bit at OCR1BH.B2;
    const register unsigned short int OCR1BH2 = 2;
    sbit  OCR1BH3_bit at OCR1BH.B3;
    const register unsigned short int OCR1BH3 = 3;
    sbit  OCR1BH4_bit at OCR1BH.B4;
    const register unsigned short int OCR1BH4 = 4;
    sbit  OCR1BH5_bit at OCR1BH.B5;
    const register unsigned short int OCR1BH5 = 5;
    sbit  OCR1BH6_bit at OCR1BH.B6;
    const register unsigned short int OCR1BH6 = 6;
    sbit  OCR1BH7_bit at OCR1BH.B7;
    const register unsigned short int OCR1BH7 = 7;

sfr io unsigned short OCR1BL absolute 0x48;
    sbit  OCR1BL0_bit at OCR1BL.B0;
    const register unsigned short int OCR1BL0 = 0;
    sbit  OCR1BL1_bit at OCR1BL.B1;
    const register unsigned short int OCR1BL1 = 1;
    sbit  OCR1BL2_bit at OCR1BL.B2;
    const register unsigned short int OCR1BL2 = 2;
    sbit  OCR1BL3_bit at OCR1BL.B3;
    const register unsigned short int OCR1BL3 = 3;
    sbit  OCR1BL4_bit at OCR1BL.B4;
    const register unsigned short int OCR1BL4 = 4;
    sbit  OCR1BL5_bit at OCR1BL.B5;
    const register unsigned short int OCR1BL5 = 5;
    sbit  OCR1BL6_bit at OCR1BL.B6;
    const register unsigned short int OCR1BL6 = 6;
    sbit  OCR1BL7_bit at OCR1BL.B7;
    const register unsigned short int OCR1BL7 = 7;

sfr io unsigned short volatile DWDR absolute 0x47;

sfr io unsigned short volatile CLKPR absolute 0x46;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS3_bit at CLKPR.B3;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPCE_bit at CLKPR.B7;
    const register unsigned short int CLKPCE = 7;

sfr io unsigned short volatile ICR1H absolute 0x45;
    sbit  ICR1H0_bit at ICR1H.B0;
    const register unsigned short int ICR1H0 = 0;
    sbit  ICR1H1_bit at ICR1H.B1;
    const register unsigned short int ICR1H1 = 1;
    sbit  ICR1H2_bit at ICR1H.B2;
    const register unsigned short int ICR1H2 = 2;
    sbit  ICR1H3_bit at ICR1H.B3;
    const register unsigned short int ICR1H3 = 3;
    sbit  ICR1H4_bit at ICR1H.B4;
    const register unsigned short int ICR1H4 = 4;
    sbit  ICR1H5_bit at ICR1H.B5;
    const register unsigned short int ICR1H5 = 5;
    sbit  ICR1H6_bit at ICR1H.B6;
    const register unsigned short int ICR1H6 = 6;
    sbit  ICR1H7_bit at ICR1H.B7;
    const register unsigned short int ICR1H7 = 7;

sfr io unsigned short volatile ICR1L absolute 0x44;
    sbit  ICR1L0_bit at ICR1L.B0;
    const register unsigned short int ICR1L0 = 0;
    sbit  ICR1L1_bit at ICR1L.B1;
    const register unsigned short int ICR1L1 = 1;
    sbit  ICR1L2_bit at ICR1L.B2;
    const register unsigned short int ICR1L2 = 2;
    sbit  ICR1L3_bit at ICR1L.B3;
    const register unsigned short int ICR1L3 = 3;
    sbit  ICR1L4_bit at ICR1L.B4;
    const register unsigned short int ICR1L4 = 4;
    sbit  ICR1L5_bit at ICR1L.B5;
    const register unsigned short int ICR1L5 = 5;
    sbit  ICR1L6_bit at ICR1L.B6;
    const register unsigned short int ICR1L6 = 6;
    sbit  ICR1L7_bit at ICR1L.B7;
    const register unsigned short int ICR1L7 = 7;

sfr io unsigned short volatile GTCCR absolute 0x43;
    sbit  PSR10_bit at GTCCR.B0;
    const register unsigned short int PSR10 = 0;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int TSM = 7;

sfr io unsigned short volatile TCCR1C absolute 0x42;
    sbit  FOC1B_bit at TCCR1C.B6;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1A = 7;

sfr io unsigned short volatile WDTCSR absolute 0x41;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP0 = 0;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP1 = 1;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP2 = 2;
    sbit  WDE_bit at WDTCSR.B3;
    const register unsigned short int WDE = 3;
    sbit  WDCE_bit at WDTCSR.B4;
    const register unsigned short int WDCE = 4;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDP3 = 5;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDIE = 6;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIF = 7;

sfr io unsigned short PCMSK1 absolute 0x40;
    sbit  PCINT8_bit at PCMSK1.B0;
    const register unsigned short int PCINT8 = 0;
    sbit  PCINT9_bit at PCMSK1.B1;
    const register unsigned short int PCINT9 = 1;
    sbit  PCINT10_bit at PCMSK1.B2;
    const register unsigned short int PCINT10 = 2;
    sbit  PCINT11_bit at PCMSK1.B3;
    const register unsigned short int PCINT11 = 3;

sfr io unsigned short EEARH absolute 0x3F;
    sbit  EEAR8_bit at EEARH.B0;
    const register unsigned short int EEAR8 = 0;

sfr io unsigned short EEARL absolute 0x3E;
    sbit  EEAR0_bit at EEARL.B0;
    const register unsigned short int EEAR0 = 0;
    sbit  EEAR1_bit at EEARL.B1;
    const register unsigned short int EEAR1 = 1;
    sbit  EEAR2_bit at EEARL.B2;
    const register unsigned short int EEAR2 = 2;
    sbit  EEAR3_bit at EEARL.B3;
    const register unsigned short int EEAR3 = 3;
    sbit  EEAR4_bit at EEARL.B4;
    const register unsigned short int EEAR4 = 4;
    sbit  EEAR5_bit at EEARL.B5;
    const register unsigned short int EEAR5 = 5;
    sbit  EEAR6_bit at EEARL.B6;
    const register unsigned short int EEAR6 = 6;
    sbit  EEAR7_bit at EEARL.B7;
    const register unsigned short int EEAR7 = 7;

sfr io unsigned short volatile EEDR absolute 0x3D;
    sbit  EEDR0_bit at EEDR.B0;
    const register unsigned short int EEDR0 = 0;
    sbit  EEDR1_bit at EEDR.B1;
    const register unsigned short int EEDR1 = 1;
    sbit  EEDR2_bit at EEDR.B2;
    const register unsigned short int EEDR2 = 2;
    sbit  EEDR3_bit at EEDR.B3;
    const register unsigned short int EEDR3 = 3;
    sbit  EEDR4_bit at EEDR.B4;
    const register unsigned short int EEDR4 = 4;
    sbit  EEDR5_bit at EEDR.B5;
    const register unsigned short int EEDR5 = 5;
    sbit  EEDR6_bit at EEDR.B6;
    const register unsigned short int EEDR6 = 6;
    sbit  EEDR7_bit at EEDR.B7;
    const register unsigned short int EEDR7 = 7;

sfr io unsigned short volatile EECR absolute 0x3C;
    sbit  EERE_bit at EECR.B0;
    const register unsigned short int EERE = 0;
    sbit  EEPE_bit at EECR.B1;
    const register unsigned short int EEPE = 1;
    sbit  EEMPE_bit at EECR.B2;
    const register unsigned short int EEMPE = 2;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EERIE = 3;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EEPM1 = 5;

sfr io unsigned short PORTA absolute 0x3B;
    sbit  PORTA0_bit at PORTA.B0;
    const register unsigned short int PORTA0 = 0;
    sbit  PORTA1_bit at PORTA.B1;
    const register unsigned short int PORTA1 = 1;
    sbit  PORTA2_bit at PORTA.B2;
    const register unsigned short int PORTA2 = 2;
    sbit  PORTA3_bit at PORTA.B3;
    const register unsigned short int PORTA3 = 3;
    sbit  PORTA4_bit at PORTA.B4;
    const register unsigned short int PORTA4 = 4;
    sbit  PORTA5_bit at PORTA.B5;
    const register unsigned short int PORTA5 = 5;
    sbit  PORTA6_bit at PORTA.B6;
    const register unsigned short int PORTA6 = 6;
    sbit  PORTA7_bit at PORTA.B7;
    const register unsigned short int PORTA7 = 7;

sfr io unsigned short DDRA absolute 0x3A;
    sbit  DDA0_bit at DDRA.B0;
    const register unsigned short int DDA0 = 0;
    sbit  DDA1_bit at DDRA.B1;
    const register unsigned short int DDA1 = 1;
    sbit  DDA2_bit at DDRA.B2;
    const register unsigned short int DDA2 = 2;
    sbit  DDA3_bit at DDRA.B3;
    const register unsigned short int DDA3 = 3;
    sbit  DDA4_bit at DDRA.B4;
    const register unsigned short int DDA4 = 4;
    sbit  DDA5_bit at DDRA.B5;
    const register unsigned short int DDA5 = 5;
    sbit  DDA6_bit at DDRA.B6;
    const register unsigned short int DDA6 = 6;
    sbit  DDA7_bit at DDRA.B7;
    const register unsigned short int DDA7 = 7;

sfr io unsigned short volatile PINA absolute 0x39;
    sbit  PINA0_bit at PINA.B0;
    const register unsigned short int PINA0 = 0;
    sbit  PINA1_bit at PINA.B1;
    const register unsigned short int PINA1 = 1;
    sbit  PINA2_bit at PINA.B2;
    const register unsigned short int PINA2 = 2;
    sbit  PINA3_bit at PINA.B3;
    const register unsigned short int PINA3 = 3;
    sbit  PINA4_bit at PINA.B4;
    const register unsigned short int PINA4 = 4;
    sbit  PINA5_bit at PINA.B5;
    const register unsigned short int PINA5 = 5;
    sbit  PINA6_bit at PINA.B6;
    const register unsigned short int PINA6 = 6;
    sbit  PINA7_bit at PINA.B7;
    const register unsigned short int PINA7 = 7;

sfr io unsigned short PORTB absolute 0x38;
    sbit  PORTB0_bit at PORTB.B0;
    const register unsigned short int PORTB0 = 0;
    sbit  PORTB1_bit at PORTB.B1;
    const register unsigned short int PORTB1 = 1;
    sbit  PORTB2_bit at PORTB.B2;
    const register unsigned short int PORTB2 = 2;
    sbit  PORTB3_bit at PORTB.B3;
    const register unsigned short int PORTB3 = 3;

sfr io unsigned short DDRB absolute 0x37;
    sbit  DDB0_bit at DDRB.B0;
    const register unsigned short int DDB0 = 0;
    sbit  DDB1_bit at DDRB.B1;
    const register unsigned short int DDB1 = 1;
    sbit  DDB2_bit at DDRB.B2;
    const register unsigned short int DDB2 = 2;
    sbit  DDB3_bit at DDRB.B3;
    const register unsigned short int DDB3 = 3;

sfr io unsigned short volatile PINB absolute 0x36;
    sbit  PINB0_bit at PINB.B0;
    const register unsigned short int PINB0 = 0;
    sbit  PINB1_bit at PINB.B1;
    const register unsigned short int PINB1 = 1;
    sbit  PINB2_bit at PINB.B2;
    const register unsigned short int PINB2 = 2;
    sbit  PINB3_bit at PINB.B3;
    const register unsigned short int PINB3 = 3;

sfr io unsigned short volatile GPIOR2 absolute 0x35;
    sbit  GPIOR20_bit at GPIOR2.B0;
    const register unsigned short int GPIOR20 = 0;
    sbit  GPIOR21_bit at GPIOR2.B1;
    const register unsigned short int GPIOR21 = 1;
    sbit  GPIOR22_bit at GPIOR2.B2;
    const register unsigned short int GPIOR22 = 2;
    sbit  GPIOR23_bit at GPIOR2.B3;
    const register unsigned short int GPIOR23 = 3;
    sbit  GPIOR24_bit at GPIOR2.B4;
    const register unsigned short int GPIOR24 = 4;
    sbit  GPIOR25_bit at GPIOR2.B5;
    const register unsigned short int GPIOR25 = 5;
    sbit  GPIOR26_bit at GPIOR2.B6;
    const register unsigned short int GPIOR26 = 6;
    sbit  GPIOR27_bit at GPIOR2.B7;
    const register unsigned short int GPIOR27 = 7;

sfr io unsigned short volatile GPIOR1 absolute 0x34;
    sbit  GPIOR10_bit at GPIOR1.B0;
    const register unsigned short int GPIOR10 = 0;
    sbit  GPIOR11_bit at GPIOR1.B1;
    const register unsigned short int GPIOR11 = 1;
    sbit  GPIOR12_bit at GPIOR1.B2;
    const register unsigned short int GPIOR12 = 2;
    sbit  GPIOR13_bit at GPIOR1.B3;
    const register unsigned short int GPIOR13 = 3;
    sbit  GPIOR14_bit at GPIOR1.B4;
    const register unsigned short int GPIOR14 = 4;
    sbit  GPIOR15_bit at GPIOR1.B5;
    const register unsigned short int GPIOR15 = 5;
    sbit  GPIOR16_bit at GPIOR1.B6;
    const register unsigned short int GPIOR16 = 6;
    sbit  GPIOR17_bit at GPIOR1.B7;
    const register unsigned short int GPIOR17 = 7;

sfr io unsigned short volatile GPIOR0 absolute 0x33;
    sbit  GPIOR00_bit at GPIOR0.B0;
    const register unsigned short int GPIOR00 = 0;
    sbit  GPIOR01_bit at GPIOR0.B1;
    const register unsigned short int GPIOR01 = 1;
    sbit  GPIOR02_bit at GPIOR0.B2;
    const register unsigned short int GPIOR02 = 2;
    sbit  GPIOR03_bit at GPIOR0.B3;
    const register unsigned short int GPIOR03 = 3;
    sbit  GPIOR04_bit at GPIOR0.B4;
    const register unsigned short int GPIOR04 = 4;
    sbit  GPIOR05_bit at GPIOR0.B5;
    const register unsigned short int GPIOR05 = 5;
    sbit  GPIOR06_bit at GPIOR0.B6;
    const register unsigned short int GPIOR06 = 6;
    sbit  GPIOR07_bit at GPIOR0.B7;
    const register unsigned short int GPIOR07 = 7;

sfr io unsigned short PCMSK0 absolute 0x32;
    sbit  PCINT0_bit at PCMSK0.B0;
    const register unsigned short int PCINT0 = 0;
    sbit  PCINT1_bit at PCMSK0.B1;
    const register unsigned short int PCINT1 = 1;
    sbit  PCINT2_bit at PCMSK0.B2;
    const register unsigned short int PCINT2 = 2;
    sbit  PCINT3_bit at PCMSK0.B3;
    const register unsigned short int PCINT3 = 3;
    sbit  PCINT4_bit at PCMSK0.B4;
    const register unsigned short int PCINT4 = 4;
    sbit  PCINT5_bit at PCMSK0.B5;
    const register unsigned short int PCINT5 = 5;
    sbit  PCINT6_bit at PCMSK0.B6;
    const register unsigned short int PCINT6 = 6;
    sbit  PCINT7_bit at PCMSK0.B7;
    const register unsigned short int PCINT7 = 7;

sfr io unsigned short volatile USIBR absolute 0x30;
    sbit  USIBR0_bit at USIBR.B0;
    const register unsigned short int USIBR0 = 0;
    sbit  USIBR1_bit at USIBR.B1;
    const register unsigned short int USIBR1 = 1;
    sbit  USIBR2_bit at USIBR.B2;
    const register unsigned short int USIBR2 = 2;
    sbit  USIBR3_bit at USIBR.B3;
    const register unsigned short int USIBR3 = 3;
    sbit  USIBR4_bit at USIBR.B4;
    const register unsigned short int USIBR4 = 4;
    sbit  USIBR5_bit at USIBR.B5;
    const register unsigned short int USIBR5 = 5;
    sbit  USIBR6_bit at USIBR.B6;
    const register unsigned short int USIBR6 = 6;
    sbit  USIBR7_bit at USIBR.B7;
    const register unsigned short int USIBR7 = 7;

sfr io unsigned short volatile USIDR absolute 0x2F;
    sbit  USIDR0_bit at USIDR.B0;
    const register unsigned short int USIDR0 = 0;
    sbit  USIDR1_bit at USIDR.B1;
    const register unsigned short int USIDR1 = 1;
    sbit  USIDR2_bit at USIDR.B2;
    const register unsigned short int USIDR2 = 2;
    sbit  USIDR3_bit at USIDR.B3;
    const register unsigned short int USIDR3 = 3;
    sbit  USIDR4_bit at USIDR.B4;
    const register unsigned short int USIDR4 = 4;
    sbit  USIDR5_bit at USIDR.B5;
    const register unsigned short int USIDR5 = 5;
    sbit  USIDR6_bit at USIDR.B6;
    const register unsigned short int USIDR6 = 6;
    sbit  USIDR7_bit at USIDR.B7;
    const register unsigned short int USIDR7 = 7;

sfr io unsigned short volatile USISR absolute 0x2E;
    sbit  USICNT0_bit at USISR.B0;
    const register unsigned short int USICNT0 = 0;
    sbit  USICNT1_bit at USISR.B1;
    const register unsigned short int USICNT1 = 1;
    sbit  USICNT2_bit at USISR.B2;
    const register unsigned short int USICNT2 = 2;
    sbit  USICNT3_bit at USISR.B3;
    const register unsigned short int USICNT3 = 3;
    sbit  USIDC_bit at USISR.B4;
    const register unsigned short int USIDC = 4;
    sbit  USIPF_bit at USISR.B5;
    const register unsigned short int USIPF = 5;
    sbit  USIOIF_bit at USISR.B6;
    const register unsigned short int USIOIF = 6;
    sbit  USISIF_bit at USISR.B7;
    const register unsigned short int USISIF = 7;

sfr io unsigned short volatile USICR absolute 0x2D;
    sbit  USITC_bit at USICR.B0;
    const register unsigned short int USITC = 0;
    sbit  USICLK_bit at USICR.B1;
    const register unsigned short int USICLK = 1;
    sbit  USICS0_bit at USICR.B2;
    const register unsigned short int USICS0 = 2;
    sbit  USICS1_bit at USICR.B3;
    const register unsigned short int USICS1 = 3;
    sbit  USIWM0_bit at USICR.B4;
    const register unsigned short int USIWM0 = 4;
    sbit  USIWM1_bit at USICR.B5;
    const register unsigned short int USIWM1 = 5;
    sbit  USIOIE_bit at USICR.B6;
    const register unsigned short int USIOIE = 6;
    sbit  USISIE_bit at USICR.B7;
    const register unsigned short int USISIE = 7;

sfr io unsigned short TIMSK1 absolute 0x2C;
    sbit  TOIE1_bit at TIMSK1.B0;
    const register unsigned short int TOIE1 = 0;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1B = 2;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int ICIE1 = 5;

sfr io unsigned short volatile TIFR1 absolute 0x2B;
    sbit  TOV1_bit at TIFR1.B0;
    const register unsigned short int TOV1 = 0;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1B = 2;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int ICF1 = 5;

sfr io unsigned short volatile ACSR absolute 0x28;
    sbit  ACIS0_bit at ACSR.B0;
    const register unsigned short int ACIS0 = 0;
    sbit  ACIS1_bit at ACSR.B1;
    const register unsigned short int ACIS1 = 1;
    sbit  ACIC_bit at ACSR.B2;
    const register unsigned short int ACIC = 2;
    sbit  ACIE_bit at ACSR.B3;
    const register unsigned short int ACIE = 3;
    sbit  ACI_bit at ACSR.B4;
    const register unsigned short int ACI = 4;
    sbit  ACO_bit at ACSR.B5;
    const register unsigned short int ACO = 5;
    sbit  ACBG_bit at ACSR.B6;
    const register unsigned short int ACBG = 6;
    sbit  ACD_bit at ACSR.B7;
    const register unsigned short int ACD = 7;

sfr io unsigned short ADMUX absolute 0x27;
    sbit  MUX0_bit at ADMUX.B0;
    const register unsigned short int MUX0 = 0;
    sbit  MUX1_bit at ADMUX.B1;
    const register unsigned short int MUX1 = 1;
    sbit  MUX2_bit at ADMUX.B2;
    const register unsigned short int MUX2 = 2;
    sbit  MUX3_bit at ADMUX.B3;
    const register unsigned short int MUX3 = 3;
    sbit  MUX4_bit at ADMUX.B4;
    const register unsigned short int MUX4 = 4;
    sbit  MUX5_bit at ADMUX.B5;
    const register unsigned short int MUX5 = 5;
    sbit  REFS0_bit at ADMUX.B6;
    const register unsigned short int REFS0 = 6;
    sbit  REFS1_bit at ADMUX.B7;
    const register unsigned short int REFS1 = 7;

sfr io unsigned short volatile ADCSRA absolute 0x26;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS2_bit at ADCSRA.B2;
    const register unsigned short int ADPS2 = 2;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADIE = 3;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIF = 4;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADATE = 5;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADSC = 6;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADEN = 7;

sfr io unsigned short volatile ADCH absolute 0x25;
    sbit  ADCH0_bit at ADCH.B0;
    const register unsigned short int ADCH0 = 0;
    sbit  ADCH1_bit at ADCH.B1;
    const register unsigned short int ADCH1 = 1;
    sbit  ADCH2_bit at ADCH.B2;
    const register unsigned short int ADCH2 = 2;
    sbit  ADCH3_bit at ADCH.B3;
    const register unsigned short int ADCH3 = 3;
    sbit  ADCH4_bit at ADCH.B4;
    const register unsigned short int ADCH4 = 4;
    sbit  ADCH5_bit at ADCH.B5;
    const register unsigned short int ADCH5 = 5;
    sbit  ADCH6_bit at ADCH.B6;
    const register unsigned short int ADCH6 = 6;
    sbit  ADCH7_bit at ADCH.B7;
    const register unsigned short int ADCH7 = 7;

sfr io unsigned short volatile ADCL absolute 0x24;
    sbit  ADCL0_bit at ADCL.B0;
    const register unsigned short int ADCL0 = 0;
    sbit  ADCL1_bit at ADCL.B1;
    const register unsigned short int ADCL1 = 1;
    sbit  ADCL2_bit at ADCL.B2;
    const register unsigned short int ADCL2 = 2;
    sbit  ADCL3_bit at ADCL.B3;
    const register unsigned short int ADCL3 = 3;
    sbit  ADCL4_bit at ADCL.B4;
    const register unsigned short int ADCL4 = 4;
    sbit  ADCL5_bit at ADCL.B5;
    const register unsigned short int ADCL5 = 5;
    sbit  ADCL6_bit at ADCL.B6;
    const register unsigned short int ADCL6 = 6;
    sbit  ADCL7_bit at ADCL.B7;
    const register unsigned short int ADCL7 = 7;

sfr io unsigned short ADCSRB absolute 0x23;
    sbit  ACME_bit at ADCSRB.B6;
    const register unsigned short int ACME = 6;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS2_bit at ADCSRB.B2;
    const register unsigned short int ADTS2 = 2;
    sbit  ADLAR_bit at ADCSRB.B4;
    const register unsigned short int ADLAR = 4;
    sbit  BIN_bit at ADCSRB.B7;
    const register unsigned short int BIN = 7;

sfr io unsigned short DIDR0 absolute 0x21;
    sbit  ADC0D_bit at DIDR0.B0;
    const register unsigned short int ADC0D = 0;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC1D = 1;
    sbit  ADC2D_bit at DIDR0.B2;
    const register unsigned short int ADC2D = 2;
    sbit  ADC3D_bit at DIDR0.B3;
    const register unsigned short int ADC3D = 3;
    sbit  ADC4D_bit at DIDR0.B4;
    const register unsigned short int ADC4D = 4;
    sbit  ADC5D_bit at DIDR0.B5;
    const register unsigned short int ADC5D = 5;
    sbit  ADC6D_bit at DIDR0.B6;
    const register unsigned short int ADC6D = 6;
    sbit  ADC7D_bit at DIDR0.B7;
    const register unsigned short int ADC7D = 7;

sfr io unsigned short volatile PRR absolute 0x20;
    sbit  PRADC_bit at PRR.B0;
    const register unsigned short int PRADC = 0;
    sbit  PRUSI_bit at PRR.B1;
    const register unsigned short int PRUSI = 1;
    sbit  PRTIM0_bit at PRR.B2;
    const register unsigned short int PRTIM0 = 2;
    sbit  PRTIM1_bit at PRR.B3;
    const register unsigned short int PRTIM1 = 3;
