// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00002000;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;


// Interrupt Vector Table Constants
const unsigned short IVT_ADDR_INT0 = 0x0001;
const unsigned short IVT_ADDR_INT1 = 0x0002;
const unsigned short IVT_ADDR_PCINT0 = 0x0003;
const unsigned short IVT_ADDR_PCINT1 = 0x0004;
const unsigned short IVT_ADDR_PCINT2 = 0x0005;
const unsigned short IVT_ADDR_PCINT3 = 0x0006;
const unsigned short IVT_ADDR_WDT = 0x0007;
const unsigned short IVT_ADDR_TIMER1_CAPT = 0x0008;
const unsigned short IVT_ADDR_TIMER1_COMPA = 0x0009;
const unsigned short IVT_ADDR_TIMER1_COMPB = 0x000A;
const unsigned short IVT_ADDR_TIMER1_OVF = 0x000B;
const unsigned short IVT_ADDR_TIMER0_COMPA = 0x000C;
const unsigned short IVT_ADDR_TIMER0_COMPB = 0x000D;
const unsigned short IVT_ADDR_TIMER0_OVF = 0x000E;
const unsigned short IVT_ADDR_SPI_STC = 0x000F;
const unsigned short IVT_ADDR_USART_START = 0x0010;
const unsigned short IVT_ADDR_USART_RX = 0x0011;
const unsigned short IVT_ADDR_USART_UDRE = 0x0012;
const unsigned short IVT_ADDR_USART_TX = 0x0013;
const unsigned short IVT_ADDR_ADC = 0x0014;
const unsigned short IVT_ADDR_EE_READY = 0x0015;
const unsigned short IVT_ADDR_ANALOG_COMP = 0x0016;
const unsigned short IVT_ADDR_TWI_SLAVE = 0x0017;
const unsigned short IVT_ADDR_SPM_Ready = 0x0018;
const unsigned short IVT_ADDR_QTRIP = 0x0019;

sfr io   unsigned char volatile SPDR                      absolute 0x004E;
sfr io   unsigned char volatile SPSR                      absolute 0x004D;
    const register unsigned short int SPIF = 7;
    sbit  SPIF_bit at SPSR.B7;
    const register unsigned short int WCOL = 6;
    sbit  WCOL_bit at SPSR.B6;
    const register unsigned short int SPI2X = 0;
    sbit  SPI2X_bit at SPSR.B0;

sfr io   unsigned char SPCR                      absolute 0x004C;
    const register unsigned short int SPIE = 7;
    sbit  SPIE_bit at SPCR.B7;
    const register unsigned short int SPE = 6;
    sbit  SPE_bit at SPCR.B6;
    const register unsigned short int DORD = 5;
    sbit  DORD_bit at SPCR.B5;
    const register unsigned short int MSTR = 4;
    sbit  MSTR_bit at SPCR.B4;
    const register unsigned short int CPOL = 3;
    sbit  CPOL_bit at SPCR.B3;
    const register unsigned short int CPHA = 2;
    sbit  CPHA_bit at SPCR.B2;
    const register unsigned short int SPR0 = 0;
    sbit  SPR0_bit at SPCR.B0;
    const register unsigned short int SPR1 = 1;
    sbit  SPR1_bit at SPCR.B1;

sfr io   unsigned char volatile PUEA                      absolute 0x0023;
sfr io   unsigned char PORTA                     absolute 0x0022;
sfr io   unsigned char DDRA                      absolute 0x0021;
sfr io   unsigned char volatile PINA                      absolute 0x0020;
sfr io   unsigned char volatile PUEB                      absolute 0x0027;
sfr io   unsigned char PORTB                     absolute 0x0026;
sfr io   unsigned char DDRB                      absolute 0x0025;
sfr io   unsigned char volatile PINB                      absolute 0x0024;
sfr io   unsigned char volatile PHDE                      absolute 0x0034;
    const register unsigned short int PHDEC = 2;
    sbit  PHDEC_bit at PHDE.B2;

sfr io   unsigned char volatile PUEC                      absolute 0x002B;
sfr io   unsigned char PORTC                     absolute 0x002A;
sfr io   unsigned char DDRC                      absolute 0x0029;
sfr io   unsigned char volatile PINC                      absolute 0x0028;
sfr io   unsigned char volatile PUED                      absolute 0x002F;
sfr io   unsigned char PORTD                     absolute 0x002E;
sfr io   unsigned char DDRD                      absolute 0x002D;
sfr io   unsigned char volatile PIND                      absolute 0x002C;
sfr data unsigned char volatile PRR                       absolute 0x0064;
    const register unsigned short int PRTWI = 7;
    sbit  PRTWI_bit at PRR.B7;
    const register unsigned short int PRTIM0 = 5;
    sbit  PRTIM0_bit at PRR.B5;
    const register unsigned short int PRTIM1 = 3;
    sbit  PRTIM1_bit at PRR.B3;
    const register unsigned short int PRSPI = 2;
    sbit  PRSPI_bit at PRR.B2;
    const register unsigned short int PRUSART0 = 1;
    sbit  PRUSART0_bit at PRR.B1;
    const register unsigned short int PRADC = 0;
    sbit  PRADC_bit at PRR.B0;

sfr io   unsigned char volatile CCP                       absolute 0x0056;
sfr data unsigned char volatile CLKPR                     absolute 0x0061;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPS3_bit at CLKPR.B3;

sfr io   unsigned char volatile SREG                      absolute 0x005F;
    const register unsigned short int SREG_I = 7;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_C_bit at SREG.B0;

sfr io   unsigned int  volatile SP                        absolute 0x005D;
sfr io   unsigned char volatile SPL                       absolute 0x005D;
sfr io   unsigned char volatile MCUCR                     absolute 0x0055;
    const register unsigned short int IVSEL = 1;
    sbit  IVSEL_bit at MCUCR.B1;

sfr io   unsigned char volatile MCUSR                     absolute 0x0054;
    const register unsigned short int WDRF = 3;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int BORF = 2;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int EXTRF = 1;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int PORF = 0;
    sbit  PORF_bit at MCUSR.B0;

sfr io   unsigned char volatile GPIOR2                    absolute 0x004B;
sfr io   unsigned char volatile GPIOR1                    absolute 0x004A;
sfr io   unsigned char volatile GPIOR0                    absolute 0x003E;
sfr io   unsigned char SMCR                      absolute 0x0053;
    const register unsigned short int SM0 = 1;
    sbit  SM0_bit at SMCR.B1;
    const register unsigned short int SM1 = 2;
    sbit  SM1_bit at SMCR.B2;
    const register unsigned short int SE = 0;
    sbit  SE_bit at SMCR.B0;

sfr io   unsigned char volatile SPMCSR                    absolute 0x0057;
    const register unsigned short int SPMIE = 7;
    sbit  SPMIE_bit at SPMCSR.B7;
    const register unsigned short int RWWSB = 6;
    sbit  RWWSB_bit at SPMCSR.B6;
    const register unsigned short int RSIG = 5;
    sbit  RSIG_bit at SPMCSR.B5;
    const register unsigned short int RWWSRE = 4;
    sbit  RWWSRE_bit at SPMCSR.B4;
    const register unsigned short int RWFLB = 3;
    sbit  RWFLB_bit at SPMCSR.B3;
    const register unsigned short int PGWRT = 2;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGERS = 1;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int SPMEN = 0;
    sbit  SPMEN_bit at SPMCSR.B0;

sfr data unsigned char volatile OSCCAL0                   absolute 0x0066;
sfr data unsigned char volatile OSCCAL1                   absolute 0x0067;
sfr data unsigned char volatile OSCTCAL0A                 absolute 0x00F0;
sfr data unsigned char volatile OSCTCAL0B                 absolute 0x00F1;
sfr io   unsigned char OCR0B                     absolute 0x0048;
sfr io   unsigned char OCR0A                     absolute 0x0047;
sfr io   unsigned char volatile TCNT0                     absolute 0x0046;
sfr io   unsigned char volatile TCNT0L                    absolute 0x0046;
sfr io   unsigned char volatile TCNT0H                    absolute 0x0047;
sfr io   unsigned char TCCR0B                    absolute 0x0045;
    const register unsigned short int FOC0A = 7;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int WGM02 = 3;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int CS00 = 0;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS01 = 1;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS02 = 2;
    sbit  CS02_bit at TCCR0B.B2;

sfr io   unsigned char TCCR0A                    absolute 0x0044;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A1 = 7;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int WGM00 = 0;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM01 = 1;
    sbit  WGM01_bit at TCCR0A.B1;

sfr data unsigned char TIMSK0                    absolute 0x006E;
    const register unsigned short int OCIE0B = 2;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int TOIE0 = 0;
    sbit  TOIE0_bit at TIMSK0.B0;

sfr io   unsigned char volatile TIFR0                     absolute 0x0035;
    const register unsigned short int OCF0B = 2;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int TOV0 = 0;
    sbit  TOV0_bit at TIFR0.B0;

sfr io   unsigned char volatile GTCCR                     absolute 0x0043;
    const register unsigned short int TSM = 7;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int PSRSYNC = 0;
    sbit  PSRSYNC_bit at GTCCR.B0;

sfr data unsigned char TIMSK1                    absolute 0x006F;
    const register unsigned short int ICIE1 = 5;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int OCIE1B = 2;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int TOIE1 = 0;
    sbit  TOIE1_bit at TIMSK1.B0;

sfr io   unsigned char volatile TIFR1                     absolute 0x0036;
    const register unsigned short int ICF1 = 5;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int OCF1B = 2;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int TOV1 = 0;
    sbit  TOV1_bit at TIFR1.B0;

sfr data unsigned char TCCR1A                    absolute 0x0080;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A1 = 7;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int WGM10 = 0;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM11 = 1;
    sbit  WGM11_bit at TCCR1A.B1;

sfr data unsigned char TCCR1B                    absolute 0x0081;
    const register unsigned short int ICNC1 = 7;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICES1 = 6;
    sbit  ICES1_bit at TCCR1B.B6;
    sbit  WGM10_TCCR1B_bit at TCCR1B.B3;
    sbit  WGM11_TCCR1B_bit at TCCR1B.B4;
    const register unsigned short int CS10 = 0;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS11 = 1;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS12 = 2;
    sbit  CS12_bit at TCCR1B.B2;

sfr data unsigned char volatile TCCR1C                    absolute 0x0082;
    const register unsigned short int FOC1A = 7;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1B_bit at TCCR1C.B6;

sfr data unsigned int  volatile TCNT1                     absolute 0x0084;
sfr data unsigned char volatile TCNT1L                    absolute 0x0084;
sfr data unsigned char volatile TCNT1H                    absolute 0x0085;
sfr data unsigned int  volatile OCR1A                     absolute 0x0088;
sfr data unsigned char volatile OCR1AL                    absolute 0x0088;
sfr data unsigned char volatile OCR1AH                    absolute 0x0089;
sfr data unsigned int  volatile OCR1B                     absolute 0x008A;
sfr data unsigned char volatile OCR1BL                    absolute 0x008A;
sfr data unsigned char volatile OCR1BH                    absolute 0x008B;
sfr data unsigned int  volatile ICR1                      absolute 0x0086;
sfr io   unsigned char volatile GTCCR_TC1                 absolute 0x0043;
    sbit  TSM_GTCCR_TC1_bit at GTCCR_TC1.B7;
    sbit  PSRSYNC_GTCCR_TC1_bit at GTCCR_TC1.B0;

sfr data unsigned char volatile TOCPMSA1                  absolute 0x00E9;
    const register unsigned short int TOCC7S0 = 6;
    sbit  TOCC7S0_bit at TOCPMSA1.B6;
    const register unsigned short int TOCC7S1 = 7;
    sbit  TOCC7S1_bit at TOCPMSA1.B7;
    const register unsigned short int TOCC6S0 = 4;
    sbit  TOCC6S0_bit at TOCPMSA1.B4;
    const register unsigned short int TOCC6S1 = 5;
    sbit  TOCC6S1_bit at TOCPMSA1.B5;
    const register unsigned short int TOCC5S0 = 2;
    sbit  TOCC5S0_bit at TOCPMSA1.B2;
    const register unsigned short int TOCC5S1 = 3;
    sbit  TOCC5S1_bit at TOCPMSA1.B3;
    const register unsigned short int TOCC4S0 = 0;
    sbit  TOCC4S0_bit at TOCPMSA1.B0;
    const register unsigned short int TOCC4S1 = 1;
    sbit  TOCC4S1_bit at TOCPMSA1.B1;

sfr data unsigned char volatile TOCPMSA0                  absolute 0x00E8;
    const register unsigned short int TOCC3S0 = 6;
    sbit  TOCC3S0_bit at TOCPMSA0.B6;
    const register unsigned short int TOCC3S1 = 7;
    sbit  TOCC3S1_bit at TOCPMSA0.B7;
    const register unsigned short int TOCC2S0 = 4;
    sbit  TOCC2S0_bit at TOCPMSA0.B4;
    const register unsigned short int TOCC2S1 = 5;
    sbit  TOCC2S1_bit at TOCPMSA0.B5;
    const register unsigned short int TOCC1S0 = 2;
    sbit  TOCC1S0_bit at TOCPMSA0.B2;
    const register unsigned short int TOCC1S1 = 3;
    sbit  TOCC1S1_bit at TOCPMSA0.B3;
    const register unsigned short int TOCC0S0 = 0;
    sbit  TOCC0S0_bit at TOCPMSA0.B0;
    const register unsigned short int TOCC0S1 = 1;
    sbit  TOCC0S1_bit at TOCPMSA0.B1;

sfr data unsigned char volatile TOCPMCOE                  absolute 0x00E2;
    const register unsigned short int TOCC7OE = 7;
    sbit  TOCC7OE_bit at TOCPMCOE.B7;
    const register unsigned short int TOCC6OE = 6;
    sbit  TOCC6OE_bit at TOCPMCOE.B6;
    const register unsigned short int TOCC5OE = 5;
    sbit  TOCC5OE_bit at TOCPMCOE.B5;
    const register unsigned short int TOCC4OE = 4;
    sbit  TOCC4OE_bit at TOCPMCOE.B4;
    const register unsigned short int TOCC3OE = 3;
    sbit  TOCC3OE_bit at TOCPMCOE.B3;
    const register unsigned short int TOCC2OE = 2;
    sbit  TOCC2OE_bit at TOCPMCOE.B2;
    const register unsigned short int TOCC1OE = 1;
    sbit  TOCC1OE_bit at TOCPMCOE.B1;
    const register unsigned short int TOCC0OE = 0;
    sbit  TOCC0OE_bit at TOCPMCOE.B0;

sfr data unsigned char volatile ADMUXA                    absolute 0x007C;
    const register unsigned short int MUX0 = 0;
    sbit  MUX0_bit at ADMUXA.B0;
    const register unsigned short int MUX1 = 1;
    sbit  MUX1_bit at ADMUXA.B1;
    const register unsigned short int MUX2 = 2;
    sbit  MUX2_bit at ADMUXA.B2;
    const register unsigned short int MUX3 = 3;
    sbit  MUX3_bit at ADMUXA.B3;
    const register unsigned short int MUX4 = 4;
    sbit  MUX4_bit at ADMUXA.B4;

sfr data unsigned char volatile ADMUXB                    absolute 0x007D;
    const register unsigned short int REFS = 5;
    sbit  REFS_bit at ADMUXB.B5;
    const register unsigned short int MUX5 = 0;
    sbit  MUX5_bit at ADMUXB.B0;

sfr data unsigned char volatile ADCSRA                    absolute 0x007A;
    const register unsigned short int ADEN = 7;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADSC = 6;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADATE = 5;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADIF = 4;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIE = 3;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS2 = 2;
    sbit  ADPS2_bit at ADCSRA.B2;

sfr data unsigned int  volatile ADC                       absolute 0x0078;
sfr data unsigned char volatile ADCL                      absolute 0x0078;
sfr data unsigned char volatile ADCH                      absolute 0x0079;
sfr data unsigned char ADCSRB                    absolute 0x007B;
    const register unsigned short int ADLAR = 3;
    sbit  ADLAR_bit at ADCSRB.B3;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS0_bit at ADCSRB.B0;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS1_bit at ADCSRB.B1;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS2_bit at ADCSRB.B2;

sfr data unsigned char volatile DIDR3                     absolute 0x00DF;
    const register unsigned short int ADC27D = 3;
    sbit  ADC27D_bit at DIDR3.B3;
    const register unsigned short int ADC26D = 2;
    sbit  ADC26D_bit at DIDR3.B2;
    const register unsigned short int ADC25D = 1;
    sbit  ADC25D_bit at DIDR3.B1;
    const register unsigned short int ADC24D = 0;
    sbit  ADC24D_bit at DIDR3.B0;

sfr data unsigned char DIDR2                     absolute 0x00DE;
    const register unsigned short int ADC23D = 7;
    sbit  ADC23D_bit at DIDR2.B7;
    const register unsigned short int ADC22D = 6;
    sbit  ADC22D_bit at DIDR2.B6;
    const register unsigned short int ADC21D = 5;
    sbit  ADC21D_bit at DIDR2.B5;
    const register unsigned short int ADC20D = 4;
    sbit  ADC20D_bit at DIDR2.B4;
    const register unsigned short int ADC19D = 3;
    sbit  ADC19D_bit at DIDR2.B3;
    const register unsigned short int ADC18D = 2;
    sbit  ADC18D_bit at DIDR2.B2;
    const register unsigned short int ADC17D = 1;
    sbit  ADC17D_bit at DIDR2.B1;
    const register unsigned short int ADC16D = 0;
    sbit  ADC16D_bit at DIDR2.B0;

sfr data unsigned char DIDR1                     absolute 0x007F;
    const register unsigned short int ADC15D = 7;
    sbit  ADC15D_bit at DIDR1.B7;
    const register unsigned short int ADC14D = 6;
    sbit  ADC14D_bit at DIDR1.B6;
    const register unsigned short int ADC13D = 5;
    sbit  ADC13D_bit at DIDR1.B5;
    const register unsigned short int ADC12D = 4;
    sbit  ADC12D_bit at DIDR1.B4;
    const register unsigned short int ADC11D = 3;
    sbit  ADC11D_bit at DIDR1.B3;
    const register unsigned short int ADC10D = 2;
    sbit  ADC10D_bit at DIDR1.B2;
    const register unsigned short int ADC9D = 1;
    sbit  ADC9D_bit at DIDR1.B1;
    const register unsigned short int ADC8D = 0;
    sbit  ADC8D_bit at DIDR1.B0;

sfr data unsigned char DIDR0                     absolute 0x007E;
    const register unsigned short int ADC7D = 7;
    sbit  ADC7D_bit at DIDR0.B7;
    const register unsigned short int ADC6D = 6;
    sbit  ADC6D_bit at DIDR0.B6;
    const register unsigned short int ADC5D = 5;
    sbit  ADC5D_bit at DIDR0.B5;
    const register unsigned short int ADC4D = 4;
    sbit  ADC4D_bit at DIDR0.B4;
    const register unsigned short int ADC3D = 3;
    sbit  ADC3D_bit at DIDR0.B3;
    const register unsigned short int ADC2D = 2;
    sbit  ADC2D_bit at DIDR0.B2;
    const register unsigned short int ADC1D = 1;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC0D = 0;
    sbit  ADC0D_bit at DIDR0.B0;

sfr io   unsigned char volatile ACSRB                     absolute 0x004F;
    const register unsigned short int HSEL = 7;
    sbit  HSEL_bit at ACSRB.B7;
    const register unsigned short int HLEV = 6;
    sbit  HLEV_bit at ACSRB.B6;
    const register unsigned short int ACNMUX0 = 2;
    sbit  ACNMUX0_bit at ACSRB.B2;
    const register unsigned short int ACNMUX1 = 3;
    sbit  ACNMUX1_bit at ACSRB.B3;
    const register unsigned short int ACPMUX0 = 0;
    sbit  ACPMUX0_bit at ACSRB.B0;
    const register unsigned short int ACPMUX1 = 1;
    sbit  ACPMUX1_bit at ACSRB.B1;

sfr io   unsigned char volatile ACSRA                     absolute 0x0050;
    const register unsigned short int ACD = 7;
    sbit  ACD_bit at ACSRA.B7;
    const register unsigned short int ACPMUX2 = 6;
    sbit  ACPMUX2_bit at ACSRA.B6;
    const register unsigned short int ACO = 5;
    sbit  ACO_bit at ACSRA.B5;
    const register unsigned short int ACI = 4;
    sbit  ACI_bit at ACSRA.B4;
    const register unsigned short int ACIE = 3;
    sbit  ACIE_bit at ACSRA.B3;
    const register unsigned short int ACIC = 2;
    sbit  ACIC_bit at ACSRA.B2;
    const register unsigned short int ACIS0 = 0;
    sbit  ACIS0_bit at ACSRA.B0;
    const register unsigned short int ACIS1 = 1;
    sbit  ACIS1_bit at ACSRA.B1;

sfr data unsigned char volatile EICRA                     absolute 0x0069;
    const register unsigned short int ISC10 = 2;
    sbit  ISC10_bit at EICRA.B2;
    const register unsigned short int ISC11 = 3;
    sbit  ISC11_bit at EICRA.B3;
    const register unsigned short int ISC00 = 0;
    sbit  ISC00_bit at EICRA.B0;
    const register unsigned short int ISC01 = 1;
    sbit  ISC01_bit at EICRA.B1;

sfr io   unsigned char EIMSK                     absolute 0x003D;
    const register unsigned short int INT0 = 0;
    sbit  INT0_bit at EIMSK.B0;
    const register unsigned short int INT1 = 1;
    sbit  INT1_bit at EIMSK.B1;

sfr io   unsigned char volatile EIFR                      absolute 0x003C;
    const register unsigned short int INTF0 = 0;
    sbit  INTF0_bit at EIFR.B0;
    const register unsigned short int INTF1 = 1;
    sbit  INTF1_bit at EIFR.B1;

sfr data unsigned char PCICR                     absolute 0x0068;
    const register unsigned short int PCIE0 = 0;
    sbit  PCIE0_bit at PCICR.B0;
    const register unsigned short int PCIE1 = 1;
    sbit  PCIE1_bit at PCICR.B1;
    const register unsigned short int PCIE2 = 2;
    sbit  PCIE2_bit at PCICR.B2;
    const register unsigned short int PCIE3 = 3;
    sbit  PCIE3_bit at PCICR.B3;

sfr data unsigned char volatile PCMSK3                    absolute 0x0073;
    const register unsigned short int PCINT0 = 0;
    sbit  PCINT0_bit at PCMSK3.B0;
    const register unsigned short int PCINT1 = 1;
    sbit  PCINT1_bit at PCMSK3.B1;
    const register unsigned short int PCINT2 = 2;
    sbit  PCINT2_bit at PCMSK3.B2;
    const register unsigned short int PCINT3 = 3;
    sbit  PCINT3_bit at PCMSK3.B3;

sfr data unsigned char PCMSK2                    absolute 0x006D;
    sbit  PCINT0_PCMSK2_bit at PCMSK2.B0;
    sbit  PCINT1_PCMSK2_bit at PCMSK2.B1;
    sbit  PCINT2_PCMSK2_bit at PCMSK2.B2;
    sbit  PCINT3_PCMSK2_bit at PCMSK2.B3;
    const register unsigned short int PCINT4 = 4;
    sbit  PCINT4_bit at PCMSK2.B4;
    const register unsigned short int PCINT5 = 5;
    sbit  PCINT5_bit at PCMSK2.B5;
    const register unsigned short int PCINT6 = 6;
    sbit  PCINT6_bit at PCMSK2.B6;
    const register unsigned short int PCINT7 = 7;
    sbit  PCINT7_bit at PCMSK2.B7;

sfr data unsigned char PCMSK1                    absolute 0x006C;
    sbit  PCINT0_PCMSK1_bit at PCMSK1.B0;
    sbit  PCINT1_PCMSK1_bit at PCMSK1.B1;
    sbit  PCINT2_PCMSK1_bit at PCMSK1.B2;
    sbit  PCINT3_PCMSK1_bit at PCMSK1.B3;
    sbit  PCINT4_PCMSK1_bit at PCMSK1.B4;
    sbit  PCINT5_PCMSK1_bit at PCMSK1.B5;
    sbit  PCINT6_PCMSK1_bit at PCMSK1.B6;
    sbit  PCINT7_PCMSK1_bit at PCMSK1.B7;

sfr data unsigned char PCMSK0                    absolute 0x006B;
    sbit  PCINT0_PCMSK0_bit at PCMSK0.B0;
    sbit  PCINT1_PCMSK0_bit at PCMSK0.B1;
    sbit  PCINT2_PCMSK0_bit at PCMSK0.B2;
    sbit  PCINT3_PCMSK0_bit at PCMSK0.B3;
    sbit  PCINT4_PCMSK0_bit at PCMSK0.B4;
    sbit  PCINT5_PCMSK0_bit at PCMSK0.B5;
    sbit  PCINT6_PCMSK0_bit at PCMSK0.B6;
    sbit  PCINT7_PCMSK0_bit at PCMSK0.B7;

sfr io   unsigned char volatile PCIFR                     absolute 0x003B;
    const register unsigned short int PCIF0 = 0;
    sbit  PCIF0_bit at PCIFR.B0;
    const register unsigned short int PCIF1 = 1;
    sbit  PCIF1_bit at PCIFR.B1;
    const register unsigned short int PCIF2 = 2;
    sbit  PCIF2_bit at PCIFR.B2;
    const register unsigned short int PCIF3 = 3;
    sbit  PCIF3_bit at PCIFR.B3;

sfr data unsigned char volatile WDTCSR                    absolute 0x0060;
    const register unsigned short int WDIF = 7;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIE = 6;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDP0 = 0;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP1 = 1;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP2 = 2;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP3 = 5;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDE = 3;
    sbit  WDE_bit at WDTCSR.B3;

sfr io   unsigned char volatile EEAR                      absolute 0x0041;
sfr io   unsigned char volatile EEARL                     absolute 0x0041;
sfr io   unsigned char volatile EEARH                     absolute 0x0042;
sfr io   unsigned char volatile EEDR                      absolute 0x0040;
sfr io   unsigned char volatile EECR                      absolute 0x003F;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM1 = 5;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EERIE = 3;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EEMPE = 2;
    sbit  EEMPE_bit at EECR.B2;
    const register unsigned short int EEPE = 1;
    sbit  EEPE_bit at EECR.B1;
    const register unsigned short int EERE = 0;
    sbit  EERE_bit at EECR.B0;

sfr data unsigned char volatile TWSCRA                    absolute 0x00B8;
    const register unsigned short int TWSHE = 7;
    sbit  TWSHE_bit at TWSCRA.B7;
    const register unsigned short int TWDIE = 5;
    sbit  TWDIE_bit at TWSCRA.B5;
    const register unsigned short int TWASIE = 4;
    sbit  TWASIE_bit at TWSCRA.B4;
    const register unsigned short int TWEN = 3;
    sbit  TWEN_bit at TWSCRA.B3;
    const register unsigned short int TWSIE = 2;
    sbit  TWSIE_bit at TWSCRA.B2;
    const register unsigned short int TWPME = 1;
    sbit  TWPME_bit at TWSCRA.B1;
    const register unsigned short int TWSME = 0;
    sbit  TWSME_bit at TWSCRA.B0;

sfr data unsigned char volatile TWSCRB                    absolute 0x00B9;
    const register unsigned short int TWHNM = 3;
    sbit  TWHNM_bit at TWSCRB.B3;
    const register unsigned short int TWAA = 2;
    sbit  TWAA_bit at TWSCRB.B2;
    const register unsigned short int TWCMD0 = 0;
    sbit  TWCMD0_bit at TWSCRB.B0;
    const register unsigned short int TWCMD1 = 1;
    sbit  TWCMD1_bit at TWSCRB.B1;

sfr data unsigned char volatile TWSSRA                    absolute 0x00BA;
    const register unsigned short int TWDIF = 7;
    sbit  TWDIF_bit at TWSSRA.B7;
    const register unsigned short int TWASIF = 6;
    sbit  TWASIF_bit at TWSSRA.B6;
    const register unsigned short int TWCH = 5;
    sbit  TWCH_bit at TWSSRA.B5;
    const register unsigned short int TWRA = 4;
    sbit  TWRA_bit at TWSSRA.B4;
    const register unsigned short int TWC = 3;
    sbit  TWC_bit at TWSSRA.B3;
    const register unsigned short int TWBE = 2;
    sbit  TWBE_bit at TWSSRA.B2;
    const register unsigned short int TWDIR = 1;
    sbit  TWDIR_bit at TWSSRA.B1;
    const register unsigned short int TWAS = 0;
    sbit  TWAS_bit at TWSSRA.B0;

sfr data unsigned char volatile TWSA                      absolute 0x00BC;
sfr data unsigned char volatile TWSD                      absolute 0x00BD;
    const register unsigned short int TWSD0 = 0;
    sbit  TWSD0_bit at TWSD.B0;
    const register unsigned short int TWSD1 = 1;
    sbit  TWSD1_bit at TWSD.B1;
    const register unsigned short int TWSD2 = 2;
    sbit  TWSD2_bit at TWSD.B2;
    const register unsigned short int TWSD3 = 3;
    sbit  TWSD3_bit at TWSD.B3;
    const register unsigned short int TWSD4 = 4;
    sbit  TWSD4_bit at TWSD.B4;
    const register unsigned short int TWSD5 = 5;
    sbit  TWSD5_bit at TWSD.B5;
    const register unsigned short int TWSD6 = 6;
    sbit  TWSD6_bit at TWSD.B6;
    const register unsigned short int TWSD7 = 7;
    sbit  TWSD7_bit at TWSD.B7;

sfr data unsigned char volatile TWSAM                     absolute 0x00BB;
    const register unsigned short int TWSAM0 = 1;
    sbit  TWSAM0_bit at TWSAM.B1;
    const register unsigned short int TWSAM1 = 2;
    sbit  TWSAM1_bit at TWSAM.B2;
    const register unsigned short int TWSAM2 = 3;
    sbit  TWSAM2_bit at TWSAM.B3;
    const register unsigned short int TWSAM3 = 4;
    sbit  TWSAM3_bit at TWSAM.B4;
    const register unsigned short int TWSAM4 = 5;
    sbit  TWSAM4_bit at TWSAM.B5;
    const register unsigned short int TWSAM5 = 6;
    sbit  TWSAM5_bit at TWSAM.B6;
    const register unsigned short int TWSAM6 = 7;
    sbit  TWSAM6_bit at TWSAM.B7;
    const register unsigned short int TWAE = 0;
    sbit  TWAE_bit at TWSAM.B0;

sfr data unsigned char volatile UDR                       absolute 0x00C6;
sfr data unsigned char volatile UCSRA                     absolute 0x00C0;
    const register unsigned short int RXC = 7;
    sbit  RXC_bit at UCSRA.B7;
    const register unsigned short int TXC = 6;
    sbit  TXC_bit at UCSRA.B6;
    const register unsigned short int UDRE = 5;
    sbit  UDRE_bit at UCSRA.B5;
    const register unsigned short int FE = 4;
    sbit  FE_bit at UCSRA.B4;
    const register unsigned short int DOR = 3;
    sbit  DOR_bit at UCSRA.B3;
    const register unsigned short int UPE = 2;
    sbit  UPE_bit at UCSRA.B2;
    const register unsigned short int U2X = 1;
    sbit  U2X_bit at UCSRA.B1;
    const register unsigned short int MPCM = 0;
    sbit  MPCM_bit at UCSRA.B0;

sfr data unsigned char volatile UCSRB                     absolute 0x00C1;
    const register unsigned short int RXCIE = 7;
    sbit  RXCIE_bit at UCSRB.B7;
    const register unsigned short int TXCIE = 6;
    sbit  TXCIE_bit at UCSRB.B6;
    const register unsigned short int UDRIE = 5;
    sbit  UDRIE_bit at UCSRB.B5;
    const register unsigned short int RXEN = 4;
    sbit  RXEN_bit at UCSRB.B4;
    const register unsigned short int TXEN = 3;
    sbit  TXEN_bit at UCSRB.B3;
    const register unsigned short int UCSZ2 = 2;
    sbit  UCSZ2_bit at UCSRB.B2;
    const register unsigned short int RXB8 = 1;
    sbit  RXB8_bit at UCSRB.B1;
    const register unsigned short int TXB8 = 0;
    sbit  TXB8_bit at UCSRB.B0;

sfr data unsigned char volatile UCSRC                     absolute 0x00C2;
    const register unsigned short int UMSEL0 = 6;
    sbit  UMSEL0_bit at UCSRC.B6;
    const register unsigned short int UMSEL1 = 7;
    sbit  UMSEL1_bit at UCSRC.B7;
    const register unsigned short int UPM0 = 4;
    sbit  UPM0_bit at UCSRC.B4;
    const register unsigned short int UPM1 = 5;
    sbit  UPM1_bit at UCSRC.B5;
    const register unsigned short int USBS = 3;
    sbit  USBS_bit at UCSRC.B3;
    const register unsigned short int UCSZ0 = 1;
    sbit  UCSZ0_bit at UCSRC.B1;
    const register unsigned short int UCSZ1 = 2;
    sbit  UCSZ1_bit at UCSRC.B2;
    const register unsigned short int UCPOL = 0;
    sbit  UCPOL_bit at UCSRC.B0;

sfr data unsigned char volatile UCSRD                     absolute 0x00C3;
    const register unsigned short int RXSIE = 7;
    sbit  RXSIE_bit at UCSRD.B7;
    const register unsigned short int RXS = 6;
    sbit  RXS_bit at UCSRD.B6;
    const register unsigned short int SFDE = 5;
    sbit  SFDE_bit at UCSRD.B5;

sfr data unsigned int  UBRR                      absolute 0x00C4;
sfr io   unsigned char volatile EXTENDED_                 absolute 0x0002;
    const register unsigned short int BOOTSZ0 = 1;
    sbit  BOOTSZ0_bit at EXTENDED_.B1;
    const register unsigned short int BOOTSZ1 = 2;
    sbit  BOOTSZ1_bit at EXTENDED_.B2;
    const register unsigned short int BOOTRST = 0;
    sbit  BOOTRST_bit at EXTENDED_.B0;
    const register unsigned short int BODPD0 = 6;
    sbit  BODPD0_bit at EXTENDED_.B6;
    const register unsigned short int BODPD1 = 7;
    sbit  BODPD1_bit at EXTENDED_.B7;
    const register unsigned short int BODACT0 = 4;
    sbit  BODACT0_bit at EXTENDED_.B4;
    const register unsigned short int BODACT1 = 5;
    sbit  BODACT1_bit at EXTENDED_.B5;

sfr io   unsigned char volatile HIGH                      absolute 0x0001;
    const register unsigned short int RSTDISBL = 7;
    sbit  RSTDISBL_bit at HIGH.B7;
    const register unsigned short int DWEN = 6;
    sbit  DWEN_bit at HIGH.B6;
    const register unsigned short int SPIEN = 5;
    sbit  SPIEN_bit at HIGH.B5;
    const register unsigned short int WDTON = 4;
    sbit  WDTON_bit at HIGH.B4;
    const register unsigned short int EESAVE = 3;
    sbit  EESAVE_bit at HIGH.B3;
    const register unsigned short int BODLEVEL0 = 0;
    sbit  BODLEVEL0_bit at HIGH.B0;
    const register unsigned short int BODLEVEL1 = 1;
    sbit  BODLEVEL1_bit at HIGH.B1;
    const register unsigned short int BODLEVEL2 = 2;
    sbit  BODLEVEL2_bit at HIGH.B2;

sfr io   unsigned char volatile LOW                       absolute 0x0000;
    const register unsigned short int CKDIV8 = 7;
    sbit  CKDIV8_bit at LOW.B7;
    const register unsigned short int CKOUT = 6;
    sbit  CKOUT_bit at LOW.B6;
    const register unsigned short int SUT_CKSEL0 = 0;
    sbit  SUT_CKSEL0_bit at LOW.B0;
    const register unsigned short int SUT_CKSEL1 = 1;
    sbit  SUT_CKSEL1_bit at LOW.B1;
    const register unsigned short int SUT_CKSEL2 = 4;
    sbit  SUT_CKSEL2_bit at LOW.B4;
    const register unsigned short int SUT_CKSEL3 = 5;
    sbit  SUT_CKSEL3_bit at LOW.B5;

sfr io   unsigned char volatile LOCKBIT                   absolute 0x0000;
    const register unsigned short int LB0 = 0;
    sbit  LB0_bit at LOCKBIT.B0;
    const register unsigned short int LB1 = 1;
    sbit  LB1_bit at LOCKBIT.B1;
    const register unsigned short int BLB00 = 2;
    sbit  BLB00_bit at LOCKBIT.B2;
    const register unsigned short int BLB01 = 3;
    sbit  BLB01_bit at LOCKBIT.B3;
    const register unsigned short int BLB10 = 4;
    sbit  BLB10_bit at LOCKBIT.B4;
    const register unsigned short int BLB11 = 5;
    sbit  BLB11_bit at LOCKBIT.B5;

