// Individual bit access constants
const char B0 = 0;
const char B1 = 1;
const char B2 = 2;
const char B3 = 3;
const char B4 = 4;
const char B5 = 5;
const char B6 = 6;
const char B7 = 7;

const unsigned long __FLASH_SIZE = 0x00002000;

const unsigned short ICS_AUTO                  =     0;
const unsigned short ICS_OFF                   =     3;

// Addres offset from Output to Input (port) registers
const signed short   OUTPUT_TO_INPUT_OFFSET    =     -2;

// Rx space registers
sfr rx unsigned short R0  absolute 0x00;
sfr rx unsigned short R1  absolute 0x01;
sfr rx unsigned short R2  absolute 0x02;
sfr rx unsigned short R3  absolute 0x03;
sfr rx unsigned short R4  absolute 0x04;
sfr rx unsigned short R5  absolute 0x05;
sfr rx unsigned short R6  absolute 0x06;
sfr rx unsigned short R7  absolute 0x07;
sfr rx unsigned short R8  absolute 0x08;
sfr rx unsigned short R9  absolute 0x09;
sfr rx unsigned short R10 absolute 0x0A;
sfr rx unsigned short R11 absolute 0x0B;
sfr rx unsigned short R12 absolute 0x0C;
sfr rx unsigned short R13 absolute 0x0D;
sfr rx unsigned short R14 absolute 0x0E;
sfr rx unsigned short R15 absolute 0x0F;
sfr rx unsigned short R16 absolute 0x10;
sfr rx unsigned short R17 absolute 0x11;
sfr rx unsigned short R18 absolute 0x12;
sfr rx unsigned short R19 absolute 0x13;
sfr rx unsigned short R20 absolute 0x14;
sfr rx unsigned short R21 absolute 0x15;
sfr rx unsigned short R22 absolute 0x16;
sfr rx unsigned short R23 absolute 0x17;
sfr rx unsigned short R24 absolute 0x18;
sfr rx unsigned short R25 absolute 0x19;
sfr rx unsigned short R26 absolute 0x1A;
sfr rx unsigned short R27 absolute 0x1B;
sfr rx unsigned short R28 absolute 0x1C;
sfr rx unsigned short R29 absolute 0x1D;
sfr rx unsigned short R30 absolute 0x1E;
sfr rx unsigned short R31 absolute 0x1F;

// X, Y and Z registers
sfr rx unsigned short XL absolute 0x1A;
sfr rx unsigned short XH absolute 0x1B;
sfr rx unsigned short YL absolute 0x1C;
sfr rx unsigned short YH absolute 0x1D;
sfr rx unsigned short ZL absolute 0x1E;
sfr rx unsigned short ZH absolute 0x1F;
sfr rx unsigned int   X  absolute 0x1A;
sfr rx unsigned int   Y  absolute 0x1C;
sfr rx unsigned int   Z  absolute 0x1E;


// Interrupt Vector Table Constants
const unsigned short IVT_ADDR_EXT_INT0 = 0x0001;
const unsigned short IVT_ADDR_PCINT0 = 0x0002;
const unsigned short IVT_ADDR_PCINT1 = 0x0003;
const unsigned short IVT_ADDR_WDT = 0x0004;
const unsigned short IVT_ADDR_TIM1_CAPT = 0x0005;
const unsigned short IVT_ADDR_TIM1_COMPA = 0x0006;
const unsigned short IVT_ADDR_TIM1_COMPB = 0x0007;
const unsigned short IVT_ADDR_TIM1_OVF = 0x0008;
const unsigned short IVT_ADDR_TIM0_COMPA = 0x0009;
const unsigned short IVT_ADDR_TIM0_COMPB = 0x000A;
const unsigned short IVT_ADDR_TIM0_OVF = 0x000B;
const unsigned short IVT_ADDR_ANA_COMP = 0x000C;
const unsigned short IVT_ADDR_ADC = 0x000D;
const unsigned short IVT_ADDR_EE_RDY = 0x000E;
const unsigned short IVT_ADDR_USI_STR = 0x000F;
const unsigned short IVT_ADDR_USI_OVF = 0x0010;

sfr io   unsigned char PORTA                     absolute 0x003B;
sfr io   unsigned char DDRA                      absolute 0x003A;
sfr io   unsigned char volatile PINA                      absolute 0x0039;
sfr io   unsigned char PORTB                     absolute 0x0038;
sfr io   unsigned char DDRB                      absolute 0x0037;
sfr io   unsigned char volatile PINB                      absolute 0x0036;
sfr io   unsigned char ADCSRB                    absolute 0x0023;
    const register unsigned short int ACME = 6;
    sbit  ACME_bit at ADCSRB.B6;

sfr io   unsigned char volatile ACSR                      absolute 0x0028;
    const register unsigned short int ACD = 7;
    sbit  ACD_bit at ACSR.B7;
    const register unsigned short int ACBG = 6;
    sbit  ACBG_bit at ACSR.B6;
    const register unsigned short int ACO = 5;
    sbit  ACO_bit at ACSR.B5;
    const register unsigned short int ACI = 4;
    sbit  ACI_bit at ACSR.B4;
    const register unsigned short int ACIE = 3;
    sbit  ACIE_bit at ACSR.B3;
    const register unsigned short int ACIC = 2;
    sbit  ACIC_bit at ACSR.B2;
    const register unsigned short int ACIS0 = 0;
    sbit  ACIS0_bit at ACSR.B0;
    const register unsigned short int ACIS1 = 1;
    sbit  ACIS1_bit at ACSR.B1;

sfr io   unsigned char DIDR0                     absolute 0x0021;
    const register unsigned short int ADC1D = 1;
    sbit  ADC1D_bit at DIDR0.B1;
    const register unsigned short int ADC0D = 0;
    sbit  ADC0D_bit at DIDR0.B0;

sfr io   unsigned char ADMUX                     absolute 0x0027;
sfr io   unsigned char volatile ADCSRA                    absolute 0x0026;
    const register unsigned short int ADEN = 7;
    sbit  ADEN_bit at ADCSRA.B7;
    const register unsigned short int ADSC = 6;
    sbit  ADSC_bit at ADCSRA.B6;
    const register unsigned short int ADATE = 5;
    sbit  ADATE_bit at ADCSRA.B5;
    const register unsigned short int ADIF = 4;
    sbit  ADIF_bit at ADCSRA.B4;
    const register unsigned short int ADIE = 3;
    sbit  ADIE_bit at ADCSRA.B3;
    const register unsigned short int ADPS0 = 0;
    sbit  ADPS0_bit at ADCSRA.B0;
    const register unsigned short int ADPS1 = 1;
    sbit  ADPS1_bit at ADCSRA.B1;
    const register unsigned short int ADPS2 = 2;
    sbit  ADPS2_bit at ADCSRA.B2;

sfr io   unsigned int  volatile ADC                       absolute 0x0024;
sfr io   unsigned char volatile ADCL                      absolute 0x0024;
sfr io   unsigned char volatile ADCH                      absolute 0x0025;
sfr io   unsigned char volatile ADCSRB_ADC                absolute 0x0023;
    const register unsigned short int BIN = 7;
    sbit  BIN_bit at ADCSRB_ADC.B7;
    const register unsigned short int ADLAR = 4;
    sbit  ADLAR_bit at ADCSRB_ADC.B4;
    const register unsigned short int ADTS0 = 0;
    sbit  ADTS0_bit at ADCSRB_ADC.B0;
    const register unsigned short int ADTS1 = 1;
    sbit  ADTS1_bit at ADCSRB_ADC.B1;
    const register unsigned short int ADTS2 = 2;
    sbit  ADTS2_bit at ADCSRB_ADC.B2;

sfr io   unsigned char volatile DIDR0_ADC                 absolute 0x0021;
sfr io   unsigned char volatile USIBR                     absolute 0x0030;
sfr io   unsigned char volatile USIDR                     absolute 0x002F;
sfr io   unsigned char volatile USISR                     absolute 0x002E;
    const register unsigned short int USISIF = 7;
    sbit  USISIF_bit at USISR.B7;
    const register unsigned short int USIOIF = 6;
    sbit  USIOIF_bit at USISR.B6;
    const register unsigned short int USIPF = 5;
    sbit  USIPF_bit at USISR.B5;
    const register unsigned short int USIDC = 4;
    sbit  USIDC_bit at USISR.B4;
    const register unsigned short int USICNT0 = 0;
    sbit  USICNT0_bit at USISR.B0;
    const register unsigned short int USICNT1 = 1;
    sbit  USICNT1_bit at USISR.B1;
    const register unsigned short int USICNT2 = 2;
    sbit  USICNT2_bit at USISR.B2;
    const register unsigned short int USICNT3 = 3;
    sbit  USICNT3_bit at USISR.B3;

sfr io   unsigned char volatile USICR                     absolute 0x002D;
    const register unsigned short int USISIE = 7;
    sbit  USISIE_bit at USICR.B7;
    const register unsigned short int USIOIE = 6;
    sbit  USIOIE_bit at USICR.B6;
    const register unsigned short int USIWM0 = 4;
    sbit  USIWM0_bit at USICR.B4;
    const register unsigned short int USIWM1 = 5;
    sbit  USIWM1_bit at USICR.B5;
    const register unsigned short int USICS0 = 2;
    sbit  USICS0_bit at USICR.B2;
    const register unsigned short int USICS1 = 3;
    sbit  USICS1_bit at USICR.B3;
    const register unsigned short int USICLK = 1;
    sbit  USICLK_bit at USICR.B1;
    const register unsigned short int USITC = 0;
    sbit  USITC_bit at USICR.B0;

sfr io   unsigned char volatile MCUCR                     absolute 0x0055;
    const register unsigned short int ISC00 = 0;
    sbit  ISC00_bit at MCUCR.B0;
    const register unsigned short int ISC01 = 1;
    sbit  ISC01_bit at MCUCR.B1;

sfr io   unsigned char volatile GIMSK                     absolute 0x005B;
    const register unsigned short int INT0 = 6;
    sbit  INT0_bit at GIMSK.B6;
    const register unsigned short int PCIE0 = 4;
    sbit  PCIE0_bit at GIMSK.B4;
    const register unsigned short int PCIE1 = 5;
    sbit  PCIE1_bit at GIMSK.B5;

sfr io   unsigned char volatile GIFR                      absolute 0x005A;
    const register unsigned short int INTF0 = 6;
    sbit  INTF0_bit at GIFR.B6;
    const register unsigned short int PCIF0 = 4;
    sbit  PCIF0_bit at GIFR.B4;
    const register unsigned short int PCIF1 = 5;
    sbit  PCIF1_bit at GIFR.B5;

sfr io   unsigned char PCMSK1                    absolute 0x0040;
sfr io   unsigned char PCMSK0                    absolute 0x0032;
sfr io   unsigned int  volatile EEAR                      absolute 0x003E;
sfr io   unsigned char volatile EEARL                     absolute 0x003E;
sfr io   unsigned char volatile EEARH                     absolute 0x003F;
sfr io   unsigned char volatile EEDR                      absolute 0x003D;
sfr io   unsigned char volatile EECR                      absolute 0x003C;
    const register unsigned short int EEPM0 = 4;
    sbit  EEPM0_bit at EECR.B4;
    const register unsigned short int EEPM1 = 5;
    sbit  EEPM1_bit at EECR.B5;
    const register unsigned short int EERIE = 3;
    sbit  EERIE_bit at EECR.B3;
    const register unsigned short int EEMPE = 2;
    sbit  EEMPE_bit at EECR.B2;
    const register unsigned short int EEPE = 1;
    sbit  EEPE_bit at EECR.B1;
    const register unsigned short int EERE = 0;
    sbit  EERE_bit at EECR.B0;

sfr io   unsigned char volatile WDTCSR                    absolute 0x0041;
    const register unsigned short int WDIF = 7;
    sbit  WDIF_bit at WDTCSR.B7;
    const register unsigned short int WDIE = 6;
    sbit  WDIE_bit at WDTCSR.B6;
    const register unsigned short int WDP0 = 0;
    sbit  WDP0_bit at WDTCSR.B0;
    const register unsigned short int WDP1 = 1;
    sbit  WDP1_bit at WDTCSR.B1;
    const register unsigned short int WDP2 = 2;
    sbit  WDP2_bit at WDTCSR.B2;
    const register unsigned short int WDP3 = 5;
    sbit  WDP3_bit at WDTCSR.B5;
    const register unsigned short int WDCE = 4;
    sbit  WDCE_bit at WDTCSR.B4;
    const register unsigned short int WDE = 3;
    sbit  WDE_bit at WDTCSR.B3;

sfr io   unsigned char TIMSK0                    absolute 0x0059;
    const register unsigned short int OCIE0B = 2;
    sbit  OCIE0B_bit at TIMSK0.B2;
    const register unsigned short int OCIE0A = 1;
    sbit  OCIE0A_bit at TIMSK0.B1;
    const register unsigned short int TOIE0 = 0;
    sbit  TOIE0_bit at TIMSK0.B0;

sfr io   unsigned char volatile TIFR0                     absolute 0x0058;
    const register unsigned short int OCF0B = 2;
    sbit  OCF0B_bit at TIFR0.B2;
    const register unsigned short int OCF0A = 1;
    sbit  OCF0A_bit at TIFR0.B1;
    const register unsigned short int TOV0 = 0;
    sbit  TOV0_bit at TIFR0.B0;

sfr io   unsigned char TCCR0A                    absolute 0x0050;
    const register unsigned short int COM0A0 = 6;
    sbit  COM0A0_bit at TCCR0A.B6;
    const register unsigned short int COM0A1 = 7;
    sbit  COM0A1_bit at TCCR0A.B7;
    const register unsigned short int COM0B0 = 4;
    sbit  COM0B0_bit at TCCR0A.B4;
    const register unsigned short int COM0B1 = 5;
    sbit  COM0B1_bit at TCCR0A.B5;
    const register unsigned short int WGM00 = 0;
    sbit  WGM00_bit at TCCR0A.B0;
    const register unsigned short int WGM01 = 1;
    sbit  WGM01_bit at TCCR0A.B1;

sfr io   unsigned char TCCR0B                    absolute 0x0053;
    const register unsigned short int FOC0A = 7;
    sbit  FOC0A_bit at TCCR0B.B7;
    const register unsigned short int FOC0B = 6;
    sbit  FOC0B_bit at TCCR0B.B6;
    const register unsigned short int WGM02 = 3;
    sbit  WGM02_bit at TCCR0B.B3;
    const register unsigned short int CS00 = 0;
    sbit  CS00_bit at TCCR0B.B0;
    const register unsigned short int CS01 = 1;
    sbit  CS01_bit at TCCR0B.B1;
    const register unsigned short int CS02 = 2;
    sbit  CS02_bit at TCCR0B.B2;

sfr io   unsigned char volatile TCNT0                     absolute 0x0052;
sfr io   unsigned char volatile TCNT0L                    absolute 0x0052;
sfr io   unsigned char volatile TCNT0H                    absolute 0x0053;
sfr io   unsigned char OCR0A                     absolute 0x0056;
sfr io   unsigned char OCR0B                     absolute 0x005C;
sfr io   unsigned char volatile GTCCR                     absolute 0x0043;
    const register unsigned short int TSM = 7;
    sbit  TSM_bit at GTCCR.B7;
    const register unsigned short int PSR10 = 0;
    sbit  PSR10_bit at GTCCR.B0;

sfr io   unsigned char TIMSK1                    absolute 0x002C;
    const register unsigned short int ICIE1 = 5;
    sbit  ICIE1_bit at TIMSK1.B5;
    const register unsigned short int OCIE1B = 2;
    sbit  OCIE1B_bit at TIMSK1.B2;
    const register unsigned short int OCIE1A = 1;
    sbit  OCIE1A_bit at TIMSK1.B1;
    const register unsigned short int TOIE1 = 0;
    sbit  TOIE1_bit at TIMSK1.B0;

sfr io   unsigned char volatile TIFR1                     absolute 0x002B;
    const register unsigned short int ICF1 = 5;
    sbit  ICF1_bit at TIFR1.B5;
    const register unsigned short int OCF1B = 2;
    sbit  OCF1B_bit at TIFR1.B2;
    const register unsigned short int OCF1A = 1;
    sbit  OCF1A_bit at TIFR1.B1;
    const register unsigned short int TOV1 = 0;
    sbit  TOV1_bit at TIFR1.B0;

sfr io   unsigned char TCCR1A                    absolute 0x004F;
    const register unsigned short int COM1A0 = 6;
    sbit  COM1A0_bit at TCCR1A.B6;
    const register unsigned short int COM1A1 = 7;
    sbit  COM1A1_bit at TCCR1A.B7;
    const register unsigned short int COM1B0 = 4;
    sbit  COM1B0_bit at TCCR1A.B4;
    const register unsigned short int COM1B1 = 5;
    sbit  COM1B1_bit at TCCR1A.B5;
    const register unsigned short int WGM10 = 0;
    sbit  WGM10_bit at TCCR1A.B0;
    const register unsigned short int WGM11 = 1;
    sbit  WGM11_bit at TCCR1A.B1;

sfr io   unsigned char TCCR1B                    absolute 0x004E;
    const register unsigned short int ICNC1 = 7;
    sbit  ICNC1_bit at TCCR1B.B7;
    const register unsigned short int ICES1 = 6;
    sbit  ICES1_bit at TCCR1B.B6;
    sbit  WGM10_TCCR1B_bit at TCCR1B.B3;
    sbit  WGM11_TCCR1B_bit at TCCR1B.B4;
    const register unsigned short int CS10 = 0;
    sbit  CS10_bit at TCCR1B.B0;
    const register unsigned short int CS11 = 1;
    sbit  CS11_bit at TCCR1B.B1;
    const register unsigned short int CS12 = 2;
    sbit  CS12_bit at TCCR1B.B2;

sfr io   unsigned char volatile TCCR1C                    absolute 0x0042;
    const register unsigned short int FOC1A = 7;
    sbit  FOC1A_bit at TCCR1C.B7;
    const register unsigned short int FOC1B = 6;
    sbit  FOC1B_bit at TCCR1C.B6;

sfr io   unsigned int  volatile TCNT1                     absolute 0x004C;
sfr io   unsigned char volatile TCNT1L                    absolute 0x004C;
sfr io   unsigned char volatile TCNT1H                    absolute 0x004D;
sfr io   unsigned int  volatile OCR1A                     absolute 0x004A;
sfr io   unsigned char volatile OCR1AL                    absolute 0x004A;
sfr io   unsigned char volatile OCR1AH                    absolute 0x004B;
sfr io   unsigned int  volatile OCR1B                     absolute 0x0048;
sfr io   unsigned char volatile OCR1BL                    absolute 0x0048;
sfr io   unsigned char volatile OCR1BH                    absolute 0x0049;
sfr io   unsigned int  volatile ICR1                      absolute 0x0044;
sfr io   unsigned char volatile PRR                       absolute 0x0020;
    const register unsigned short int PRTIM1 = 3;
    sbit  PRTIM1_bit at PRR.B3;
    const register unsigned short int PRTIM0 = 2;
    sbit  PRTIM0_bit at PRR.B2;
    const register unsigned short int PRUSI = 1;
    sbit  PRUSI_bit at PRR.B1;
    const register unsigned short int PRADC = 0;
    sbit  PRADC_bit at PRR.B0;

sfr io   unsigned char OSCCAL                    absolute 0x0051;
    const register unsigned short int OSCCAL0 = 0;
    sbit  OSCCAL0_bit at OSCCAL.B0;
    const register unsigned short int OSCCAL1 = 1;
    sbit  OSCCAL1_bit at OSCCAL.B1;
    const register unsigned short int OSCCAL2 = 2;
    sbit  OSCCAL2_bit at OSCCAL.B2;
    const register unsigned short int OSCCAL3 = 3;
    sbit  OSCCAL3_bit at OSCCAL.B3;
    const register unsigned short int OSCCAL4 = 4;
    sbit  OSCCAL4_bit at OSCCAL.B4;
    const register unsigned short int OSCCAL5 = 5;
    sbit  OSCCAL5_bit at OSCCAL.B5;
    const register unsigned short int OSCCAL6 = 6;
    sbit  OSCCAL6_bit at OSCCAL.B6;
    const register unsigned short int OSCCAL7 = 7;
    sbit  OSCCAL7_bit at OSCCAL.B7;

sfr io   unsigned char volatile CLKPR                     absolute 0x0046;
    const register unsigned short int CLKPCE = 7;
    sbit  CLKPCE_bit at CLKPR.B7;
    const register unsigned short int CLKPS0 = 0;
    sbit  CLKPS0_bit at CLKPR.B0;
    const register unsigned short int CLKPS1 = 1;
    sbit  CLKPS1_bit at CLKPR.B1;
    const register unsigned short int CLKPS2 = 2;
    sbit  CLKPS2_bit at CLKPR.B2;
    const register unsigned short int CLKPS3 = 3;
    sbit  CLKPS3_bit at CLKPR.B3;

sfr io   unsigned char volatile SREG                      absolute 0x005F;
    const register unsigned short int SREG_I = 7;
    sbit  SREG_I_bit at SREG.B7;
    const register unsigned short int SREG_T = 6;
    sbit  SREG_T_bit at SREG.B6;
    const register unsigned short int SREG_H = 5;
    sbit  SREG_H_bit at SREG.B5;
    const register unsigned short int SREG_S = 4;
    sbit  SREG_S_bit at SREG.B4;
    const register unsigned short int SREG_V = 3;
    sbit  SREG_V_bit at SREG.B3;
    const register unsigned short int SREG_N = 2;
    sbit  SREG_N_bit at SREG.B2;
    const register unsigned short int SREG_Z = 1;
    sbit  SREG_Z_bit at SREG.B1;
    const register unsigned short int SREG_C = 0;
    sbit  SREG_C_bit at SREG.B0;

sfr io   unsigned int  volatile SP                        absolute 0x005D;
sfr io   unsigned char volatile SPL                       absolute 0x005D;
sfr io   unsigned char volatile MCUCR_CPU                 absolute 0x0055;
    const register unsigned short int PUD = 6;
    sbit  PUD_bit at MCUCR_CPU.B6;
    const register unsigned short int SE = 5;
    sbit  SE_bit at MCUCR_CPU.B5;
    const register unsigned short int SM0 = 3;
    sbit  SM0_bit at MCUCR_CPU.B3;
    const register unsigned short int SM1 = 4;
    sbit  SM1_bit at MCUCR_CPU.B4;

sfr io   unsigned char volatile MCUSR                     absolute 0x0054;
    const register unsigned short int WDRF = 3;
    sbit  WDRF_bit at MCUSR.B3;
    const register unsigned short int BORF = 2;
    sbit  BORF_bit at MCUSR.B2;
    const register unsigned short int EXTRF = 1;
    sbit  EXTRF_bit at MCUSR.B1;
    const register unsigned short int PORF = 0;
    sbit  PORF_bit at MCUSR.B0;

sfr io   unsigned char volatile GPIOR2                    absolute 0x0035;
sfr io   unsigned char volatile GPIOR1                    absolute 0x0034;
sfr io   unsigned char volatile GPIOR0                    absolute 0x0033;
sfr io   unsigned char volatile SPMCSR                    absolute 0x0057;
    const register unsigned short int CTPB = 4;
    sbit  CTPB_bit at SPMCSR.B4;
    const register unsigned short int RFLB = 3;
    sbit  RFLB_bit at SPMCSR.B3;
    const register unsigned short int PGWRT = 2;
    sbit  PGWRT_bit at SPMCSR.B2;
    const register unsigned short int PGERS = 1;
    sbit  PGERS_bit at SPMCSR.B1;
    const register unsigned short int SPMEN = 0;
    sbit  SPMEN_bit at SPMCSR.B0;

sfr io   unsigned char volatile EXTENDED_                 absolute 0x0002;
    const register unsigned short int SELFPRGEN = 0;
    sbit  SELFPRGEN_bit at EXTENDED_.B0;

sfr io   unsigned char volatile HIGH                      absolute 0x0001;
    const register unsigned short int RSTDISBL = 7;
    sbit  RSTDISBL_bit at HIGH.B7;
    const register unsigned short int DWEN = 6;
    sbit  DWEN_bit at HIGH.B6;
    const register unsigned short int SPIEN = 5;
    sbit  SPIEN_bit at HIGH.B5;
    const register unsigned short int WDTON = 4;
    sbit  WDTON_bit at HIGH.B4;
    const register unsigned short int EESAVE = 3;
    sbit  EESAVE_bit at HIGH.B3;
    const register unsigned short int BODLEVEL0 = 0;
    sbit  BODLEVEL0_bit at HIGH.B0;
    const register unsigned short int BODLEVEL1 = 1;
    sbit  BODLEVEL1_bit at HIGH.B1;
    const register unsigned short int BODLEVEL2 = 2;
    sbit  BODLEVEL2_bit at HIGH.B2;

sfr io   unsigned char volatile LOW                       absolute 0x0000;
    const register unsigned short int CKDIV8 = 7;
    sbit  CKDIV8_bit at LOW.B7;
    const register unsigned short int CKOUT = 6;
    sbit  CKOUT_bit at LOW.B6;
    const register unsigned short int SUT_CKSEL0 = 0;
    sbit  SUT_CKSEL0_bit at LOW.B0;
    const register unsigned short int SUT_CKSEL1 = 1;
    sbit  SUT_CKSEL1_bit at LOW.B1;
    const register unsigned short int SUT_CKSEL2 = 2;
    sbit  SUT_CKSEL2_bit at LOW.B2;
    const register unsigned short int SUT_CKSEL3 = 3;
    sbit  SUT_CKSEL3_bit at LOW.B3;
    const register unsigned short int SUT_CKSEL4 = 4;
    sbit  SUT_CKSEL4_bit at LOW.B4;
    const register unsigned short int SUT_CKSEL5 = 5;
    sbit  SUT_CKSEL5_bit at LOW.B5;

sfr io   unsigned char volatile LOCKBIT                   absolute 0x0000;
    const register unsigned short int LB0 = 0;
    sbit  LB0_bit at LOCKBIT.B0;
    const register unsigned short int LB1 = 1;
    sbit  LB1_bit at LOCKBIT.B1;

