if(${MCU_NAME} MATCHES "(^PIC18F57Q43$)")
    set(SYSTEM_LIB_SOURCE "system/P18/src/__Lib_System_Q43.c")
    set(SYSTEM_LIB_INCLUDE_DIR "")
    set(MATH_LIB_SOURCE "math/P18/__Lib_Math.c")
    set(MATH_DOUBLE_SOURCE "math_double/P18/__Lib_MathDouble.c")
    set(DELAY_SOURCE "delay/p18/__lib_delays.c")
else()
    set(SYSTEM_LIB_SOURCE "no_file_found")
    set(SYSTEM_LIB_INCLUDE_DIR "no_file_found")
endif()