if(${MCU_NAME} MATCHES "^R5F566TAFDFL$|^R5F566TAFDFP$|^R5F566TAFGFL$|^R5F566TAFGFP$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r5f566taf/init_clock.c)
endif()
