if(${MCU_NAME} MATCHES "^R5F566TABDFL$|^R5F566TABDFP$|^R5F566TABGFL$|^R5F566TABGFP$")
    set(${linkerScript} linker_scripts/${vendor}/${mcu_match}.ld PARENT_SCOPE)
    set(${startupFile} startup/${vendor}/${mcu_match}.S PARENT_SCOPE)
    list(APPEND local_list_include system/src/${vendor}/r5f566tab/init_clock.c)
endif()
