name: Index Latest Release

on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'MikroE CORE Packages previous release tag version'
        default: 'v'
        required: true
        type: string

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp
          pip install aiofiles
          pip install requests
          pip install elasticsearch==7.13.4
          sudo apt-get install p7zip-full

      - name: Run Index Script
        env:
          ES_HOST: ${{ secrets.ES_HOST }}
          ES_INDEX: ${{ secrets.ES_INDEX }}
          ES_USER: ${{ secrets.ES_USER }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
        run: python -u scripts/index.py ${{ github.repository }} ${{ github.event.inputs.tag_version }} ${{ secrets.GITHUB_TOKEN }}
