name: Index Latest Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: Which release version to index (type v1.0.6 for example)
        default: "latest"
      select_index:
        type: choice
        description: Index as test or live
        options:
          - Test
          - Live
      force_index:
        type: boolean
        default: false
        description: Force index packages (even if hash is the same, index with new package)

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements/shared.txt
          sudo apt-get install p7zip-full

      - name: Run Index Script
        env:
          ES_HOST: ${{ secrets.ES_HOST }}
          ES_USER: ${{ secrets.ES_USER }}
          ES_PASSWORD: ${{ secrets.ES_PASSWORD }}
        run: |
          if [[ ${{ github.event.inputs.select_index }} == "Live" ]]; then
            echo "Indexing to Live."
            python -u scripts/index.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ES_INDEX_LIVE }} ${{ github.event.inputs.force_index }} ${{ github.event.inputs.release_version }}
          else
            echo "Indexing to Test."
            python -u scripts/index.py ${{ github.repository }} ${{ secrets.GITHUB_TOKEN }} ${{ secrets.ES_INDEX_TEST }} ${{ github.event.inputs.force_index }} ${{ github.event.inputs.release_version }}
          fi
