name: Merge Main To Release Branches

on:
  workflow_dispatch:

  push:
    branches:
      - main  # This will trigger on every push (merge) to the 'main' branch

jobs:
  merge_master_to_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Add GitHub Actions credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Merge main to new-feature branches
        run: |
          python -u scripts/merge_master_to_branches.py
